var annotated_dup =
[
    [ "MonkeyPaste", "namespace_monkey_paste.html", [
      [ "Common", "namespace_monkey_paste_1_1_common.html", [
        [ "Plugin", "namespace_monkey_paste_1_1_common_1_1_plugin.html", [
          [ "MpAnalyzerComponent", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_analyzer_component.html", null ],
          [ "MpAnalyzerPluginRequestFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_analyzer_plugin_request_format.html", null ],
          [ "MpAnalyzerPluginResponseFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_analyzer_plugin_response_format.html", null ],
          [ "MpAnnotationNodeFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_annotation_node_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_annotation_node_format" ],
          [ "MpClipboardComponent", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_clipboard_component.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_clipboard_component" ],
          [ "MpClipboardHandlerFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_clipboard_handler_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_clipboard_handler_format" ],
          [ "MpContactFetcherFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_contact_fetcher_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_contact_fetcher_format" ],
          [ "MpCsvFormatProperties", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_csv_format_properties.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_csv_format_properties" ],
          [ "MpDeferredParameterCommandRequestFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_deferred_parameter_command_request_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_deferred_parameter_command_request_format" ],
          [ "MpDeferredParameterValueRequestFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_deferred_parameter_value_request_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_deferred_parameter_value_request_format" ],
          [ "MpDeferredParameterValueResponseFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_deferred_parameter_value_response_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_deferred_parameter_value_response_format" ],
          [ "MpHeadlessComponent", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_headless_component.html", null ],
          [ "MpHeadlessComponentFormatRequest", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_headless_component_format_request.html", null ],
          [ "MpIActionOutputNode", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_action_output_node.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_action_output_node" ],
          [ "MpIActionPluginComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_action_plugin_component.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_action_plugin_component" ],
          [ "MpIAnalyzeComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_analyze_component.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_analyze_component" ],
          [ "MpIAnalyzeComponentAsync", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_analyze_component_async.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_analyze_component_async" ],
          [ "MpIAnnotationNode", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_annotation_node.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_annotation_node" ],
          [ "MpIClampedValue", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_clamped_value.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_clamped_value" ],
          [ "MpIContact", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_contact.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_contact" ],
          [ "MpIContactFetcherComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_contact_fetcher_component.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_contact_fetcher_component" ],
          [ "MpIContactFetcherComponentAsync", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_contact_fetcher_component_async.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_contact_fetcher_component_async" ],
          [ "MpICustomCsvFormat", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_custom_csv_format.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_custom_csv_format" ],
          [ "MpIExpandable", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_expandable.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_expandable" ],
          [ "MpIFetchComponentBase", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_fetch_component_base.html", null ],
          [ "MpIHeadlessComponentFormatBase", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_headless_component_format_base.html", null ],
          [ "MpIIconResource", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_icon_resource.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_icon_resource" ],
          [ "MpILabelText", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_label_text.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_label_text" ],
          [ "MpImageAnnotationNodeFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_image_annotation_node_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_image_annotation_node_format" ],
          [ "MpINotificationFormat", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_notification_format.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_notification_format" ],
          [ "MpIOComponentBase", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_o_component_base.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_o_component_base" ],
          [ "MpIOlePluginComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_ole_plugin_component.html", null ],
          [ "MpIOleReaderComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_ole_reader_component.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_ole_reader_component" ],
          [ "MpIOleWriterComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_ole_writer_component.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_ole_writer_component" ],
          [ "MpIParamterValueProvider", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_paramter_value_provider.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_paramter_value_provider" ],
          [ "MpIPlainTextCompatible", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_plain_text_compatible.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_plain_text_compatible" ],
          [ "MpIPlatformDataObjectRegistrar", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_platform_data_object_registrar.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_platform_data_object_registrar" ],
          [ "MpIPluginComponentBase", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_plugin_component_base.html", null ],
          [ "MpIRectangle", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_rectangle.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_rectangle" ],
          [ "MpISupportDeferredParameterCommand", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_deferred_parameter_command.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_deferred_parameter_command" ],
          [ "MpISupportDeferredValue", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_deferred_value.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_deferred_value" ],
          [ "MpISupportDeferredValueAsync", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_deferred_value_async.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_deferred_value_async" ],
          [ "MpISupportHeadlessAnalyzerFormat", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_headless_analyzer_format.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_headless_analyzer_format" ],
          [ "MpISupportHeadlessClipboardComponentFormat", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_headless_clipboard_component_format.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_support_headless_clipboard_component_format" ],
          [ "MpITextRange", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_text_range.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_text_range" ],
          [ "MpITreeNode", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_tree_node.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_tree_node" ],
          [ "MpITriggerPluginComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_trigger_plugin_component.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_trigger_plugin_component" ],
          [ "MpIUnloadPluginComponent", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_unload_plugin_component.html", "interface_monkey_paste_1_1_common_1_1_plugin_1_1_mp_i_unload_plugin_component" ],
          [ "MpManifestFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_manifest_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_manifest_format" ],
          [ "MpMessageFormatBase", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_message_format_base.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_message_format_base" ],
          [ "MpMessageRequestFormatBase", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_message_request_format_base.html", null ],
          [ "MpMessageResponseFormatBase", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_message_response_format_base.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_message_response_format_base" ],
          [ "MpOlePluginRequest", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_ole_plugin_request.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_ole_plugin_request" ],
          [ "MpOlePluginResponse", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_ole_plugin_response.html", null ],
          [ "MpParameterFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_format" ],
          [ "MpParameterMessageRequestFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_message_request_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_message_request_format" ],
          [ "MpParameterRequestItemFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_request_item_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_request_item_format" ],
          [ "MpParameterValueFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_value_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_parameter_value_format" ],
          [ "MpPluginComponentBase", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_component_base.html", null ],
          [ "MpPluginContactFetchRequestFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_contact_fetch_request_format.html", null ],
          [ "MpPluginContactFetchResponseFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_contact_fetch_response_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_contact_fetch_response_format" ],
          [ "MpPluginDependency", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_dependency.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_dependency" ],
          [ "MpPluginFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_format" ],
          [ "MpPluginInputFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_input_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_input_format" ],
          [ "MpPluginOutputFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_output_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_output_format" ],
          [ "MpPluginParameterCommandResponseFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_parameter_command_response_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_plugin_parameter_command_response_format" ],
          [ "MpPortableDataFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_portable_data_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_portable_data_format" ],
          [ "MpPresetFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_preset_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_preset_format" ],
          [ "MpPresetParamaterHostBase", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_preset_paramater_host_base.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_preset_paramater_host_base" ],
          [ "MpPresetValueFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_preset_value_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_preset_value_format" ],
          [ "MpQuillAttributes", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_attributes.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_attributes" ],
          [ "MpQuillDelta", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_delta.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_delta" ],
          [ "MpQuillDeltaRange", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_delta_range.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_delta_range" ],
          [ "MpQuillImageInsert", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_image_insert.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_image_insert" ],
          [ "MpQuillOp", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_op.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_op" ],
          [ "MpQuillTableCellLine", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_table_cell_line.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_table_cell_line" ],
          [ "MpQuillTableCol", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_table_col.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_quill_table_col" ],
          [ "MpTextAnnotationNodeFormat", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_text_annotation_node_format.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_text_annotation_node_format" ],
          [ "MpUserNotification", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_user_notification.html", "class_monkey_paste_1_1_common_1_1_plugin_1_1_mp_user_notification" ]
        ] ],
        [ "MpIDocumentComponent", "interface_monkey_paste_1_1_common_1_1_mp_i_document_component.html", "interface_monkey_paste_1_1_common_1_1_mp_i_document_component" ]
      ] ]
    ] ]
];