namespace CoreOleHandler {
    public enum CoreOleParamType {
        None = 0,
        //readers
        TEXT_R_MAXCHARCOUNT,
        TEXT_R_IGNORE,
        TEXT_W_MAXCHARCOUNT,
        TEXT_W_IGNORE,

        TEXTPLAIN_R_MAXCHARCOUNT,
        TEXTPLAIN_R_IGNORE,
        TEXTPLAIN_W_MAXCHARCOUNT,
        TEXTPLAIN_W_IGNORE,

        RICHTEXTFORMAT_R_MAXCHARCOUNT,
        RICHTEXTFORMAT_R_IGNORE,
        RICHTEXTFORMAT_R_TOHTML,
        RICHTEXTFORMAT_W_MAXCHARCOUNT,
        RICHTEXTFORMAT_W_IGNORE,
        RICHTEXTFORMAT_W_TOHTML,

        HTMLFORMAT_R_MAXCHARCOUNT,
        HTMLFORMAT_R_IGNORE,
        HTMLFORMAT_R_TORTF,
        HTMLFORMAT_W_MAXCHARCOUNT,
        HTMLFORMAT_W_IGNORE,
        HTMLFORMAT_W_TORTF,

        TEXTHTML_R_MAXCHARCOUNT,
        TEXTHTML_R_IGNORE,
        TEXTHTML_R_TORTF,
        TEXTHTML_W_MAXCHARCOUNT,
        TEXTHTML_W_IGNORE,
        TEXTHTML_W_TORTF,

        TEXTXMOZURLPRIV_R_IGNORE,
        TEXTXMOZURLPRIV_W_IGNORE,

        PNG_R_IGNORE,
        PNG_W_IGNORE,
        PNG_W_EXPORTTYPE,

        FILES_R_IGNORE,
        FILES_R_IGNOREEXTS,
        FILES_R_IGNOREDIRS,
        FILES_W_IGNORE,
        FILES_W_IGNOREEXTS,

        CSV_R_IGNORE,
        CSV_R_MAXCHARCOUNT,
        CSV_W_IGNORE,
        CSV_W_MAXCHARCOUNT
    }
}