//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyPaste.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkeyPaste.Avalonia.Resources.Localization.Listings.ListingStrings", typeof(ListingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this subscription you will receive:
        ///● up to 1,000 clips of content 
        ///● unlimited trash &amp; archive.
        /// </summary>
        public static string BasicDescription {
            get {
                return ResourceManager.GetString("BasicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic - Monthly.
        /// </summary>
        public static string BasicMonthlyTitle {
            get {
                return ResourceManager.GetString("BasicMonthlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic - Yearly.
        /// </summary>
        public static string BasicYearlyTitle {
            get {
                return ResourceManager.GetString("BasicYearlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/StoreLogo_1080x1080.png.
        /// </summary>
        public static string logo1080x1080 {
            get {
                return ResourceManager.GetString("logo1080x1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/StoreLogo_150x150.png.
        /// </summary>
        public static string logo150x150 {
            get {
                return ResourceManager.GetString("logo150x150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/StoreLogo_1920x1080.png.
        /// </summary>
        public static string logo1920x1080 {
            get {
                return ResourceManager.GetString("logo1920x1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/StoreLogo_300x300.png.
        /// </summary>
        public static string logo300x300 {
            get {
                return ResourceManager.GetString("logo300x300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/StoreLogo_71x71.png.
        /// </summary>
        public static string logo71x71 {
            get {
                return ResourceManager.GetString("logo71x71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/StoreLogo_720x1080.png.
        /// </summary>
        public static string logo720x1080 {
            get {
                return ResourceManager.GetString("logo720x1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string OverrideLogosForWin10 {
            get {
                return ResourceManager.GetString("OverrideLogosForWin10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clipboard manager.
        /// </summary>
        public static string SearchTerm1 {
            get {
                return ResourceManager.GetString("SearchTerm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string SearchTerm2 {
            get {
                return ResourceManager.GetString("SearchTerm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste.
        /// </summary>
        public static string SearchTerm3 {
            get {
                return ResourceManager.GetString("SearchTerm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clipboard manager.
        /// </summary>
        public static string SearchTerm4 {
            get {
                return ResourceManager.GetString("SearchTerm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.
        /// </summary>
        public static string SearchTerm5 {
            get {
                return ResourceManager.GetString("SearchTerm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utility.
        /// </summary>
        public static string SearchTerm6 {
            get {
                return ResourceManager.GetString("SearchTerm6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automation.
        /// </summary>
        public static string SearchTerm7 {
            get {
                return ResourceManager.GetString("SearchTerm7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger &amp; Action Designer for custom automations and action chaining.
        /// </summary>
        public static string ssCaption1 {
            get {
                return ResourceManager.GetString("ssCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal/vertical layouts, list/grid view and multi-monitor support.
        /// </summary>
        public static string ssCaption2 {
            get {
                return ResourceManager.GetString("ssCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully-featured clip editor with find/replace, rich text (tables, lists, links, etc.) text templating for quick, dynamic pasting from your snippet collection.
        /// </summary>
        public static string ssCaption3 {
            get {
                return ResourceManager.GetString("ssCaption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe, secure and private local data storage with optional 2-factor password protection.
        /// </summary>
        public static string ssCaption4 {
            get {
                return ResourceManager.GetString("ssCaption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in plugin browser with an ever-growing community-driven library of plugins.
        /// </summary>
        public static string ssCaption5 {
            get {
                return ResourceManager.GetString("ssCaption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/ss1.png.
        /// </summary>
        public static string ssSrc1 {
            get {
                return ResourceManager.GetString("ssSrc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/ss2.png.
        /// </summary>
        public static string ssSrc2 {
            get {
                return ResourceManager.GetString("ssSrc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/ss3.png.
        /// </summary>
        public static string ssSrc3 {
            get {
                return ResourceManager.GetString("ssSrc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/ss4.png.
        /// </summary>
        public static string ssSrc4 {
            get {
                return ResourceManager.GetString("ssSrc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/ss5.png.
        /// </summary>
        public static string ssSrc5 {
            get {
                return ResourceManager.GetString("ssSrc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonkeyPaste is a clipboard manager, automation and productivity tool like no other. Enhancing your clipboard into an enriched and organized part of your workflow,
        ///featuring an intuitive and low-profile interface that supports text, files and images. Designed for flexibility, with an ever-growing community-driven libray of plugins.
        ///
        ///It began as an experiment by a programmer wanting more than just copy and paste out of the clipboard. He wanted a simple command like Control+C that would &apos;add to&apos; instead 
        ///o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StoreDescription {
            get {
                return ResourceManager.GetString("StoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thomas Kefauver.
        /// </summary>
        public static string StoreDevStudio {
            get {
                return ResourceManager.GetString("StoreDevStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Simple and friendly interface with both horizontal/vertical layouts, list/grid view and multi-monitor support.
        /// </summary>
        public static string StoreFeature1 {
            get {
                return ResourceManager.GetString("StoreFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Append mode: Copying becomes &apos;add to&apos; instead of &apos;replace&apos; on the clipboard. Both text and files, fully customizable.
        /// </summary>
        public static string StoreFeature10 {
            get {
                return ResourceManager.GetString("StoreFeature10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Sophisticated clip tracking, sources and usage with enhanced support for Firefox and Chromium-based browsers (Chrome, Edge, Brave).
        /// </summary>
        public static string StoreFeature11 {
            get {
                return ResourceManager.GetString("StoreFeature11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Fully-featured clip editor with rich text (tables, lists, links, etc.) with find/replace and highlighting.
        /// </summary>
        public static string StoreFeature12 {
            get {
                return ResourceManager.GetString("StoreFeature12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Store your images in the secure database, ready to use as files anytime on-demand just drag-and-drop!.
        /// </summary>
        public static string StoreFeature13 {
            get {
                return ResourceManager.GetString("StoreFeature13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Powerful text templating for quick, dynamic pasting from your snippet collection.
        /// </summary>
        public static string StoreFeature14 {
            get {
                return ResourceManager.GetString("StoreFeature14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Trigger &amp; Action designer for custom automations and action chaining.
        /// </summary>
        public static string StoreFeature15 {
            get {
                return ResourceManager.GetString("StoreFeature15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Simple to use and extend plugin system for both analyzing clips or read/write any format to your clipboard.
        /// </summary>
        public static string StoreFeature16 {
            get {
                return ResourceManager.GetString("StoreFeature16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Built-in plugin browser with an ever-growing community-driven library of plugins.
        /// </summary>
        public static string StoreFeature17 {
            get {
                return ResourceManager.GetString("StoreFeature17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Automate everything with plugin presets, stash and use your any of your AI prompts or commands with ease.
        /// </summary>
        public static string StoreFeature18 {
            get {
                return ResourceManager.GetString("StoreFeature18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● More platforms and features coming soon! We&apos;re just gettings started 🎉.
        /// </summary>
        public static string StoreFeature19 {
            get {
                return ResourceManager.GetString("StoreFeature19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Both light &amp; dark themes are completely dynamic, use any color you want.
        /// </summary>
        public static string StoreFeature2 {
            get {
                return ResourceManager.GetString("StoreFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Integrated help &amp; hints right in the interface. Online manual, videos and forum to get you started all on the website (monkeypaste.com/docs).
        /// </summary>
        public static string StoreFeature3 {
            get {
                return ResourceManager.GetString("StoreFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Optimized for performance and stressed tested with 1,000,000s of clips..
        /// </summary>
        public static string StoreFeature4 {
            get {
                return ResourceManager.GetString("StoreFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Anytime search, just start typing using both simple &amp; advanced filtering on clips and their sources over dozens of fields.
        /// </summary>
        public static string StoreFeature5 {
            get {
                return ResourceManager.GetString("StoreFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Organize your clips in tag trees and create resusable filters.
        /// </summary>
        public static string StoreFeature6 {
            get {
                return ResourceManager.GetString("StoreFeature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Safe, secure and private local data storage (no data collection) always encrypted with optional 2-factor password protection and easily block apps or websites from your tracker.
        /// </summary>
        public static string StoreFeature7 {
            get {
                return ResourceManager.GetString("StoreFeature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Extensive drag-and-drop support, custom global shortcuts, routing and mouse-free navigation.
        /// </summary>
        public static string StoreFeature8 {
            get {
                return ResourceManager.GetString("StoreFeature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Custom mouse modes: right-click paste and left-click auto-copy.
        /// </summary>
        public static string StoreFeature9 {
            get {
                return ResourceManager.GetString("StoreFeature9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Simple and friendly interface 
        ///● Horizontal/vertical layouts, list/grid view and multi-monitor support
        ///● Both light &amp; dark themes are completely dynamic, use any color you want
        ///
        ///● Integrated help &amp; hints right in the interface
        ///● Help manual, videos and forum to get you started all on the website (monkeypaste.com/docs)
        ///
        ///● Optimized for performance and stressed tested with 1,000,000s of clips.
        ///● Anytime search, just start typing
        ///● Both simple &amp; advanced filtering on clips and their sources over doz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StoreFeatures {
            get {
                return ResourceManager.GetString("StoreFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard is a jungle. MonkeyPaste is the KING! Swing from app to app, copying this and pasting that like never before with MonkeyPaste!! A brand-new, cutting edge clipboard and analytic automation tool!!!.
        /// </summary>
        public static string StoreShortDescription {
            get {
                return ResourceManager.GetString("StoreShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonkeyPaste.
        /// </summary>
        public static string StoreTitle {
            get {
                return ResourceManager.GetString("StoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample of MonkeyPaste in action!.
        /// </summary>
        public static string TeaserCaption {
            get {
                return ResourceManager.GetString("TeaserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/teaser.mp4.
        /// </summary>
        public static string TeaserSrc {
            get {
                return ResourceManager.GetString("TeaserSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/teaser.mp4.
        /// </summary>
        public static string TrailerToPlayAtTopOfListing {
            get {
                return ResourceManager.GetString("TrailerToPlayAtTopOfListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed in this language. English is only for these examples.
        /// </summary>
        public static string TranslationShortWarning {
            get {
                return ResourceManager.GetString("TranslationShortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note! Screen shots are only examples. What you install has been translated to this language..
        /// </summary>
        public static string TranslationWarning {
            get {
                return ResourceManager.GetString("TranslationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this subscription you will receive:
        ///● unlimited capacity
        ///● device syncing (upon availability).
        /// </summary>
        public static string UnlimitedDescription {
            get {
                return ResourceManager.GetString("UnlimitedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited - Monthly.
        /// </summary>
        public static string UnlimitedMonthlyTitle {
            get {
                return ResourceManager.GetString("UnlimitedMonthlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited - Yearly.
        /// </summary>
        public static string UnlimitedYearlyTitle {
            get {
                return ResourceManager.GetString("UnlimitedYearlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Release.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
    }
}
