//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyPaste.Avalonia.Resources.Legal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Attributions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Attributions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkeyPaste.Avalonia.Resources.Legal.Attributions", typeof(Attributions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectors and icons by &lt;a href=&quot;https://github.com/googlefonts/noto-emoji?ref=svgrepo.com&quot; target=&quot;_blank&quot;&gt;Googlefonts&lt;/a&gt; in Apache License via &lt;a href=&quot;https://www.svgrepo.com/&quot; target=&quot;_blank&quot;&gt;SVG Repo&lt;/a&gt;.
        /// </summary>
        internal static string banana_png {
            get {
                return ResourceManager.GetString("banana.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectors and icons by &lt;a href=&quot;https://github.com/mozilla/fxemoji?ref=svgrepo.com&quot; target=&quot;_blank&quot;&gt;Mozilla&lt;/a&gt; in Apache License via &lt;a href=&quot;https://www.svgrepo.com/&quot; target=&quot;_blank&quot;&gt;SVG Repo&lt;/a&gt;.
        /// </summary>
        internal static string bananas_png {
            get {
                return ResourceManager.GetString("bananas.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectors and icons by &lt;a href=&quot;https://github.com/framework7io/framework7-icons?ref=svgrepo.com&quot; target=&quot;_blank&quot;&gt;Framework7io&lt;/a&gt; in MIT License via &lt;a href=&quot;https://www.svgrepo.com/&quot; target=&quot;_blank&quot;&gt;SVG Repo&lt;/a&gt;.
        /// </summary>
        internal static string bolt_png {
            get {
                return ResourceManager.GetString("bolt.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string gavel_png {
            get {
                return ResourceManager.GetString("gavel.png", resourceCulture);
            }
        }
    }
}
