-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmhBccLcFDZGJydXN
jDBWhUlcLlmoXmcYFgMuohR9X6ugCgYIKoZIzj0DAQehRANCAARSI4gNifSTezZE
zY+aGhBh+AG1EAiVw1isIg8mcpZ09ts7R3/wH07fjDFH/tvpYa8m2GTAVDzpRFAo
R6Sa+Zib
-----END PRIVATE KEY-----