//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyPaste.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkeyPaste.Avalonia.Resources.UiStrings.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next to delete! Upgrade to avoid 💪🏽.
        /// </summary>
        public static string AccountNextRemoveToolTipText {
            get {
                return ResourceManager.GetString("AccountNextRemoveToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next to trash! Upgrade to avoid 💪🏽.
        /// </summary>
        public static string AccountNextTrashToolTipText {
            get {
                return ResourceManager.GetString("AccountNextTrashToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string ActionMoveLabel {
            get {
                return ResourceManager.GetString("ActionMoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        public static string ClipboardPluginFormatsHeader {
            get {
                return ResourceManager.GetString("ClipboardPluginFormatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readers.
        /// </summary>
        public static string ClipboardPluginFormatTypeReadersLabel {
            get {
                return ResourceManager.GetString("ClipboardPluginFormatTypeReadersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writers.
        /// </summary>
        public static string ClipboardPluginFormatTypeWritersLabel {
            get {
                return ResourceManager.GetString("ClipboardPluginFormatTypeWritersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlers.
        /// </summary>
        public static string ClipboardPluginHandlersHeader {
            get {
                return ResourceManager.GetString("ClipboardPluginHandlersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string ClipTileDefTitleFilesPrefix {
            get {
                return ResourceManager.GetString("ClipTileDefTitleFilesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ClipTileDefTitleImagePrefix {
            get {
                return ResourceManager.GetString("ClipTileDefTitleImagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ClipTileDefTitleTextPrefix {
            get {
                return ResourceManager.GetString("ClipTileDefTitleTextPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0}.
        /// </summary>
        public static string ClipTileDetailCreated {
            get {
                return ResourceManager.GetString("ClipTileDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files | {1} MBs.
        /// </summary>
        public static string ClipTileDetailDimFiles {
            get {
                return ResourceManager.GetString("ClipTileDetailDimFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1} px.
        /// </summary>
        public static string ClipTileDetailDimImage {
            get {
                return ResourceManager.GetString("ClipTileDetailDimImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chars | {1} lines.
        /// </summary>
        public static string ClipTileDetailDimText {
            get {
                return ResourceManager.GetString("ClipTileDetailDimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copies | {1} pastes.
        /// </summary>
        public static string ClipTileDetailUsage {
            get {
                return ResourceManager.GetString("ClipTileDetailUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string ClipTileTagContextMenuLabel {
            get {
                return ResourceManager.GetString("ClipTileTagContextMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CommonAddLabel {
            get {
                return ResourceManager.GetString("CommonAddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CommonCopyOpLabel {
            get {
                return ResourceManager.GetString("CommonCopyOpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CommonCutOpLabel {
            get {
                return ResourceManager.GetString("CommonCutOpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CommonDeleteLabel {
            get {
                return ResourceManager.GetString("CommonDeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string CommonDuplicateLabel {
            get {
                return ResourceManager.GetString("CommonDuplicateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Name.
        /// </summary>
        public static string CommonEditLabel {
            get {
                return ResourceManager.GetString("CommonEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results available..
        /// </summary>
        public static string CommonEmptyListText {
            get {
                return ResourceManager.GetString("CommonEmptyListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CommonNoneLabel {
            get {
                return ResourceManager.GetString("CommonNoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CommonNtfConfirmTitle {
            get {
                return ResourceManager.GetString("CommonNtfConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string CommonPasteOpLabel {
            get {
                return ResourceManager.GetString("CommonPasteOpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CommonRefreshTooltip {
            get {
                return ResourceManager.GetString("CommonRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string CommonResetLabel {
            get {
                return ResourceManager.GetString("CommonResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommonSaveLabel {
            get {
                return ResourceManager.GetString("CommonSaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string CommonSearchWatermark {
            get {
                return ResourceManager.GetString("CommonSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string CommonSettingsTitle {
            get {
                return ResourceManager.GetString("CommonSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Copy.
        /// </summary>
        public static string CommonTitledCopyTitleText {
            get {
                return ResourceManager.GetString("CommonTitledCopyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All interop shortcuts (those useful outside of MonkeyPaste) are enabled by default. Pressing Caps Lock (without any other key) will show or hide the interface at anytime (not currently supported on Linux).
        /// </summary>
        public static string GestureProfileGlobal {
            get {
                return ResourceManager.GetString("GestureProfileGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global shortcuts are enabled by default. .
        /// </summary>
        public static string GestureProfileInternal {
            get {
                return ResourceManager.GetString("GestureProfileInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits:.
        /// </summary>
        public static string PluginBrowserCreditsLabel {
            get {
                return ResourceManager.GetString("PluginBrowserCreditsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string PluginBrowserDependenciesLabel {
            get {
                return ResourceManager.GetString("PluginBrowserDependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string PluginBrowserDescriptionLabel {
            get {
                return ResourceManager.GetString("PluginBrowserDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate:.
        /// </summary>
        public static string PluginBrowserDonateLabel {
            get {
                return ResourceManager.GetString("PluginBrowserDonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PluginBrowserInstallLabel {
            get {
                return ResourceManager.GetString("PluginBrowserInstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string PluginBrowserLicenseLabel {
            get {
                return ResourceManager.GetString("PluginBrowserLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove &apos;{0}&apos; and all its presets and shortcuts?.
        /// </summary>
        public static string PluginBrowserNtfUninstallMsg {
            get {
                return ResourceManager.GetString("PluginBrowserNtfUninstallMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL:.
        /// </summary>
        public static string PluginBrowserProjectUrlLabel {
            get {
                return ResourceManager.GetString("PluginBrowserProjectUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published:.
        /// </summary>
        public static string PluginBrowserPublishedLabel {
            get {
                return ResourceManager.GetString("PluginBrowserPublishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Me:.
        /// </summary>
        public static string PluginBrowserReadMeLabel {
            get {
                return ResourceManager.GetString("PluginBrowserReadMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abuse:.
        /// </summary>
        public static string PluginBrowserReportAbuseLabel {
            get {
                return ResourceManager.GetString("PluginBrowserReportAbuseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        public static string PluginBrowserTagsLabel {
            get {
                return ResourceManager.GetString("PluginBrowserTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string PluginBrowserUninstallLabel {
            get {
                return ResourceManager.GetString("PluginBrowserUninstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update:.
        /// </summary>
        public static string PluginBrowserUpdateLabel {
            get {
                return ResourceManager.GetString("PluginBrowserUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string PluginBrowserVersionLabel {
            get {
                return ResourceManager.GetString("PluginBrowserVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard is a jungle. You need the prowess of a primate to navigate the terrain and tap its true potential..
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed Filter.
        /// </summary>
        public static string QueryTrayEmptyPendingTagName {
            get {
                return ResourceManager.GetString("QueryTrayEmptyPendingTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has no results..
        /// </summary>
        public static string QueryTrayEmptyText {
            get {
                return ResourceManager.GetString("QueryTrayEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection..
        /// </summary>
        public static string QueryTrayNoSelection {
            get {
                return ResourceManager.GetString("QueryTrayNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please Select -.
        /// </summary>
        public static string SearchCriteriaDefaultOptionLabel {
            get {
                return ResourceManager.GetString("SearchCriteriaDefaultOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Window.
        /// </summary>
        public static string SearchCriteriaHeadePopoutTooltipText {
            get {
                return ResourceManager.GetString("SearchCriteriaHeadePopoutTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string SearchCriteriaHeaderDismissButtonLabel {
            get {
                return ResourceManager.GetString("SearchCriteriaHeaderDismissButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string SearchCriteriaHeadeRefreshTooltipText {
            get {
                return ResourceManager.GetString("SearchCriteriaHeadeRefreshTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test &lt;b color=&quot;green&quot;&gt;test&lt;/b&gt; &lt;em color=&quot;red&quot;&gt;&lt;b&gt;test&lt;/b&lt;/em&gt; &lt;a color=&quot;pink&quot; href=&quot;https://www.google.com/&quot;&gt;test&lt;/a&gt;.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No features are limited by subscription, only storage capacity and can be changed at anytime..
        /// </summary>
        public static string WelcomeAccountCaption {
            get {
                return ResourceManager.GetString("WelcomeAccountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore your existing account....
        /// </summary>
        public static string WelcomeAccountDescription1 {
            get {
                return ResourceManager.GetString("WelcomeAccountDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content and archive is limited to {0} and {1} clips respectively. No syncing capabilities are enabled..
        /// </summary>
        public static string WelcomeAccountDescription2 {
            get {
                return ResourceManager.GetString("WelcomeAccountDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/{0}{2} (monthly/annually) {4} Content is limited to {3} clips with an unlimited archive and syncing across all devices. .
        /// </summary>
        public static string WelcomeAccountDescription3 {
            get {
                return ResourceManager.GetString("WelcomeAccountDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/{0}{2} (monthly/annually) {3} Unrestricted, unlimited storage (optimized for efficiency with millions of items) with syncing across all devices..
        /// </summary>
        public static string WelcomeAccountDescription4 {
            get {
                return ResourceManager.GetString("WelcomeAccountDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string WelcomeAccountLabel1 {
            get {
                return ResourceManager.GetString("WelcomeAccountLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string WelcomeAccountLabel2 {
            get {
                return ResourceManager.GetString("WelcomeAccountLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string WelcomeAccountLabel3 {
            get {
                return ResourceManager.GetString("WelcomeAccountLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        public static string WelcomeAccountLabel4 {
            get {
                return ResourceManager.GetString("WelcomeAccountLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string WelcomeAccountTitle {
            get {
                return ResourceManager.GetString("WelcomeAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy is important and clipboard data can be very personal. Storage is always encrypted but you can set a password that will be required in case your device is stolen or someone else is using your device..
        /// </summary>
        public static string WelcomeDbPasswordCaption {
            get {
                return ResourceManager.GetString("WelcomeDbPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string WelcomeDbPasswordTitle {
            get {
                return ResourceManager.GetString("WelcomeDbPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, dragging from any application to the top of the screen will reveal MonkeyPaste to easily drop content into MonkeyPaste..
        /// </summary>
        public static string WelcomeDragToOpenCaption {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling the &apos;lock&apos; in the top left of the main window will still allow dropping into MonkeyPaste..
        /// </summary>
        public static string WelcomeDragToOpenDescription1 {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More window preferences are available from the &apos;Settings-&gt;Preferences-&gt;Window&apos; menu..
        /// </summary>
        public static string WelcomeDragToOpenDescription2 {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Me!.
        /// </summary>
        public static string WelcomeDragToOpenDragSourceLabel {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenDragSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p align=&quot;center&quot;&gt;MonkeyPaste is &lt;span color=&quot;red&gt;fully integrated&lt;/span&gt; with Drag-and-Drop to and from the application.&lt;/p&gt;.
        /// </summary>
        public static string WelcomeDragToOpenFakeWindowDetail {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenFakeWindowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy RIght?.
        /// </summary>
        public static string WelcomeDragToOpenFakeWindowLabel {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenFakeWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string WelcomeDragToOpenLabel1 {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string WelcomeDragToOpenLabel2 {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Bananas Up Here!.
        /// </summary>
        public static string WelcomeDragToOpenMarkerLabel {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenMarkerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag-to-Open.
        /// </summary>
        public static string WelcomeDragToOpenTitle {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it out!.
        /// </summary>
        public static string WelcomeDragToOpenTryButtonLabel {
            get {
                return ResourceManager.GetString("WelcomeDragToOpenTryButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts can be reviewed or changed at anytime from the &apos;Settings-&gt;Shortcuts&apos; menu..
        /// </summary>
        public static string WelcomeGestureProfileCaption {
            get {
                return ResourceManager.GetString("WelcomeGestureProfileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string WelcomeGestureProfileDescription1 {
            get {
                return ResourceManager.GetString("WelcomeGestureProfileDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonkeyPaste&apos;s clipboard shortcuts will be available in all applications..
        /// </summary>
        public static string WelcomeGestureProfileDescription2 {
            get {
                return ResourceManager.GetString("WelcomeGestureProfileDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string WelcomeGestureProfileLabel1 {
            get {
                return ResourceManager.GetString("WelcomeGestureProfileLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string WelcomeGestureProfileLabel2 {
            get {
                return ResourceManager.GetString("WelcomeGestureProfileLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Profile.
        /// </summary>
        public static string WelcomeGestureProfileTitle {
            get {
                return ResourceManager.GetString("WelcomeGestureProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! Let&apos;s setup a few things to improve your overall experience with MonkeyPaste..
        /// </summary>
        public static string WelcomeGreetingCaption {
            get {
                return ResourceManager.GetString("WelcomeGreetingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeGreetingTitle {
            get {
                return ResourceManager.GetString("WelcomeGreetingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get the most use out of MonkeyPaste, loading automatically when you log in is a good idea. But, that&apos;s entirely up to you..
        /// </summary>
        public static string WelcomeLoginLoadCaption {
            get {
                return ResourceManager.GetString("WelcomeLoginLoadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonkeyPaste will only load when this user account is logged in, not for other users..
        /// </summary>
        public static string WelcomeLoginLoadDescription1 {
            get {
                return ResourceManager.GetString("WelcomeLoginLoadDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string WelcomeLoginLoadLabel1 {
            get {
                return ResourceManager.GetString("WelcomeLoginLoadLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load On Login?.
        /// </summary>
        public static string WelcomeLoginLoadTitle {
            get {
                return ResourceManager.GetString("WelcomeLoginLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, a scroll gesture at the top of the screen will reveal MonkeyPaste..
        /// </summary>
        public static string WelcomeScrollToOpenCaption {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-clicking the taskbar icon will still open MonkeyPaste..
        /// </summary>
        public static string WelcomeScrollToOpenDescription1 {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More window preferences are available from the &apos;Settings-&gt;Preferences-&gt;Window&apos; menu..
        /// </summary>
        public static string WelcomeScrollToOpenDescription2 {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p align=&quot;center&quot;&gt;This way, MonkeyPaste can be accessed&lt;br&gt; &lt;span color=&quot;red&quot;&gt;without a click&lt;/span&gt; or even &lt;span color=&quot;red&quot;&gt;batting an eye&lt;/span&gt; &amp;#x1F440&lt;/p&gt;.
        /// </summary>
        public static string WelcomeScrollToOpenFakeWindowDetail {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenFakeWindowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Right?.
        /// </summary>
        public static string WelcomeScrollToOpenFakeWindowLabel {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenFakeWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string WelcomeScrollToOpenLabel1 {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string WelcomeScrollToOpenLabel2 {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Up Here!.
        /// </summary>
        public static string WelcomeScrollToOpenMarkerLabel {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenMarkerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll-to-Open.
        /// </summary>
        public static string WelcomeScrollToOpenTitle {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it out!.
        /// </summary>
        public static string WelcomeScrollToOpenTryButtonLabel {
            get {
                return ResourceManager.GetString("WelcomeScrollToOpenTryButtonLabel", resourceCulture);
            }
        }
    }
}
