var UiStrings = {
	EditorAppendCloseLabel: `Қосылуды аяқтаңыз`,
	EditorAppendInlineModeLabel: `Блокты қосу`,
	EditorAppendLineModeLabel: `Кірістірілген қосу`,
	EditorAppendManualModeLabel: `Қолмен ауыстырыңыз`,
	EditorAppendNonManualModeLabel: `Қолмен ауыстырыңыз`,
	EditorAppendPauseLabel: `Кідірту қосымшасы`,
	EditorAppendPostLabel: `Дейін ауыстырыңыз`,
	EditorAppendPreLabel: `Дейін ауыстырыңыз`,
	EditorAppendResumeLabel: `Қосу Қосу`,
	EditorBgColorLabel: `Фон түсі`,
	EditorClearAllLabel: `Барлығын тазалаңыз`,
	EditorClipboardFormatsLabel: `Алмасу буферінің форматтары`,
	EditorConfirmNtfTitle: `Растау`,
	EditorDeleteAllButtonText: `Барлығын жойыңыз`,
	EditorDeleteAllTemplatesNtfText: `'{0}' барлық пайдаланушыларын жойғыңыз келе ме?

Мұны болдырмауға болмайды!`,
	EditorEditTemplateDetailsLabel: `Мәліметтерді өңдеу`,
	EditorEditTemplateNameLabel: `Есім`,
	EditorFindLabel: `Табу`,
	EditorFontColorLabel: `Қаріп түсі`,
	EditorFormatPaintLabel: `Пішімдеу бояуы`,
	EditorInSelectionLabel: ` Таңдау`,
	EditorInsertImageLabel: `Суретті салыңыз`,
	EditorInsertLinkLabel: `Сілтеме салыңыз`,
	EditorInsertVideoLabel: `Бейнені салыңыз`,
	EditorMatchCaseLabel: ` Сәйкестік корпусы`,
	EditorNewTemplateLabel: `Жаңа шаблон`,
	EditorNextTemplateLabel: `Келесі шаблон`,
	EditorPasteButtonAppendBeginLabel: `Қосу ...`,
	EditorPasteButtonLabel: `Ұту`,
	EditorPasteTemplateWatermark: `Қою мәтінді енгізіңіз ...`,
	EditorPrevTemplateLabel: `Алдыңғы шаблон`,
	EditorRegExLabel: ` Тұрақты өрнек`,
	EditorReplaceAllLabel: `Барлығын ауыстырыңыз`,
	EditorReplaceLabel: `Орнын басу`,
	EditorTemplateContactHint: `<p> Қол жетімді контактілерді пайдалану (FECTUREL плагині қажет) Бұл өріс осы құжаттың барлық даналары үшін осы құжаттың барлық даналары үшін пайдаланылады немесе кез-келген жағдайда ол кейінірек сілтеме жасалады. </ p> <p> Егер электрондық пошта мекенжайы таңдаңыз Мұнда сіз таңдаған контактінің электрондық поштасы осы құжаттағы барлық даналар үшін пайдаланылады. </ p>`,
	EditorTemplateContactName: `Байланысу`,
	EditorTemplateDateTimeCustomHint: `yy = Қысқа жыл <br/> YYYY = жыл! . Апта күні (Дүйсенбі, сейсенбі ... жексенбі) <br/> e = Аптаның қысқа күні. 3, 21, 22N, 23, 31, 44, 4-ші ...) <br/> h = сағат (0-12) сағат (0-12) <br/> hh = сағ / сағат (00-12) <br / > H = тәулігіне (0-23), күніне сағат (0-23) <br/> MM = MOOLT = MOOLD <br/> SS = секундтық <br/> sss = sss = milliseconds <br/> A = AM / PM белгісі <br/> p = a.m./p.m. саудахана`,
	EditorTemplateDateTimeCustomLabel: `Әдет-ғұрып`,
	EditorTemplateDateTimeHint: `Ағымдағы күн және / немесе уақыт олар қойылған кезде DateTime шаблондары үшін ауыстырылады.`,
	EditorTemplateDateTimeName: `Күн уақыты`,
	EditorTemplateDynamicHint: `<p> Осы шаблонның барлық орын алуы берілген мәтінді пайдаланады. </ p>`,
	EditorTemplateDynamicName: `Динамикалық`,
	EditorTemplateEmptyPlaceholder: `{0} бос ...`,
	EditorTemplateStaticHint: `<p> Осы шаблонның барлық орын алуы берілген мәтінді пайдаланады. </ p>`,
	EditorTemplateStaticName: `Статистикалық`,
	EditorTemplateTeaserText: `Жақында келеді!`,
	EditorWatermark: `Өтінемін күте тұрыңыз...`,
	EditorWholeWordLabel: ` Бүкіл сөз`,
	EditorWrapLabel: ` Орау`,

};