var UiStrings = {
	EditorAppendCloseLabel: `បញ្ចប់ការបន្ថែម`,
	EditorAppendInlineModeLabel: `បើកដំណើរការប្លុក`,
	EditorAppendLineModeLabel: `បើកដំណើរការក្នុងជួរ`,
	EditorAppendManualModeLabel: `បិទបើកសៀវភៅណែនាំ`,
	EditorAppendNonManualModeLabel: `បិទបើកសៀវភៅណែនាំ`,
	EditorAppendPauseLabel: `ការផ្អាកផ្អាក`,
	EditorAppendPostLabel: `បិទបើកមុន`,
	EditorAppendPreLabel: `បិទបើកមុន`,
	EditorAppendResumeLabel: `ការបន្ថែមបន្តទៀត`,
	EditorBgColorLabel: `ពណ៌ផ្ទៃខាងក្រោយ`,
	EditorClearAllLabel: `លុបចេញ​ទាំងអស់`,
	EditorClipboardFormatsLabel: `ទំរង់ឃ្លិបបក`,
	EditorConfirmNtfTitle: `បហ្ជាក់`,
	EditorDeleteAllButtonText: `លុប​ទាំងអស់`,
	EditorDeleteAllTemplatesNtfText: `តើអ្នកពិតជាចង់លុបការប្រើប្រាស់ទាំងអស់នៃ '{0}' ទេ?

នេះមិនអាចធ្វើវិញបានទេ!`,
	EditorEditTemplateDetailsLabel: `កែសម្រួលព័ត៌មានលំអិត`,
	EditorEditTemplateNameLabel: `ឈ្ផោហ`,
	EditorFindLabel: `រកឃើញ`,
	EditorFontColorLabel: `ពណ៌ពុម្ពអក្សរ`,
	EditorFormatPaintLabel: `ធ្វើទ្រង់ទ្រាយថ្នាំលាបទ្រង់ទ្រាយ`,
	EditorInSelectionLabel: ` ក្នុងការជ្រើសរើស`,
	EditorInsertImageLabel: `បញ្ចូលរូបភាព`,
	EditorInsertLinkLabel: `បញ្ចូលតំណ`,
	EditorInsertVideoLabel: `បញ្ចូលវីដេអូ`,
	EditorMatchCaseLabel: ` ករណី​ការ​ប្រកួត`,
	EditorNewTemplateLabel: `គំរូថ្មី`,
	EditorNextTemplateLabel: `គំរូបន្ទាប់`,
	EditorPasteButtonAppendBeginLabel: `បន្ថែមទៀត ...`,
	EditorPasteButtonLabel: `រេនាយោហរការ`,
	EditorPasteTemplateWatermark: `បញ្ចូលអត្ថបទបិទភ្ជាប់ ...`,
	EditorPrevTemplateLabel: `គំរូមុន`,
	EditorRegExLabel: ` កន្សោមធម្មតា`,
	EditorReplaceAllLabel: `ជំនួសទាំងអស់`,
	EditorReplaceLabel: `ដាក់លើងវិញ`,
	EditorTemplateContactHint: `<p>ការ ប្រើ ទំនាក់ទំនង ដែល មាន (តម្រូវ ឲ្យ មាន កម្មវិធី ជំនួយ fetcher) វាល នេះ នឹង ត្រូវ បាន ប្រើ សម្រាប់ គ្រប់ ករណី នៃ template នេះ នៅ ទូទាំង ឯកសារ នេះ ឬ នៅ ក្នុង ឯកសារ ណាមួយ ដែល វា នឹង ត្រូវ បាន យោង នៅ ពេល ក្រោយ ។</p><p> ដូច្នេះ ឧទាហរណ៍ ប្រសិន បើ ជ្រើស អាសយដ្ឋាន អ៊ីមែល នៅ ទីនេះ នោះ វាល អ៊ីមែល នៃ ទំនាក់ទំនង ដែល អ្នក ជ្រើស នឹង ត្រូវ បាន ប្រើ សម្រាប់ រាល់ ករណី នៅ ក្នុង ឯកសារ នេះ ។</p>`,
	EditorTemplateContactName: `ការតាក់តង`,
	EditorTemplateDateTimeCustomHint: `y = ឆ្នាំខ្លី<br/>yyy = ឆ្នាំវែង<br/>M = ខែ (1-12)<br/>MM = ខែ (01-12)<br/>MMM = ខែ កាត់ (Jan, Feb ... Dec)<br/>MMMM = ខែវែង (មករា កុម្ភៈ ... ធ្នូ)<br/>d = ថ្ងៃ (1 - 31)<br/>dd = ថ្ងៃ (01 - 31)<br/>ddd = ថ្ងៃនៃសប្តាហ៍ក្នុងពាក្យ (ច័ន្ទ, ថ្ងៃអង្គារ ... ថ្ងៃអាទិត្យ)<br/>E = ថ្ងៃខ្លីនៃសប្តាហ៍ក្នុងពាក្យ (ម៉ន, ធូ ... ព្រះអាទិត្យ)<br/>ឃ - ថ្ងៃ អក អរឌីណាល់ (១, ទី ២, ទី ៣, ទី ២១, ទី ២២, ទី ២៣, ទី ៣១, ទី ៤...)<br/>h = ម៉ោងក្នុង am/pm (0-12)<br/>hh = ម៉ោងក្នុង am/pm (00-12)<br/>H = ម៉ោងក្នុងមួយថ្ងៃ (0-23)<br/>HH = ម៉ោងក្នុងមួយថ្ងៃ (00-23)<br/>មម = នាទី<br/>ss = វិនាទី<br/>SSS = មីល្លីវិនាទី<br/>a = AM/PM marker<br/>p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `តមន្យេមតមលាប់`,
	EditorTemplateDateTimeHint: `កាលបរិច្ឆេទបច្ចុប្បន្ននិង / ឬពេលវេលានឹងត្រូវបានជំនួសសម្រាប់គំរូ DETETINE នៅពេលពួកគេបានបិទភ្ជាប់។`,
	EditorTemplateDateTimeName: `ពេល​ណាត់ជួប`,
	EditorTemplateDynamicHint: `<p>រាល់ ការ កើត ឡើង នៃ ពុម្ព នេះ នឹង ប្រើ អត្ថបទ ដែល បាន ផ្ដល់ ឲ្យ ។</p>`,
	EditorTemplateDynamicName: `ដេលក្ផានមងាង`,
	EditorTemplateEmptyPlaceholder: `{0} គឺទទេ ...`,
	EditorTemplateStaticHint: `<p>រាល់ ការ កើត ឡើង នៃ ពុម្ព នេះ នឹង ប្រើ អត្ថបទ ដែល បាន ផ្ដល់ ឲ្យ ។</p>`,
	EditorTemplateStaticName: `ដេលឋិតរមដដែល`,
	EditorTemplateTeaserText: `ចូលមកឆាប់ៗនេះ!`,
	EditorWatermark: `សូមរង់ចាំ ...`,
	EditorWholeWordLabel: ` ពាក្យទាំងមូល`,
	EditorWrapLabel: ` រុំជុំវិញ`,

};