var UiStrings = {
	EditorAppendCloseLabel: `சேர்ந்து முடிக்கவும்`,
	EditorAppendInlineModeLabel: `தொகுதியை இயக்கு`,
	EditorAppendLineModeLabel: `இன்லைன் இயக்கவும்`,
	EditorAppendManualModeLabel: `கையேட்டை மாற்றவும்`,
	EditorAppendNonManualModeLabel: `கையேட்டை மாற்றவும்`,
	EditorAppendPauseLabel: `இடைநிறுத்தம்`,
	EditorAppendPostLabel: `முன் மாற்று`,
	EditorAppendPreLabel: `முன் மாற்று`,
	EditorAppendResumeLabel: `மறுதொடக்கம் செய்யுங்கள்`,
	EditorBgColorLabel: `பின்னணி நிறம்`,
	EditorClearAllLabel: `அனைத்தையும் அழி`,
	EditorClipboardFormatsLabel: `கிளிப்போர்டு வடிவங்கள்`,
	EditorConfirmNtfTitle: `உறுதிப்படுத்தவும்`,
	EditorDeleteAllButtonText: `அனைத்தையும் நீக்கு`,
	EditorDeleteAllTemplatesNtfText: `'{0}' இன் அனைத்து பயன்பாடுகளையும் நீக்க விரும்புகிறீர்களா?

இதை முடிக்காமல் விட கூடாது!`,
	EditorEditTemplateDetailsLabel: `விவரங்களைத் திருத்தவும்`,
	EditorEditTemplateNameLabel: `பெயர்`,
	EditorFindLabel: `கண்டுபிடி`,
	EditorFontColorLabel: `எழுத்துரு நிறம்`,
	EditorFormatPaintLabel: `வடிவமைப்பு வண்ணப்பூச்சு`,
	EditorInSelectionLabel: ` தேர்வில்`,
	EditorInsertImageLabel: `படத்தைச் செருகவும்`,
	EditorInsertLinkLabel: `இணைப்பைச் செருகவும்`,
	EditorInsertVideoLabel: `வீடியோவைச் செருகவும்`,
	EditorMatchCaseLabel: ` போட்டி வழக்கு`,
	EditorNewTemplateLabel: `புதிய வார்ப்புரு`,
	EditorNextTemplateLabel: `அடுத்த வார்ப்புரு`,
	EditorPasteButtonAppendBeginLabel: `சேர்க்க ...`,
	EditorPasteButtonLabel: `ஒட்டவும்`,
	EditorPasteTemplateWatermark: `பேஸ்ட் உரையை உள்ளிடவும் ...`,
	EditorPrevTemplateLabel: `முந்தைய வார்ப்புரு`,
	EditorRegExLabel: ` வழக்கமான வெளிப்பாடு`,
	EditorReplaceAllLabel: `அனைத்தையும் மாற்று`,
	EditorReplaceLabel: `மாற்றவும்`,
	EditorTemplateContactHint: `<p>கிடைக்கக்கூடிய தொடர்புகளைப் பயன்படுத்தி (ஒரு ஃபெட்சர் சொருகி தேவை) இந்த ஆவணம் முழுவதும் இந்த வார்ப்புருவின் அனைத்து நிகழ்வுகளுக்கும் இந்த புலம் பயன்படுத்தப்படும், அல்லது பின்னர் குறிப்பிடப்படும்.</p><p> எனவே, எடுத்துக்காட்டாக, இங்கே மின்னஞ்சல் முகவரியைத் தேர்ந்தெடுத்தால், நீங்கள் தேர்ந்தெடுக்கும் தொடர்பின் மின்னஞ்சல் புலம் இந்த ஆவணத்தில் உள்ள அனைத்து நிகழ்வுகளுக்கும் பயன்படுத்தப்படும்.</p>`,
	EditorTemplateContactName: `தொடர்பு`,
	EditorTemplateDateTimeCustomHint: `yy = குறுகிய ஆண்டு<br/>yyyy = நீண்ட ஆண்டு<br/>M = மாதம் (1-12)<br/>MM = மாதம் (01-12)<br/>MMM = மாதம் சுருக்கம் (ஜனவரி, பிப்ரவரி ... டிசம்பர்)<br/>MMMM = நீண்ட மாதம் (ஜனவரி, பிப்ரவரி ... டிசம்பர்)<br/>d = நாள் (1 - 31)<br/>DD = நாள் (01 - 31)<br/>ddd = வார்த்தைகளில் வாரத்தின் நாள் (திங்கள், செவ்வாய் ... ஞாயிற்றுக்கிழமை)<br/>E = சொற்களில் வாரத்தின் குறுகிய நாள் (திங்கள், செவ்வாய் ... சூரியன்)<br/>D - சாதாரண நாள் (1வது, 2வது, 3வது, 21வது, 22வது, 23வது, 31வது, 4வது...)<br/>h = AM / PM இல் மணி (0-12)<br/>hh = AM/PM இல் மணி (00-12)<br/>H = பகலில் மணி (0-23)<br/>HH = பகலில் மணி (00-23)<br/>மிமீ = நிமிடம்<br/>ss = இரண்டாவது<br/>SSS = மில்லி விநாடிகள்<br/>a = AM/PM மார்க்கர்<br/>P = a.m./p.m. குறிப்பான்`,
	EditorTemplateDateTimeCustomLabel: `வழக்கம்`,
	EditorTemplateDateTimeHint: `தற்போதைய தேதி மற்றும்/அல்லது நேரம் தேதிநேர வார்ப்புருக்கள் ஒட்டப்படும் போது மாற்றாக மாற்றப்படும்.`,
	EditorTemplateDateTimeName: `தேதி நேரம்`,
	EditorTemplateDynamicHint: `<p>இந்த வார்ப்புருவின் அனைத்து நிகழ்வுகளும் வழங்கப்பட்ட உரையைப் பயன்படுத்தும்.</p>`,
	EditorTemplateDynamicName: `மாறும்`,
	EditorTemplateEmptyPlaceholder: `{0} காலியாக உள்ளது ...`,
	EditorTemplateStaticHint: `<p>இந்த வார்ப்புருவின் அனைத்து நிகழ்வுகளும் வழங்கப்பட்ட உரையைப் பயன்படுத்தும்.</p>`,
	EditorTemplateStaticName: `நிலையான`,
	EditorTemplateTeaserText: `மேலும் விரைவில் வருகிறது!`,
	EditorWatermark: `தயவுசெய்து காத்திருங்கள் ...`,
	EditorWholeWordLabel: ` முழு சொல்`,
	EditorWrapLabel: ` சுற்றி மடக்கு`,

};