var UiStrings = {
	EditorAppendCloseLabel: `ضمیمه کردن`,
	EditorAppendInlineModeLabel: `بلوک را فعال کنید`,
	EditorAppendLineModeLabel: `Inline را فعال کنید`,
	EditorAppendManualModeLabel: `دفترچه راهنما`,
	EditorAppendNonManualModeLabel: `دفترچه راهنما`,
	EditorAppendPauseLabel: `مکث ضمیمه`,
	EditorAppendPostLabel: `قبل از`,
	EditorAppendPreLabel: `قبل از`,
	EditorAppendResumeLabel: `رزومه ضمیمه`,
	EditorBgColorLabel: `رنگ پس زمینه`,
	EditorClearAllLabel: `همه را پاک کن`,
	EditorClipboardFormatsLabel: `قالب های کلیپ بورد`,
	EditorColorChooserTitle: `رنگ ویرایشگر`,
	EditorConfirmNtfTitle: `تایید`,
	EditorDeleteAllButtonText: `همه را حذف کنید`,
	EditorDeleteAllTemplatesNtfText: `آیا مطمئن هستید که می خواهید تمام کاربردهای "{0}" را حذف کنید؟

این قابل بازگشت نیست!`,
	EditorEditTemplateDetailsLabel: `جزئیات ویرایش`,
	EditorEditTemplateNameLabel: `نام`,
	EditorFindLabel: `پیدا کردن`,
	EditorFontColorLabel: `رنگ فونت`,
	EditorFormatPaintLabel: `رنگ قالب`,
	EditorInSelectionLabel: ` در انتخاب`,
	EditorInsertImageLabel: `درج تصویر`,
	EditorInsertLinkLabel: `پیوند`,
	EditorInsertVideoLabel: `وارد کردن فیلم`,
	EditorLinkButtonText: `صرفه جویی`,
	EditorLinkLabel: `لینک را وارد کنید`,
	EditorLinkPlaceholder: `آدرس اینترنتی را وارد کنید`,
	EditorMatchCaseLabel: ` مورد تطبیق`,
	EditorNewTemplateLabel: `الگوی جدید`,
	EditorNextTemplateLabel: `الگوی بعدی`,
	EditorPasteButtonAppendBeginLabel: `ضمیمه ...`,
	EditorPasteButtonLabel: `خمیر`,
	EditorPasteTemplateWatermark: `متن خمیر را وارد کنید ...`,
	EditorPrevTemplateLabel: `الگوی قبلی`,
	EditorRegExLabel: ` عبارت منظم`,
	EditorReplaceAllLabel: `جایگزین همه`,
	EditorReplaceLabel: `جایگزین کردن`,
	EditorTemplateContactHint: `<p>با استفاده از اشناهای موجود ) نیاز به وصلۀ واکشی ( این زمینه برای همۀ نمونههای این قالب در سراسر این سند یا در هر موردی که بعدا به ان ارجاع داده خواهد شد ، استفاده خواهد شد.</p><p> بنابراین به عنوان مثال اگر ادرس ایمیل را در اینجا انتخاب کنید، فیلد ایمیل مخاطبی که انتخاب می کنید برای همه موارد موجود در این سند استفاده می شود.</p>`,
	EditorTemplateContactName: `مخاطب`,
	EditorTemplateDateTimeCustomHint: `YY = سال کوتاه<br/>yyyyy = سال طولانی<br/>M = ماه (1-12)<br/>MM = ماه (01-12)<br/>MMM = اختصار ماه (ژانویه، فوریه ... دسامبر)<br/>MMMM = ماه طولانی (ژانویه، فوریه ... دسامبر)<br/>d = روز (1 - 31)<br/>dd = روز (01 - 31)<br/>ddd = روز هفته در کلمات (دوشنبه، سه شنبه ... یکشنبه)<br/>E = روز کوتاه هفته در کلمات (دوشنبه، سه شنبه ... خورشید)<br/>D - روز ترتیبی (1، 2، 3، 21، 22، 23، 31، 4 ...)<br/>h = ساعت در am / pm (0-12)<br/>hh = ساعت در am / pm (00-12)<br/>H = ساعت در روز (0-23)<br/>HH = ساعت در روز (00-23)<br/>mm = دقیقه<br/>ss = ثانیه<br/>SSS = میلی ثانیه<br/>a = نشانگر AM / PM<br/>p = نشانگر صبح / بعد از ظهر`,
	EditorTemplateDateTimeCustomLabel: `سفارشی`,
	EditorTemplateDateTimeHint: `تاریخ و/یا زمان فعلی در هنگام چسباندن برای الگوهای DateTime جایگزین می شود.`,
	EditorTemplateDateTimeName: `زمان قرار`,
	EditorTemplateDynamicHint: `<p>تمام رخدادهای این قالب از متن ارائه شده استفاده خواهند کرد.</p>`,
	EditorTemplateDynamicName: `پویا`,
	EditorTemplateEmptyPlaceholder: `{0} خالی است ...`,
	EditorTemplateStaticHint: `<p>تمام رخدادهای این قالب از متن ارائه شده استفاده خواهند کرد.</p>`,
	EditorTemplateStaticName: `ثابت`,
	EditorTemplateTeaserText: `به زودی!`,
	EditorTt1: `کلیک`,
	EditorTt2: `ویرایش '<em> {0} </em>' ...`,
	EditorTt3: `ویرایش رنگ ...`,
	EditorTt4: `حذف '<em> {0} </em>' ...`,
	EditorTt5: `حذف مورد`,
	EditorTt6: `پيگيري كردن ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `لطفا صبر کنید...`,
	EditorWholeWordLabel: ` کلمه کلیدی`,
	EditorWrapLabel: ` پیچیدن`,

};