var UiStrings = {
	EditorAppendCloseLabel: `დასრულების დასრულება`,
	EditorAppendInlineModeLabel: `ბლოკის ჩართვა`,
	EditorAppendLineModeLabel: `ჩართეთ inline`,
	EditorAppendManualModeLabel: `გადარიცხვის სახელმძღვანელო`,
	EditorAppendNonManualModeLabel: `გადარიცხვის სახელმძღვანელო`,
	EditorAppendPauseLabel: `პაუზის დანართი`,
	EditorAppendPostLabel: `ადრე გადარიცხვა`,
	EditorAppendPreLabel: `ადრე გადარიცხვა`,
	EditorAppendResumeLabel: `განაახლეთ დანართი`,
	EditorBgColorLabel: `Ფონის ფერი`,
	EditorClearAllLabel: `Ყველაფრის გასუფთავება`,
	EditorClipboardFormatsLabel: `ბუფერული ფორმატები`,
	EditorConfirmNtfTitle: `დადასტურება`,
	EditorDeleteAllButtonText: `წაშალეთ ყველა`,
	EditorDeleteAllTemplatesNtfText: `დარწმუნებული ხართ, რომ გსურთ წაშალოთ '{0}' ყველა გამოყენება?

ეს არ შეიძლება გაუქმდეს!`,
	EditorEditTemplateDetailsLabel: `დეტალების რედაქტირება`,
	EditorEditTemplateNameLabel: `სახელი`,
	EditorFindLabel: `პოვნა`,
	EditorFontColorLabel: `Შრიფტის ფერი`,
	EditorFormatPaintLabel: `ფორმატის საღებავი`,
	EditorInSelectionLabel: ` შერჩევაში`,
	EditorInsertImageLabel: `გამოსახულების ჩასმა`,
	EditorInsertLinkLabel: `ჩადეთ ბმული`,
	EditorInsertVideoLabel: `ჩადეთ ვიდეო`,
	EditorMatchCaseLabel: ` მატჩის საქმე`,
	EditorNewTemplateLabel: `ახალი შაბლონი`,
	EditorNextTemplateLabel: `შემდეგი შაბლონი`,
	EditorPasteButtonAppendBeginLabel: `დანართი ...`,
	EditorPasteButtonLabel: `პასი`,
	EditorPasteTemplateWatermark: `შეიყვანეთ პასტის ტექსტი ...`,
	EditorPrevTemplateLabel: `წინა შაბლონი`,
	EditorRegExLabel: ` რეგულარული გამოხატულება`,
	EditorReplaceAllLabel: `შეცვალეთ ყველა`,
	EditorReplaceLabel: `შეცვლა`,
	EditorTemplateContactHint: `<p> ხელმისაწვდომი კონტაქტების გამოყენებით (მოითხოვს Fetcher მოდულს) ეს ველი გამოყენებული იქნება ამ შაბლონის ყველა შემთხვევაში ამ დოკუმენტში, ან ნებისმიერში, მას მოგვიანებით მოიხსენიებთ. </p> <p> მაგალითად, თუ აირჩიეთ ელ.ფოსტის მისამართი აქ შემდეგ თქვენს მიერ არჩეული კონტაქტის ელ.ფოსტის ველი გამოიყენება ამ დოკუმენტში ყველა ინსტანციისთვის. </p>`,
	EditorTemplateContactName: `კონტაქტი`,
	EditorTemplateDateTimeCustomHint: `yy = მოკლე წელი <br/> yyyy = გრძელი წელი <br/> m = თვე (1-12) <br/> mm = თვე (01-12) . დეკ) <br/> mmmm = გრძელი თვე (იანვარი, თებერვალი ... დეკემბერი) კვირის დღე სიტყვებით (ორშაბათი, სამშაბათი ... კვირა) <br/> E = კვირის მოკლე დღე სიტყვებით (ორშაბათს, მზე) მე -3, 21st, 22nd, 23-ე, 31-ე, მე -4 ...) <br/> H = საათი AM/PM- ში (0-12) <br/> HH = საათი AM/PM- ში (00-12) <BR/ > H = დღეში საათში (0-23) <br/> HH = დღეში საათში (00-23) A = AM/PM მარკერი <br/> P = A.M./P.M. ნიშანი`,
	EditorTemplateDateTimeCustomLabel: `ჩვეულება`,
	EditorTemplateDateTimeHint: `მიმდინარე თარიღი ან/და დრო შეიცვალა DateTime შაბლონებისთვის, როდესაც ისინი ჩასვით.`,
	EditorTemplateDateTimeName: `თარიღი დრო`,
	EditorTemplateDynamicHint: `<p> ამ შაბლონის ყველა შემთხვევა გამოიყენებს მოცემულ ტექსტს. </p>`,
	EditorTemplateDynamicName: `დინამიური`,
	EditorTemplateEmptyPlaceholder: `{0} ცარიელია ...`,
	EditorTemplateStaticHint: `<p> ამ შაბლონის ყველა შემთხვევა გამოიყენებს მოცემულ ტექსტს. </p>`,
	EditorTemplateStaticName: `სტატიკური`,
	EditorTemplateTeaserText: `Უფრო მეტი იქნება მალე!`,
	EditorWatermark: `Გთხოვთ მოიცადოთ...`,
	EditorWholeWordLabel: ` მთელი სიტყვა`,
	EditorWrapLabel: ` გახეხეთ გარშემო`,

};