var UiStrings = {
	EditorAppendCloseLabel: `Përfundoni Shtojcën`,
	EditorAppendInlineModeLabel: `Aktivizo bllokun`,
	EditorAppendLineModeLabel: `Aktivizo Inline`,
	EditorAppendManualModeLabel: `Manuali i ndryshuar`,
	EditorAppendNonManualModeLabel: `Manuali i ndryshuar`,
	EditorAppendPauseLabel: `Pauzë shtoj`,
	EditorAppendPostLabel: `Toggle më parë`,
	EditorAppendPreLabel: `Toggle më parë`,
	EditorAppendResumeLabel: `Rifilloj shtojcën`,
	EditorBgColorLabel: `Ngjyrë e sfondit`,
	EditorClearAllLabel: `Pastroji të gjitha`,
	EditorClipboardFormatsLabel: `Formate clipboard`,
	EditorConfirmNtfTitle: `Konfirmoj`,
	EditorDeleteAllButtonText: `Fshij te gjitha`,
	EditorDeleteAllTemplatesNtfText: `A jeni i sigurt që doni të fshini të gjitha përdorimet e '{0}'?

Kjo nuk mund të zhbëhet!`,
	EditorEditTemplateDetailsLabel: `Redakto detajet`,
	EditorEditTemplateNameLabel: `Emër`,
	EditorFindLabel: `Gjej`,
	EditorFontColorLabel: `Ngjyra e shkronjave`,
	EditorFormatPaintLabel: `Bojë formati`,
	EditorInSelectionLabel: ` Në përzgjedhje`,
	EditorInsertImageLabel: `Vendosni imazhin`,
	EditorInsertLinkLabel: `Vendosni lidhjen`,
	EditorInsertVideoLabel: `Fut video`,
	EditorMatchCaseLabel: ` Rast i ndeshjes`,
	EditorNewTemplateLabel: `Shabllon i ri`,
	EditorNextTemplateLabel: `Modeli tjetër`,
	EditorPasteButtonAppendBeginLabel: `Shtoj ...`,
	EditorPasteButtonLabel: `Ngjit`,
	EditorPasteTemplateWatermark: `Futni tekstin e pastës ...`,
	EditorPrevTemplateLabel: `Shablloni i mëparshëm`,
	EditorRegExLabel: ` Shprehje e rregullt`,
	EditorReplaceAllLabel: `Zëvendësoni të gjitha`,
	EditorReplaceLabel: `Zëvendësoj`,
	EditorTemplateContactHint: `<p> Përdorimi i kontakteve të disponueshme (kërkon një shtojcë fetcher) Kjo fushë do të përdoret për të gjitha rastet e këtij shablloni në të gjithë këtë dokument ose në çfarëdo që do të referohet më vonë. Këtu atëherë fusha e postës elektronike të kontaktit që zgjidhni do të përdoret për të gjitha rastet në këtë dokument. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = vit i shkurtër <br/> yyyy = vit i gjatë <br/> m = muaj (1-12) <br/> mm = muaj (01-12) <br/> mmm = shkurtim i muajit (Jan, Shkurt .. . Dhjetor) <br/> mmmm = muaj i gjatë (janar, shkurt ... dhjetor) <br/> d = ditë (1 - 31) <br/> dd = ditë (01 - 31) <br/> ddd = Dita e javës me fjalë (e hënë, e martë ... e diel) <br/> e = ditë e shkurtër e javës me fjalë (e hënë, e martë ... diell) <br/> d - dita e zakonshme (1, 2, 3, 21, 22, 23, 31, 4 ...) <br/> h = orë në AM/PM (0-12) <br/> hh = orë në AM/PM (00-12) <Br/ > H = orë në ditë (0-23) <br/> hh = orë në ditë (00-23) <br/> mm = minutë <br/> ss = e dyta <br/> sss = milisekonda <br/> A = AM/PM MARKER <br/> p = a.m./p.m. shënues`,
	EditorTemplateDateTimeCustomLabel: `I zakonshëm`,
	EditorTemplateDateTimeHint: `Data aktuale dhe/ose koha do të zëvendësohet për shabllonet e DateTime kur ato ngjiten.`,
	EditorTemplateDateTimeName: `Koha e datës`,
	EditorTemplateDynamicHint: `<p> Të gjitha ndodhjet e këtij shablloni do të përdorin tekstin e dhënë. </p>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} është bosh ...`,
	EditorTemplateStaticHint: `<p> Të gjitha ndodhjet e këtij shablloni do të përdorin tekstin e dhënë. </p>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Më shumë së shpejti!`,
	EditorWatermark: `Te lutem prit...`,
	EditorWholeWordLabel: ` Fjalë e plotë`,
	EditorWrapLabel: ` Mbështjellë`,

};