var UiStrings = {
	EditorAppendCloseLabel: `Долазак на допис`,
	EditorAppendInlineModeLabel: `Омогући блок`,
	EditorAppendLineModeLabel: `Омогућите инлине`,
	EditorAppendManualModeLabel: `Пребацивање приручника`,
	EditorAppendNonManualModeLabel: `Пребацивање приручника`,
	EditorAppendPauseLabel: `Прилог паузе`,
	EditorAppendPostLabel: `Пре тога пре`,
	EditorAppendPreLabel: `Пре тога пре`,
	EditorAppendResumeLabel: `Настављање прилога`,
	EditorBgColorLabel: `Боја позадине`,
	EditorClearAllLabel: `Избриши све`,
	EditorClipboardFormatsLabel: `Цлипбоард Форматс`,
	EditorConfirmNtfTitle: `Потврди`,
	EditorDeleteAllButtonText: `Избришите све`,
	EditorDeleteAllTemplatesNtfText: `Јесте ли сигурни да желите да избришете све употребе '{0}'?

Ово се не може поништити!`,
	EditorEditTemplateDetailsLabel: `Уређивање детаља`,
	EditorEditTemplateNameLabel: `Назив`,
	EditorFindLabel: `Пронаћи`,
	EditorFontColorLabel: `Боја фонта`,
	EditorFormatPaintLabel: `Формат Боја`,
	EditorInSelectionLabel: ` У избору`,
	EditorInsertImageLabel: `Убаци слику`,
	EditorInsertLinkLabel: `Уметнути линк`,
	EditorInsertVideoLabel: `Уметните видео`,
	EditorMatchCaseLabel: ` Случај утакмице`,
	EditorNewTemplateLabel: `Нови шаблон`,
	EditorNextTemplateLabel: `Следећи образац`,
	EditorPasteButtonAppendBeginLabel: `Додати...`,
	EditorPasteButtonLabel: `Залепити`,
	EditorPasteTemplateWatermark: `Унесите налепи текст ...`,
	EditorPrevTemplateLabel: `Претходни предложак`,
	EditorRegExLabel: ` Регуларни израз`,
	EditorReplaceAllLabel: `Замените`,
	EditorReplaceLabel: `Заменити`,
	EditorTemplateContactHint: `<p>Korišćenje dostupnih kontakata (zahteva dodatnu komponentu za dobavljanje) ovo polje će biti korišćeno za sve instance ovog predloška u ovom dokumentu ili u bilo kom od njih na koje će kasnije biti upućeno.</p><p> Na primer, ako ovde izaberete e-adresu, polje e-pošte kontakta koje izaberete biće korišćeno za sve instance u ovom dokumentu.</p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = kratka godina<br/>yyyy = duga godina<br/>M = mesec (1-12)<br/>MM = mesec (01-12)<br/>MMM = skraćenica meseca (Jan, Feb ... Dec)<br/>MMMM = dug mesec (januar, februar ... Decembar)<br/>d = dan (1 - 31)<br/>dd = dan (01 - 31)<br/>ddd = dan u nedelji rečima (ponedeljak, utorak ... Nedelja)<br/>E = kratak dan u nedelji u rečima (Mon, Tue ... Sunce)<br/>D - Ordinalni dan (1, 2., 3.<br/>h = sat u am/pm (0-12)<br/>hh = sat u am/pm (00-12)<br/>H = sat u danu (0-23)<br/>HH = sat u danu (00-23)<br/>mm = minut<br/>ss = second<br/>SSS = milisekunde<br/>a = AM/PM marker<br/>p = a.m./p.m. označivač`,
	EditorTemplateDateTimeCustomLabel: `Обичај`,
	EditorTemplateDateTimeHint: `Тренутни датум и / или време биће замењене предлозима ДатеТиме када су залепите.`,
	EditorTemplateDateTimeName: `Датум време`,
	EditorTemplateDynamicHint: `<p>Sve pojave ovog predloška će koristiti navedeni tekst.</p>`,
	EditorTemplateDynamicName: `Динамичан`,
	EditorTemplateEmptyPlaceholder: `{0} је празно ...`,
	EditorTemplateStaticHint: `<p>Sve pojave ovog predloška će koristiti navedeni tekst.</p>`,
	EditorTemplateStaticName: `Статички`,
	EditorTemplateTeaserText: `Више ускоро!`,
	EditorWatermark: `Сачекајте...`,
	EditorWholeWordLabel: ` Целе речи`,
	EditorWrapLabel: ` Замотати око`,

};