var UiStrings = {
	EditorAppendCloseLabel: `Voltooi toevoegen`,
	EditorAppendInlineModeLabel: `Schakel blok in`,
	EditorAppendLineModeLabel: `Schakel inline in`,
	EditorAppendManualModeLabel: `Schakelhandleiding`,
	EditorAppendNonManualModeLabel: `Schakelhandleiding`,
	EditorAppendPauseLabel: `Pauzeer toevoegen`,
	EditorAppendPostLabel: `Schakel eerder in`,
	EditorAppendPreLabel: `Schakel eerder in`,
	EditorAppendResumeLabel: `Hervatten toevoegen`,
	EditorBgColorLabel: `Achtergrond kleur`,
	EditorClearAllLabel: `Wis alles`,
	EditorClipboardFormatsLabel: `Klembordformaten`,
	EditorColorChooserTitle: `Redacteur kleur`,
	EditorConfirmNtfTitle: `Bevestigen`,
	EditorDeleteAllButtonText: `Verwijder alles`,
	EditorDeleteAllTemplatesNtfText: `Weet u zeker dat u alle gebruik van '{0}' wilt verwijderen?

Dit kan niet ongedaan gemaakt worden!`,
	EditorEditTemplateDetailsLabel: `Details bewerken`,
	EditorEditTemplateNameLabel: `Naam`,
	EditorFindLabel: `Vinden`,
	EditorFontColorLabel: `Lettertype kleur`,
	EditorFormatPaintLabel: `Formaat verf`,
	EditorInSelectionLabel: ` In selectie`,
	EditorInsertImageLabel: `Voeg afbeelding in`,
	EditorInsertLinkLabel: `Voeg link in`,
	EditorInsertVideoLabel: `Video invoegen`,
	EditorLinkButtonText: `Redden`,
	EditorLinkLabel: `Voer link in`,
	EditorLinkPlaceholder: `URL invoeren`,
	EditorMatchCaseLabel: ` Match case`,
	EditorNewTemplateLabel: `Nieuwe sjabloon`,
	EditorNextTemplateLabel: `Volgende sjabloon`,
	EditorPasteButtonAppendBeginLabel: `Toevoegen ...`,
	EditorPasteButtonLabel: `Plakken`,
	EditorPasteTemplateWatermark: `Voer tekst in plakken ...`,
	EditorPrevTemplateLabel: `Vorige sjabloon`,
	EditorRegExLabel: ` Regelmatige expressie`,
	EditorReplaceAllLabel: `Vervang alles`,
	EditorReplaceLabel: `Vervangen`,
	EditorTemplateContactHint: `<p>Met behulp van beschikbare contacten (vereist een fetcher-plug-in) wordt dit veld gebruikt voor alle exemplaren van dit sjabloon in dit document of in een ander waarnaar later wordt verwezen.</p><p> Dus als u hier bijvoorbeeld een e-mailadres selecteert, wordt het e-mailveld van de contactpersoon die u selecteert gebruikt voor alle instanties in dit document.</p>`,
	EditorTemplateContactName: `Contact`,
	EditorTemplateDateTimeCustomHint: `yy = kort jaar<br/>jjjj = lang jaar<br/>M = maand (1-12)<br/>MM = maand (01-12)<br/>MMM = maand afkorting (jan, feb ... Dec)<br/>MMMM = lange maand (januari, februari ... december)<br/>d = dag (1 - 31)<br/>dd = dag (01 - 31)<br/>ddd = dag van de week in woorden (maandag, dinsdag ... Zondag)<br/>E = korte dag van de week in woorden (ma, di ... Zon)<br/>D - Ordinale dag (1e, 2e, 3e, 21e, 22e, 23e, 31e, 4e...)<br/>h = uur in am/pm (0-12)<br/>hh = uur in am/pm (00-12)<br/>H = uur in dag (0-23)<br/>HH = uur in dag (00-23)<br/>mm = minuut<br/>hs = seconde<br/>SSS = milliseconden<br/>a = AM/PM-markering<br/>p = a.m./p.m. markering`,
	EditorTemplateDateTimeCustomLabel: `Aangepast`,
	EditorTemplateDateTimeHint: `De huidige datum en/of tijd worden vervangen door datetime -sjablonen wanneer ze worden geplakt.`,
	EditorTemplateDateTimeName: `Datum Tijd`,
	EditorTemplateDynamicHint: `<p>Alle keren dat dit sjabloon voorkomt, wordt de meegeleverde tekst gebruikt.</p>`,
	EditorTemplateDynamicName: `Dynamisch`,
	EditorTemplateEmptyPlaceholder: `{0} is leeg ...`,
	EditorTemplateStaticHint: `<p>Alle keren dat dit sjabloon voorkomt, wordt de meegeleverde tekst gebruikt.</p>`,
	EditorTemplateStaticName: `Statisch`,
	EditorTemplateTeaserText: `Binnenkort meer!`,
	EditorTt1: `Klik`,
	EditorTt2: `bewerken '<em> {0} </em>' ...`,
	EditorTt3: `Kleur bewerken ...`,
	EditorTt4: `verwijder '<em> {0} </em>' ...`,
	EditorTt5: `Verwijder voorwerp`,
	EditorTt6: `volgen ...`,
	EditorTt7: `goTo '<em> {0} </em>' ...`,
	EditorWatermark: `Even geduld aub...`,
	EditorWholeWordLabel: ` Hele wereld`,
	EditorWrapLabel: ` Omwikkelen`,

};