var UiStrings = {
	EditorAppendCloseLabel: `Završiti dodavanje`,
	EditorAppendInlineModeLabel: `Omogući blok`,
	EditorAppendLineModeLabel: `Omogući inline`,
	EditorAppendManualModeLabel: `Prebacivanje priručnika`,
	EditorAppendNonManualModeLabel: `Prebacivanje priručnika`,
	EditorAppendPauseLabel: `Pauza dodatak`,
	EditorAppendPostLabel: `Prebacivanje prije`,
	EditorAppendPreLabel: `Prebacivanje prije`,
	EditorAppendResumeLabel: `Nastavite dodatak`,
	EditorBgColorLabel: `Boja pozadine`,
	EditorClearAllLabel: `Očistiti sve`,
	EditorClipboardFormatsLabel: `Formati za međuspremnik`,
	EditorConfirmNtfTitle: `Potvrditi`,
	EditorDeleteAllButtonText: `Izbrisati sve`,
	EditorDeleteAllTemplatesNtfText: `Jeste li sigurni da želite izbrisati sve upotrebe '{0}'?

To se ne može poništiti!`,
	EditorEditTemplateDetailsLabel: `Uredite detalje`,
	EditorEditTemplateNameLabel: `Ime`,
	EditorFindLabel: `Pronaći`,
	EditorFontColorLabel: `Boja fonta`,
	EditorFormatPaintLabel: `Format boja`,
	EditorInSelectionLabel: ` U odabiru`,
	EditorInsertImageLabel: `Umetni slika`,
	EditorInsertLinkLabel: `Umetni veza`,
	EditorInsertVideoLabel: `Umetni video`,
	EditorMatchCaseLabel: ` Kutija šibica`,
	EditorNewTemplateLabel: `Novi predložak`,
	EditorNextTemplateLabel: `Sljedeći predložak`,
	EditorPasteButtonAppendBeginLabel: `Dodati...`,
	EditorPasteButtonLabel: `Zalijepiti`,
	EditorPasteTemplateWatermark: `Unesite tekst zalijepljenja ...`,
	EditorPrevTemplateLabel: `Prethodni predložak`,
	EditorRegExLabel: ` Pravilno izražavanje`,
	EditorReplaceAllLabel: `Zamjeni sve`,
	EditorReplaceLabel: `Zamijeniti`,
	EditorTemplateContactHint: `<p>Korištenjem dostupnih kontakata (potreban je dodatak za dohvaćanje) ovo će se polje koristiti za sve instance ovog predloška u ovom dokumentu ili u bilo kojem na koje će se kasnije referencirati.</p><p> Tako, na primjer, ako ovdje odaberete adresu e-pošte, polje e-pošte odabranog kontakta koristit će se za sve instance u ovom dokumentu.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kratka godina<br/>gggg = duga godina<br/>M = mjesec (1-12)<br/>MM = mjesec (01-12)<br/>MMM = kratica mjeseca (siječanj, veljača ... Prosinca)<br/>MMMM = dugi mjesec (siječanj, veljača ... Prosinac)<br/>d = dan (1 - 31)<br/>dd = dan (01 - 31)<br/>ddd = dan u tjednu riječima (ponedjeljak, utorak ... Nedjelja)<br/>E = kratki dan u tjednu riječima (pon, uto ... Sunce)<br/>D - Redni dan (1., 2., 3., 21., 22., 23., 31., 4.)<br/>h = sat u am/pm (0-12)<br/>HH = sat u AM/PM (00-12)<br/>H = sat u danu (0-23)<br/>HH = sat u danu (00-23)<br/>mm = minuta<br/>ss = drugi<br/>SSS = milisekunde<br/>a = AM/PM oznaka<br/>p = oznaka a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Prilagođen`,
	EditorTemplateDateTimeHint: `Trenutni datum i/ili vrijeme bit će zamijenjeni za predloške DateTime kada su zalijepljeni.`,
	EditorTemplateDateTimeName: `Datum vrijeme`,
	EditorTemplateDynamicHint: `<p>Sva pojavljivanja ovog predloška koristit će navedeni tekst.</p>`,
	EditorTemplateDynamicName: `Dinamičan`,
	EditorTemplateEmptyPlaceholder: `{0} je prazan ...`,
	EditorTemplateStaticHint: `<p>Sva pojavljivanja ovog predloška koristit će navedeni tekst.</p>`,
	EditorTemplateStaticName: `Statički`,
	EditorTemplateTeaserText: `Uskoro dolazi!`,
	EditorWatermark: `Molim vas pričekajte ...`,
	EditorWholeWordLabel: ` Cijela riječ`,
	EditorWrapLabel: ` Omotati`,

};