var UiStrings = {
	EditorAppendCloseLabel: `മികച്ചത് പൂർത്തിയാക്കുക`,
	EditorAppendInlineModeLabel: `തടക്കുക പ്രാപ്തമാക്കുക`,
	EditorAppendLineModeLabel: `ഇൻലൈൻ പ്രാപ്തമാക്കുക`,
	EditorAppendManualModeLabel: `മാവൽ ടോഗിൾ ചെയ്യുക`,
	EditorAppendNonManualModeLabel: `മാവൽ ടോഗിൾ ചെയ്യുക`,
	EditorAppendPauseLabel: `താൽക്കാലികമായ കൂട്ടിച്ചേർക്കൽ`,
	EditorAppendPostLabel: `മുമ്പ് ടോഗിൾ ചെയ്യുക`,
	EditorAppendPreLabel: `മുമ്പ് ടോഗിൾ ചെയ്യുക`,
	EditorAppendResumeLabel: `പുനരാരംഭിക്കുക കൂട്ടിച്ചേർക്കുക`,
	EditorBgColorLabel: `പശ്ചാത്തല നിറം`,
	EditorClearAllLabel: `എല്ലാം മായ്ക്കുക`,
	EditorClipboardFormatsLabel: `ക്ലിപ്പ്ബോർഡ് ഫോർമാറ്റുകൾ`,
	EditorConfirmNtfTitle: `ഉറപ്പിക്കുക`,
	EditorDeleteAllButtonText: `എല്ലാം ഇല്ലാതാക്കുക`,
	EditorDeleteAllTemplatesNtfText: `'{0}' ന്റെ എല്ലാ ഉപയോഗങ്ങളും ഇല്ലാതാക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?

ഇത് പഴയപടിയാക്കാൻ കഴിയില്ല!`,
	EditorEditTemplateDetailsLabel: `വിശദാംശങ്ങൾ എഡിറ്റുചെയ്യുക`,
	EditorEditTemplateNameLabel: `പേര്`,
	EditorFindLabel: `കണ്ടെത്തുക`,
	EditorFontColorLabel: `അക്ഷരത്തിന്റെ നിറം`,
	EditorFormatPaintLabel: `ഫോർമാറ്റ് പെയിന്റ്`,
	EditorInSelectionLabel: ` തിരഞ്ഞെടുക്കലിൽ`,
	EditorInsertImageLabel: `ചിത്രം ചേർക്കുക`,
	EditorInsertLinkLabel: `ലിങ്ക് ചേർക്കുക`,
	EditorInsertVideoLabel: `വീഡിയോ ചേർക്കുക`,
	EditorMatchCaseLabel: ` പൊരുത്തക്കേടുകൾ`,
	EditorNewTemplateLabel: `പുതിയ ടെംപ്ലേറ്റ്`,
	EditorNextTemplateLabel: `അടുത്ത ടെംപ്ലേറ്റ്`,
	EditorPasteButtonAppendBeginLabel: `കൂട്ടിച്ചേർക്കുക ...`,
	EditorPasteButtonLabel: `പേസ്റ്റ്`,
	EditorPasteTemplateWatermark: `ഒട്ടിക്കുക വാചകം നൽകുക ...`,
	EditorPrevTemplateLabel: `മുമ്പത്തെ ടെംപ്ലേറ്റ്`,
	EditorRegExLabel: ` പതിവ് എക്സ്പ്രഷൻ`,
	EditorReplaceAllLabel: `എല്ലാം മാറ്റിസ്ഥാപിക്കുക`,
	EditorReplaceLabel: `തിരികെവയ്ക്കുക`,
	EditorTemplateContactHint: `<p> ലഭ്യമായ കോൺടാക്റ്റുകൾ ഉപയോഗിക്കുന്നു (ഒരു ലഭ്യത പ്ലഗിൻ ആവശ്യമാണ്) ഈ ഫീൽഡ് ഈ പ്രമാണത്തിലുടനീളമുള്ള ഈ ടെംപ്ലേറ്റിനായി ഉപയോഗിക്കും. </ p> <p> ഉദാഹരണത്തിന് ഇമെയിൽ വിലാസം തിരഞ്ഞെടുക്കുക ഇവിടെ നിങ്ങൾ തിരഞ്ഞെടുത്ത കോൺടാക്റ്റിന്റെ ഇമെയിൽ ഫീൽഡ് ഈ പ്രമാണത്തിലെ എല്ലാ ഉദാഹരണങ്ങൾക്കും ഉപയോഗിക്കും. </ P>`,
	EditorTemplateContactName: `സന്വര്ക്കം`,
	EditorTemplateDateTimeCustomHint: `YY = ഹ്രസ്വ വർഷം <br/YY = ദൈർഘ്യമുള്ള വർഷം (1-12) <br/> മില്ലീമീറ്റർ (01-12) <br/> മിഎംഎം = മാസ ചുരുക്കെഴുത്ത് (ജനുവരി, ഫെബ്രുവരി .. . Dex) <br/> Mmmm = ദൈർഘ്യമേറിയ മാസം (ജനുവരി, ഫെബ്രുവരി ... ദിവസം) <br/> D = ദിവസം (1 - 31) ദിവസം (01 - 31) <br/> DDD = വാക്കുകളിൽ ആഴ്ചയിലെ ദിവസം (തിങ്കൾ, ചൊവ്വാഴ്ച ... ഞായർ) <br/> ഇ = ആഴ്ചയിലെ ആഴ്ചയിലെ ആഴ്ചയിലെ ഹ്രസ്വ ദിവസം) <br/> ഡി - ഓർഡിനൽ ദിവസം (1st, 2nd, 3RD, 21, 21, 22 > H = ദിവസം (0-23) <br/> HH = ദിവസം (00-23) <br/> MM = നിമിഷം <br/> SS = സെക്കൻഡ് <br/> SSS = മില്ലിസെക്കൻഡുകൾ <br/> a = am / pm മാർക്കർ <br/> p = A.M./P.M. മാർക്കർ`,
	EditorTemplateDateTimeCustomLabel: `സന്വദായം`,
	EditorTemplateDateTimeHint: `നിലവിലെ തീയതിയും കൂടാതെ / അല്ലെങ്കിൽ സമയവും ഡേറ്റ്ടൈം ടെംപ്ലേറ്റുകൾക്ക് പകരമായി സജ്ജമാക്കും.`,
	EditorTemplateDateTimeName: `തീയതി സമയം`,
	EditorTemplateDynamicHint: `<p> ഈ ടെംപ്ലേറ്റിന്റെ എല്ലാ സംഭവങ്ങളും നൽകിയ വാചകം ഉപയോഗിക്കും. </ P>`,
	EditorTemplateDynamicName: `ചലനാത്മക`,
	EditorTemplateEmptyPlaceholder: `{0} ശൂന്യമാണ് ...`,
	EditorTemplateStaticHint: `<p> ഈ ടെംപ്ലേറ്റിന്റെ എല്ലാ സംഭവങ്ങളും നൽകിയ വാചകം ഉപയോഗിക്കും. </ P>`,
	EditorTemplateStaticName: `സ്ഥിതിവിവരകം`,
	EditorTemplateTeaserText: `കൂടുതൽ ഉടനെ വരും!`,
	EditorWatermark: `കാത്തിരിക്കൂ...`,
	EditorWholeWordLabel: ` മുഴുവൻ വാക്ക്`,
	EditorWrapLabel: ` ചുറ്റും പൊതിയുക`,

};