var UiStrings = {
	EditorAppendCloseLabel: `এপ্লাইড শেষ কৰক`,
	EditorAppendInlineModeLabel: `ব্লক সামৰ্থবান কৰক`,
	EditorAppendLineModeLabel: `ইনলাইন সামৰ্থবান কৰক`,
	EditorAppendManualModeLabel: `টগল মেনুৱেল`,
	EditorAppendNonManualModeLabel: `টগল মেনুৱেল`,
	EditorAppendPauseLabel: `বিৰতিৰ সংযোজন`,
	EditorAppendPostLabel: `টগল আগতে`,
	EditorAppendPreLabel: `টগল আগতে`,
	EditorAppendResumeLabel: `ৰিজ্যুম এপেণ্ড`,
	EditorBgColorLabel: `রঙ`,
	EditorClearAllLabel: `সকলো পৰিষ্কাৰ কৰক`,
	EditorClipboardFormatsLabel: `ক্লিপবোৰ্ড ফৰ্মেটসমূহ`,
	EditorConfirmNtfTitle: `নিশ্চিত`,
	EditorDeleteAllButtonText: `সকলো মচি পেলাওক`,
	EditorDeleteAllTemplatesNtfText: `আপুনি নিশ্চিত নেকি যে আপুনি '{0}' ৰ সকলো ব্যৱহাৰ মচি পেলাব বিচাৰে?

এইটোক পুনৰ কৰিব নোৱাৰি!`,
	EditorEditTemplateDetailsLabel: `বিৱৰণ সম্পাদনা কৰক`,
	EditorEditTemplateNameLabel: `নাম`,
	EditorFindLabel: `সন্ধান কৰা`,
	EditorFontColorLabel: `ফন্ট ৰঙৰ ৰং`,
	EditorFormatPaintLabel: `ফৰ্মেট পেইন্ট`,
	EditorInSelectionLabel: ` নিৰ্বাচনত`,
	EditorInsertImageLabel: `ছবি সন্নিবিষ্ট কৰক`,
	EditorInsertLinkLabel: `লিংক সন্নিবিষ্ট কৰক`,
	EditorInsertVideoLabel: `ভিডিঅ' সন্নিবিষ্ট কৰক`,
	EditorMatchCaseLabel: ` মেচ কেছ`,
	EditorNewTemplateLabel: `নতুন টেমপ্লেট`,
	EditorNextTemplateLabel: `পৰৱৰ্তী সাঁচ`,
	EditorPasteButtonAppendBeginLabel: `append...`,
	EditorPasteButtonLabel: `পেষ্ট কৰক`,
	EditorPasteTemplateWatermark: `লিখনী পেষ্ট কৰক...`,
	EditorPrevTemplateLabel: `পূৰ্বৰ সাঁচ`,
	EditorRegExLabel: ` নিয়মিত অভিব্যক্তি`,
	EditorReplaceAllLabel: `সকলো সলনি কৰক`,
	EditorReplaceLabel: `প্ৰৰ্তিস্থাপন কৰা`,
	EditorTemplateContactHint: `<p>পৰ্যন্ত পৰিচয়সমূহ ব্যৱহাৰ কৰা (এটা ফেচাৰ প্লাগইনৰ প্ৰয়োজন) ইয়াত তেতিয়া আপুনি নিৰ্বাচন কৰা যোগাযোগৰ ইমেইল ক্ষেত্ৰ এই দস্তাবেজত থকা সকলো দৃষ্টান্তৰ বাবে ব্যৱহাৰ কৰা হ'ব।</p>`,
	EditorTemplateContactName: `যোগাযোগ কৰক`,
	EditorTemplateDateTimeCustomHint: `yy = চুটি বছৰ<br/>yyyy = দীঘলীয়া বছৰ<br/>m = মাহ (১-১২)<br/>mm = মাহ (০১-১২)<br/>mmm = মাহ সংক্ষিপ্তকৰণ (জানুৱাৰী, ফেব্ৰুৱাৰী .. .ডিচেম্বৰ)<br/>mmmm = দীঘলীয়া মাহ (জানুৱাৰী, ফেব্ৰুৱাৰী ... ডিচেম্বৰ)<br/>d = দিন (১ - ৩১)<br/>dd = দিন (০১ - ৩১)<br/>ddd = সপ্তাহৰ দিন শব্দৰে (সোমবাৰ, মঙলবাৰ ... দেওবাৰ)<br/>e = শব্দত সপ্তাহৰ চুটি দিন (ম, মঙল... সূৰ্য্য)<br/>d - ক্ৰমিক দিন (১ম, ২য়, ৩য়, ২১ নং, ২২, ২৩, ৩১, ৪ৰ্থ...)<br/>h = এ এম/পাইm ত ঘণ্টা (০-১২)<br/>HH = ঘণ্টা/পাইবলৈ ঘণ্টা (০০-১২)<br/ >H = দিনত ঘণ্টা (০-২৩)<br/>HH = দিনত ঘণ্টা (০০-২৩)<br/>mm = মিনিট<br/>SS = দ্বিতীয়<br/>SSS = মিলিছেকেণ্ড<br/> A = AM/PM মাৰ্কাৰ<br/>p = a.m./p.m. মাৰ্কাৰ`,
	EditorTemplateDateTimeCustomLabel: `অনুকুলন কৰা`,
	EditorTemplateDateTimeHint: `বৰ্তমান তাৰিখ আৰু/বা সময় তাৰিখ সময় সাঁচসমূহৰ বাবে প্ৰতিস্থাপন কৰা হ'ব যেতিয়া সিহত পেষ্ট কৰা হয়।`,
	EditorTemplateDateTimeName: `তাৰিখৰ সময়`,
	EditorTemplateDynamicHint: `<p>এই সাঁচটোৰ সকলো পৰিঘটনাই প্ৰদান কৰা লিখনী ব্যৱহাৰ কৰিব।</p>`,
	EditorTemplateDynamicName: `ডাইনামিক`,
	EditorTemplateEmptyPlaceholder: `{0} খালী...`,
	EditorTemplateStaticHint: `<p>এই সাঁচটোৰ সকলো পৰিঘটনাই প্ৰদান কৰা লিখনী ব্যৱহাৰ কৰিব।</p>`,
	EditorTemplateStaticName: `ষ্টেটিক`,
	EditorTemplateTeaserText: `অতি সোনকালে আহিবলগীয়া আৰু অধিক!`,
	EditorWatermark: `অনুগ্ৰহ কৰি অপেক্ষা কৰক...`,
	EditorWholeWordLabel: ` গোটেই শব্দ`,
	EditorWrapLabel: ` চাৰিওফালে মেৰিয়াই লওক`,

};