var UiStrings = {
	EditorAppendCloseLabel: `Ljúktu viðauka`,
	EditorAppendInlineModeLabel: `Virkja blokk`,
	EditorAppendLineModeLabel: `Virkja inline`,
	EditorAppendManualModeLabel: `Skipta handbók`,
	EditorAppendNonManualModeLabel: `Skipta handbók`,
	EditorAppendPauseLabel: `Hlé bæta við`,
	EditorAppendPostLabel: `Skiptu áður`,
	EditorAppendPreLabel: `Skiptu áður`,
	EditorAppendResumeLabel: `Halda áfram bætt við`,
	EditorBgColorLabel: `Bakgrunns litur`,
	EditorClearAllLabel: `Hreinsa allt`,
	EditorClipboardFormatsLabel: `Klemmuspjald`,
	EditorColorChooserTitle: `Ritstjóralitur`,
	EditorConfirmNtfTitle: `Staðfesta`,
	EditorDeleteAllButtonText: `Eyða öllu`,
	EditorDeleteAllTemplatesNtfText: `Ertu viss um að þú viljir eyða öllum notkun '{0}'?

Þetta er ekki hægt að afturkalla!`,
	EditorEditTemplateDetailsLabel: `Breyta smáatriðum`,
	EditorEditTemplateNameLabel: `Nafn`,
	EditorFindLabel: `Finndu`,
	EditorFontColorLabel: `Leturlitur`,
	EditorFormatPaintLabel: `Sniðmálning`,
	EditorInSelectionLabel: ` Í vali`,
	EditorInsertImageLabel: `Settu inn mynd`,
	EditorInsertLinkLabel: `Settu inn hlekk`,
	EditorInsertVideoLabel: `Settu inn myndband`,
	EditorLinkButtonText: `Vista`,
	EditorLinkLabel: `Sláðu inn hlekk`,
	EditorLinkPlaceholder: `Sláðu inn url`,
	EditorMatchCaseLabel: ` Samsvörunarmál`,
	EditorNewTemplateLabel: `Nýtt sniðmát`,
	EditorNextTemplateLabel: `Næsta sniðmát`,
	EditorPasteButtonAppendBeginLabel: `Bæta við ...`,
	EditorPasteButtonLabel: `Límu`,
	EditorPasteButtonLabelMobile: `Afritaðu`,
	EditorPasteTemplateWatermark: `Sláðu inn líma texta ...`,
	EditorPrevTemplateLabel: `Fyrra sniðmát`,
	EditorRegExLabel: ` Regluleg tjáning`,
	EditorReplaceAllLabel: `Skiptu um allt`,
	EditorReplaceLabel: `Skiptu um`,
	EditorTemplateContactHint: `<p>Notkun tiltækra tengiliða (þarf að sækja íforrit) á þessi reitur að verða notaður fyrir öll tilfelli af þessu sniðmáti í þessu skjali eða í þeim tilvikum sem vísað verður í það síðar.</p><p> Svo til dæmis, ef veldu netfang hér, þá verður tölvupóstreitur tengiliðarins sem þú velur notaður í öllum tilvikum í þessu skjali.</p>`,
	EditorTemplateContactName: `Hafðu samband`,
	EditorTemplateDateTimeCustomHint: `yy = stutt ár<br/>yyyy = langt ár<br/>M = mánuður (1-12)<br/>MM = mánuður (01-12)<br/>MMM = mánaðar skammstöfun (jan, feb ... des.)<br/>MMMM = langur mánuður (janúar, febrúar ... desember)<br/>d = dagur (1-31)<br/>dd = dagur (01 - 31)<br/>ddd = dagur vikunnar í orðum (mánudagur, þriðjudagur ... Sunnudagur)<br/>E = stuttur dagur vikunnar í orðum (mán, þri ... Sun)<br/>D - Venjulegur dagur (1., 2., 3., 21., 22., 23., 31., 4....)<br/>klst. = klst. að morgni (0–12)<br/>klst. = klst. að morgni (00-12)<br/>H = klukkustund að degi til (0–23)<br/>HH = klukkustund á dag (00-23)<br/>mm = mínúta<br/>ss = sekúnda<br/>SSS = millisekúndur<br/>a = AM/PM merki<br/>p = a.m./p.m. merki`,
	EditorTemplateDateTimeCustomLabel: `Sérsniðin`,
	EditorTemplateDateTimeHint: `Núverandi dagsetning og/eða tíminn verður skipt út fyrir sniðmát datetime þegar þau eru límd.`,
	EditorTemplateDateTimeName: `Dagsetningartími`,
	EditorTemplateDynamicHint: `<p>Öll tilvik af þessu sniðmáti munu nota meðfylgjandi texta.</p>`,
	EditorTemplateDynamicName: `Kraftmikið`,
	EditorTemplateEmptyPlaceholder: `{0} er tómt ...`,
	EditorTemplateStaticHint: `<p>Öll tilvik af þessu sniðmáti munu nota meðfylgjandi texta.</p>`,
	EditorTemplateStaticName: `Truflanir`,
	EditorTemplateTeaserText: `Meira að koma fljótlega!`,
	EditorTt1: `Smellur`,
	EditorTt2: `Breyttu '<em> {0} </em>' ...`,
	EditorTt3: `breyta lit ...`,
	EditorTt4: `Fjarlægðu '<em> {0} </em>' ...`,
	EditorTt5: `Fjarlægðu hlutinn`,
	EditorTt6: `að fylgja ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Vinsamlegast bíðið...`,
	EditorWholeWordLabel: ` Allt orð`,
	EditorWrapLabel: ` Vefja utan um`,

};