var UiStrings = {
	EditorAppendCloseLabel: `Applingを終了します`,
	EditorAppendInlineModeLabel: `ブロックを有効にします`,
	EditorAppendLineModeLabel: `インラインを有効にします`,
	EditorAppendManualModeLabel: `トグルマニュアル`,
	EditorAppendNonManualModeLabel: `トグルマニュアル`,
	EditorAppendPauseLabel: `一時停止の追加`,
	EditorAppendPostLabel: `前に切り替えます`,
	EditorAppendPreLabel: `前に切り替えます`,
	EditorAppendResumeLabel: `履歴書追加`,
	EditorBgColorLabel: `背景色`,
	EditorClearAllLabel: `すべてクリア`,
	EditorClipboardFormatsLabel: `クリップボード形式`,
	EditorConfirmNtfTitle: `確認する`,
	EditorDeleteAllButtonText: `すべて削除`,
	EditorDeleteAllTemplatesNtfText: `「{0}」のすべての使用法を削除する必要がありますか？

これは、元に戻すことはできません！`,
	EditorEditTemplateDetailsLabel: `詳細を編集する`,
	EditorEditTemplateNameLabel: `名前`,
	EditorFindLabel: `探す`,
	EditorFontColorLabel: `フォントカラー`,
	EditorFormatPaintLabel: `フォーマットペイント`,
	EditorInSelectionLabel: ` 選択`,
	EditorInsertImageLabel: `画像を挿入します`,
	EditorInsertLinkLabel: `リンクを挿入します`,
	EditorInsertVideoLabel: `ビデオを挿入します`,
	EditorMatchCaseLabel: ` マッチケース`,
	EditorNewTemplateLabel: `新しいテンプレート`,
	EditorNextTemplateLabel: `次のテンプレート`,
	EditorPasteButtonAppendBeginLabel: `追加...`,
	EditorPasteButtonLabel: `ペースト`,
	EditorPasteTemplateWatermark: `貼り付けテキストを入力してください...`,
	EditorPrevTemplateLabel: `前のテンプレート`,
	EditorRegExLabel: ` 正規表現`,
	EditorReplaceAllLabel: `すべてを交換します`,
	EditorReplaceLabel: `交換する`,
	EditorTemplateContactHint: `<p>利用可能な連絡先を使用（フェッチャープラグインが必要）このフィールドは、このドキュメント全体でこのテンプレートのすべてのインスタンスに使用されます。ここで、選択した連絡先の電子メールフィールドは、このドキュメントのすべてのインスタンスに使用されます。</p>`,
	EditorTemplateContactName: `接触`,
	EditorTemplateDateTimeCustomHint: `yy =短い年<br/> yyyy = long year <br/> m = month（1-12）<br/> mm = month（01-12）<br/> mmm =月略語（1月、2月。 。dec）<br/> mmmm =長年（1月、2月... 12月）<br/> d = day（1-31）<br/> dd = day（01-31）<br/> ddd =言葉の曜日（月曜日、火曜日...日曜日）<br/> e =言葉での短い曜日（月、火...太陽）<br/> d-序数（1日、2日、2日、 3番目、21日、22日、23日、31日、4日...）<br/> h = hour in am/pm（0-12）<br/> hh = hour in am/pm（00-12）<br/ > h = 1日の時間（0-23）<br/> hh = hour in day（00-23）<br/> mm = minute <br/> ss = second <br/> sss = milliseconds <br/> a = am/pmマーカー<br/> p = a.m./p.m。マーカー`,
	EditorTemplateDateTimeCustomLabel: `カスタム`,
	EditorTemplateDateTimeHint: `現在の日付および/または時間は、貼り付けられたときにDateTimeテンプレートに置き換えられます。`,
	EditorTemplateDateTimeName: `日付時刻`,
	EditorTemplateDynamicHint: `<p>このテンプレートのすべての発生は、提供されたテキストを使用します。</p>`,
	EditorTemplateDynamicName: `動的`,
	EditorTemplateEmptyPlaceholder: `{0}は空です...`,
	EditorTemplateStaticHint: `<p>このテンプレートのすべての発生は、提供されたテキストを使用します。</p>`,
	EditorTemplateStaticName: `静的`,
	EditorTemplateTeaserText: `もうすぐ来る！`,
	EditorWatermark: `お待ちください...`,
	EditorWholeWordLabel: ` 単語全体`,
	EditorWrapLabel: ` 包み込む`,

};