var UiStrings = {
	EditorAppendCloseLabel: `Afslut at tilføje`,
	EditorAppendInlineModeLabel: `Aktivér blok`,
	EditorAppendLineModeLabel: `Aktivér inline`,
	EditorAppendManualModeLabel: `Skift manual`,
	EditorAppendNonManualModeLabel: `Skift manual`,
	EditorAppendPauseLabel: `Pause Tilføj`,
	EditorAppendPostLabel: `Skift før`,
	EditorAppendPreLabel: `Skift før`,
	EditorAppendResumeLabel: `Genoptag tilføj`,
	EditorBgColorLabel: `Baggrundsfarve`,
	EditorClearAllLabel: `Slet alt`,
	EditorClipboardFormatsLabel: `Clipboard -formater`,
	EditorConfirmNtfTitle: `Bekræfte`,
	EditorDeleteAllButtonText: `Slet alt`,
	EditorDeleteAllTemplatesNtfText: `Er du sikker på, at du vil slette alle anvendelser af '{0}'?

Dette kan ikke fortrydes!`,
	EditorEditTemplateDetailsLabel: `Rediger detaljer`,
	EditorEditTemplateNameLabel: `Navn`,
	EditorFindLabel: `Find`,
	EditorFontColorLabel: `Skrift farve`,
	EditorFormatPaintLabel: `Formatmaling`,
	EditorInSelectionLabel: ` I udvælgelse`,
	EditorInsertImageLabel: `Indsæt billede`,
	EditorInsertLinkLabel: `Indsæt link`,
	EditorInsertVideoLabel: `Indsæt video`,
	EditorMatchCaseLabel: ` Match -sag`,
	EditorNewTemplateLabel: `Ny skabelon`,
	EditorNextTemplateLabel: `Næste skabelon`,
	EditorPasteButtonAppendBeginLabel: `Tilføj...`,
	EditorPasteButtonLabel: `sæt ind`,
	EditorPasteTemplateWatermark: `Indtast pastatekst ...`,
	EditorPrevTemplateLabel: `Tidligere skabelon`,
	EditorRegExLabel: ` Almindelig udtryk`,
	EditorReplaceAllLabel: `Udskift alle`,
	EditorReplaceLabel: `Erstatte`,
	EditorTemplateContactHint: `meget Her bruges e -mail -feltet for den kontakt, du vælger, til alle tilfælde i dette dokument. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kort år <br/> yyyy = lang år <br/> m = måned (1-12) <br/> mm = måned (01-12) <br/> mmm = måned forkortelse (januar, februar .. . Dec) <br/> mmmm = lang måned (januar, februar ... december) <br/> d = dag (1 - 31) <br/> dd = dag (01 - 31) <br/> ddd = Ugedag med ord (mandag, tirsdag ... søndag) <br/> e = kort ugedag i ord (mandag, tirsdag ... sol) <br/> d - ordinal dag (1., 2., 3., 21., 22., 23., 31., 4. ...) <br/> H = time i am/pm (0-12) <br/> hh = time i am/pm (00-12) <br/ > H = time i dag (0-23) <br/> hh = time in dag (00-23) <br/> mm = minut <br/> ss = anden <br/> sss = millisekunder <br/> A = am/pm markør <br/> p = a.m./p.m. markør`,
	EditorTemplateDateTimeCustomLabel: `Brugerdefinerede`,
	EditorTemplateDateTimeHint: `Den aktuelle dato og/eller tiden erstattes af DateTime -skabeloner, når de indsættes.`,
	EditorTemplateDateTimeName: `Dato tid`,
	EditorTemplateDynamicHint: `<p> Alle forekomster af denne skabelon bruger den medfølgende tekst. </p>`,
	EditorTemplateDynamicName: `Dynamisk`,
	EditorTemplateEmptyPlaceholder: `{0} er tom ...`,
	EditorTemplateStaticHint: `<p> Alle forekomster af denne skabelon bruger den medfølgende tekst. </p>`,
	EditorTemplateStaticName: `Statisk`,
	EditorTemplateTeaserText: `Flere kommer snart!`,
	EditorWatermark: `Vent venligst...`,
	EditorWholeWordLabel: ` Hele ord`,
	EditorWrapLabel: ` Vikle om`,

};