var UiStrings = {
	EditorAppendCloseLabel: `الانتهاء من الإلحاق`,
	EditorAppendInlineModeLabel: `تمكين كتلة`,
	EditorAppendLineModeLabel: `تمكين مضمونة`,
	EditorAppendManualModeLabel: `دليل تبديل`,
	EditorAppendNonManualModeLabel: `دليل تبديل`,
	EditorAppendPauseLabel: `الإيقاف التوقف`,
	EditorAppendPostLabel: `تبديل من قبل`,
	EditorAppendPreLabel: `تبديل من قبل`,
	EditorAppendResumeLabel: `استئناف إلحاق`,
	EditorBgColorLabel: `لون الخلفية`,
	EditorClearAllLabel: `امسح الكل`,
	EditorClipboardFormatsLabel: `تنسيقات الحافظة`,
	EditorConfirmNtfTitle: `يتأكد`,
	EditorDeleteAllButtonText: `حذف الكل`,
	EditorDeleteAllTemplatesNtfText: `هل أنت متأكد من أنك تريد حذف جميع استخدامات "{0}؟

هذا لا يمكن التراجع عنها!`,
	EditorEditTemplateDetailsLabel: `عدل التفاصيل`,
	EditorEditTemplateNameLabel: `اسم`,
	EditorFindLabel: `يجد`,
	EditorFontColorLabel: `لون الخط`,
	EditorFormatPaintLabel: `تنسيق الطلاء`,
	EditorInSelectionLabel: ` في الاختيار`,
	EditorInsertImageLabel: `إدراج صورة`,
	EditorInsertLinkLabel: `أدخل الرابط`,
	EditorInsertVideoLabel: `أدخل الفيديو`,
	EditorMatchCaseLabel: ` حالة مباراة`,
	EditorNewTemplateLabel: `قالب جديد`,
	EditorNextTemplateLabel: `القالب التالي`,
	EditorPasteButtonAppendBeginLabel: `ألحق...`,
	EditorPasteButtonLabel: `معجون`,
	EditorPasteTemplateWatermark: `أدخل نص لصق ...`,
	EditorPrevTemplateLabel: `القالب السابق`,
	EditorRegExLabel: ` تعبير عادي`,
	EditorReplaceAllLabel: `استبدل كل شيء`,
	EditorReplaceLabel: `يستبدل`,
	EditorTemplateContactHint: `<p> استخدام جهات الاتصال المتاحة (يتطلب مكونًا إضافيًا لـ Fotcher) سيتم استخدام هذا الحقل لجميع مثيلات هذا القالب عبر هذا المستند أو في أي سيتم الرجوع إليه لاحقًا. </p> <p> لذلك على سبيل المثال إذا حدد عنوان البريد الإلكتروني هنا سيتم استخدام حقل البريد الإلكتروني لجهة الاتصال التي تحددها لجميع الحالات في هذا المستند. </p>`,
	EditorTemplateContactName: `اتصال`,
	EditorTemplateDateTimeCustomHint: `yy = سنة قصيرة <br/> yyyy = long year <br/> m = month (1-12) <br/> mm = month (01-12) <br/> mmm = شهر الاختصار (يناير ، فبراير .. . يوم الأسبوع بالكلمات (الاثنين ، الثلاثاء ... الأحد) <br/> e = يوم قصير من الأسبوع بالكلمات (الاثنين ، الثلاثاء ... الشمس) <br/> د - يوم ترتيبي (الأول ، الثاني ، 3rd ، 21 ، 22 ، 23 ، 31 ، 4 ...) <br/> H = ساعة في AM/PM (0-12) <br/> hh = ساعة في AM/PM (00-12) <br/ > h = ساعة في اليوم (0-23) <br/> hh = ساعة في اليوم (00-23) <br/> mm = minate <br/> ss = second <br/> sss = milliseconds <br/> a = am/pm علامة <br/> p = amm/p.m. علامة`,
	EditorTemplateDateTimeCustomLabel: `مخصص`,
	EditorTemplateDateTimeHint: `سيتم استبدال التاريخ و/أو الوقت الحالي لقوالب DateTime عند لصقها.`,
	EditorTemplateDateTimeName: `وقت التاريخ`,
	EditorTemplateDynamicHint: `<p> ستستخدم جميع حالات هذا القالب النص المقدم. </p>`,
	EditorTemplateDynamicName: `متحرك`,
	EditorTemplateEmptyPlaceholder: `{0} فارغ ...`,
	EditorTemplateStaticHint: `<p> ستستخدم جميع حالات هذا القالب النص المقدم. </p>`,
	EditorTemplateStaticName: `ثابتة`,
	EditorTemplateTeaserText: `المزيد قادم قريبا!`,
	EditorWatermark: `انتظر من فضلك...`,
	EditorWholeWordLabel: ` الكلمة بالكامل`,
	EditorWrapLabel: ` التفاف حول`,

};