var UiStrings = {
	EditorAppendCloseLabel: `Hoàn thành việc nối thêm`,
	EditorAppendInlineModeLabel: `Bật khối`,
	EditorAppendLineModeLabel: `Bật nội tuyến`,
	EditorAppendManualModeLabel: `Chuyển đổi hướng dẫn sử dụng`,
	EditorAppendNonManualModeLabel: `Chuyển đổi hướng dẫn sử dụng`,
	EditorAppendPauseLabel: `Tạm dừng nối thêm`,
	EditorAppendPostLabel: `Chuyển đổi trước`,
	EditorAppendPreLabel: `Chuyển đổi trước`,
	EditorAppendResumeLabel: `Tiếp tục nối tiếp`,
	EditorBgColorLabel: `Màu nền`,
	EditorClearAllLabel: `Làm sạch tất cả`,
	EditorClipboardFormatsLabel: `Định dạng bảng tạm`,
	EditorConfirmNtfTitle: `Xác nhận`,
	EditorDeleteAllButtonText: `Xóa hết`,
	EditorDeleteAllTemplatesNtfText: `Bạn có chắc là bạn muốn xóa tất cả các cách sử dụng của '{0}' không?

Điều này không thể được hoàn tác!`,
	EditorEditTemplateDetailsLabel: `Chỉnh sửa chi tiết`,
	EditorEditTemplateNameLabel: `Tên`,
	EditorFindLabel: `Tìm thấy`,
	EditorFontColorLabel: `Màu chữ`,
	EditorFormatPaintLabel: `Định dạng sơn`,
	EditorInSelectionLabel: ` Trong lựa chọn`,
	EditorInsertImageLabel: `Chèn hình ảnh`,
	EditorInsertLinkLabel: `Chèn đường dẫn`,
	EditorInsertVideoLabel: `Chèn video`,
	EditorMatchCaseLabel: ` Trường hợp khớp`,
	EditorNewTemplateLabel: `Bản mẫu mới`,
	EditorNextTemplateLabel: `Mẫu tiếp theo`,
	EditorPasteButtonAppendBeginLabel: `Nối thêm ...`,
	EditorPasteButtonLabel: `Dán`,
	EditorPasteTemplateWatermark: `Nhập văn bản Paste ...`,
	EditorPrevTemplateLabel: `Mẫu trước`,
	EditorRegExLabel: ` Biểu hiện thông thường`,
	EditorReplaceAllLabel: `Thay thế tất cả`,
	EditorReplaceLabel: `Thay thế`,
	EditorTemplateContactHint: `<p>Sử dụng các liên hệ có sẵn (yêu cầu plugin trình tải), trường này sẽ được sử dụng cho tất cả các trường hợp của mẫu này trên tài liệu này hoặc trong bất kỳ trường hợp nào sẽ được tham chiếu sau.</p><p> Vì vậy, ví dụ: nếu chọn địa chỉ email ở đây thì trường email của liên hệ bạn chọn sẽ được sử dụng cho tất cả các trường hợp trong tài liệu này.</p>`,
	EditorTemplateContactName: `Liên hệ`,
	EditorTemplateDateTimeCustomHint: `yy = năm ngắn ngủi<br/>yyyy = năm dài<br/>M = tháng (1-12)<br/>MM = tháng (01-12)<br/>MMM = tháng viết tắt (Jan, Feb ... Tháng mười hai)<br/>MMMM = tháng dài (tháng Giêng, tháng Hai ... Tháng mười hai)<br/>d = ngày (1 - 31)<br/>đ = ngày (01 - 31)<br/>ddd = ngày trong tuần bằng từ (Thứ Hai, Thứ Ba ... Chủ nhật)<br/>E = ngày ngắn trong tuần bằng từ (Thứ Hai, Thứ Ba ... Mặt trời)<br/>D – Ngày thứ tự (mùng 1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = giờ tính bằng sáng / chiều (0-12)<br/>HH = giờ tính bằng sáng / chiều (00-12)<br/>H = giờ trong ngày (0-23)<br/>HH = giờ trong ngày (00-23)<br/>mm = phút<br/>ss = giây<br/>SSS = mili giây<br/>a = điểm đánh dấu AM / PM<br/>p = điểm đánh dấu sáng / chiều`,
	EditorTemplateDateTimeCustomLabel: `Phong tục`,
	EditorTemplateDateTimeHint: `Ngày và/hoặc thời gian hiện tại sẽ được thay thế cho các mẫu DateTime khi chúng được dán.`,
	EditorTemplateDateTimeName: `Ngày giờ`,
	EditorTemplateDynamicHint: `<p>Tất cả các lần xuất hiện của bản mẫu này sẽ sử dụng văn bản được cung cấp.</p>`,
	EditorTemplateDynamicName: `Năng động`,
	EditorTemplateEmptyPlaceholder: `{0} trống ...`,
	EditorTemplateStaticHint: `<p>Tất cả các lần xuất hiện của bản mẫu này sẽ sử dụng văn bản được cung cấp.</p>`,
	EditorTemplateStaticName: `Tĩnh`,
	EditorTemplateTeaserText: `Sắp có thêm!`,
	EditorWatermark: `Vui lòng chờ...`,
	EditorWholeWordLabel: ` Cả từ`,
	EditorWrapLabel: ` Quấn quanh`,

};