var UiStrings = {
	EditorAppendCloseLabel: `จบท้าย`,
	EditorAppendInlineModeLabel: `เปิดใช้งานบล็อก`,
	EditorAppendLineModeLabel: `เปิดใช้งาน Inline`,
	EditorAppendManualModeLabel: `คู่มือการสลับ`,
	EditorAppendNonManualModeLabel: `คู่มือการสลับ`,
	EditorAppendPauseLabel: `หยุดชั่วคราว`,
	EditorAppendPostLabel: `สลับมาก่อน`,
	EditorAppendPreLabel: `สลับมาก่อน`,
	EditorAppendResumeLabel: `ภาคผนวกกลับมาทำงาน`,
	EditorBgColorLabel: `สีพื้นหลัง`,
	EditorClearAllLabel: `ลบทั้งหมด`,
	EditorClipboardFormatsLabel: `รูปแบบคลิปบอร์ด`,
	EditorColorChooserTitle: `สีบรรณาธิการ`,
	EditorConfirmNtfTitle: `ยืนยัน`,
	EditorDeleteAllButtonText: `ลบทั้งหมด`,
	EditorDeleteAllTemplatesNtfText: `แน่ใจหรือว่าต้องการลบการใช้งานทั้งหมดของ '{0}'?

สิ่งนี้ไม่สามารถยกเลิกได้!`,
	EditorEditTemplateDetailsLabel: `แก้ไขรายละเอียด`,
	EditorEditTemplateNameLabel: `ชื่อ`,
	EditorFindLabel: `หา`,
	EditorFontColorLabel: `สีตัวอักษร`,
	EditorFormatPaintLabel: `รูปแบบสี`,
	EditorInSelectionLabel: ` ในการเลือก`,
	EditorInsertImageLabel: `แทรกภาพ`,
	EditorInsertLinkLabel: `แทรกลิงค์`,
	EditorInsertVideoLabel: `แทรกวิดีโอ`,
	EditorLinkButtonText: `บันทึก`,
	EditorLinkLabel: `ป้อนลิงค์`,
	EditorLinkPlaceholder: `ป้อน URL`,
	EditorMatchCaseLabel: ` เคสจับคู่`,
	EditorNewTemplateLabel: `เทมเพลตใหม่`,
	EditorNextTemplateLabel: `เทมเพลตถัดไป`,
	EditorPasteButtonAppendBeginLabel: `ผนวก...`,
	EditorPasteButtonLabel: `แปะ`,
	EditorPasteTemplateWatermark: `ป้อนข้อความ Paste ...`,
	EditorPrevTemplateLabel: `เทมเพลตก่อนหน้า`,
	EditorRegExLabel: ` การแสดงออกปกติ`,
	EditorReplaceAllLabel: `แทนที่ทั้งหมด`,
	EditorReplaceLabel: `แทนที่`,
	EditorTemplateContactHint: `<p>การใช้ผู้ติดต่อที่มีอยู่ (ต้องใช้ปลั๊กอินตัวดึงข้อมูล) ฟิลด์นี้จะใช้สําหรับอินสแตนซ์ทั้งหมดของเทมเพลตนี้ในเอกสารนี้หรือในการอ้างอิงในภายหลัง</p><p> ตัวอย่างเช่น หากเลือกที่อยู่อีเมลที่นี่ ช่องอีเมลของผู้ติดต่อที่คุณเลือกจะถูกใช้สําหรับทุกอินสแตนซ์ในเอกสารนี้</p>`,
	EditorTemplateContactName: `ติดต่อ`,
	EditorTemplateDateTimeCustomHint: `yy = ปีสั้น<br/>yyyy = ปีที่ยาวนาน<br/>M = เดือน (1-12)<br/>MM = เดือน (01-12)<br/>MMM = ตัวย่อเดือน (ม.ค. ก.พ. ... ธ.ค.)<br/>MMMM = เดือนที่ยาวนาน (มกราคมกุมภาพันธ์ ... ธันวาคม)<br/>d = วัน (1 - 31)<br/>dd = วัน (01 - 31)<br/>ddd = วันในสัปดาห์ในคํา (วันจันทร์วันอังคาร ... วันอาทิตย์)<br/>= วันสั้น ๆ ของสัปดาห์ในคํา (จันทร์ อังคาร ... อาทิตย์)<br/>D - วันลําดับ (วันที่ 1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = ชั่วโมงเป็น am/pm (0-12)<br/>hh = ชั่วโมงเป็น am/pm (00-12)<br/>H = ชั่วโมงในวัน (0-23)<br/>HH = ชั่วโมงในวัน (00-23)<br/>มม. = นาที<br/>ss = วินาที<br/>SSS = มิลลิวินาที<br/>a = เครื่องหมาย AM/PM<br/>p = เครื่องหมาย am/pm`,
	EditorTemplateDateTimeCustomLabel: `กำหนดเอง`,
	EditorTemplateDateTimeHint: `วันที่และ/หรือเวลาปัจจุบันจะถูกแทนที่สำหรับเทมเพลต dateTime เมื่อวาง`,
	EditorTemplateDateTimeName: `วันเวลา`,
	EditorTemplateDynamicHint: `<p>การเกิดขึ้นทั้งหมดของเทมเพลตนี้จะใช้ข้อความที่ให้มา</p>`,
	EditorTemplateDynamicName: `พลวัต`,
	EditorTemplateEmptyPlaceholder: `{0} ว่างเปล่า ...`,
	EditorTemplateStaticHint: `<p>การเกิดขึ้นทั้งหมดของเทมเพลตนี้จะใช้ข้อความที่ให้มา</p>`,
	EditorTemplateStaticName: `คงที่`,
	EditorTemplateTeaserText: `เพิ่มเติมเร็ว ๆ นี้!`,
	EditorTt1: `คลิก`,
	EditorTt2: `แก้ไข '<em> {0} </em>' ...`,
	EditorTt3: `แก้ไขสี ...`,
	EditorTt4: `ลบ '<em> {0} </em>' ...`,
	EditorTt5: `ลบรายการ`,
	EditorTt6: `ที่จะติดตาม ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `โปรดรอ...`,
	EditorWholeWordLabel: ` ทั้งคำ`,
	EditorWrapLabel: ` ห่อรอบ ๆ`,

};