var UiStrings = {
	EditorAppendCloseLabel: `Gorffen atodi`,
	EditorAppendInlineModeLabel: `Galluogi Bloc`,
	EditorAppendLineModeLabel: `Galluogi Inline`,
	EditorAppendManualModeLabel: `Llawlyfr Toggle`,
	EditorAppendNonManualModeLabel: `Llawlyfr Toggle`,
	EditorAppendPauseLabel: `Oedi atodi`,
	EditorAppendPostLabel: `Togl o'r blaen`,
	EditorAppendPreLabel: `Togl o'r blaen`,
	EditorAppendResumeLabel: `Ailddechrau atodi`,
	EditorBgColorLabel: `Lliw cefndir`,
	EditorClearAllLabel: `Clirio popeth`,
	EditorClipboardFormatsLabel: `Fformatau clipfwrdd`,
	EditorConfirmNtfTitle: `Chadarnhasoch`,
	EditorDeleteAllButtonText: `Dileu popeth`,
	EditorDeleteAllTemplatesNtfText: `Ydych chi'n siŵr eich bod chi am ddileu pob defnydd o '{0}'?

Ni ellir dadwneud hyn!`,
	EditorEditTemplateDetailsLabel: `Golygu Manylion`,
	EditorEditTemplateNameLabel: `Henwem`,
	EditorFindLabel: `Ffeindia`,
	EditorFontColorLabel: `Lliw ffont`,
	EditorFormatPaintLabel: `Paent fformat`,
	EditorInSelectionLabel: ` Wrth ddewis`,
	EditorInsertImageLabel: `Mewnosod Delwedd`,
	EditorInsertLinkLabel: `Mewnosod dolen`,
	EditorInsertVideoLabel: `Mewnosod fideo`,
	EditorMatchCaseLabel: ` Cydweddu Achos`,
	EditorNewTemplateLabel: `Templed newydd`,
	EditorNextTemplateLabel: `Templed Nesaf`,
	EditorPasteButtonAppendBeginLabel: `Atodi ...`,
	EditorPasteButtonLabel: `Pastia`,
	EditorPasteTemplateWatermark: `Nodwch destun past ...`,
	EditorPrevTemplateLabel: `Templed Blaenorol`,
	EditorRegExLabel: ` Mynegiant rheolaidd`,
	EditorReplaceAllLabel: `Disodli popeth`,
	EditorReplaceLabel: `Hamnewidia ’`,
	EditorTemplateContactHint: `<p>Gan ddefnyddio cysylltiadau sydd ar gael (mae angen ategyn fetcher) bydd y maes hwn yn cael ei ddefnyddio ar gyfer pob achos o'r templed hwn ar draws y ddogfen hon neu mewn unrhyw un y cyfeirir ato yn ddiweddarach.</p><p> Felly, er enghraifft, os dewiswch gyfeiriad e-bost yma, bydd maes e-bost y cyswllt a ddewiswch yn cael ei ddefnyddio ar gyfer pob achos yn y ddogfen hon.</p>`,
	EditorTemplateContactName: `Nghyswllt`,
	EditorTemplateDateTimeCustomHint: `yy = blwyddyn fer<br/>yyyy = blwyddyn hir<br/>M = mis (1-12)<br/>MM = mis (01-12)<br/>MMM = byrfodd mis (Ionawr, Chwefror ... Rhagfyr)<br/>MMMM = mis hir (Ionawr, Chwefror ... Rhagfyr)<br/>d = diwrnod (1 - 31)<br/>dd = diwrnod (01 - 31)<br/>ddd = diwrnod yr wythnos mewn geiriau (Dydd Llun, Dydd Mawrth ... Dydd Sul)<br/>E = diwrnod byr o'r wythnos mewn geiriau (Llun, Maw ... Haul)<br/>D - Diwrnod arferol (1af, 2il, 3ydd, 21ain, 22ain, 23ain, 31ain, 4ydd...)<br/>h = hour in am/pm (0-12)<br/>hh = awr yn am/pm (00-12)<br/>H = awr yn y dydd (0-23)<br/>HH = awr yn y dydd (00-23)<br/>mm = munud<br/>SS = ail<br/>SSS = milieiliadau<br/>a = AC / PM marciwr<br/>p = a.m./p.m. marciwr`,
	EditorTemplateDateTimeCustomLabel: `Arferol`,
	EditorTemplateDateTimeHint: `Bydd y dyddiad a/neu'r amser cyfredol yn cael ei amnewid yn lle templedi amser dyddiad pan gânt eu pastio.`,
	EditorTemplateDateTimeName: `Amser Dyddiad`,
	EditorTemplateDynamicHint: `<p>Bydd holl achosion y templed hwn yn defnyddio'r testun a ddarparwyd.</p>`,
	EditorTemplateDynamicName: `Ddeinamig`,
	EditorTemplateEmptyPlaceholder: `Mae {0} yn wag ...`,
	EditorTemplateStaticHint: `<p>Bydd holl achosion y templed hwn yn defnyddio'r testun a ddarparwyd.</p>`,
	EditorTemplateStaticName: `Statig`,
	EditorTemplateTeaserText: `Mwy yn dod yn fuan!`,
	EditorWatermark: `Arhoswch os gwelwch yn dda...`,
	EditorWholeWordLabel: ` Gair cyfan`,
	EditorWrapLabel: ` Lapio o gwmpas`,

};