var UiStrings = {
	EditorAppendCloseLabel: `Finition d'appel`,
	EditorAppendInlineModeLabel: `Activer le bloc`,
	EditorAppendLineModeLabel: `Activer en ligne`,
	EditorAppendManualModeLabel: `Manuel de basculement`,
	EditorAppendNonManualModeLabel: `Manuel de basculement`,
	EditorAppendPauseLabel: `Pause Ajouter`,
	EditorAppendPostLabel: `Basculer avant`,
	EditorAppendPreLabel: `Basculer avant`,
	EditorAppendResumeLabel: `Reprendre`,
	EditorBgColorLabel: `Couleur de l'arrière plan`,
	EditorClearAllLabel: `Tout effacer`,
	EditorClipboardFormatsLabel: `Formats de presse-papiers`,
	EditorConfirmNtfTitle: `Confirmer`,
	EditorDeleteAllButtonText: `Supprimer tout`,
	EditorDeleteAllTemplatesNtfText: `Êtes-vous sûr de vouloir supprimer tous les usages de '{0}'?

Ça ne peut pas être annulé!`,
	EditorEditTemplateDetailsLabel: `Modifier les détails`,
	EditorEditTemplateNameLabel: `Nom`,
	EditorFindLabel: `Trouver`,
	EditorFontColorLabel: `Couleur de la police`,
	EditorFormatPaintLabel: `Peinture au format`,
	EditorInSelectionLabel: ` En sélection`,
	EditorInsertImageLabel: `Insérer une image`,
	EditorInsertLinkLabel: `Insérer un lien`,
	EditorInsertVideoLabel: `Insérer une vidéo`,
	EditorMatchCaseLabel: ` Cas de correspondance`,
	EditorNewTemplateLabel: `Nouveau modèle`,
	EditorNextTemplateLabel: `Modèle suivant`,
	EditorPasteButtonAppendBeginLabel: `Ajouter...`,
	EditorPasteButtonLabel: `Pâte`,
	EditorPasteTemplateWatermark: `Entrez le texte de la pâte ...`,
	EditorPrevTemplateLabel: `Modèle précédent`,
	EditorRegExLabel: ` Expression régulière`,
	EditorReplaceAllLabel: `Remplace tout`,
	EditorReplaceLabel: `Remplacer`,
	EditorTemplateContactHint: `<p> Utilisation des contacts disponibles (nécessite un plugin de récupérateur) Ce champ sera utilisé pour toutes les instances de ce modèle sur ce document ou dans tout ce qui sera référencé plus tard. </p> <p> Ainsi, par exemple si sélectionnez l'adresse e-mail Ici, le champ de messagerie du contact que vous sélectionnez sera utilisé pour toutes les instances de ce document. </p>`,
	EditorTemplateContactName: `Contact`,
	EditorTemplateDateTimeCustomHint: `yy = courte année <br/> yyyy = longue année <br/> m = mois (1-12) <br/> mm = mois (01-12) <br/> mmm = mois d'abréviation (janvier, février .. . Dec) <br/> mmmm = long mois (janvier, février ... décembre) <br/> d = jour (1 - 31) <br/> dd = jour (01 - 31) <br/> ddd = Jour de la semaine en mots (lundi, mardi ... dimanche) <br/> E = courte du jour de la semaine en mots (lun, mar ... soleil) <br/> D - Jour ordinaire (1er, 2e, 3e, 21e, 22e, 23e, 31e, 4e ...) <br/> h = heure en am / pm (0-12) <br/> hh = heure en am / pm (00-12) <Br / Br / > H = heure en jour (0-23) <br/> Hh = heure en jour (00-23) <br/> mm = minute <br/> ss = second <br/> sss = milliseconds <br/> A = marqueur am / pm <br/> p = a.m./p.m. marqueur`,
	EditorTemplateDateTimeCustomLabel: `Coutume`,
	EditorTemplateDateTimeHint: `La date et / ou l'heure actuelles seront remplacées par des modèles DateTime lorsqu'ils sont collés.`,
	EditorTemplateDateTimeName: `Date`,
	EditorTemplateDynamicHint: `<p> Toutes les accessions de ce modèle utiliseront le texte fourni. </p>`,
	EditorTemplateDynamicName: `Dynamique`,
	EditorTemplateEmptyPlaceholder: `{0} est vide ...`,
	EditorTemplateStaticHint: `<p> Toutes les accessions de ce modèle utiliseront le texte fourni. </p>`,
	EditorTemplateStaticName: `Statique`,
	EditorTemplateTeaserText: `Plus à venir bientôt!`,
	EditorWatermark: `S'il vous plaît, attendez...`,
	EditorWholeWordLabel: ` Mot entier`,
	EditorWrapLabel: ` Enrouler autour`,

};