var UiStrings = {
	EditorAppendCloseLabel: `完成追加`,
	EditorAppendInlineModeLabel: `启用段落`,
	EditorAppendLineModeLabel: `启用内联`,
	EditorAppendManualModeLabel: `切换手动`,
	EditorAppendNonManualModeLabel: `切换手动`,
	EditorAppendPauseLabel: `暂停附加到剪贴板`,
	EditorAppendPostLabel: `切换之前`,
	EditorAppendPreLabel: `切换之前`,
	EditorAppendResumeLabel: `继续附加到剪贴板`,
	EditorBgColorLabel: `背景颜色`,
	EditorClearAllLabel: `全部清除`,
	EditorClipboardFormatsLabel: `剪贴板格式`,
	EditorConfirmNtfTitle: `确认`,
	EditorDeleteAllButtonText: `删除所有`,
	EditorDeleteAllTemplatesNtfText: `您确定要删除“{0}”的所有使用情况吗？`,
	EditorEditTemplateDetailsLabel: `编辑详细信息`,
	EditorEditTemplateNameLabel: `姓名`,
	EditorFindLabel: `寻找`,
	EditorFontColorLabel: `字体颜色`,
	EditorFormatPaintLabel: `格式绘制`,
	EditorInSelectionLabel: `选拔中`,
	EditorInsertImageLabel: `插入图片`,
	EditorInsertLinkLabel: `插入链接`,
	EditorInsertVideoLabel: `插入视频`,
	EditorMatchCaseLabel: `相符`,
	EditorNewTemplateLabel: `新模板`,
	EditorNextTemplateLabel: `下一个模板`,
	EditorPasteButtonAppendBeginLabel: `附加...`,
	EditorPasteButtonLabel: `粘贴`,
	EditorPasteTemplateWatermark: `输入粘贴文本...`,
	EditorPrevTemplateLabel: `上一个模板`,
	EditorRegExLabel: `正则表达式`,
	EditorReplaceAllLabel: `全部替换`,
	EditorReplaceLabel: `代替`,
	EditorTemplateContactHint: `<p>使用可用的联系人（需要提取器插件），此字段将用于本文档中此模板的所有实例或稍后将引用的任何实例。</p><p> 例如，如果选择电子邮件地址`,
	EditorTemplateContactName: `接触`,
	EditorTemplateDateTimeCustomHint: `<p>yy = 短年份</p><p>yyyy = 长年份</p><p>M = 月份（1-12）</p><p>MM = 月份（01-12）</p>`,
	EditorTemplateDateTimeCustomLabel: `风俗`,
	EditorTemplateDateTimeHint: `<p>从评估那一刻起，当前日期和/或时间将替换为 DateTime 模板。`,
	EditorTemplateDateTimeName: `约会时间`,
	EditorTemplateDynamicHint: `<p>此模板的所有出现都将设置为您在此处提供的值</p>`,
	EditorTemplateDynamicName: `动态的`,
	EditorTemplateEmptyPlaceholder: `{0} 为空...`,
	EditorTemplateStaticHint: `<p>从评估那一刻起，当前日期和/或时间将替换为 DateTime 模板。`,
	EditorTemplateStaticName: `静止的`,
	EditorTemplateTeaserText: `更多即将推出！`,
	EditorWholeWordLabel: `整个词`,
	EditorWrapLabel: `环绕式`,

};