var UiStrings = {
	EditorAppendCloseLabel: `Закінчити додавання`,
	EditorAppendInlineModeLabel: `Увімкнути блок`,
	EditorAppendLineModeLabel: `Увімкнути вбудовано`,
	EditorAppendManualModeLabel: `Посібник з перемикання`,
	EditorAppendNonManualModeLabel: `Посібник з перемикання`,
	EditorAppendPauseLabel: `Пауза додає`,
	EditorAppendPostLabel: `Перемикатися до`,
	EditorAppendPreLabel: `Перемикатися до`,
	EditorAppendResumeLabel: `Відновити додаток`,
	EditorBgColorLabel: `Колір фону`,
	EditorClearAllLabel: `Очистити все`,
	EditorClipboardFormatsLabel: `Формати буфера обміну`,
	EditorConfirmNtfTitle: `Підтверджувати`,
	EditorDeleteAllButtonText: `Видалити все`,
	EditorDeleteAllTemplatesNtfText: `Ви впевнені, що хочете видалити всі використання '{0}'?

Це не може бути скасоване!`,
	EditorEditTemplateDetailsLabel: `Редагувати деталі`,
	EditorEditTemplateNameLabel: `Назва`,
	EditorFindLabel: `Знаходити`,
	EditorFontColorLabel: `Шрифт`,
	EditorFormatPaintLabel: `Форма фарба`,
	EditorInSelectionLabel: ` У виборі`,
	EditorInsertImageLabel: `Вставте зображення`,
	EditorInsertLinkLabel: `Вставте посилання`,
	EditorInsertVideoLabel: `Вставити відео`,
	EditorMatchCaseLabel: ` Справа з відповідності`,
	EditorNewTemplateLabel: `Новий шаблон`,
	EditorNextTemplateLabel: `Наступний шаблон`,
	EditorPasteButtonAppendBeginLabel: `Додайте ...`,
	EditorPasteButtonLabel: `Пасти`,
	EditorPasteTemplateWatermark: `Введіть текст вставки ...`,
	EditorPrevTemplateLabel: `Попередній шаблон`,
	EditorRegExLabel: ` Регулярний вираз`,
	EditorReplaceAllLabel: `Замініть усі`,
	EditorReplaceLabel: `Замінити`,
	EditorTemplateContactHint: `4 Тут поле електронної пошти вибраного вами контакту буде використовуватися для всіх екземплярів цього документа. </p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = короткий рік <br/> yyyy = довгий рік <br/> m = місяць (1-12) <br/> мм = місяць (01-12) <br/> mmm = абревіатура місяця (січень, лютий .. . Грудня) <br/> ммм = довгий місяць (січень, лютий ... грудень) <br/> d = день (1 - 31) <br/> dd = день (01 - 31) <br/> ddd = День тижня у словах (понеділок, вівторок ... неділя) <br/> e = короткий день тижня у словах (пн, тю ... сонце) <br/> d - порядковий день (1 -й, 2 -й, 3-й, 21-й, 22-й, 23-й, 31-й, 4-й ...) <br/> H = година в AM/PM (0-12) <br/> HH = година в AM/PM (00-12) <BR/ > H = година в день (0-23) <br/> hh = година в день (00-23) <br/> мм = хвилина <br/> ss = другий <br/> sss = мілісекунди <br/> A = AM/PM Маркер <br/> p = a.m./p.m. маркер`,
	EditorTemplateDateTimeCustomLabel: `Звичайний`,
	EditorTemplateDateTimeHint: `Поточна дата та/або час буде замінена на шаблони DateTime, коли вони вставляються.`,
	EditorTemplateDateTimeName: `Дата, час`,
	EditorTemplateDynamicHint: `<p> Усі трапляються цього шаблону використовуватимуть наданий текст. </p>`,
	EditorTemplateDynamicName: `Динамічний`,
	EditorTemplateEmptyPlaceholder: `{0} порожній ...`,
	EditorTemplateStaticHint: `<p> Усі трапляються цього шаблону використовуватимуть наданий текст. </p>`,
	EditorTemplateStaticName: `Статичний`,
	EditorTemplateTeaserText: `Більше скоро!`,
	EditorWatermark: `Зачекайте ...`,
	EditorWholeWordLabel: ` Ціле слово`,
	EditorWrapLabel: ` Обгортати`,

};