var UiStrings = {
	EditorAppendCloseLabel: `Finish appending`,
	EditorAppendInlineModeLabel: `Enable Block`,
	EditorAppendLineModeLabel: `Enable Inline`,
	EditorAppendManualModeLabel: `Toggle manual`,
	EditorAppendNonManualModeLabel: `Toggle manual`,
	EditorAppendPauseLabel: `Pause append`,
	EditorAppendPostLabel: `Toggle Before`,
	EditorAppendPreLabel: `Toggle Before`,
	EditorAppendResumeLabel: `Resume append`,
	EditorBgColorLabel: `Background Color`,
	EditorClearAllLabel: `Clear All`,
	EditorClipboardFormatsLabel: `Clipboard Formats`,
	EditorColorChooserTitle: `Editor Color`,
	EditorConfirmNtfTitle: `Confirm`,
	EditorDeleteAllButtonText: `Delete All`,
	EditorDeleteAllTemplatesNtfText: `Are you sure you want to delete ALL usages of '{0}'? 

This cannot be undone!`,
	EditorEditTemplateDetailsLabel: `Edit Details`,
	EditorEditTemplateNameLabel: `Name`,
	EditorFindLabel: `Find`,
	EditorFontColorLabel: `Font Color`,
	EditorFormatPaintLabel: `Format Paint`,
	EditorInSelectionLabel: ` In Selection`,
	EditorInsertImageLabel: `Insert Image`,
	EditorInsertLinkLabel: `Insert Link`,
	EditorInsertVideoLabel: `Insert Video`,
	EditorLinkButtonText: `Save`,
	EditorLinkLabel: `Enter Link`,
	EditorLinkPlaceholder: `Enter Url`,
	EditorMatchCaseLabel: ` Match Case`,
	EditorNewTemplateLabel: `New Template`,
	EditorNextTemplateLabel: `Next Template`,
	EditorPasteButtonAppendBeginLabel: `Append...`,
	EditorPasteButtonLabel: `Paste`,
	EditorPasteButtonLabelMobile: `Copy`,
	EditorPasteTemplateWatermark: `Enter paste text...`,
	EditorPrevTemplateLabel: `Previous Template`,
	EditorRegExLabel: ` Regular Expression`,
	EditorReplaceAllLabel: `Replace All`,
	EditorReplaceLabel: `Replace`,
	EditorTemplateContactHint: `<p>Using available contacts (requires a fetcher plugin) this field will be used for all instances of this template across this document or in any it will be referenced in later.</p><p> So for example if select email address here then the email field of the contact you select will be used for all instances in this document.</p>`,
	EditorTemplateContactName: `Contact`,
	EditorTemplateDateTimeCustomHint: `yy = short year<br/>yyyy = long year<br/>M = month (1-12)<br/>MM = month (01-12)<br/>MMM = month abbreviation (Jan, Feb ... Dec)<br/>MMMM = long month (January, February ... December)<br/>d = day (1 - 31)<br/>dd = day (01 - 31)<br/>ddd = day of the week in words (Monday, Tuesday ... Sunday)<br/>E = short day of the week in words (Mon, Tue ... Sun)<br/>D - Ordinal day (1st, 2nd, 3rd, 21st, 22nd, 23rd, 31st, 4th...)<br/>h = hour in am/pm (0-12)<br/>hh = hour in am/pm (00-12)<br/>H = hour in day (0-23)<br/>HH = hour in day (00-23)<br/>mm = minute<br/>ss = second<br/>SSS = milliseconds<br/>a = AM/PM marker<br/>p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Custom`,
	EditorTemplateDateTimeHint: `The current date and/or time will be substituted for DateTime templates when they are pasted.`,
	EditorTemplateDateTimeName: `Date Time`,
	EditorTemplateDynamicHint: `<p>All occurances of this template will use the provided text.</p>`,
	EditorTemplateDynamicName: `Dynamic`,
	EditorTemplateEmptyPlaceholder: `{0} is empty...`,
	EditorTemplateStaticHint: `<p>All occurances of this template will use the provided text.</p>`,
	EditorTemplateStaticName: `Static`,
	EditorTemplateTeaserText: `More coming soon!`,
	EditorTt1: `Click`,
	EditorTt2: `edit '<em>{0}</em>' ...`,
	EditorTt3: `edit color ...`,
	EditorTt4: `remove '<em>{0}</em>' ...`,
	EditorTt5: `remove item`,
	EditorTt6: `to follow ...`,
	EditorTt7: `goto '<em>{0}</em>' ...`,
	EditorWatermark: `Please wait...`,
	EditorWholeWordLabel: ` Whole Word`,
	EditorWrapLabel: ` Wrap Around`,

};