var UiStrings = {
	EditorAppendCloseLabel: `ສໍາເລັດການເພີ່ມເຕີມ`,
	EditorAppendInlineModeLabel: `ເປີດໃຊ້ງານ`,
	EditorAppendLineModeLabel: `ເປີດສາຍ`,
	EditorAppendManualModeLabel: `ຄູ່ມືສະຫຼັບ`,
	EditorAppendNonManualModeLabel: `ຄູ່ມືສະຫຼັບ`,
	EditorAppendPauseLabel: `ຢຸດຊົ່ວຄາວ`,
	EditorAppendPostLabel: `ສະຫຼັບກ່ອນ`,
	EditorAppendPreLabel: `ສະຫຼັບກ່ອນ`,
	EditorAppendResumeLabel: `ຊິ້ງຂໍ້ມູນ`,
	EditorBgColorLabel: `ສີພື້ນຫລັງ`,
	EditorClearAllLabel: `ລ້າງທັງຫມົດ`,
	EditorClipboardFormatsLabel: `ຮູບແບບ clipboard`,
	EditorConfirmNtfTitle: `ຢືນຢັນ`,
	EditorDeleteAllButtonText: `ລົບ​ທັງ​ຫມົດ`,
	EditorDeleteAllTemplatesNtfText: `ທ່ານແນ່ໃຈບໍ່ວ່າທ່ານຕ້ອງການລຶບການນໍາໃຊ້ທັງຫມົດຂອງ '{0}'?

ນີ້​ບໍ່​ສາ​ມາດ​ຍົກ​ເລີກ​ໄດ້!`,
	EditorEditTemplateDetailsLabel: `ແກ້ໄຂລາຍລະອຽດ`,
	EditorEditTemplateNameLabel: `ຊື່`,
	EditorFindLabel: `ຊອກ`,
	EditorFontColorLabel: `ສີຕົວອັກສອນ`,
	EditorFormatPaintLabel: `ສີຮູບແບບ`,
	EditorInSelectionLabel: ` ໃນການເລືອກ`,
	EditorInsertImageLabel: `ໃສ່ຮູບ`,
	EditorInsertLinkLabel: `ໃສ່ລິ້ງ`,
	EditorInsertVideoLabel: `ໃສ່ວິດີໂອ`,
	EditorMatchCaseLabel: ` ເປົ້າກໍລະນີແຂ່ງຂັນ`,
	EditorNewTemplateLabel: `ແມ່ແບບໃຫມ່`,
	EditorNextTemplateLabel: `ແມ່ແບບຕໍ່ໄປ`,
	EditorPasteButtonAppendBeginLabel: `ເພີ່ມເຕີມ ...`,
	EditorPasteButtonLabel: `ວາງໄວ້`,
	EditorPasteTemplateWatermark: `ໃສ່ຂໍ້ຄວາມທີ່ວາງໄວ້ ...`,
	EditorPrevTemplateLabel: `ແມ່ແບບຜ່ານມາ`,
	EditorRegExLabel: ` ການສະແດງອອກເປັນປະຈໍາ`,
	EditorReplaceAllLabel: `ທົດແທນທັງຫມົດ`,
	EditorReplaceLabel: `ປ່ຽນແທນ`,
	EditorTemplateContactHint: `<p> ການນໍາໃຊ້ລາຍຊື່ຜູ້ຕິດຕໍ່ທີ່ມີຢູ່ (ຕ້ອງການໂປແກຼມ FIVERCER) ນີ້ຫຼັງຈາກນັ້ນພາກສະຫນາມ Email ຂອງຜູ້ຕິດຕໍ່ທ່ານເລືອກຈະຖືກນໍາໃຊ້ສໍາລັບທຸກກໍລະນີທີ່ຢູ່ໃນເອກະສານນີ້. </ p>`,
	EditorTemplateContactName: `ຕິດຕໍ່`,
	EditorTemplateDateTimeCustomHint: `yy = ປີທີ່ຜ່ານມາ <br/> yyyy = ປີທີ່ຍາວກວ່າ <br/> mm = ເດືອນ = mmm = mmm = ເດືອນລະເດືອນ . CUR) <br/> mmmm = ເດືອນຍາວນານ (ເດືອນມັງກອນ, ເດືອນມັງກອນ) ມື້ຂອງອາທິດໃນຄໍາສັບ (ວັນຈັນ, ວັນອັງຄານ ... ຄັ້ງທີ 3, ວັນທີ 21, 19, ວັນທີ 4, ວັນທີ 4 ... ) <br/> (0-12 )/ > h = ຊົ່ວໂມງໃນມື້ (0-23) <br/> ຊົ່ວໂມງໃນມື້ (00-to> mm = ທີສອງ/> ss = milliseconds <br/> A = AM / PM Marker <br/> P = A.m./p.m.m. ເຄື່ອງຫມາຍ`,
	EditorTemplateDateTimeCustomLabel: `ປະເພນີ`,
	EditorTemplateDateTimeHint: `ວັນທີປະຈຸບັນແລະ / ຫຼືເວລາຈະຖືກທົດແທນສໍາລັບແມ່ແບບທີ່ກໍານົດໃນເວລາທີ່ພວກມັນຖືກວາງໄວ້.`,
	EditorTemplateDateTimeName: `ເວລາວັນທີ`,
	EditorTemplateDynamicHint: `<p> ການເກີດຂື້ນທັງຫມົດຂອງແມ່ແບບນີ້ຈະໃຊ້ຂໍ້ຄວາມທີ່ສະຫນອງໃຫ້. </ p>`,
	EditorTemplateDynamicName: `Dynamic`,
	EditorTemplateEmptyPlaceholder: `{0} ແມ່ນຫວ່າງເປົ່າ ...`,
	EditorTemplateStaticHint: `<p> ການເກີດຂື້ນທັງຫມົດຂອງແມ່ແບບນີ້ຈະໃຊ້ຂໍ້ຄວາມທີ່ສະຫນອງໃຫ້. </ p>`,
	EditorTemplateStaticName: `ສະຖິດ`,
	EditorTemplateTeaserText: `ອີກໃນໄວໆນີ້ຈະມາເຖິງໃນໄວໆນີ້!`,
	EditorWatermark: `ກະ​ລຸ​ນາ​ລໍ​ຖ້າ...`,
	EditorWholeWordLabel: ` ຕາທັງຫມົດ`,
	EditorWrapLabel: ` ຫໍ່ປະມານ`,

};