var UiStrings = {
	EditorAppendCloseLabel: `Finire l'avvio`,
	EditorAppendInlineModeLabel: `Abilita blocco`,
	EditorAppendLineModeLabel: `Abilita in linea`,
	EditorAppendManualModeLabel: `Manuale a disattivazione`,
	EditorAppendNonManualModeLabel: `Manuale a disattivazione`,
	EditorAppendPauseLabel: `Pausa aggiungi`,
	EditorAppendPostLabel: `Attiva alterni prima`,
	EditorAppendPreLabel: `Attiva alterni prima`,
	EditorAppendResumeLabel: `Riprendi l'append`,
	EditorBgColorLabel: `Colore di sfondo`,
	EditorClearAllLabel: `Cancella tutto`,
	EditorClipboardFormatsLabel: `Formati degli appunti`,
	EditorConfirmNtfTitle: `Confermare`,
	EditorDeleteAllButtonText: `Cancella tutto`,
	EditorDeleteAllTemplatesNtfText: `Sei sicuro di voler eliminare tutti gli usi di '{0}'?

Questo non può essere annullato!`,
	EditorEditTemplateDetailsLabel: `Modifica i dettagli`,
	EditorEditTemplateNameLabel: `Nome`,
	EditorFindLabel: `Trovare`,
	EditorFontColorLabel: `Colore del carattere`,
	EditorFormatPaintLabel: `Formato di vernice`,
	EditorInSelectionLabel: ` In selezione`,
	EditorInsertImageLabel: `Inserire l'immagine`,
	EditorInsertLinkLabel: `Inserisci il collegamento`,
	EditorInsertVideoLabel: `Inserire video`,
	EditorMatchCaseLabel: ` Match Case`,
	EditorNewTemplateLabel: `Nuovo modello`,
	EditorNextTemplateLabel: `Modello successivo`,
	EditorPasteButtonAppendBeginLabel: `Aggiungere...`,
	EditorPasteButtonLabel: `Impasto`,
	EditorPasteTemplateWatermark: `Immettere il testo in pasta ...`,
	EditorPrevTemplateLabel: `Modello precedente`,
	EditorRegExLabel: ` Espressione regolare`,
	EditorReplaceAllLabel: `Sostituisci tutto`,
	EditorReplaceLabel: `Sostituire`,
	EditorTemplateContactHint: `<p>Utilizzando i contatti disponibili (richiede un plug-in di recupero), questo campo verrà utilizzato per tutte le istanze di questo modello in questo documento o in qualsiasi in cui verrà fatto riferimento in seguito.</p><p> Quindi, ad esempio, se si seleziona l'indirizzo e-mail qui, il campo e-mail del contatto selezionato verrà utilizzato per tutte le istanze in questo documento.</p>`,
	EditorTemplateContactName: `Contatto`,
	EditorTemplateDateTimeCustomHint: `yy = anno corto<br/>aaaa = anno lungo<br/>M = mese (1-12)<br/>MM = mese (01-12)<br/>MMM = abbreviazione del mese (gennaio, febbraio ... Dic)<br/>MMMM = mese lungo (gennaio, febbraio... Dicembre)<br/>d = giorno (1 - 31)<br/>gg = giorno (01 - 31)<br/>ddd = giorno della settimana in parole (lunedì, martedì ... Domenica)<br/>E = giorno corto della settimana in parole (lun, mar ... Sole)<br/>D - Giorno ordinale (1°, 2°, 3°, 21°, 22°, 23°, 31°, 4°...)<br/>h = ora in am/pm (0-12)<br/>HH = ora in am/pm (00-12)<br/>H = ora del giorno (0-23)<br/>HH = ora del giorno (00-23)<br/>mm = minuto<br/>ss = secondo<br/>SSS = millisecondi<br/>a = indicatore AM/PM<br/>p = marcatore a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Costume`,
	EditorTemplateDateTimeHint: `La data e/o l'ora correnti saranno sostituiti con i modelli DateTime quando vengono incollati.`,
	EditorTemplateDateTimeName: `Appuntamento`,
	EditorTemplateDynamicHint: `<p>Tutte le occorrenze di questo modello utilizzeranno il testo fornito.</p>`,
	EditorTemplateDynamicName: `Dinamico`,
	EditorTemplateEmptyPlaceholder: `{0} è vuoto ...`,
	EditorTemplateStaticHint: `<p>Tutte le occorrenze di questo modello utilizzeranno il testo fornito.</p>`,
	EditorTemplateStaticName: `Statico`,
	EditorTemplateTeaserText: `Maggiori informazioni tra breve!`,
	EditorWatermark: `Attendere prego...`,
	EditorWholeWordLabel: ` Parola intera`,
	EditorWrapLabel: ` Arrotolare`,

};