var UiStrings = {
	EditorAppendCloseLabel: `Applingを終了します`,
	EditorAppendInlineModeLabel: `ブロックを有効にします`,
	EditorAppendLineModeLabel: `インラインを有効にします`,
	EditorAppendManualModeLabel: `トグルマニュアル`,
	EditorAppendNonManualModeLabel: `トグルマニュアル`,
	EditorAppendPauseLabel: `一時停止の追加`,
	EditorAppendPostLabel: `前に切り替えます`,
	EditorAppendPreLabel: `前に切り替えます`,
	EditorAppendResumeLabel: `履歴書追加`,
	EditorBgColorLabel: `背景色`,
	EditorClearAllLabel: `すべてクリア`,
	EditorClipboardFormatsLabel: `クリップボード形式`,
	EditorColorChooserTitle: `編集者の色`,
	EditorConfirmNtfTitle: `確認する`,
	EditorDeleteAllButtonText: `すべて削除`,
	EditorDeleteAllTemplatesNtfText: `「{0}」のすべての使用法を削除する必要がありますか？

これは、元に戻すことはできません！`,
	EditorEditTemplateDetailsLabel: `詳細を編集する`,
	EditorEditTemplateNameLabel: `名前`,
	EditorFindLabel: `探す`,
	EditorFontColorLabel: `フォントカラー`,
	EditorFormatPaintLabel: `フォーマットペイント`,
	EditorInSelectionLabel: ` 選択`,
	EditorInsertImageLabel: `画像を挿入します`,
	EditorInsertLinkLabel: `リンクを挿入します`,
	EditorInsertVideoLabel: `ビデオを挿入します`,
	EditorLinkButtonText: `保存`,
	EditorLinkLabel: `リンクを入力します`,
	EditorLinkPlaceholder: `URLを入力`,
	EditorMatchCaseLabel: ` マッチケース`,
	EditorNewTemplateLabel: `新しいテンプレート`,
	EditorNextTemplateLabel: `次のテンプレート`,
	EditorPasteButtonAppendBeginLabel: `追加...`,
	EditorPasteButtonLabel: `ペースト`,
	EditorPasteTemplateWatermark: `貼り付けテキストを入力してください...`,
	EditorPrevTemplateLabel: `前のテンプレート`,
	EditorRegExLabel: ` 正規表現`,
	EditorReplaceAllLabel: `すべてを交換します`,
	EditorReplaceLabel: `交換する`,
	EditorTemplateContactHint: `<p>利用可能な連絡先(フェッチャープラグインが必要)を使用すると、このフィールドは、このドキュメント全体のこのテンプレートのすべてのインスタンス、または後で参照されるすべてのインスタンスに使用されます。</p><p> たとえば、ここでメールアドレスを選択すると、選択した連絡先のメールフィールドがこのドキュメントのすべてのインスタンスに使用されます。</p>`,
	EditorTemplateContactName: `接触`,
	EditorTemplateDateTimeCustomHint: `yy = 短い年<br/>yyyy = 長い年<br/>M = 月 (1-12)<br/>MM = 月 (01-12)<br/>MMM = 月の省略形 (Jan, Feb ...12月)<br/>MMMM = 長い月(1月、2月...12月)<br/>d = 日 (1 - 31)<br/>dd = 日 (01 - 31)<br/>ddd =単語の曜日(月曜日、火曜日...日曜日)<br/>E =単語の短い曜日(月、火...日)<br/>D - 通常の日(1日、2日、3日、21日、22日、23日、31日、4日...)<br/>h = 時間 (午前/午後) (0-12)<br/>hh = 午前/午後の時間 (00 から 12)<br/>H = 時間 (0 から 23)<br/>HH = 時間 (00-23)<br/>mm = 分<br/>ss = 秒<br/>SSS = ミリ秒<br/>a = AM/PM マーカー<br/>p = a.m./p.m. マーカー`,
	EditorTemplateDateTimeCustomLabel: `カスタム`,
	EditorTemplateDateTimeHint: `現在の日付および/または時間は、貼り付けられたときにDateTimeテンプレートに置き換えられます。`,
	EditorTemplateDateTimeName: `日付時刻`,
	EditorTemplateDynamicHint: `<p>このテンプレートのすべての出現箇所では、提供されたテキストが使用されます。</p>`,
	EditorTemplateDynamicName: `動的`,
	EditorTemplateEmptyPlaceholder: `{0}は空です...`,
	EditorTemplateStaticHint: `<p>このテンプレートのすべての出現箇所では、提供されたテキストが使用されます。</p>`,
	EditorTemplateStaticName: `静的`,
	EditorTemplateTeaserText: `もうすぐ来る！`,
	EditorTt1: `クリック`,
	EditorTt2: `編集 '<em> {0} </em>' ...`,
	EditorTt3: `色を編集...`,
	EditorTt4: `'<em> {0} </em>'を削除します。`,
	EditorTt5: `アイテムを削除します`,
	EditorTt6: `従うために...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `お待ちください...`,
	EditorWholeWordLabel: ` 単語全体`,
	EditorWrapLabel: ` 包み込む`,

};