var UiStrings = {
	EditorAppendCloseLabel: `Selesai Menambahkan`,
	EditorAppendInlineModeLabel: `Aktifkan blok`,
	EditorAppendLineModeLabel: `Aktifkan inline`,
	EditorAppendManualModeLabel: `Toggle Manual`,
	EditorAppendNonManualModeLabel: `Toggle Manual`,
	EditorAppendPauseLabel: `Jeda Tambahkan`,
	EditorAppendPostLabel: `Beralih sebelumnya`,
	EditorAppendPreLabel: `Beralih sebelumnya`,
	EditorAppendResumeLabel: `Lanjutkan menambahkan`,
	EditorBgColorLabel: `Warna latar belakang`,
	EditorClearAllLabel: `Bersihkan semua`,
	EditorClipboardFormatsLabel: `Format clipboard`,
	EditorColorChooserTitle: `Warna editor`,
	EditorConfirmNtfTitle: `Mengonfirmasi`,
	EditorDeleteAllButtonText: `Hapus semua`,
	EditorDeleteAllTemplatesNtfText: `Apakah Anda yakin ingin menghapus semua penggunaan '{0}'?

Ini tidak dapat dibatalkan!`,
	EditorEditTemplateDetailsLabel: `Edit detail`,
	EditorEditTemplateNameLabel: `Nama`,
	EditorFindLabel: `Menemukan`,
	EditorFontColorLabel: `Warna huruf`,
	EditorFormatPaintLabel: `Format cat`,
	EditorInSelectionLabel: ` Dalam seleksi`,
	EditorInsertImageLabel: `Masukkan gambar`,
	EditorInsertLinkLabel: `Masukkan tautan`,
	EditorInsertVideoLabel: `Sisipkan video`,
	EditorLinkButtonText: `Menyimpan`,
	EditorLinkLabel: `Masukkan tautan`,
	EditorLinkPlaceholder: `Masukkan URL`,
	EditorMatchCaseLabel: ` Kasing pertandingan`,
	EditorNewTemplateLabel: `Template baru`,
	EditorNextTemplateLabel: `Template berikutnya`,
	EditorPasteButtonAppendBeginLabel: `Menambahkan...`,
	EditorPasteButtonLabel: `Tempel`,
	EditorPasteButtonLabelMobile: `Menyalin`,
	EditorPasteTemplateWatermark: `Masukkan teks pasta ...`,
	EditorPrevTemplateLabel: `Template sebelumnya`,
	EditorRegExLabel: ` Ekspresi reguler`,
	EditorReplaceAllLabel: `Menggantikan semua`,
	EditorReplaceLabel: `Mengganti`,
	EditorTemplateContactHint: `<p>Menggunakan kontak yang tersedia (memerlukan plugin pengambil) bidang ini akan digunakan untuk semua contoh templat ini di seluruh dokumen ini atau di mana pun itu akan dirujuk nanti.</p><p> Jadi misalnya jika pilih alamat email di sini maka bidang email dari kontak yang Anda pilih akan digunakan untuk semua contoh dalam dokumen ini.</p>`,
	EditorTemplateContactName: `Kontak`,
	EditorTemplateDateTimeCustomHint: `yy = tahun pendek<br/>yyyy = tahun panjang<br/>M = bulan (1-12)<br/>MM = bulan (01-12)<br/>MMM = singkatan bulan (Jan, Feb ... Desember)<br/>MMMM = bulan panjang (Januari, Februari ... Desember)<br/>d = hari (1 – 31)<br/>DD = Hari (01 - 31)<br/>ddd = hari dalam seminggu dengan kata-kata (Senin, Selasa ... Minggu)<br/>E = hari pendek dalam seminggu dengan kata-kata (Sen, Tue ... Matahari)<br/>D - Hari ordinal (1st, 2nd, 3rd, 21st, 22nd, 23rd, 31st, 4th...)<br/>H = Jam dalam AM/PM (0-12)<br/>HH = Jam dalam AM/PM (00-12)<br/>H = jam dalam sehari (0-23)<br/>HH = jam dalam sehari (00-23)<br/>mm = menit<br/>ss = detik<br/>SSS = milidetik<br/>a = Penanda AM/PM<br/>p = penanda a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Kebiasaan`,
	EditorTemplateDateTimeHint: `Tanggal dan/atau waktu saat ini akan diganti dengan template datetime saat ditempel.`,
	EditorTemplateDateTimeName: `Tanggal Waktu`,
	EditorTemplateDynamicHint: `<p>Semua kemunculan template ini akan menggunakan teks yang disediakan.</p>`,
	EditorTemplateDynamicName: `Dinamis`,
	EditorTemplateEmptyPlaceholder: `{0} kosong ...`,
	EditorTemplateStaticHint: `<p>Semua kemunculan template ini akan menggunakan teks yang disediakan.</p>`,
	EditorTemplateStaticName: `Statis`,
	EditorTemplateTeaserText: `Selebihnya datang segera!`,
	EditorTt1: `Klik`,
	EditorTt2: `Edit '<em> {0} </em>' ...`,
	EditorTt3: `Edit Warna ...`,
	EditorTt4: `hapus '<em> {0} </em>' ...`,
	EditorTt5: `Hapus item`,
	EditorTt6: `mengikuti ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Harap tunggu...`,
	EditorWholeWordLabel: ` Seluruh kata`,
	EditorWrapLabel: ` Membungkus`,

};