var UiStrings = {
	EditorAppendCloseLabel: `Аяктоо`,
	EditorAppendInlineModeLabel: `Блок иштетүү`,
	EditorAppendLineModeLabel: `Inline иштетүү`,
	EditorAppendManualModeLabel: `Колдонмо которгуюл`,
	EditorAppendNonManualModeLabel: `Колдонмо которгуюл`,
	EditorAppendPauseLabel: `Тыныгуу тиркеме`,
	EditorAppendPostLabel: `Чейин которгуч`,
	EditorAppendPreLabel: `Чейин которгуч`,
	EditorAppendResumeLabel: `Резюме тиркеме`,
	EditorBgColorLabel: `Фон түсү`,
	EditorClearAllLabel: `Баарын тазалоо`,
	EditorClipboardFormatsLabel: `Алмашуу форматтары`,
	EditorConfirmNtfTitle: `Ыраста`,
	EditorDeleteAllButtonText: `Бардыгын жок кыл`,
	EditorDeleteAllTemplatesNtfText: `'{0}' керектөөчүлүктү жок кылгыңыз келеби?

Бул артка кайтаруу мүмкүн эмес!`,
	EditorEditTemplateDetailsLabel: `Маалыматты түзөтүү`,
	EditorEditTemplateNameLabel: `Аты`,
	EditorFindLabel: `Табуу`,
	EditorFontColorLabel: `Арип түсү`,
	EditorFormatPaintLabel: `Форматтоо боёк`,
	EditorInSelectionLabel: ` Тандоо`,
	EditorInsertImageLabel: `Сүрөттү кыстарыңыз`,
	EditorInsertLinkLabel: `Шилтемени кыстарыңыз`,
	EditorInsertVideoLabel: `Видеону киргизиңиз`,
	EditorMatchCaseLabel: ` Матч иши`,
	EditorNewTemplateLabel: `Жаңы шаблон`,
	EditorNextTemplateLabel: `Кийинки шаблон`,
	EditorPasteButtonAppendBeginLabel: `Кошуу...`,
	EditorPasteButtonLabel: `Паста`,
	EditorPasteTemplateWatermark: `Паста текстти киргизиңиз ...`,
	EditorPrevTemplateLabel: `Мурунку шаблон`,
	EditorRegExLabel: ` Үзгүлтүксүз билдирүү`,
	EditorReplaceAllLabel: `Баарын алмаштыруу`,
	EditorReplaceLabel: `Алмаштыруу`,
	EditorTemplateContactHint: `Байланышты колдонуу (Фетчердин плагин плагин талап кылынат) Бул документтин бардык учурлары ушул документтин бардык учурлары үчүн колдонулат же ал документтин бардык учурлары үчүн колдонулат же андан кийинчерээк шилтемелешет. </ p> <p> электрондук почта дареги Бул жерде сиз тандаган байланыштын электрондук почта талаасы бул документтеги бардык учурларда колдонулат. </ p>`,
	EditorTemplateContactName: `Байланыш`,
	EditorTemplateDateTimeCustomHint: `YY = Кыска жыл <br/> YYYY = узак жыл <br/> <br/> m = Ай (1-12) <br////30 мм = Ай (01-12) <br/> МММ = Ай Аббревиатура (Ян, Фев) .) <br/> МММм = Узун ай (январь, февраль ... декабрь) <br/> D = Day (1 - 31) <br/> DD = Day (01 - 31) <br/> DDD = Дүйшөмбү (Дүйшөмбү, Шейшемби ... Жекшемби) <br/> E = жуманын кыска күнү (Дүйшөмбү, С. 3-, 21-, 23-, 23-, 4-, 4-, 4-...) <br/> h = саат am / pm (0-12) <br/> hh = саат AM / PM (00-12) <br / > H = саат күнүнө (0-23) <br/> HH = HISE DEADE (00-23) <br/> MM = Минута <br/> SS = Second <br/> SSS = Миллисекунд: A = Am / PM Marker <br/> P = A.M.M.m. Маркер`,
	EditorTemplateDateTimeCustomLabel: `Салт`,
	EditorTemplateDateTimeHint: `Учурдагы датасы жана / же убактысы белгиленген учурларда, даталар шаблондоруна алмаштырылат.`,
	EditorTemplateDateTimeName: `Дата убакыт`,
	EditorTemplateDynamicHint: `<p> Бул шаблондун бардык заряддары берилген текстти колдонот. </ p>`,
	EditorTemplateDynamicName: `Динамикалык`,
	EditorTemplateEmptyPlaceholder: `{0} бош ...`,
	EditorTemplateStaticHint: `<p> Бул шаблондун бардык заряддары берилген текстти колдонот. </ p>`,
	EditorTemplateStaticName: `Статикалык`,
	EditorTemplateTeaserText: `Жакында көбүрөөк келет!`,
	EditorWatermark: `Сураныч, күтө туруңуз ...`,
	EditorWholeWordLabel: ` Бүт сөз`,
	EditorWrapLabel: ` Ороп`,

};