var UiStrings = {
	EditorAppendCloseLabel: `Voltooi by`,
	EditorAppendInlineModeLabel: `Aktiveer blok`,
	EditorAppendLineModeLabel: `Aktiveer inline`,
	EditorAppendManualModeLabel: `Skakelhandleiding`,
	EditorAppendNonManualModeLabel: `Skakelhandleiding`,
	EditorAppendPauseLabel: `Pouse voeg by`,
	EditorAppendPostLabel: `Wissel voor`,
	EditorAppendPreLabel: `Wissel voor`,
	EditorAppendResumeLabel: `Hervat bygevoeg`,
	EditorBgColorLabel: `Agtergrondkleur`,
	EditorClearAllLabel: `Duidelik alles`,
	EditorClipboardFormatsLabel: `Knipbordformate`,
	EditorConfirmNtfTitle: `Bevestig`,
	EditorDeleteAllButtonText: `Vee alles uit`,
	EditorDeleteAllTemplatesNtfText: `Is u seker dat u alle gebruike van '{0}' wil uitvee?

Dit kan nie ongedaan gemaak word nie!`,
	EditorEditTemplateDetailsLabel: `Redigeer besonderhede`,
	EditorEditTemplateNameLabel: `Naam`,
	EditorFindLabel: `Vind`,
	EditorFontColorLabel: `Lettertipe kleur`,
	EditorFormatPaintLabel: `Formaat verf`,
	EditorInSelectionLabel: ` In seleksie`,
	EditorInsertImageLabel: `Voeg beeld in`,
	EditorInsertLinkLabel: `Voeg skakel in`,
	EditorInsertVideoLabel: `Voeg video in`,
	EditorMatchCaseLabel: ` Vuurhoutjie doos`,
	EditorNewTemplateLabel: `Nuwe sjabloon`,
	EditorNextTemplateLabel: `Volgende sjabloon`,
	EditorPasteButtonAppendBeginLabel: `Voeg ...`,
	EditorPasteButtonLabel: `Plak`,
	EditorPasteTemplateWatermark: `Voer plak teks in ...`,
	EditorPrevTemplateLabel: `Vorige sjabloon`,
	EditorRegExLabel: ` Gewone uitdrukking`,
	EditorReplaceAllLabel: `Vervang alles`,
	EditorReplaceLabel: `Vervang`,
	EditorTemplateContactHint: `<p> Gebruik beskikbare kontakte (benodig 'n fetcher -inprop) Hierdie veld word gebruik vir alle gevalle van hierdie sjabloon oor hierdie dokument, of daar word later verwys. Hier sal die e -posveld van die kontak wat u kies, gebruik word vir alle gevalle in hierdie dokument. </p>`,
	EditorTemplateContactName: `Kontak`,
	EditorTemplateDateTimeCustomHint: `yy = kort jaar <br/> yyyy = lang jaar <br/> m = maand (1-12) <br/> mm = maand (01-12) <br/> mmm = maand afkorting (Jan, Feb .. . Dec) <br/> mmmm = lang maand (Januarie, Februarie ... Desember) <br/> d = dag (1 - 31) <br/> dd = dag (01 - 31) <br/> ddd = Dag van die week in woorde (Maandag, Dinsdag ... Sondag) <br/> E = Kort dag van die week in woorde (Ma, Di ... Sun) <br/> D - Ordinale dag (1ste, 2de, 3de, 21ste, 22ste, 23ste, 31ste, 4de ...) <br/> h = uur in am/pm (0-12) <br/> hh = uur in am/pm (00-12) <br/ > H = uur in die dag (0-23) <br/> hh = uur in die dag (00-23) <br/> mm = minuut <br/> ss = tweede <br/> sss = millisekondes <br/> A = AM/PM -merker <br/> p = a.m./p.m. merker`,
	EditorTemplateDateTimeCustomLabel: `Gebruik`,
	EditorTemplateDateTimeHint: `Die huidige datum en/of tyd sal vervang word met die datumsjablone wanneer dit geplak word.`,
	EditorTemplateDateTimeName: `Datum Tyd`,
	EditorTemplateDynamicHint: `<p> Alle voorvalle van hierdie sjabloon sal die verskafde teks gebruik. </p>`,
	EditorTemplateDynamicName: `Dinamies`,
	EditorTemplateEmptyPlaceholder: `{0} is leeg ...`,
	EditorTemplateStaticHint: `<p> Alle voorvalle van hierdie sjabloon sal die verskafde teks gebruik. </p>`,
	EditorTemplateStaticName: `Staties`,
	EditorTemplateTeaserText: `Meer kom binnekort!`,
	EditorWatermark: `Wag asseblief...`,
	EditorWholeWordLabel: ` Hele woord`,
	EditorWrapLabel: ` Wrap rond`,

};