var UiStrings = {
	EditorAppendCloseLabel: `完成添加`,
	EditorAppendInlineModeLabel: `啟用塊`,
	EditorAppendLineModeLabel: `啟用內聯`,
	EditorAppendManualModeLabel: `切換手冊`,
	EditorAppendNonManualModeLabel: `切換手冊`,
	EditorAppendPauseLabel: `暫停附加`,
	EditorAppendPostLabel: `切換之前`,
	EditorAppendPreLabel: `切換之前`,
	EditorAppendResumeLabel: `簡歷附加`,
	EditorBgColorLabel: `背景顏色`,
	EditorClearAllLabel: `清除全部`,
	EditorClipboardFormatsLabel: `剪貼板格式`,
	EditorColorChooserTitle: `編輯顏色`,
	EditorConfirmNtfTitle: `確認`,
	EditorDeleteAllButtonText: `刪除所有`,
	EditorDeleteAllTemplatesNtfText: `您確定要刪除“ {0}”的所有用法？

這不能被撤消！`,
	EditorEditTemplateDetailsLabel: `編輯詳細信息`,
	EditorEditTemplateNameLabel: `姓名`,
	EditorFindLabel: `尋找`,
	EditorFontColorLabel: `字體顏色`,
	EditorFormatPaintLabel: `格式塗料`,
	EditorInSelectionLabel: ` 在選擇中`,
	EditorInsertImageLabel: `插入圖像`,
	EditorInsertLinkLabel: `插入鏈接`,
	EditorInsertVideoLabel: `插入視頻`,
	EditorLinkButtonText: `節省`,
	EditorLinkLabel: `輸入鏈接`,
	EditorLinkPlaceholder: `輸入網址`,
	EditorMatchCaseLabel: ` 相符`,
	EditorNewTemplateLabel: `新模板`,
	EditorNextTemplateLabel: `下一個模板`,
	EditorPasteButtonAppendBeginLabel: `附加...`,
	EditorPasteButtonLabel: `粘貼`,
	EditorPasteTemplateWatermark: `輸入糊狀文字...`,
	EditorPrevTemplateLabel: `以前的模板`,
	EditorRegExLabel: ` 正則表達式`,
	EditorReplaceAllLabel: `全部替換`,
	EditorReplaceLabel: `代替`,
	EditorTemplateContactHint: `<p>使用可用的聯繫人（需要提取器外掛程式），此欄位將用於本文檔中此範本的所有實例，或稍後將引用的任何範本。</p><p> 因此，例如，如果在此處選擇電子郵件位址，則您選擇的聯繫人的電子郵件欄位將用於本文檔中的所有實例。</p>`,
	EditorTemplateContactName: `接觸`,
	EditorTemplateDateTimeCustomHint: `yy = 短年<br/>yyyy = 長年<br/>M = 月 （1-12）<br/>MM = 月 （01-12）<br/>MMM = 月份縮寫（Jan、Feb ...12月）<br/>MMMM = 長月（1 月、2 月......12月）<br/>d = 天 （1 - 31）<br/>dd = 天 （01 - 31）<br/>ddd = 星期幾（星期一、星期二......星期天）<br/>E = 一周中的短日子（週一、週二......周日）<br/>D - 序數日（1日、2日、3日、21日、22日、23日、31日、4日...<br/>h = 小時，單位為上午 / 下午 （0-12）<br/>hh = 小時（上午 /下午 ）（00-12）<br/>H = 一天中的小時 （0-23）<br/>HH = 一天中的小時 （00-23）<br/>mm = 分鐘<br/>ss = 秒<br/>SSS = 毫秒<br/>a = AM/PM 標記<br/>p = 上午/下午標記`,
	EditorTemplateDateTimeCustomLabel: `風俗`,
	EditorTemplateDateTimeHint: `當前日期和/或時間將粘貼時DateTime模板。`,
	EditorTemplateDateTimeName: `約會時間`,
	EditorTemplateDynamicHint: `<p>此範本的所有匹配項都將使用提供的文字。</p>`,
	EditorTemplateDynamicName: `動態的`,
	EditorTemplateEmptyPlaceholder: `{0}是空...`,
	EditorTemplateStaticHint: `<p>此範本的所有匹配項都將使用提供的文字。</p>`,
	EditorTemplateStaticName: `靜止的`,
	EditorTemplateTeaserText: `更多即將推出！`,
	EditorTt1: `點擊`,
	EditorTt2: `編輯'<em> {0} </em>'...`,
	EditorTt3: `編輯顏色...`,
	EditorTt4: `刪除'<em> {0} </em>'...`,
	EditorTt5: `除去項目`,
	EditorTt6: `跟隨 ...`,
	EditorTt7: `goto'<em> {0} </em>'...`,
	EditorWatermark: `請稍等...`,
	EditorWholeWordLabel: ` 整個詞`,
	EditorWrapLabel: ` 環繞`,

};