var UiStrings = {
	EditorAppendCloseLabel: `Аяктоо`,
	EditorAppendInlineModeLabel: `Блок иштетүү`,
	EditorAppendLineModeLabel: `Inline иштетүү`,
	EditorAppendManualModeLabel: `Колдонмо которгуюл`,
	EditorAppendNonManualModeLabel: `Колдонмо которгуюл`,
	EditorAppendPauseLabel: `Тыныгуу тиркеме`,
	EditorAppendPostLabel: `Чейин которгуч`,
	EditorAppendPreLabel: `Чейин которгуч`,
	EditorAppendResumeLabel: `Резюме тиркеме`,
	EditorBgColorLabel: `Фон түсү`,
	EditorClearAllLabel: `Баарын тазалоо`,
	EditorClipboardFormatsLabel: `Алмашуу форматтары`,
	EditorColorChooserTitle: `Редактор түсү`,
	EditorConfirmNtfTitle: `Ыраста`,
	EditorDeleteAllButtonText: `Бардыгын жок кыл`,
	EditorDeleteAllTemplatesNtfText: `'{0}' керектөөчүлүктү жок кылгыңыз келеби?

Бул артка кайтаруу мүмкүн эмес!`,
	EditorEditTemplateDetailsLabel: `Маалыматты түзөтүү`,
	EditorEditTemplateNameLabel: `Аты`,
	EditorFindLabel: `Табуу`,
	EditorFontColorLabel: `Арип түсү`,
	EditorFormatPaintLabel: `Форматтоо боёк`,
	EditorInSelectionLabel: ` Тандоо`,
	EditorInsertImageLabel: `Сүрөттү кыстарыңыз`,
	EditorInsertLinkLabel: `Шилтемени кыстарыңыз`,
	EditorInsertVideoLabel: `Видеону киргизиңиз`,
	EditorLinkButtonText: `Сактоо`,
	EditorLinkLabel: `Шилтеме киргизиңиз`,
	EditorLinkPlaceholder: `URL киргизиңиз`,
	EditorMatchCaseLabel: ` Матч иши`,
	EditorNewTemplateLabel: `Жаңы шаблон`,
	EditorNextTemplateLabel: `Кийинки шаблон`,
	EditorPasteButtonAppendBeginLabel: `Кошуу...`,
	EditorPasteButtonLabel: `Паста`,
	EditorPasteTemplateWatermark: `Паста текстти киргизиңиз ...`,
	EditorPrevTemplateLabel: `Мурунку шаблон`,
	EditorRegExLabel: ` Үзгүлтүксүз билдирүү`,
	EditorReplaceAllLabel: `Баарын алмаштыруу`,
	EditorReplaceLabel: `Алмаштыруу`,
	EditorTemplateContactHint: `<p>Жеткиликтүү контакттарды колдонуу (фетчер плагинди талап кылат) бул талаа ушул документ боюнча бул шаблондун бардык учурлары үчүн колдонулат же кийин шилтеме кылынат.</p><p> Мисалы, бул жерде электрондук почта дарегин тандап алсаңар, анда сиз тандаган контакттын электрондук почта талаасы бул документте бардык учурлар үчүн колдонулат.</p>`,
	EditorTemplateContactName: `Байланыш`,
	EditorTemplateDateTimeCustomHint: `y = кыска жыл<br/>йе = узак жыл<br/>М = ай (1-12)<br/>ММ = ай (01-12)<br/>МММ = ай кесүү (Ян, февраль ... Декабрь)<br/>МММ = узак ай (январь, февраль ... Декабрь)<br/>д = күнү (1 — 31)<br/>дд = күнү (01 — 31)<br/>ддд = жуманын күнү сөз менен (дүйшөмбү, шейшемби ... Жекшемби)<br/>Е = жуманын кыска күнү сөз менен (Мон, Тюэ ... Күн)<br/>Д - Чыгыш күнү (1-, 2-, 3-, 21-, 22-, 23-, 31-, 4-...)<br/>саат ам / саат (0-12)<br/>саат ам / саат (00-12)<br/>Н = күндүз саат (0-23)<br/>HH = күндүз саат (00-23)<br/>мм = мүнөт<br/>ss = экинчи<br/>SSS = миллисекунд<br/>= AM /PM маркери<br/>p = саат 13.00 /13.00 маркер`,
	EditorTemplateDateTimeCustomLabel: `Салт`,
	EditorTemplateDateTimeHint: `Учурдагы датасы жана / же убактысы белгиленген учурларда, даталар шаблондоруна алмаштырылат.`,
	EditorTemplateDateTimeName: `Дата убакыт`,
	EditorTemplateDynamicHint: `<p>Бул шаблондун бардык пайда болушу берилген текстти колдонот.</p>`,
	EditorTemplateDynamicName: `Динамикалык`,
	EditorTemplateEmptyPlaceholder: `{0} бош ...`,
	EditorTemplateStaticHint: `<p>Бул шаблондун бардык пайда болушу берилген текстти колдонот.</p>`,
	EditorTemplateStaticName: `Статикалык`,
	EditorTemplateTeaserText: `Жакында көбүрөөк келет!`,
	EditorTt1: `Чыкылдатуу`,
	EditorTt2: `'<em> {0} </ em>' оңдоо ...`,
	EditorTt3: `Түстүү түс ...`,
	EditorTt4: `'<Em> {0} </ em>' алып салуу ...`,
	EditorTt5: `Нерсени алып салуу`,
	EditorTt6: `ээрчүү ...`,
	EditorTt7: `goto '<em> {0} </ em>' ...`,
	EditorWatermark: `Сураныч, күтө туруңуз ...`,
	EditorWholeWordLabel: ` Бүт сөз`,
	EditorWrapLabel: ` Ороп`,

};