var UiStrings = {
	EditorAppendCloseLabel: `Eklemeyi bitir`,
	EditorAppendInlineModeLabel: `Bloğu Etkinleştir`,
	EditorAppendLineModeLabel: `Satır içi etkinleştir`,
	EditorAppendManualModeLabel: `Başlangıç ​​Kılavuzu`,
	EditorAppendNonManualModeLabel: `Başlangıç ​​Kılavuzu`,
	EditorAppendPauseLabel: `Duraklat eklemek`,
	EditorAppendPostLabel: `Daha önce geçiş yap`,
	EditorAppendPreLabel: `Daha önce geçiş yap`,
	EditorAppendResumeLabel: `Özgeçmiş Ekle`,
	EditorBgColorLabel: `Arka plan rengi`,
	EditorClearAllLabel: `Hepsini temizle`,
	EditorClipboardFormatsLabel: `Pano Biçimleri`,
	EditorConfirmNtfTitle: `Onaylamak`,
	EditorDeleteAllButtonText: `Hepsini sil`,
	EditorDeleteAllTemplatesNtfText: `'{0}' in tüm kullanımlarını silmek istediğinizden emin misiniz?

Bu geri alınamaz!`,
	EditorEditTemplateDetailsLabel: `Detayları düzenle`,
	EditorEditTemplateNameLabel: `İsim`,
	EditorFindLabel: `Bulmak`,
	EditorFontColorLabel: `Yazı rengi`,
	EditorFormatPaintLabel: `Biçim Boyası`,
	EditorInSelectionLabel: ` Seçimde`,
	EditorInsertImageLabel: `Resim ekle`,
	EditorInsertLinkLabel: `Bağlantı Ekle`,
	EditorInsertVideoLabel: `Video ekle`,
	EditorMatchCaseLabel: ` Kibrit kasası`,
	EditorNewTemplateLabel: `Yeni şablon`,
	EditorNextTemplateLabel: `Sonraki Şablon`,
	EditorPasteButtonAppendBeginLabel: `Ek ...`,
	EditorPasteButtonLabel: `Yapıştırmak`,
	EditorPasteTemplateWatermark: `Macun metnine girin ...`,
	EditorPrevTemplateLabel: `Önceki Şablon`,
	EditorRegExLabel: ` Düzenli ifade`,
	EditorReplaceAllLabel: `Hepsini değiştir`,
	EditorReplaceLabel: `Yer değiştirmek`,
	EditorTemplateContactHint: `<p> Mevcut kişileri kullanma (bir toplama eklentisi gerektirir) Bu alan, bu şablonun tüm örnekleri için bu belgede veya daha sonra referans verilecektir. Burada seçtiğiniz kişinin e -posta alanı bu belgedeki tüm örnekler için kullanılacaktır. </p>`,
	EditorTemplateContactName: `Temas etmek`,
	EditorTemplateDateTimeCustomHint: `yy = kısa yıl <br/> yyyy = uzun yıl <br/> ay (1-12) <br/> mm = ay (01-12) <br/> mmm = ay kısaltma (Ocak, Şubat .. . Aralık) <br/> mmmm = uzun ay (Ocak, Şubat ... Aralık) <br/> d = gün (1 - 31) <br/> dd = gün (01 - 31) <br/> ddd = Kelimelerde Haftanın Günü (Pazartesi, Salı ... Pazar) <br/> E = Kelimelerde Haftanın Kısa Günü (Pzt, Sal ... Güneş) <br/> D - Sıralı Günü (1, 2., 3, 21, 22, 23, 31, 4. ...) <br/> H = saat/pm (0-12) <br/> HH = saat/pm (00-12) > H = gün içinde saat (0-23) <br/> hh = gün içinde saat (00-23) <br/> mm = dakika <br/> ss = ikinci <br/> sss = milisaniye <br/> a = am/pm işaretleyici <br/> p = a.m./p.m. işaretleyici`,
	EditorTemplateDateTimeCustomLabel: `Gelenek`,
	EditorTemplateDateTimeHint: `Mevcut tarih ve/veya saat, yapıştırıldıklarında DateTime şablonları için değiştirilecektir.`,
	EditorTemplateDateTimeName: `Tarih saati`,
	EditorTemplateDynamicHint: `<p> Bu şablonun tüm olayları sağlanan metni kullanacaktır. </p>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} boş ...`,
	EditorTemplateStaticHint: `<p> Bu şablonun tüm olayları sağlanan metni kullanacaktır. </p>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Daha fazlası yakında!`,
	EditorWatermark: `Lütfen bekleyin...`,
	EditorWholeWordLabel: ` Tüm dünya`,
	EditorWrapLabel: ` Etrafına sarmak`,

};