var UiStrings = {
	EditorAppendCloseLabel: `Whakaoti i te Apiti`,
	EditorAppendInlineModeLabel: `Whakahohe Poraka`,
	EditorAppendLineModeLabel: `Whakahohe i roto`,
	EditorAppendManualModeLabel: `Toggle Topggle`,
	EditorAppendNonManualModeLabel: `Toggle Topggle`,
	EditorAppendPauseLabel: `Te taapiri mo te taapiri`,
	EditorAppendPostLabel: `Tuhinga o mua`,
	EditorAppendPreLabel: `Tuhinga o mua`,
	EditorAppendResumeLabel: `Taapiri taapiri`,
	EditorBgColorLabel: `Tae papamuri`,
	EditorClearAllLabel: `Horoia katoa`,
	EditorClipboardFormatsLabel: `Nga Puka Takahi`,
	EditorConfirmNtfTitle: `Whakaū`,
	EditorDeleteAllButtonText: `Mukua te katoa`,
	EditorDeleteAllTemplatesNtfText: `Kei te hiahia koe ki te muku i nga waahanga katoa o te '{0}'?

Kaore e taea te whakakore!`,
	EditorEditTemplateDetailsLabel: `Whakatika Taipitopito`,
	EditorEditTemplateNameLabel: `Ingoa`,
	EditorFindLabel: `Kite`,
	EditorFontColorLabel: `Tae momotuhi`,
	EditorFormatPaintLabel: `Pepa Hōp`,
	EditorInSelectionLabel: ` I te kowhiringa`,
	EditorInsertImageLabel: `Whakauruhia te Whakaahua`,
	EditorInsertLinkLabel: `Whakauruhia he hononga`,
	EditorInsertVideoLabel: `Whakauruhia he ataata`,
	EditorMatchCaseLabel: ` Taka whakataetae`,
	EditorNewTemplateLabel: `Tātauira Hou`,
	EditorNextTemplateLabel: `Panuku`,
	EditorPasteButtonAppendBeginLabel: `Tāpiri ...`,
	EditorPasteButtonLabel: `Whakapiri`,
	EditorPasteTemplateWatermark: `Whakauruhia te tuhinga whakapiri ...`,
	EditorPrevTemplateLabel: `Tuhinga o mua`,
	EditorRegExLabel: ` Whakapuakitanga auau`,
	EditorReplaceAllLabel: `Whakakapihia te katoa`,
	EditorReplaceLabel: `Whakakapi`,
	EditorTemplateContactHint: `<p>Mā te whakamahi i ngā hoapā e wātea ana (e hiahiatia ana he mono mai tiki) ka whakamahia tēnei āpure mō ngā tauira katoa o tēnei tātauira puta noa i tēnei tuhinga, ka tohutorotia rānei ā muri ake rānei.</p><p> Hei tauira, ki te tīpako wāhitau īmēra ki konei ka whakamahia te āpure īmēra o te hoapā ka tīpakohia e koe mō ngā tauira katoa o tēnei tuhinga.</p>`,
	EditorTemplateContactName: `Whakapā`,
	EditorTemplateDateTimeCustomHint: `yy = tau poto<br/>yyyy = tau roa<br/>M = marama (1-12)<br/>MM = marama (01-12)<br/>MMM = marama abbreviation (Jan, Feb ... Tekau mā rua)<br/>MMMM = marama roa (Ko Hānuere, Hēpuari ... Haki)<br/>d = rā (1 - 31)<br/>dd = rā (01 - 31)<br/>ddd = rā o te wiki i roto i ngā kupu (Monday, Tūrei ... Rātapu)<br/>E = rā poto o te wiki ki ngā kupu (Mon, Tue ... Rā)<br/>D - Rā Ordinal (1, tua2, tua3, 21, 22nd, 23, 31, 4th...)<br/>h = haora i roto i te am/pm (0-12)<br/>hh = haora i roto i te am/pm (00-12)<br/>H = haora i te rā (0-23)<br/>HH = haora i te rā (00-23)<br/>mm = meneti<br/>ss = hēkona<br/>SSS = hēkona mira<br/>he tautohu = AM/PM<br/>p = a.m./p.m. tautohu`,
	EditorTemplateDateTimeCustomLabel: `Ritenga`,
	EditorTemplateDateTimeHint: `Ko te ra o naianei me / te waa ranei ka whakakapihia mo nga tauira o te waa ka oti te whakakii.`,
	EditorTemplateDateTimeName: `Te wa`,
	EditorTemplateDynamicHint: `<p>Ka whakamahia e ngā putanga katoa o tēnei tātauira te kupu kua whakaratoa.</p>`,
	EditorTemplateDynamicName: `Huatau`,
	EditorTemplateEmptyPlaceholder: `{0} he waatea ...`,
	EditorTemplateStaticHint: `<p>Ka whakamahia e ngā putanga katoa o tēnei tātauira te kupu kua whakaratoa.</p>`,
	EditorTemplateStaticName: `Pūmahara`,
	EditorTemplateTeaserText: `Ka hoki mai ano!`,
	EditorWatermark: `Tatari koa ...`,
	EditorWholeWordLabel: ` Kupu katoa`,
	EditorWrapLabel: ` Takai`,

};