var UiStrings = {
	EditorAppendCloseLabel: `Lõpeta lisamine`,
	EditorAppendInlineModeLabel: `Luba blokeerimine`,
	EditorAppendLineModeLabel: `Lubage sisemine`,
	EditorAppendManualModeLabel: `Lülitusjuhend`,
	EditorAppendNonManualModeLabel: `Lülitusjuhend`,
	EditorAppendPauseLabel: `Pausi lisama`,
	EditorAppendPostLabel: `Enne`,
	EditorAppendPreLabel: `Enne`,
	EditorAppendResumeLabel: `Jätkata lisa`,
	EditorBgColorLabel: `Taustavärv`,
	EditorClearAllLabel: `Kustuta kõik`,
	EditorClipboardFormatsLabel: `Lõikelauavormingud`,
	EditorConfirmNtfTitle: `Kinnitama`,
	EditorDeleteAllButtonText: `Kustutada kõik`,
	EditorDeleteAllTemplatesNtfText: `Kas olete kindel, et soovite kustutada kõik '{0}' kasutusalad?

Seda ei saa olematuks teha!`,
	EditorEditTemplateDetailsLabel: `Redigeerimise üksikasjad`,
	EditorEditTemplateNameLabel: `Nimetus`,
	EditorFindLabel: `Leidma`,
	EditorFontColorLabel: `Fondi värv`,
	EditorFormatPaintLabel: `Vormingus värv`,
	EditorInSelectionLabel: ` Valimisel`,
	EditorInsertImageLabel: `Sisestage pilt`,
	EditorInsertLinkLabel: `Sisestage link`,
	EditorInsertVideoLabel: `Sisestage video`,
	EditorMatchCaseLabel: ` Tikutoos`,
	EditorNewTemplateLabel: `Uus mall`,
	EditorNextTemplateLabel: `Järgmine mall`,
	EditorPasteButtonAppendBeginLabel: `Lisa ...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteTemplateWatermark: `Sisestage pasta tekst ...`,
	EditorPrevTemplateLabel: `Eelmine mall`,
	EditorRegExLabel: ` Regulaarne väljendus`,
	EditorReplaceAllLabel: `Asendage kõik`,
	EditorReplaceLabel: `Asendama`,
	EditorTemplateContactHint: `<p> Kättesaadavate kontaktide kasutamine (nõuab Fetcheri pistikprogrammi) Seda välja kasutatakse selle malli kõigi juhtumite jaoks kogu selle dokumendi korral või mis tahes mis tahes sellele viidatakse sellele hilisemas. </p> <p> Nii et näiteks kui valige e -posti aadress Seejärel kasutatakse valitud kontakti e -posti valdkonda kõigi selle dokumendi eksemplaride jaoks. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = lühike aasta <br/> yyyy = pikk aasta <br/> m = kuu (1-12) <br/> mm = kuu (01-12) <br/> mmm = kuu lühend (jaanuar, veebruar .. . Detsember) <br/> mmmm = pikk kuu (jaanuar, veebruar ... detsember) <br/> d = päev (1 - 31) <br/> dd = päev (01 - 31) <br/> ddd = Nädalapäev sõnades (esmaspäev, teisipäev ... pühapäev) <br/> e = lühikese nädala päev sõnades (esmaspäev, teisipäev ... päike) <br/> d - ordinaalne päev (1., 2., 2., 3., 21., 22., 23., 31., 4. ...) <br/> h = tund am/pm (0-12) <br/> hh = tund am/pm (00-12) <br/ > H = tund päevas (0-23) <br/> hh = tund päeval (00-23) <br/> mm = minut <br/> ss = sekund <br/> sss = milliseconds <br/> a = am/pm marker <br/> p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Kohandatud`,
	EditorTemplateDateTimeHint: `Praegune kuupäev ja/või kellaaeg asendatakse nende kleepimisel DateTime'i mallidega.`,
	EditorTemplateDateTimeName: `Kuupäev Kellaaeg`,
	EditorTemplateDynamicHint: `<p> Selle malli kõik esinemised kasutavad esitatud teksti. </p>`,
	EditorTemplateDynamicName: `Dünaamiline`,
	EditorTemplateEmptyPlaceholder: `{0} on tühi ...`,
	EditorTemplateStaticHint: `<p> Selle malli kõik esinemised kasutavad esitatud teksti. </p>`,
	EditorTemplateStaticName: `Staatiline`,
	EditorTemplateTeaserText: `Veel varsti!`,
	EditorWatermark: `Palun oota...`,
	EditorWholeWordLabel: ` Terve sõna`,
	EditorWrapLabel: ` Ümber mähkima`,

};