var UiStrings = {
	EditorAppendCloseLabel: `Қосылуды аяқтаңыз`,
	EditorAppendInlineModeLabel: `Блокты қосу`,
	EditorAppendLineModeLabel: `Кірістірілген қосу`,
	EditorAppendManualModeLabel: `Қолмен ауыстырыңыз`,
	EditorAppendNonManualModeLabel: `Қолмен ауыстырыңыз`,
	EditorAppendPauseLabel: `Кідірту қосымшасы`,
	EditorAppendPostLabel: `Дейін ауыстырыңыз`,
	EditorAppendPreLabel: `Дейін ауыстырыңыз`,
	EditorAppendResumeLabel: `Қосу Қосу`,
	EditorBgColorLabel: `Фон түсі`,
	EditorClearAllLabel: `Барлығын тазалаңыз`,
	EditorClipboardFormatsLabel: `Алмасу буферінің форматтары`,
	EditorColorChooserTitle: `Редактордың түсі`,
	EditorConfirmNtfTitle: `Растау`,
	EditorDeleteAllButtonText: `Барлығын жойыңыз`,
	EditorDeleteAllTemplatesNtfText: `'{0}' барлық пайдаланушыларын жойғыңыз келе ме?

Мұны болдырмауға болмайды!`,
	EditorEditTemplateDetailsLabel: `Мәліметтерді өңдеу`,
	EditorEditTemplateNameLabel: `Есім`,
	EditorFindLabel: `Табу`,
	EditorFontColorLabel: `Қаріп түсі`,
	EditorFormatPaintLabel: `Пішімдеу бояуы`,
	EditorInSelectionLabel: ` Таңдау`,
	EditorInsertImageLabel: `Суретті салыңыз`,
	EditorInsertLinkLabel: `Сілтеме салыңыз`,
	EditorInsertVideoLabel: `Бейнені салыңыз`,
	EditorLinkButtonText: `Жинау`,
	EditorLinkLabel: `Сілтемені енгізіңіз`,
	EditorLinkPlaceholder: `URL мекен-жайын енгізіңіз`,
	EditorMatchCaseLabel: ` Сәйкестік корпусы`,
	EditorNewTemplateLabel: `Жаңа шаблон`,
	EditorNextTemplateLabel: `Келесі шаблон`,
	EditorPasteButtonAppendBeginLabel: `Қосу ...`,
	EditorPasteButtonLabel: `Ұту`,
	EditorPasteButtonLabelMobile: `Еліктеу`,
	EditorPasteTemplateWatermark: `Қою мәтінді енгізіңіз ...`,
	EditorPrevTemplateLabel: `Алдыңғы шаблон`,
	EditorRegExLabel: ` Тұрақты өрнек`,
	EditorReplaceAllLabel: `Барлығын ауыстырыңыз`,
	EditorReplaceLabel: `Орнын басу`,
	EditorTemplateContactHint: `<p>Қол жетімді контактілерді пайдалану (fetcher плагинін қажет етеді) бұл өріс осы құжаттағы үлгінің барлық нұсқалары үшін қолданылады немесе кейінірек сілтеме жасалатын болады.</p><p> Мысалы, осында электрондық пошта мекенжайын таңдасаңыз, таңдалған контактінің электрондық пошта өрісі осы құжаттағы барлық нұсқалар үшін пайдаланылады.</p>`,
	EditorTemplateContactName: `Байланысу`,
	EditorTemplateDateTimeCustomHint: `yy = қысқа жыл<br/>Yyyy = long year<br/>M = ай (1-12)<br/>MM = ай (01-12)<br/>MMM = ай қысқартуы (ян, ақпан ... Dec)<br/>MMMM = ұзақ ай (қаңтар, ақпан ... Желтоқсан)<br/>d = күн (1 – 31)<br/>dd = күн (01 - 31)<br/>dd = аптаның күні сөз түрінде (дүйсенбі, сейсенбі ... Жексенбі)<br/>Е = аптаның қысқа күні сөзбен (Мон, Туэ ... Күн)<br/>Д – Ординал күні (1-ші, 2-ші, 3-ші, 21-ші, 22-ші, 23-ші, 31-ші, 4-ші...)<br/>h = сағат ам/пм (0-12)<br/>hh = сағат ам/пм (00-12)<br/>Н = күндізгі сағат (0-23)<br/>HH = күндізгі сағат (00-23)<br/>mm = минут<br/>ss = екінші<br/>ССС = миллисекунд<br/>a = AM/PM маркері<br/>p = a.m./p.m. маркері`,
	EditorTemplateDateTimeCustomLabel: `Әдет-ғұрып`,
	EditorTemplateDateTimeHint: `Ағымдағы күн және / немесе уақыт олар қойылған кезде DateTime шаблондары үшін ауыстырылады.`,
	EditorTemplateDateTimeName: `Күн уақыты`,
	EditorTemplateDynamicHint: `<p>Бұл үлгінің барлық пайда болуы берілген мәтінді пайдаланады.</p>`,
	EditorTemplateDynamicName: `Динамикалық`,
	EditorTemplateEmptyPlaceholder: `{0} бос ...`,
	EditorTemplateStaticHint: `<p>Бұл үлгінің барлық пайда болуы берілген мәтінді пайдаланады.</p>`,
	EditorTemplateStaticName: `Статистикалық`,
	EditorTemplateTeaserText: `Жақында келеді!`,
	EditorTt1: `Нұқыңыз`,
	EditorTt2: `'<em> {0} </ um>' өңдеу ...`,
	EditorTt3: `Түсті өңдеу ...`,
	EditorTt4: `'<em> {0} </ um>' алып тастаңыз ...`,
	EditorTt5: `Элементті алып тастаңыз`,
	EditorTt6: `Келесіде жүру ...`,
	EditorTt7: `goto '<em> {0} </ em>' ...`,
	EditorWatermark: `Өтінемін күте тұрыңыз...`,
	EditorWholeWordLabel: ` Бүкіл сөз`,
	EditorWrapLabel: ` Орау`,

};