var UiStrings = {
	EditorAppendCloseLabel: `Terminați apariția`,
	EditorAppendInlineModeLabel: `Activați bloc`,
	EditorAppendLineModeLabel: `Activați inline`,
	EditorAppendManualModeLabel: `Manual de comutare`,
	EditorAppendNonManualModeLabel: `Manual de comutare`,
	EditorAppendPauseLabel: `Pauză anexa`,
	EditorAppendPostLabel: `Comutați înainte`,
	EditorAppendPreLabel: `Comutați înainte`,
	EditorAppendResumeLabel: `Reluați anexa`,
	EditorBgColorLabel: `Culoare de fundal`,
	EditorClearAllLabel: `Curata tot`,
	EditorClipboardFormatsLabel: `Formate clipboard`,
	EditorConfirmNtfTitle: `A confirma`,
	EditorDeleteAllButtonText: `Sterge tot`,
	EditorDeleteAllTemplatesNtfText: `Ești sigur că vrei să ștergeți toate utilizările „{0}”?

Acest lucru nu poate fi anulat!`,
	EditorEditTemplateDetailsLabel: `Editează detaliile`,
	EditorEditTemplateNameLabel: `Nume`,
	EditorFindLabel: `Găsi`,
	EditorFontColorLabel: `Culoarea fontului`,
	EditorFormatPaintLabel: `Format vopsea`,
	EditorInSelectionLabel: ` În selecție`,
	EditorInsertImageLabel: `Introduceți imaginea`,
	EditorInsertLinkLabel: `Introduceți legătura`,
	EditorInsertVideoLabel: `Introduceți videoclipuri`,
	EditorMatchCaseLabel: ` Caz de potrivire`,
	EditorNewTemplateLabel: `Șablon nou`,
	EditorNextTemplateLabel: `Următorul șablon`,
	EditorPasteButtonAppendBeginLabel: `Adăuga...`,
	EditorPasteButtonLabel: `Pastă`,
	EditorPasteTemplateWatermark: `Introduceți textul paste ...`,
	EditorPrevTemplateLabel: `Șablon anterior`,
	EditorRegExLabel: ` Expresie uzuala`,
	EditorReplaceAllLabel: `Înlocuiește-le pe toate`,
	EditorReplaceLabel: `A inlocui`,
	EditorTemplateContactHint: `<p>Folosind contactele disponibile (necesită un plugin fetcher), acest câmp va fi utilizat pentru toate instanțele acestui șablon din acest document sau în orice va fi menționat ulterior.</p><p> De exemplu, dacă selectați adresa de e-mail aici, atunci câmpul de e-mail al contactului pe care îl selectați va fi utilizat pentru toate instanțele din acest document.</p>`,
	EditorTemplateContactName: `a lua legatura`,
	EditorTemplateDateTimeCustomHint: `ay = an scurt<br/>aaaa = an lung<br/>M = lună (1-12)<br/>MM = lună (01-12)<br/>MMM = abrevierea lunii (ian, februarie ... Decembrie)<br/>MMMM = lună lungă (ianuarie, februarie ... decembrie)<br/>d = zi (1 - 31)<br/>zz = zi (01 - 31)<br/>ddd = ziua săptămânii în cuvinte (luni, marți ... Duminică)<br/>E = zi scurtă a săptămânii în cuvinte (luni, marți ... Soare)<br/>D - Ziua ordinală (1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = oră în am/pm (0-12)<br/>hh = oră în am/pm (00-12)<br/>H = oră în zi (0-23)<br/>HH = oră din zi (00-23)<br/>mm = minut<br/>ss = al doilea<br/>SSS = milisecunde<br/>a = marcajul AM/PM<br/>p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Personalizat`,
	EditorTemplateDateTimeHint: `Data și/sau ora curente vor fi înlocuite cu șabloanele de date de date atunci când sunt lipite.`,
	EditorTemplateDateTimeName: `Ora datei`,
	EditorTemplateDynamicHint: `<p>Toate aparițiile acestui șablon vor utiliza textul furnizat.</p>`,
	EditorTemplateDynamicName: `Dinamic`,
	EditorTemplateEmptyPlaceholder: `{0} este gol ...`,
	EditorTemplateStaticHint: `<p>Toate aparițiile acestui șablon vor utiliza textul furnizat.</p>`,
	EditorTemplateStaticName: `Static`,
	EditorTemplateTeaserText: `Mai multe în curând!`,
	EditorWatermark: `Va rugam asteptati...`,
	EditorWholeWordLabel: ` Intregul cuvant`,
	EditorWrapLabel: ` Înfășurați -vă`,

};