var UiStrings = {
	EditorAppendCloseLabel: `Zakończyć dołączenie`,
	EditorAppendInlineModeLabel: `Włącz blok`,
	EditorAppendLineModeLabel: `Włącz inline`,
	EditorAppendManualModeLabel: `Podręcznik przełączania`,
	EditorAppendNonManualModeLabel: `Podręcznik przełączania`,
	EditorAppendPauseLabel: `Załącz pauzę`,
	EditorAppendPostLabel: `Przełącz wcześniej`,
	EditorAppendPreLabel: `Przełącz wcześniej`,
	EditorAppendResumeLabel: `Wznowić dodatek`,
	EditorBgColorLabel: `Kolor tła`,
	EditorClearAllLabel: `Wyczyść wszystko`,
	EditorClipboardFormatsLabel: `Formaty schowka`,
	EditorConfirmNtfTitle: `Potwierdzać`,
	EditorDeleteAllButtonText: `Usuń wszystko`,
	EditorDeleteAllTemplatesNtfText: `Czy na pewno chcesz usunąć wszystkie zastosowania „{0}”?

Tego nie da się cofnąć!`,
	EditorEditTemplateDetailsLabel: `Edytuj szczegóły`,
	EditorEditTemplateNameLabel: `Nazwa`,
	EditorFindLabel: `Znajdować`,
	EditorFontColorLabel: `Kolor czcionki`,
	EditorFormatPaintLabel: `Formatowanie farby`,
	EditorInSelectionLabel: ` W selekcji`,
	EditorInsertImageLabel: `Umieść obraz`,
	EditorInsertLinkLabel: `Wstaw link`,
	EditorInsertVideoLabel: `Wstaw wideo`,
	EditorMatchCaseLabel: ` Sprawa meczu`,
	EditorNewTemplateLabel: `Nowy szablon`,
	EditorNextTemplateLabel: `Następny szablon`,
	EditorPasteButtonAppendBeginLabel: `Dodać...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteTemplateWatermark: `Wprowadź tekst wklejania ...`,
	EditorPrevTemplateLabel: `Poprzedni szablon`,
	EditorRegExLabel: ` Wyrażenie regularne`,
	EditorReplaceAllLabel: `Zamień wszystko`,
	EditorReplaceLabel: `Zastępować`,
	EditorTemplateContactHint: `<p>Korzystając z dostępnych kontaktów (wymaga wtyczki fetchera), to pole będzie używane we wszystkich wystąpieniach tego szablonu w tym dokumencie lub w dowolnych, do których będzie się odwoływać później.</p><p> Na przykład, jeśli w tym miejscu wybierzesz adres e-mail, pole adresu e-mail wybranego kontaktu będzie używane we wszystkich wystąpieniach w tym dokumencie.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = krótki rok<br/>rrrr = długi rok<br/>M = miesiąc (1-12)<br/>MM = miesiąc (01-12)<br/>MMM = skrót miesiąca (Jan, Feb ... Grudzień)<br/>MMMM = długi miesiąc (styczeń, luty ... grudzień)<br/>d = dzień (1 - 31)<br/>dd = dzień (01 - 31)<br/>ddd = słownie dzień tygodnia (poniedziałek, wtorek ... Niedziela)<br/>E = słownie krótki dzień tygodnia (pon., wt. ... Słońce)<br/>D - dzień porządkowy (1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = godzina w godzinach porannych/po południu (0-12)<br/>hh = godzina w godzinach porannych/wieczornych (00-12)<br/>H = godzina w dniu (0-23)<br/>HH = godzina w dniu (00-23)<br/>mm = minuta<br/>ss = sekunda<br/>SSS = milisekundy<br/>a = znacznik AM/PM<br/>p = znacznik a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Zwyczaj`,
	EditorTemplateDateTimeHint: `Obecna data i/lub godzina zostaną zastąpione szablonami DATETIME po wklejeniu.`,
	EditorTemplateDateTimeName: `Data godzina`,
	EditorTemplateDynamicHint: `<p>Wszystkie wystąpienia tego szablonu będą używać dostarczonego tekstu.</p>`,
	EditorTemplateDynamicName: `Dynamiczny`,
	EditorTemplateEmptyPlaceholder: `{0} jest pusty ...`,
	EditorTemplateStaticHint: `<p>Wszystkie wystąpienia tego szablonu będą używać dostarczonego tekstu.</p>`,
	EditorTemplateStaticName: `Statyczny`,
	EditorTemplateTeaserText: `Więcej wkrótce!`,
	EditorWatermark: `Proszę czekać...`,
	EditorWholeWordLabel: ` Cały świat`,
	EditorWrapLabel: ` Owinąć`,

};