var UiStrings = {
	EditorAppendCloseLabel: `Завършете добавянето`,
	EditorAppendInlineModeLabel: `Активиране на блок`,
	EditorAppendLineModeLabel: `Активирайте вграденото`,
	EditorAppendManualModeLabel: `Ръководство за превключване`,
	EditorAppendNonManualModeLabel: `Ръководство за превключване`,
	EditorAppendPauseLabel: `Пауза Приложение`,
	EditorAppendPostLabel: `Превключвайте преди`,
	EditorAppendPreLabel: `Превключвайте преди`,
	EditorAppendResumeLabel: `Възобновете добавката`,
	EditorBgColorLabel: `Цвят на фона`,
	EditorClearAllLabel: `Изчисти всичко`,
	EditorClipboardFormatsLabel: `Формати на клипборд`,
	EditorConfirmNtfTitle: `Потвърдете`,
	EditorDeleteAllButtonText: `Изтриване на всички`,
	EditorDeleteAllTemplatesNtfText: `Сигурни ли сте, че искате да изтриете всички употреби на '{0}'?

Това не може да бъде отменено!`,
	EditorEditTemplateDetailsLabel: `Редактирайте подробности`,
	EditorEditTemplateNameLabel: `Име`,
	EditorFindLabel: `намирам`,
	EditorFontColorLabel: `Цвят на шрифта`,
	EditorFormatPaintLabel: `Форматиране на боя`,
	EditorInSelectionLabel: ` В подбор`,
	EditorInsertImageLabel: `Поставете изображение`,
	EditorInsertLinkLabel: `Вмъкване на връзка`,
	EditorInsertVideoLabel: `Вмъкнете видео`,
	EditorMatchCaseLabel: ` Случай на съвпадение`,
	EditorNewTemplateLabel: `Нов шаблон`,
	EditorNextTemplateLabel: `Следващ шаблон`,
	EditorPasteButtonAppendBeginLabel: `Добавяне ...`,
	EditorPasteButtonLabel: `Поставете`,
	EditorPasteTemplateWatermark: `Въведете текст на паста ...`,
	EditorPrevTemplateLabel: `Предишен шаблон`,
	EditorRegExLabel: ` Редовно изразяване`,
	EditorReplaceAllLabel: `Заменете всички`,
	EditorReplaceLabel: `Заменете`,
	EditorTemplateContactHint: `<p> Използване на налични контакти (изисква приставка за извличане) Това поле ще бъде използвано за всички случаи на този шаблон в този документ или във всеки то ще бъде посочено по -късно. </p> <p> Така например, ако изберете имейл адрес Тогава след това полето за имейл на избрания контакт ще бъде използвано за всички случаи в този документ. </p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = кратка година <br/> yyyy = дълга година <br/> m = месец (1-12) <br/> mm = месец (01-12) <br/> mmm = месец съкращение (ян, февруари .. . Dec) <br/> mmmm = дълъг месец (януари, февруари ... декември) <br/> d = ден (1 - 31) <br/> dd = ден (01 - 31) <br/> ddd = Ден на седмицата с думи (понеделник, вторник ... неделя) <br/> e = кратък ден от седмицата с думи (пн, вторник ... слънце) <br/> d - порядъчен ден (1 -ви, 2 -ри, 3-ти, 21-ви, 22-ри, 23-и, 31-ви, 4-ти ...) <br/> h = час в AM/PM (0-12) <br/> HH = час в AM/PM (00-12) <BR/ > H = час в ден (0-23) <br/> hh = час в ден (00-23) <br/> mm = минута <br/> ss = второ <br/> sss = milliseconds <br/> a = am/pm маркер <br/> p = a.m./p.m. Маркер`,
	EditorTemplateDateTimeCustomLabel: `Персонализиран`,
	EditorTemplateDateTimeHint: `Текущата дата и/или часа ще бъдат заменени с шаблони за дата, когато са поставени.`,
	EditorTemplateDateTimeName: `Време за среща`,
	EditorTemplateDynamicHint: `<p> Всички появата на този шаблон ще използват предоставения текст. </p>`,
	EditorTemplateDynamicName: `Динамичен`,
	EditorTemplateEmptyPlaceholder: `{0} е празен ...`,
	EditorTemplateStaticHint: `<p> Всички появата на този шаблон ще използват предоставения текст. </p>`,
	EditorTemplateStaticName: `Статично`,
	EditorTemplateTeaserText: `Още скоро идват скоро!`,
	EditorWatermark: `Моля Изчакай...`,
	EditorWholeWordLabel: ` Цяла дума`,
	EditorWrapLabel: ` Обгърне`,

};