var UiStrings = {
	EditorAppendCloseLabel: `ئادرېسنى تاماملاڭ`,
	EditorAppendInlineModeLabel: `چەكلەش`,
	EditorAppendLineModeLabel: `ئىقتىدارنى قوزغىتىڭ`,
	EditorAppendManualModeLabel: `قوللانما`,
	EditorAppendNonManualModeLabel: `قوللانما`,
	EditorAppendPauseLabel: `توختىتىش`,
	EditorAppendPostLabel: `To toggle`,
	EditorAppendPreLabel: `To toggle`,
	EditorAppendResumeLabel: `چېكىنىش`,
	EditorBgColorLabel: `تەگلىك رەڭگى`,
	EditorClearAllLabel: `ھەممىنى تازىلاش`,
	EditorClipboardFormatsLabel: `چاپلاش تاختىسى`,
	EditorConfirmNtfTitle: `جەزملەشتۈرۈڭ`,
	EditorDeleteAllButtonText: `ھەممىنى ئۆچۈرۈڭ`,
	EditorDeleteAllTemplatesNtfText: `«{0}» نىڭ بارلىق ئىشلىتىشلىرىنى ئۆچۈرمەكچىمۇ?

بۇنى ئەمەلدىن قالدۇرغىلى بولمايدۇ!`,
	EditorEditTemplateDetailsLabel: `تەپسىلاتلارنى تەھرىرلەڭ`,
	EditorEditTemplateNameLabel: `Name`,
	EditorFindLabel: `تېپىش`,
	EditorFontColorLabel: `خەت نۇسخىسىنى`,
	EditorFormatPaintLabel: `فورماتى`,
	EditorInSelectionLabel: ` تاللاشتا`,
	EditorInsertImageLabel: `رەسىم قىستۇرۇش`,
	EditorInsertLinkLabel: `ئۇلىنىش قىستۇرۇش`,
	EditorInsertVideoLabel: `سىن قىستۇرۇش`,
	EditorMatchCaseLabel: ` ماسلاشتۇرۇش دېلوسى`,
	EditorNewTemplateLabel: `يېڭى قېلىپ`,
	EditorNextTemplateLabel: `كېيىنكى قېلىپ`,
	EditorPasteButtonAppendBeginLabel: `قوشۇلدى ...`,
	EditorPasteButtonLabel: `چاپلاڭ`,
	EditorPasteTemplateWatermark: `چاپلاش تېكىستىنى كىرگۈزۈڭ ...`,
	EditorPrevTemplateLabel: `ئىلگىرىكى قېلىپ`,
	EditorRegExLabel: ` دائىملىق ئىپادىلەش`,
	EditorReplaceAllLabel: `بارلىق ئالماشتۇرۇڭ`,
	EditorReplaceLabel: `ئالماشتۇرۇش`,
	EditorTemplateContactHint: `<p>ئىشلىتىشكە بولىدىغان ئالاقىداش (fetcher قىستۇرمىسىنى تەلەپ قىلىدۇ) بۇ ساھە بۇ ھۆججەتتىكى ياكى ھەرقانداق بىر ھۆججەتتىكى بارلىق مىساللار ئۈچۈن كېيىن پايدىلىنىشقا بولىدۇ.</p><p> شۇڭا مەسىلەن، بۇ يەردە ئېلخەت ئادرېسىنى تاللىسىڭىز، ئۇنداقتا سىز تاللىغان ئالاقىداشنىڭ ئېلخەت ساھەسى بۇ ھۆججەتتىكى بارلىق مىساللار ئۈچۈن ئىشلىتىلىدۇ.</p>`,
	EditorTemplateContactName: `ئالاقىلىشىڭ`,
	EditorTemplateDateTimeCustomHint: `yy = قىسقا يىل<br/>yyyy = ئۇزۇن يىل<br/>م = ئاي (1-12)<br/>MM = ئاي (01- 12)<br/>MMM = ئاينىڭ قىسقارتىلمىسى (Jan, Feb ... دىۋى)<br/>MMMM = ئۇزۇن ئاي (يانۋار، فېۋرال ... 12- ئاي)<br/>d = كۈنى (1 - 31 )<br/>dd = كۈنى (01 - 31)<br/>ddd = خەتلىك ھەپتىنىڭ كۈنى (دۈشەنبە، سەيشەنبە ... يەكشەنبە)<br/>E = خەتلىك ھەپتىنىڭ قىسقىغىنە كۈنى (مون، تۇي ... قۇياش)<br/>D - ئوردىدا كۈنى (1-، 2-، 3-، 21-، 22-، 23-، 31-، 4-...)<br/>h = سائەت am/pm (0-12)<br/>hh = سائەتلىك am/pm (00-12)<br/>H = كۈندۈزدىكى سائەت (0-23)<br/>HH = بىر كۈندە سائەت (00-23)<br/>mm = مىنۇت<br/>ss = ئىككىنچى<br/>SSS = مىللىسېكونت<br/>a = AM/PM بەلگىسى<br/>p = a.m./p.m. بەلگىسى`,
	EditorTemplateDateTimeCustomLabel: `ئادەت`,
	EditorTemplateDateTimeHint: `نۆۋەتتىكى چېسلا ۋە ياكى ۋاقىت چاپلانغان ۋاقىتتا ۋاقىت تېمىسىدا ۋاقىت چىقىرىۋېتىلىدۇ.`,
	EditorTemplateDateTimeName: `چېسلا ۋاقتى`,
	EditorTemplateDynamicHint: `<p>بۇ قېلىپنىڭ بارلىق يۈز بېرىشى بىلەن تەمىنلەنگەن تېكىست ئىشلىتىلىدۇ.</p>`,
	EditorTemplateDynamicName: `ھەرىكەتچان`,
	EditorTemplateEmptyPlaceholder: `{0}} قۇرۇق ...`,
	EditorTemplateStaticHint: `<p>بۇ قېلىپنىڭ بارلىق يۈز بېرىشى بىلەن تەمىنلەنگەن تېكىست ئىشلىتىلىدۇ.</p>`,
	EditorTemplateStaticName: `تۇراقلىق`,
	EditorTemplateTeaserText: `تېخىمۇ كۆپ كېلىدۇ!`,
	EditorWatermark: `ساقلاپ تۇرۇڭ ...`,
	EditorWholeWordLabel: ` پۈتۈن سۆز`,
	EditorWrapLabel: ` ئوراش`,

};