var UiStrings = {
	EditorAppendCloseLabel: `थपिरहेको छ`,
	EditorAppendInlineModeLabel: `ब्लक सक्षम गर्नुहोस्`,
	EditorAppendLineModeLabel: `इनलाइन सक्षम गर्नुहोस्`,
	EditorAppendManualModeLabel: `टगल म्यानुअल`,
	EditorAppendNonManualModeLabel: `टगल म्यानुअल`,
	EditorAppendPauseLabel: `रोक्नुहोस्`,
	EditorAppendPostLabel: `अगाडि टगल गर्नुहोस्`,
	EditorAppendPreLabel: `अगाडि टगल गर्नुहोस्`,
	EditorAppendResumeLabel: `पुन: संयोजन गर्नुहोस्`,
	EditorBgColorLabel: `पृष्ठभूमि र color`,
	EditorClearAllLabel: `सबै खाली गर्नुहोस्`,
	EditorClipboardFormatsLabel: `क्लिपबोर्ड ढाँचाहरू`,
	EditorConfirmNtfTitle: `पक्का गर्नु`,
	EditorDeleteAllButtonText: `सबैलाई मेट्नुहोस्`,
	EditorDeleteAllTemplatesNtfText: `के तपाईं '{0}' को सबै सामानहरू मेटाउन निश्चित हुनुहुन्छ?

यो उल्ट्याउन सकिदैन!`,
	EditorEditTemplateDetailsLabel: `विवरण सम्पादन गर्नुहोस्`,
	EditorEditTemplateNameLabel: `नाम`,
	EditorFindLabel: `पाउनु`,
	EditorFontColorLabel: `फन्ट रंग`,
	EditorFormatPaintLabel: `ढाँचा पेन्ट`,
	EditorInSelectionLabel: ` छनौटमा`,
	EditorInsertImageLabel: `छवि घुसाउनुहोस्`,
	EditorInsertLinkLabel: `लिंक घुसाउनुहोस्`,
	EditorInsertVideoLabel: `भिडियो घुसाउनु`,
	EditorMatchCaseLabel: ` म्याच केस`,
	EditorNewTemplateLabel: `नयाँ टेम्प्लेट`,
	EditorNextTemplateLabel: `अर्को टेम्पलेट`,
	EditorPasteButtonAppendBeginLabel: `जोडिएको ...`,
	EditorPasteButtonLabel: `टाँसिनु`,
	EditorPasteTemplateWatermark: `टाँस्नुहोस् पाठ प्रविष्ट गर्नुहोस् ...`,
	EditorPrevTemplateLabel: `अघिल्लो टेम्पलेट`,
	EditorRegExLabel: ` नियमित अभिव्यक्ति`,
	EditorReplaceAllLabel: `सबैलाई बदल्नुहोस्`,
	EditorReplaceLabel: `ठाउमा राख्नु`,
	EditorTemplateContactHint: `<p>उपलब्ध सम्पर्कहरू प्रयोग गरेर (फेचर प्लगइन आवश्यक पर्दछ) यो फिल्ड यो कागजातमा यो टेम्प्लेटको सबै उदाहरणका लागि प्रयोग गरिनेछ वा कुनै पनि मा यो पछि सन्दर्भित गरिनेछ।</p><p> त्यसैले उदाहरणका लागि यदि यहाँ इमेल ठेगाना चयन गर्नुहोस् भने तपाईले चयन गर्नुभएको सम्पर्कको इमेल फिल्ड यस कागजातमा सबै उदाहरणहरूको लागि प्रयोग गरिनेछ।</p>`,
	EditorTemplateContactName: `सम्पर्क`,
	EditorTemplateDateTimeCustomHint: `वाई = छोटा वर्ष<br/>यय्य = लामो वर्ष<br/>म = महिना (१-१२)<br/>एमएम = महिना (01-12)<br/>एमएमएम = महिनाको संक्षिप्त नाम (जनवरी, फेब्रुअरी ... डिसेम्बर)<br/>एमएमएमएम = लामो महिना (जनवरी, फेब्रुअरी ... डिसेम्बर)<br/>घ = दिन (१ - ३१)<br/>डीडी = दिन (01 - 31)<br/>डीडीडी = शब्दहरूमा हप्ताको दिन (सोमबार, मंगलवार ... आइतबार)<br/>ई = शब्दहरूमा हप्ताको छोटो दिन (सोम, मंगल ... सूर्य)<br/>डी - क्रमिक दिन (1, 2, 3, 21, 22, 23, 31, 4 ...)<br/>एच = घण्टा मा एएम / पीएम (0-12)<br/>एचएच = घण्टा मा एएम / पीएम (00-12)<br/>एच = दिनमा घण्टा (0-23)<br/>एचएच = दिनमा घण्टा (00-23)<br/>मिमी = मिनेट<br/>एसएस = सेकेन्ड<br/>एसएसएस = मिलिसेकेन्ड<br/>ए = एएम / पीएम मार्कर<br/>पी = ए.एम./पी.एम. मार्कर`,
	EditorTemplateDateTimeCustomLabel: `चलन`,
	EditorTemplateDateTimeHint: `हालको मिति र / वा समय मिति टेक्नेटि with को लागि प्रतिस्थापित गरिनेछ जब तिनीहरू टाँसिन्छन्।`,
	EditorTemplateDateTimeName: `मिति समय`,
	EditorTemplateDynamicHint: `<p>यो टेम्प्लेटका सबै घटनाहरूले प्रदान गरिएको पाठ प्रयोग गर्नेछ ।</p>`,
	EditorTemplateDynamicName: `गतिशील`,
	EditorTemplateEmptyPlaceholder: `{0} खाली छ ...`,
	EditorTemplateStaticHint: `<p>यो टेम्प्लेटका सबै घटनाहरूले प्रदान गरिएको पाठ प्रयोग गर्नेछ ।</p>`,
	EditorTemplateStaticName: `निर्मूल`,
	EditorTemplateTeaserText: `अधिक आउँदै!`,
	EditorWatermark: `कृपया पर्खनुहोस्...`,
	EditorWholeWordLabel: ` पुरै शब्द`,
	EditorWrapLabel: ` वरिपरि लपेट`,

};