var UiStrings = {
	EditorAppendCloseLabel: `Ljúktu viðauka`,
	EditorAppendInlineModeLabel: `Virkja blokk`,
	EditorAppendLineModeLabel: `Virkja inline`,
	EditorAppendManualModeLabel: `Skipta handbók`,
	EditorAppendNonManualModeLabel: `Skipta handbók`,
	EditorAppendPauseLabel: `Hlé bæta við`,
	EditorAppendPostLabel: `Skiptu áður`,
	EditorAppendPreLabel: `Skiptu áður`,
	EditorAppendResumeLabel: `Halda áfram bætt við`,
	EditorBgColorLabel: `Bakgrunns litur`,
	EditorClearAllLabel: `Hreinsa allt`,
	EditorClipboardFormatsLabel: `Klemmuspjald`,
	EditorConfirmNtfTitle: `Staðfesta`,
	EditorDeleteAllButtonText: `Eyða öllu`,
	EditorDeleteAllTemplatesNtfText: `Ertu viss um að þú viljir eyða öllum notkun '{0}'?

Þetta er ekki hægt að afturkalla!`,
	EditorEditTemplateDetailsLabel: `Breyta smáatriðum`,
	EditorEditTemplateNameLabel: `Nafn`,
	EditorFindLabel: `Finndu`,
	EditorFontColorLabel: `Leturlitur`,
	EditorFormatPaintLabel: `Sniðmálning`,
	EditorInSelectionLabel: ` Í vali`,
	EditorInsertImageLabel: `Settu inn mynd`,
	EditorInsertLinkLabel: `Settu inn hlekk`,
	EditorInsertVideoLabel: `Settu inn myndband`,
	EditorMatchCaseLabel: ` Samsvörunarmál`,
	EditorNewTemplateLabel: `Nýtt sniðmát`,
	EditorNextTemplateLabel: `Næsta sniðmát`,
	EditorPasteButtonAppendBeginLabel: `Bæta við ...`,
	EditorPasteButtonLabel: `Límu`,
	EditorPasteTemplateWatermark: `Sláðu inn líma texta ...`,
	EditorPrevTemplateLabel: `Fyrra sniðmát`,
	EditorRegExLabel: ` Regluleg tjáning`,
	EditorReplaceAllLabel: `Skiptu um allt`,
	EditorReplaceLabel: `Skiptu um`,
	EditorTemplateContactHint: `<p> Notkun tiltækra tengiliða (krefst fetcher viðbótar) Þessi reitur verður notaður í öllum tilvikum þessa sniðmáts í þessu skjali eða í öllu því verður vísað til síðar. </p> <p> Svo til dæmis ef valið er netfang Hér verður tölvupóstsvið tengiliðsins sem þú velur notaður í öllum tilvikum í þessu skjali. </p>`,
	EditorTemplateContactName: `Hafðu samband`,
	EditorTemplateDateTimeCustomHint: `yy = stutt ár <br/> yyyy = langt árið <br/> m = mánuður (1-12) <br/> mm = mánuður (01-12) <br/> mmm = mánuður skammstöfun (Jan, Feb .. . Dec) <br/> mmmm = langur mánuður (janúar, febrúar ... desember) <br/> d = dagur (1 - 31) <br/> dd = dagur (01 - 31) <br/> ddd = Dagur vikunnar í orðum (mánudagur, þriðjudagur ... sunnudagur) <br/> e = stuttur dagur vikunnar í orðum (mán, Þri ... sól) <br/> d - Venjulegur dagur (1., 2., 3., 21., 22., 23., 31., 4. ...) <br/> h = klukkustund í Am/PM (0-12) <br/> HH = klukkustund í Am/PM (00-12) <Br/ > H = klukkustund í dag (0-23) <br/> HH = klukkustund í dag (00-23) <br/> mm = mínúta <br/> ss = önnur <br/> sss = millisekúndur <br/> A = Am/PM merki <br/> p = a.m./p.m. Merki`,
	EditorTemplateDateTimeCustomLabel: `Sérsniðin`,
	EditorTemplateDateTimeHint: `Núverandi dagsetning og/eða tíminn verður skipt út fyrir sniðmát datetime þegar þau eru límd.`,
	EditorTemplateDateTimeName: `Dagsetningartími`,
	EditorTemplateDynamicHint: `<p> Öll atburðir þessa sniðmáts munu nota textann sem fylgir. </p>`,
	EditorTemplateDynamicName: `Kraftmikið`,
	EditorTemplateEmptyPlaceholder: `{0} er tómt ...`,
	EditorTemplateStaticHint: `<p> Öll atburðir þessa sniðmáts munu nota textann sem fylgir. </p>`,
	EditorTemplateStaticName: `Truflanir`,
	EditorTemplateTeaserText: `Meira að koma fljótlega!`,
	EditorWatermark: `Vinsamlegast bíðið...`,
	EditorWholeWordLabel: ` Allt orð`,
	EditorWrapLabel: ` Vefja utan um`,

};