var UiStrings = {
	EditorAppendCloseLabel: `Dokončit připojení`,
	EditorAppendInlineModeLabel: `Povolit blok`,
	EditorAppendLineModeLabel: `Povolit inline`,
	EditorAppendManualModeLabel: `Přepínač`,
	EditorAppendNonManualModeLabel: `Přepínač`,
	EditorAppendPauseLabel: `Pozastavte připojení`,
	EditorAppendPostLabel: `Přepínat dříve`,
	EditorAppendPreLabel: `Přepínat dříve`,
	EditorAppendResumeLabel: `Pokračovat v připojení`,
	EditorBgColorLabel: `Barva pozadí`,
	EditorClearAllLabel: `Vymazat vše`,
	EditorClipboardFormatsLabel: `Formáty schránky`,
	EditorConfirmNtfTitle: `Potvrdit`,
	EditorDeleteAllButtonText: `Smazat všechny`,
	EditorDeleteAllTemplatesNtfText: `Jste si jisti, že chcete odstranit všechna využití '{0}'?

To nelze vrátit zpět!`,
	EditorEditTemplateDetailsLabel: `Upravit detaily`,
	EditorEditTemplateNameLabel: `název`,
	EditorFindLabel: `Nalézt`,
	EditorFontColorLabel: `Barva fontu`,
	EditorFormatPaintLabel: `Formát barvy`,
	EditorInSelectionLabel: ` Při výběru`,
	EditorInsertImageLabel: `Vložte obrázek`,
	EditorInsertLinkLabel: `Vložte odkaz`,
	EditorInsertVideoLabel: `Vložte video`,
	EditorMatchCaseLabel: ` Shodný případ`,
	EditorNewTemplateLabel: `Nová šablona`,
	EditorNextTemplateLabel: `Další šablona`,
	EditorPasteButtonAppendBeginLabel: `Připojit...`,
	EditorPasteButtonLabel: `Vložit`,
	EditorPasteTemplateWatermark: `Zadejte text vložení ...`,
	EditorPrevTemplateLabel: `Předchozí šablona`,
	EditorRegExLabel: ` Regulární výraz`,
	EditorReplaceAllLabel: `Vyměnit vše`,
	EditorReplaceLabel: `Nahradit`,
	EditorTemplateContactHint: `<p> Pomocí dostupných kontaktů (vyžaduje plugin Fetcher) Toto pole bude použito pro všechny případy této šablony napříč tímto dokumentem nebo v jakémkoli, na který bude odkazováno později. </p> <p> Například pokud vyberte e -mailovou adresu Zde pak bude pole e -mailu, který vyberte, použito pro všechny instance v tomto dokumentu. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = krátký rok <br/> yyyy = dlouhý rok <br/> m = měsíc (1-12) <br/> mm = měsíc (01-12) <br/> mmm = zkratka měsíce (leden, únor .. . Dec) <br/> mmmm = dlouhý měsíc (leden, únor ... prosinec) <br/> d = den (1 - 31) <br/> dd = den (01 - 31) <br/> ddd = Den v týdnu ve slovech (pondělí, úterý ... neděle) <br/> e = krátký den v týdnu ve slovech (mon, út ... slunce) <br/> d - ordinální den (1., 2., 2. 3., 21., 22., 23., 31., 4. ...) <br/> h = hodina v am/pm (0-12) <br/> hh = hodina v AM/PM (00-12) <Br/ > H = hodina v den (0-23) <br/> hh = hodina v den (00-23) <br/> mm = minuta <br/> ss = second <br/> sss = milisekundy <br/> A = AM/PM Marker <br/> p = a.m./p.m. popisovač`,
	EditorTemplateDateTimeCustomLabel: `Zvyk`,
	EditorTemplateDateTimeHint: `Aktuální datum a/nebo čas bude nahrazen šablonami DateTime, když jsou vloženy.`,
	EditorTemplateDateTimeName: `Čas schůzky`,
	EditorTemplateDynamicHint: `<p> Všechny platnosti této šablony použijí poskytnutý text. </p>`,
	EditorTemplateDynamicName: `Dynamický`,
	EditorTemplateEmptyPlaceholder: `{0} je prázdný ...`,
	EditorTemplateStaticHint: `<p> Všechny platnosti této šablony použijí poskytnutý text. </p>`,
	EditorTemplateStaticName: `Statický`,
	EditorTemplateTeaserText: `Více již brzy!`,
	EditorWatermark: `Prosím, čekejte...`,
	EditorWholeWordLabel: ` Celý svět`,
	EditorWrapLabel: ` Obalit`,

};