var UiStrings = {
	EditorAppendCloseLabel: `Tispiċċa l-apping`,
	EditorAppendInlineModeLabel: `Enable Block`,
	EditorAppendLineModeLabel: `Jippermettu inline`,
	EditorAppendManualModeLabel: `Toggle Manwal`,
	EditorAppendNonManualModeLabel: `Toggle Manwal`,
	EditorAppendPauseLabel: `Nieqaf append`,
	EditorAppendPostLabel: `Toggle qabel`,
	EditorAppendPreLabel: `Toggle qabel`,
	EditorAppendResumeLabel: `Ibda mill-ġdid append`,
	EditorBgColorLabel: `Kulur fl-isfond`,
	EditorClearAllLabel: `Żbarazza kollox`,
	EditorClipboardFormatsLabel: `Formati tal-clipboard`,
	EditorConfirmNtfTitle: `Ikkonferma`,
	EditorDeleteAllButtonText: `Ħassar kollox`,
	EditorDeleteAllTemplatesNtfText: `Int żgur li trid tħassar l-użi kollha ta '' {0} '?

Dan ma jistax jitneħħa!`,
	EditorEditTemplateDetailsLabel: `Editja d-dettalji`,
	EditorEditTemplateNameLabel: `Isem`,
	EditorFindLabel: `Sib`,
	EditorFontColorLabel: `Kulur tat-tipa`,
	EditorFormatPaintLabel: `Format taż-żebgħa`,
	EditorInSelectionLabel: ` Fl-għażla`,
	EditorInsertImageLabel: `Daħħal l-immaġni`,
	EditorInsertLinkLabel: `Daħħal link`,
	EditorInsertVideoLabel: `Daħħal vidjow`,
	EditorMatchCaseLabel: ` Każ tal-partita`,
	EditorNewTemplateLabel: `Mudell ġdid`,
	EditorNextTemplateLabel: `Mudell li jmiss`,
	EditorPasteButtonAppendBeginLabel: `Append ...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteTemplateWatermark: `Daħħal it-test tal-pejst ...`,
	EditorPrevTemplateLabel: `Mudell preċedenti`,
	EditorRegExLabel: ` Espressjoni regolari`,
	EditorReplaceAllLabel: `Ibdel kollox`,
	EditorReplaceLabel: `Ibdel`,
	EditorTemplateContactHint: `<p> Uża l-kuntatti disponibbli (teħtieġ plugin Fetcher) Dan il-qasam se jintuża għall-każijiet kollha ta 'dan il-mudell f'dan id-dokument jew f'kull wieħed minnhom se jkun referenzjat aktar tard. </p> <p> Allura pereżempju jekk tagħżel l-indirizz elettroniku Hawnhekk allura l-kamp tal-email tal-kuntatt li tagħżel se jintuża għall-każijiet kollha f'dan id-dokument. </p>`,
	EditorTemplateContactName: `Kuntatt`,
	EditorTemplateDateTimeCustomHint: `yy = sena qasira <br/> yyyy = sena twila <br/> m = xahar (1-12) <br/> mm = xahar (01-12) <br/> mmm = Arevrevediment ta 'xahar (Jan, Feb .. . Dec) <br/> mmmm = xahar twil (Jannar, Frar ... Diċembru) <br/> d = jum (1 - 31) <br/> dd = jum (01 - 31) <br/> ddd = Jum tal-Ġimgħa fi kliem (it-Tnejn, it-Tlieta ... il-Ħadd) <br/> E = Jum Qasir tal-Ġimgħa bil-Kliem (Tnejn, Tue ... Sun) <br/> D - Jum Ordinal (1, it-2, 3, 21, 22, 23, 31, 4 ...) <br/> H = siegħa f'Am / PM (0-12) <br/> hh = siegħa f'Am / PM (00-12) <br / > H = siegħa fil-jum (0-23) <br/> hh = siegħa fil-jum (00-23) <br/> mm = minuta <br/> ss = it-tieni <br/> sss = millisekondi <br/> A = AM / PM markatur <br/> p = a.m./p.m. markatur`,
	EditorTemplateDateTimeCustomLabel: `Drawwa`,
	EditorTemplateDateTimeHint: `Id-data kurrenti u / jew il-ħin jiġu sostitwiti għal mudelli ta 'datetime meta jiġu mwaħħlin.`,
	EditorTemplateDateTimeName: `Ħin tad-data`,
	EditorTemplateDynamicHint: `<p> L-okkorrenzi kollha ta 'dan il-mudell jużaw it-test provdut. </p>`,
	EditorTemplateDynamicName: `Dinamiku`,
	EditorTemplateEmptyPlaceholder: `{0} huwa vojt ...`,
	EditorTemplateStaticHint: `<p> L-okkorrenzi kollha ta 'dan il-mudell jużaw it-test provdut. </p>`,
	EditorTemplateStaticName: `Statiku`,
	EditorTemplateTeaserText: `Aktar ġej dalwaqt!`,
	EditorWatermark: `Stenna...`,
	EditorWholeWordLabel: ` Kelma sħiħa`,
	EditorWrapLabel: ` Kebbeb`,

};