var UiStrings = {
	EditorAppendCloseLabel: `Тәмамлау`,
	EditorAppendInlineModeLabel: `Блокны кушу`,
	EditorAppendLineModeLabel: `Йомшаклау`,
	EditorAppendManualModeLabel: `Кулланма`,
	EditorAppendNonManualModeLabel: `Кулланма`,
	EditorAppendPauseLabel: `Пауза кушымтасы`,
	EditorAppendPostLabel: `Моңа кадәр`,
	EditorAppendPreLabel: `Моңа кадәр`,
	EditorAppendResumeLabel: `Резюме кушымтасы`,
	EditorBgColorLabel: `Фон төсе`,
	EditorClearAllLabel: `Барысын да чистарту`,
	EditorClipboardFormatsLabel: `Такталар форматлары`,
	EditorConfirmNtfTitle: `Раслагыз`,
	EditorDeleteAllButtonText: `Барысын да бетерү`,
	EditorDeleteAllTemplatesNtfText: `"{0}" барлык кулланмаларны бетерергә телисезме?

Моны кире кайтарып булмый!`,
	EditorEditTemplateDetailsLabel: `Детальләрне үзгәртү`,
	EditorEditTemplateNameLabel: `Исем`,
	EditorFindLabel: `Табу`,
	EditorFontColorLabel: `Шрифт төсе`,
	EditorFormatPaintLabel: `Буяу Буяу`,
	EditorInSelectionLabel: ` Сайлауда`,
	EditorInsertImageLabel: `Рәсем кертү`,
	EditorInsertLinkLabel: `Ссылка салу`,
	EditorInsertVideoLabel: `Видео кертегез`,
	EditorMatchCaseLabel: ` Матч эше`,
	EditorNewTemplateLabel: `Яңа шаблон`,
	EditorNextTemplateLabel: `Киләсе шаблон`,
	EditorPasteButtonAppendBeginLabel: `Кушымта ...`,
	EditorPasteButtonLabel: `Паста`,
	EditorPasteTemplateWatermark: `Паста текстын кертегез ...`,
	EditorPrevTemplateLabel: `Элеккеге шаблон`,
	EditorRegExLabel: ` Регуляр белдерү`,
	EditorReplaceAllLabel: `Барысын да алыштырыгыз`,
	EditorReplaceLabel: `Алыштырыгыз`,
	EditorTemplateContactHint: `<p> Кулланылган контактны куллану) Бу кыр бу шаблонның бу документ аша барлык очракларында кулланылачак, яисә ул соңрак алынган. </ p> p> Шулай итеп, электрон почта адресын сайлагыз Монда, сез сайлаган контактның электрон почта кыры бу документта барлык очракларда кулланылачак. </ p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = кыска ел = озын ел = ай (1-12) <br/> mm = ай (01-12) <br/> mmm = айлык кыскарту (Ян, Фев .. . Декабрь) <br/> мммм = озын ай (февраль, февраль) <br/> d = көн (1 - 31) <br/> dd = Көн (01 - 31) <br/> ddd = Атна көне (дүшәмбе, сишәмбе ... Якшәмбе) <br/> e = Минем атнаның кыска көне 3нче, 22 нче, 4 нче, 4 нче ...) <br/> H = Сәгать (0-12) <br / HH = Сәгать Ам / PM (00-12) <BR / > H = Сәгать (0-23) көндез (0-23) 2 сәгать A = AM / PM Маркер <br/> p = A. / әм. маркер`,
	EditorTemplateDateTimeCustomLabel: `Гадәт`,
	EditorTemplateDateTimeHint: `Агымдагы датада һәм / яки вакыт ябык булганда даталы шаблоннар өчен алыштырылачак.`,
	EditorTemplateDateTimeName: `Дата вакыты`,
	EditorTemplateDynamicHint: `<p> Бу шаблонның барлык сәхнәләре бирелгән текстны кулланачак. </ p>`,
	EditorTemplateDynamicName: `Динамик`,
	EditorTemplateEmptyPlaceholder: `{0} буш ...`,
	EditorTemplateStaticHint: `<p> Бу шаблонның барлык сәхнәләре бирелгән текстны кулланачак. </ p>`,
	EditorTemplateStaticName: `Статик`,
	EditorTemplateTeaserText: `Тиздән тагын да күбрәк якынлаша!`,
	EditorWatermark: `Зинһар, көтегез...`,
	EditorWholeWordLabel: ` Бөтен сүз`,
	EditorWrapLabel: ` Урлау`,

};