var UiStrings = {
	EditorAppendCloseLabel: `Qatışmağı bitirmək`,
	EditorAppendInlineModeLabel: `Bloku aktivləşdirmək`,
	EditorAppendLineModeLabel: `İnline aktivləşdirin`,
	EditorAppendManualModeLabel: `Əlləşdirmək`,
	EditorAppendNonManualModeLabel: `Əlləşdirmək`,
	EditorAppendPauseLabel: `Fasilə əlavə edin`,
	EditorAppendPostLabel: `Daha əvvəl dəyişdirin`,
	EditorAppendPreLabel: `Daha əvvəl dəyişdirin`,
	EditorAppendResumeLabel: `Əlavə etmək`,
	EditorBgColorLabel: `Fon rəngi`,
	EditorClearAllLabel: `Hamısını sil, hamısını təmizlə`,
	EditorClipboardFormatsLabel: `Panoya formatları`,
	EditorConfirmNtfTitle: `Təsdiq etmək`,
	EditorDeleteAllButtonText: `Hamısını silmək`,
	EditorDeleteAllTemplatesNtfText: `'{0}' nin bütün istifadə sənədlərini silmək istədiyinizə əminsiniz?

Bu geri qaytarıla bilməz!`,
	EditorEditTemplateDetailsLabel: `Təfərrüatları düzəldin`,
	EditorEditTemplateNameLabel: `Ad`,
	EditorFindLabel: `Tapmaq`,
	EditorFontColorLabel: `Şriftin`,
	EditorFormatPaintLabel: `Format boya`,
	EditorInSelectionLabel: ` Seçmədə`,
	EditorInsertImageLabel: `Şəkil qoymaq`,
	EditorInsertLinkLabel: `Linki daxil etmək`,
	EditorInsertVideoLabel: `Videoya salmaq`,
	EditorMatchCaseLabel: ` Kibrit qutusu`,
	EditorNewTemplateLabel: `Yeni şablon`,
	EditorNextTemplateLabel: `Növbəti şablon`,
	EditorPasteButtonAppendBeginLabel: `Əlavə ...`,
	EditorPasteButtonLabel: `Yapışdır`,
	EditorPasteTemplateWatermark: `Paste mətnini daxil edin ...`,
	EditorPrevTemplateLabel: `Əvvəlki şablon`,
	EditorRegExLabel: ` Müntəzəm ifadə`,
	EditorReplaceAllLabel: `Hamısını əvəz edin`,
	EditorReplaceLabel: `Əvəz etmək`,
	EditorTemplateContactHint: `<p> Mövcud kontaktlardan istifadə etmək (bu sahə bu sahə bu sənəddəki bu şablonun bütün halları üçün istifadə ediləcək və ya sonradan istinad ediləcək. </ p> <p> Beləliklə, e-poçt ünvanı seçilməlidir Burada seçim etdiyiniz kontaktın e-poçt sahəsi bu sənəddəki bütün hallar üçün istifadə ediləcəkdir. </ p>`,
	EditorTemplateContactName: `Əlaqə`,
	EditorTemplateDateTimeCustomHint: `YY = qısa bir il <br/> YYYY = Uzun il <br/> m = ay (1-12) <br/> mm = ay (01-12) <br/> mmm = aylıq ixtisarlar (Yanvar, Fevral .. . Dekabr) Həftənin günü sözləri (Bazar ertəsi, Çərşənbə axşamı ... Bazar günü) <br/> e = sözlərdə (Mon, Tue ... Sun) <br/> d - Ordinal Günü (1, 2-ci, 3, 21, 22-ci, 22, 23-cü, 31, 31, 4-cü, 4-cü ...) <br/> h = saat AM / PM (0-12) / saat AM / PM > H = saatda (0-23) <br/> hh = gündə saat (00-23) <br/> mm = dəqiqə <br/> ss = ikinci A = AM / PM marker <br/> p = A.M./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Adlı`,
	EditorTemplateDateTimeHint: `Cari tarix və / və ya vaxt yapışdırıldıqda doğma şablonları üçün əvəz ediləcəkdir.`,
	EditorTemplateDateTimeName: `Tarix vaxt`,
	EditorTemplateDynamicHint: `<p> Bu şablonun bütün yararları verilən mətni istifadə edəcəkdir. </ p>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} boşdur ...`,
	EditorTemplateStaticHint: `<p> Bu şablonun bütün yararları verilən mətni istifadə edəcəkdir. </ p>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Daha çox gələcək!`,
	EditorWatermark: `Zəhmət olmasa, gözləyin...`,
	EditorWholeWordLabel: ` Bütöv`,
	EditorWrapLabel: ` Dolaşdırmaq`,

};