var UiStrings = {
	EditorAppendCloseLabel: `Críochnaigh ag clúdach`,
	EditorAppendInlineModeLabel: `Bloc Cumasaigh`,
	EditorAppendLineModeLabel: `Cumasaigh inlíne`,
	EditorAppendManualModeLabel: `Lámhleabhar Toggle`,
	EditorAppendNonManualModeLabel: `Lámhleabhar Toggle`,
	EditorAppendPauseLabel: `Sos aguisín`,
	EditorAppendPostLabel: `Toggle roimhe seo`,
	EditorAppendPreLabel: `Toggle roimhe seo`,
	EditorAppendResumeLabel: `Atosú aguisín`,
	EditorBgColorLabel: `Dath an chúlra`,
	EditorClearAllLabel: `Soiléir ar fad`,
	EditorClipboardFormatsLabel: `Formáidí gearrthaisce`,
	EditorColorChooserTitle: `Dath eagarthóir`,
	EditorConfirmNtfTitle: `Daingnigh`,
	EditorDeleteAllButtonText: `Scrios gach duine`,
	EditorDeleteAllTemplatesNtfText: `An bhfuil tú cinnte gur mian leat gach úsáid de '{0}' a scriosadh?

Ní féidir é seo a dhíothú!`,
	EditorEditTemplateDetailsLabel: `Sonraí a chur in eagar`,
	EditorEditTemplateNameLabel: `Ainmnigh`,
	EditorFindLabel: `Faigh amach`,
	EditorFontColorLabel: `Cló dath`,
	EditorFormatPaintLabel: `Péint fhormáid`,
	EditorInSelectionLabel: ` Agus é ag roghnú`,
	EditorInsertImageLabel: `Cuir isteach íomhá`,
	EditorInsertLinkLabel: `Cuir isteach nasc`,
	EditorInsertVideoLabel: `Cuir isteach físeán`,
	EditorLinkButtonText: `Spáráil`,
	EditorLinkLabel: `Iontráil Nasc`,
	EditorLinkPlaceholder: `Iontráil URL`,
	EditorMatchCaseLabel: ` Cás an chluiche`,
	EditorNewTemplateLabel: `Teimpléad nua`,
	EditorNextTemplateLabel: `An chéad teimpléad eile`,
	EditorPasteButtonAppendBeginLabel: `Aguisín ...`,
	EditorPasteButtonLabel: `Greab`,
	EditorPasteButtonLabelMobile: `Cóip`,
	EditorPasteTemplateWatermark: `Iontráil téacs greamaigh ...`,
	EditorPrevTemplateLabel: `Teimpléad roimhe seo`,
	EditorRegExLabel: ` Léiriú rialta`,
	EditorReplaceAllLabel: `Ionadaigh go léir`,
	EditorReplaceLabel: `Cuir isteach`,
	EditorTemplateContactHint: `<p>Ag baint úsáide as teagmhálacha atá ar fáil (éilíonn breiseán fetcher) Beidh an réimse seo a úsáid le haghaidh gach cás den teimpléad seo ar fud an doiciméad seo nó in aon beidh sé tagairt i níos déanaí.</p><p> Mar sin, mar shampla má roghnaíonn tú seoladh ríomhphoist anseo, úsáidfear réimse ríomhphoist na teagmhála a roghnaíonn tú do gach cás sa doiciméad seo.</p>`,
	EditorTemplateContactName: `Lionsa`,
	EditorTemplateDateTimeCustomHint: `yy = bliain ghearr<br/>yyyy = bliain fhada<br/>M = mí (1-12)<br/>MM = mí (01-12)<br/>MMM = giorrúchán míosa (Eanáir, Feabhra ... Nollaig)<br/>MMMM = mí fhada (Eanáir, Feabhra ... Nollaig)<br/>d = lá (1 - 31)<br/>dd = lá (01 - 31)<br/>ddd = lá na seachtaine i bhfocail (Dé Luain, Dé Máirt ... Dé Domhnaigh)<br/>E = lá gearr na seachtaine i bhfocail (Luan, Máirt ... An Ghrian)<br/>D - Ordinal day (1ú, 2ú, 3ú, 21ú, 22ú, 23ú, 31ú, 4ú...)<br/>h = uair an chloig in am / pm (0-12)<br/>HH = uair an chloig i AM / PM (00-12)<br/>H = uair an chloig sa lá (0-23)<br/>HH = uair sa lá (00-23)<br/>mm = nóiméad<br/>ss = an dara<br/>SSS = milleasoicindí<br/>a = marcóir AM / PM<br/>p = a.m./p.m. marcóir`,
	EditorTemplateDateTimeCustomLabel: `Cur síos`,
	EditorTemplateDateTimeHint: `Cuirfear an dáta agus/nó an t -am reatha in ionad teimpléid dhátú nuair a ghreamaítear iad.`,
	EditorTemplateDateTimeName: `Dáta Am`,
	EditorTemplateDynamicHint: `<p>Bainfidh gach tarlú den teimpléad seo úsáid as an téacs atá curtha ar fáil.</p>`,
	EditorTemplateDynamicName: `Dinimiciúil`,
	EditorTemplateEmptyPlaceholder: `Tá {0} folamh ...`,
	EditorTemplateStaticHint: `<p>Bainfidh gach tarlú den teimpléad seo úsáid as an téacs atá curtha ar fáil.</p>`,
	EditorTemplateStaticName: `Statach`,
	EditorTemplateTeaserText: `Níos mó ag teacht go luath!`,
	EditorTt1: `Cliceáil`,
	EditorTt2: `Athraigh '<em> {0} </em>' ...`,
	EditorTt3: `Dath a chur in eagar ...`,
	EditorTt4: `Bain '<em> {0} </em>' ...`,
	EditorTt5: `Bain an mhír`,
	EditorTt6: `leanúint ...`,
	EditorTt7: `Goto '<em> {0} </em>' ...`,
	EditorWatermark: `Fán le do thoil...`,
	EditorWholeWordLabel: ` Focal iomlán`,
	EditorWrapLabel: ` Timfhilleadh timpeall`,

};