var UiStrings = {
	EditorAppendCloseLabel: `Ավարտեք հավելվածը`,
	EditorAppendInlineModeLabel: `Միացնել բլոկը`,
	EditorAppendLineModeLabel: `Միացնել inline- ը`,
	EditorAppendManualModeLabel: `Փոփոխել ձեռնարկը`,
	EditorAppendNonManualModeLabel: `Փոփոխել ձեռնարկը`,
	EditorAppendPauseLabel: `Դադարացրեք հավելված`,
	EditorAppendPostLabel: `Անցնել նախկինում`,
	EditorAppendPreLabel: `Անցնել նախկինում`,
	EditorAppendResumeLabel: `Վերսկսել հավելվածը`,
	EditorBgColorLabel: `Ֆոնի գույնը`,
	EditorClearAllLabel: `Մաքրել բոլորը`,
	EditorClipboardFormatsLabel: `Clipboard- ի ձեւաչափերը`,
	EditorConfirmNtfTitle: `Հաստատել`,
	EditorDeleteAllButtonText: `Delete նջել բոլորը`,
	EditorDeleteAllTemplatesNtfText: `Համոզված եք, որ ցանկանում եք ջնջել «{0}» -ի բոլոր օգտագործումը:

Սա չի կարող վերացնել:`,
	EditorEditTemplateDetailsLabel: `Խմբագրել Մանրամասները`,
	EditorEditTemplateNameLabel: `Անուն`,
	EditorFindLabel: `Գտնել`,
	EditorFontColorLabel: `Տառատեսակի գույնը`,
	EditorFormatPaintLabel: `Ձեւաչափի ներկ`,
	EditorInSelectionLabel: ` Ընտրության մեջ`,
	EditorInsertImageLabel: `Տեղադրեք պատկերը`,
	EditorInsertLinkLabel: `Տեղադրեք հղումը`,
	EditorInsertVideoLabel: `Տեղադրեք տեսանյութը`,
	EditorMatchCaseLabel: ` Համընկնում`,
	EditorNewTemplateLabel: `Նոր ձեւանմուշ`,
	EditorNextTemplateLabel: `Հաջորդ ձեւանմուշը`,
	EditorPasteButtonAppendBeginLabel: `Հավելված ...`,
	EditorPasteButtonLabel: `Մածուկ`,
	EditorPasteTemplateWatermark: `Մուտքագրեք մածուկի տեքստը ...`,
	EditorPrevTemplateLabel: `Նախորդ ձեւանմուշ`,
	EditorRegExLabel: ` Պարբերաբար արտահայտում`,
	EditorReplaceAllLabel: `Փոխարինել բոլորը`,
	EditorReplaceLabel: `Փոխարինել`,
	EditorTemplateContactHint: `<p> Առկա կոնտակտներ օգտագործելը (պահանջում է Fetcher plugin) Այս դաշտը կօգտագործվի այս ձեւանմուշի բոլոր դեպքերի համար այս փաստաթղթում կամ ցանկացած դեպքում, եթե ընտրեք էլ. Փոստի հասցե Այստեղ այն դեպքում, երբ ձեր ընտրած կոնտակտի էլփոստի դաշտը կօգտագործվի այս փաստաթղթի բոլոր ատյանների համար: </ p>`,
	EditorTemplateContactName: `Կապ`,
	EditorTemplateDateTimeCustomHint: `YY = կարճ տարին <br/> YYYY = երկար տարի <br/> մ տարի (1-12) <br/> mm = ամիս (01-12) <br/> mmm = ամսվա կրճատում (հունվար, փետր): . Դեկտեմբեր) <br /> mmmm = երկար ամիս (հունվար, փետրվար ... դեկտեմբեր) <br /> D = Day (1 - 31) <br/> DDD = Շաբաթվա օրը (երկուշաբթի, երեքշաբթի ... կիրակի) <br /> e = շաբաթվա կարճ օրը բառերով (երկուշաբթի, ... Արեւ) <br/> D - 1-ին, 3-րդ, 21-րդ, 22-րդ, 23-րդ, 31-րդ, 4-րդ ...) <br /> AM = ժամ առավոտյան / երեկոյան (0-12) <br/> HH = ժամ AM / PM (00-12) <BR / > H = ժամվա ընթացքում (0-23) <br /> HH = ժամվա ժամ (00-23) <br/> MM = րոպե <br/> <br/> <br/> Ա = AM / PM Մարկեր <br/> p = q.m./p.m. մարկեր`,
	EditorTemplateDateTimeCustomLabel: `Մաքսատուրք`,
	EditorTemplateDateTimeHint: `Ընթացիկ ամսաթիվը եւ (կամ) ժամանակը կփոխարինվի DateTime ձեւանմուշների համար, երբ դրանք տեղադրվեն:`,
	EditorTemplateDateTimeName: `Ամսաթիվ ժամանակ`,
	EditorTemplateDynamicHint: `Այս ձեւանմուշի բոլոր դեպքերը կօգտագործեն տրամադրված տեքստը: </ p>`,
	EditorTemplateDynamicName: `Դինամիկ`,
	EditorTemplateEmptyPlaceholder: `{0} դատարկ է ...`,
	EditorTemplateStaticHint: `Այս ձեւանմուշի բոլոր դեպքերը կօգտագործեն տրամադրված տեքստը: </ p>`,
	EditorTemplateStaticName: `Ստատիկ`,
	EditorTemplateTeaserText: `Ավելի շուտ շուտ կգա:`,
	EditorWatermark: `Խնդրում ենք սպասել...`,
	EditorWholeWordLabel: ` Ամբողջ բառը`,
	EditorWrapLabel: ` Փաթեթավորեք շուրջը`,

};