var UiStrings = {
	EditorAppendCloseLabel: `Përfundoni Shtojcën`,
	EditorAppendInlineModeLabel: `Aktivizo bllokun`,
	EditorAppendLineModeLabel: `Aktivizo Inline`,
	EditorAppendManualModeLabel: `Manuali i ndryshuar`,
	EditorAppendNonManualModeLabel: `Manuali i ndryshuar`,
	EditorAppendPauseLabel: `Pauzë shtoj`,
	EditorAppendPostLabel: `Toggle më parë`,
	EditorAppendPreLabel: `Toggle më parë`,
	EditorAppendResumeLabel: `Rifilloj shtojcën`,
	EditorBgColorLabel: `Ngjyrë e sfondit`,
	EditorClearAllLabel: `Pastroji të gjitha`,
	EditorClipboardFormatsLabel: `Formate clipboard`,
	EditorColorChooserTitle: `Ngjyra e redaktorit`,
	EditorConfirmNtfTitle: `Konfirmoj`,
	EditorDeleteAllButtonText: `Fshij te gjitha`,
	EditorDeleteAllTemplatesNtfText: `A jeni i sigurt që doni të fshini të gjitha përdorimet e '{0}'?

Kjo nuk mund të zhbëhet!`,
	EditorEditTemplateDetailsLabel: `Redakto detajet`,
	EditorEditTemplateNameLabel: `Emër`,
	EditorFindLabel: `Gjej`,
	EditorFontColorLabel: `Ngjyra e shkronjave`,
	EditorFormatPaintLabel: `Bojë formati`,
	EditorInSelectionLabel: ` Në përzgjedhje`,
	EditorInsertImageLabel: `Vendosni imazhin`,
	EditorInsertLinkLabel: `Vendosni lidhjen`,
	EditorInsertVideoLabel: `Fut video`,
	EditorLinkButtonText: `Ruaj`,
	EditorLinkLabel: `Fut Link`,
	EditorLinkPlaceholder: `Hyni në URL`,
	EditorMatchCaseLabel: ` Rast i ndeshjes`,
	EditorNewTemplateLabel: `Shabllon i ri`,
	EditorNextTemplateLabel: `Modeli tjetër`,
	EditorPasteButtonAppendBeginLabel: `Shtoj ...`,
	EditorPasteButtonLabel: `Ngjit`,
	EditorPasteButtonLabelMobile: `Kopjoj`,
	EditorPasteTemplateWatermark: `Futni tekstin e pastës ...`,
	EditorPrevTemplateLabel: `Shablloni i mëparshëm`,
	EditorRegExLabel: ` Shprehje e rregullt`,
	EditorReplaceAllLabel: `Zëvendësoni të gjitha`,
	EditorReplaceLabel: `Zëvendësoj`,
	EditorTemplateContactHint: `<p>Duke përdorur kontaktet në dispozicion (kërkon një plugin fetcher) kjo fushë do të përdoret për të gjitha instancat e këtij template në të gjithë këtë dokument ose në çdo gjë që do të referohet më vonë.</p><p> Pra, për shembull, nëse zgjidhni adresën e emailit këtu atëherë fusha e email-it e kontaktit që zgjidhni do të përdoret për të gjitha instancat në këtë dokument.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = vit i shkurtër<br/>yyyy = vit i gjatë<br/>M = muaj (1-12)<br/>MM = muaj (01-12)<br/>MMM = shkurtesa mujore (Jan, Feb ... Dec)<br/>MMMM = muaj i gjatë (janar, shkurt ... Dhjetor)<br/>d = ditë (1 - 31)<br/>dd = dita (01 - 31)<br/>ddd = dita e javës me fjalë (e hënë, e martë ... E diel)<br/>E = ditë e shkurtër e javës me fjalë (Mon, Tue ... Sun)<br/>D - Dita ordinale (1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = orë në am/pm (0-12)<br/>hh = orë në am/pm (00-12)<br/>H = orë në ditë (0-23)<br/>HH = orë në ditë (00-23)<br/>mm = minutë<br/>ss = i dyti<br/>SSS = milisekonda<br/>a = shënues AM/PM<br/>p = shënues a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `I zakonshëm`,
	EditorTemplateDateTimeHint: `Data aktuale dhe/ose koha do të zëvendësohet për shabllonet e DateTime kur ato ngjiten.`,
	EditorTemplateDateTimeName: `Koha e datës`,
	EditorTemplateDynamicHint: `<p>Të gjitha ndodhitë e këtij template do të përdorin tekstin e dhënë.</p>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} është bosh ...`,
	EditorTemplateStaticHint: `<p>Të gjitha ndodhitë e këtij template do të përdorin tekstin e dhënë.</p>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Më shumë së shpejti!`,
	EditorTt1: `Klikos`,
	EditorTt2: `Redakto '<em> {0} </em>' ...`,
	EditorTt3: `Redakto ngjyrën ...`,
	EditorTt4: `Hiq '<em> {0} </em>' ...`,
	EditorTt5: `Hiq artikullin`,
	EditorTt6: `ta ndjek ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Te lutem prit...`,
	EditorWholeWordLabel: ` Fjalë e plotë`,
	EditorWrapLabel: ` Mbështjellë`,

};