var UiStrings = {
	EditorAppendCloseLabel: `Дуусгах ажлыг дуусгах`,
	EditorAppendInlineModeLabel: `Блок идэвхжүүлэх`,
	EditorAppendLineModeLabel: `Доторыг идэвхжүүлэх`,
	EditorAppendManualModeLabel: `Гарын авлага`,
	EditorAppendNonManualModeLabel: `Гарын авлага`,
	EditorAppendPauseLabel: `Түр зогсоох`,
	EditorAppendPostLabel: `Өмнө нь сэлгэх`,
	EditorAppendPreLabel: `Өмнө нь сэлгэх`,
	EditorAppendResumeLabel: `ҮЙЛЧИЛГЭЭНИЙ ТӨЛӨВЛӨГӨӨ`,
	EditorBgColorLabel: `Дэвсгэр өнгө`,
	EditorClearAllLabel: `Бүгдийг цэвэрлэ`,
	EditorClipboardFormatsLabel: `Хяналтын самбарын форматууд`,
	EditorColorChooserTitle: `Програмад өнгө`,
	EditorConfirmNtfTitle: `Батлах`,
	EditorDeleteAllButtonText: `Бүгдийг устгах`,
	EditorDeleteAllTemplatesNtfText: `Та '{0}' хэрэглээг устгахыг хүсч байна уу?

Энэ буцаах боломжгүй!`,
	EditorEditTemplateDetailsLabel: `Дэлгэрэнгүй чиглүүлэх`,
	EditorEditTemplateNameLabel: `Нэр`,
	EditorFindLabel: `Илрүүлэх`,
	EditorFontColorLabel: `Үсгийн өнгө`,
	EditorFormatPaintLabel: `Автомат чанар`,
	EditorInSelectionLabel: ` Сонгон шалгаруулах`,
	EditorInsertImageLabel: `Зураг оруулах`,
	EditorInsertLinkLabel: `Холбоос суулгах`,
	EditorInsertVideoLabel: `Судлах`,
	EditorLinkButtonText: `Аврах`,
	EditorLinkLabel: `Оруулах`,
	EditorLinkPlaceholder: `Өргдуун үд оруулна`,
	EditorMatchCaseLabel: ` Тохируулгын хэрэг`,
	EditorNewTemplateLabel: `Шинэ загвар`,
	EditorNextTemplateLabel: `Дараагийн загвар`,
	EditorPasteButtonAppendBeginLabel: `Нэмэх ...`,
	EditorPasteButtonLabel: `Товч`,
	EditorPasteTemplateWatermark: `Буулгах текстийг оруулна уу ...`,
	EditorPrevTemplateLabel: `Өмнөх загвар`,
	EditorRegExLabel: ` Тогтмол илэрхийлэл`,
	EditorReplaceAllLabel: `Бүгдийг орлуулаарай`,
	EditorReplaceLabel: `Буцааж тавих`,
	EditorTemplateContactHint: `<p>ᠬᠡᠷᠡᠭᠯᠡᠵᠦ ᠪᠣᠯᠬᠤ ᠬᠠᠷᠢᠯᠴᠠᠬᠤ ᠬᠥᠮᠦᠨ ( ᠭᠠᠷᠭᠠᠵᠤ ᠠᠪᠬᠤ ᠮᠠᠰᠢᠨ ᠤ ᠬᠠᠪᠴᠢᠭᠤᠷ ᠬᠡᠷᠡᠭᠰᠡᠬᠦ ) ᠂ ᠡᠨᠡ ᠦᠰᠦᠭ ᠢ ᠲᠤᠰ ᠵᠣᠬᠢᠶᠠᠯ ᠤᠨ ᠳᠠᠩᠰᠠ ᠡᠪᠬᠡᠮᠡᠯ ᠳᠣᠲᠣᠷᠠᠬᠢ ᠡᠨᠡ ᠬᠡᠪ ᠵᠠᠭᠪᠤᠷ ᠤᠨ ᠠᠯᠢᠪᠠ ᠪᠣᠳᠠᠲᠤ ᠵᠢᠱᠢᠶ᠎ᠡ ᠳᠦ ᠬᠡᠷᠡᠭᠯᠡᠨ᠎ᠡ ᠂ ᠡᠰᠡᠭᠦᠯ᠎ᠡ ᠵᠢᠭᠠᠬᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠡᠰᠢᠯᠡᠨ ᠬᠡᠷᠡᠭᠯᠡᠨ᠎ᠡ ᠃</p><p> ᠡᠶᠢᠮᠦ ᠡᠴᠡ ᠂ ᠵᠢᠱᠢᠶᠡᠯᠡᠪᠡᠯ ᠂ ᠬᠡᠷᠪᠡ ᠡᠨᠳᠡ ᠡᠯᠧᠺᠲ᠋ᠷᠣᠨ ᠰᠢᠤᠳᠠᠨ ᠤ ᠬᠠᠶᠢᠭ ᠢ ᠰᠣᠩᠭᠣᠪᠠᠯ ᠂ ᠲᠠᠨ ᠤ ᠰᠤᠩᠭᠤᠭᠰᠠᠨ ᠬᠠᠷᠢᠯᠴᠠᠬᠤ ᠬᠥᠮᠦᠨ ᠦ ᠡᠯᠧᠺᠲ᠋ᠷᠣᠨ ᠰᠢᠤᠳᠠᠨ ᠤ ᠦᠰᠦᠭ ᠦᠨ ᠬᠡᠰᠡᠭ ᠢ ᠲᠤᠰ ᠵᠣᠬᠢᠶᠠᠯ ᠤᠨ ᠳᠡᠰ ᠦᠨ ᠳᠣᠲᠣᠷᠠᠬᠢ ᠪᠤᠳᠠᠲᠤ ᠵᠢᠱᠢᠶ᠎ᠡ ᠳᠦ ᠬᠡᠷᠡᠭᠯᠡᠨ᠎ᠡ ᠃</p>`,
	EditorTemplateContactName: `Харилцах`,
	EditorTemplateDateTimeCustomHint: `yy ᠣᠬᠣᠷᠬᠠᠨ ᠵᠢᠯ᠃<br/>yy ᠤᠷᠲᠤ ᠵᠢᠯ᠃<br/>ᠮᠠ = ᠰᠠᠷ᠎ᠠ (1-12)<br/>MMt ᠰᠠᠷ᠎ᠠ (01-12)<br/>MMM= ᠰᠠᠷ᠎ᠠ ᠳᠤ ᠪᠢᠴᠢᠬᠦ (ᠵᠧᠨ᠂ ᠹᠧᠪ ᠁ 12 ᠰᠠᠷ᠎ᠠ )<br/>MMMM= ᠤᠷᠲᠤ ᠰᠠᠷᠠᠨ (1 ᠰᠠᠷ᠎ᠠ᠂ 2 ᠳ᠋ᠤᠭᠠᠷ ᠰᠠᠷ᠎ᠠ ...... 12 ᠰᠠᠷ᠎ᠠ )<br/>d= ᠲᠢᠶᠠᠨ (1-31)<br/>dd= ᠲᠢᠶᠠᠨ (01-31)<br/>ᠭᠠᠷᠠᠭ ᠤᠨ ᠬᠡᠳᠦᠨ ( ᠭᠠᠷᠠᠭ ᠤᠨ ᠨᠢᠭᠡᠨ ᠂ ᠭᠠᠷᠠᠭ ᠤᠨ ᠬᠣᠶᠠᠷ ᠤᠨ ...... ᠭᠠᠷᠠᠭ ᠤᠨ ᠡᠳᠦᠷ )<br/>E= ᠨᠢᠭᠡ ᠭᠠᠷᠠᠭ ᠤᠨ ᠳᠣᠲᠣᠷᠠᠬᠢ ᠣᠬᠣᠷ ᠡᠳᠦᠷ ( ᠭᠠᠷᠠᠭ ᠤᠨ ᠨᠢᠭᠡᠨ ᠂ ᠭᠠᠷᠠᠭ ᠤᠨ ᠬᠣᠶᠠᠷ ᠤᠨ ...... ᠭᠠᠷᠠᠭ ᠤᠨ ᠡᠳᠦᠷ )<br/>D̓ ᠳᠡᠰ ᠳᠠᠷᠠᠭᠠᠯᠠᠯ ᠤᠨ ᠬᠡᠳᠦᠨ ᠡᠳᠦᠷ (1 ᠤ ᠡᠳᠦᠷ᠂ 2 ᠤᠨ ᠡᠳᠦᠷ᠂ 3᠂ 21᠎ ᠤ ᠡᠳᠦᠷ᠂ 21᠎ ᠤ ᠡᠳᠦᠷ᠂ 22 ᠤᠨ ᠡᠳᠦᠷ᠂ 22 ᠤᠨ ᠡᠳᠦᠷ᠂ 23᠂ 23᠂ 31᠎ ᠤ ᠡᠳᠦᠷ᠂ 31᠎ ᠤ ᠡᠳᠦᠷ᠂ 4 ᠤ ᠡᠳᠦᠷ ᠁<br/>h= ᠴᠠᠭ ᠲᠤ ᠨᠢᠭᠡᠴᠢ ᠦᠳᠡ ᠶᠢᠨ ᠡᠮᠦᠨ᠎ᠡ / ᠦᠳᠡ ᠶᠢᠨ ᠬᠣᠶᠢᠨ᠎ᠠ (0-12)<br/>hh=ᠴᠠᠭ (ᠦᠳᠡ ᠶᠢᠨ ᠡᠮᠦᠨ᠎ᠡ /ᠦᠳᠡ ᠶᠢᠨ ᠬᠣᠶᠢᠨ᠎ᠠ)(00-12)<br/>H ᠨᠢᠭᠡ ᠡᠳᠦᠷ ᠦᠨ ᠳᠤᠮᠳᠠᠬᠢ ᠴᠠᠭ (0-23)<br/>HH ᠨᠢᠭᠡ ᠡᠳᠦᠷ ᠦᠨ ᠳᠣᠲᠣᠷᠠᠬᠢ ᠴᠠᠭ (00-23)<br/>ᠮᠢᠨᠦᠢᠲ᠋ ᠃<br/>s= ᠰᠧᠺᠦᠢᠨᠳ᠋᠃<br/>SSS ᠮᠢᠯᠢᠯᠢᠮᠧᠲ᠋ᠷ᠃<br/>AM/PM ᠲᠡᠮᠳᠡᠭ᠃<br/>p ᠦᠳᠡ ᠶᠢᠨ ᠡᠮᠦᠨ᠎ᠡ / ᠦᠳᠡ ᠶᠢᠨ ᠬᠣᠶᠢᠨ᠎ᠠ ᠲᠡᠮᠳᠡᠭᠯᠡᠯ᠃`,
	EditorTemplateDateTimeCustomLabel: `Ес заншил`,
	EditorTemplateDateTimeHint: `Одоогийн огноо ба / эсвэл цаг хугацааг буулгах үед DateTime загварыг орлуулах болно.`,
	EditorTemplateDateTimeName: `Он сар өдөр цаг`,
	EditorTemplateDynamicHint: `<p>ᠡᠨᠡ ᠬᠡᠪ ᠵᠠᠭᠪᠤᠷ ᠤᠨ ᠪᠤᠢ ᠪᠥᠬᠥᠢ ᠲᠣᠨᠣᠭ ᠲᠥᠰᠥᠪ ᠢ ᠪᠦᠷ ᠬᠠᠩᠭᠠᠭᠰᠠᠨ ᠪᠢᠴᠢᠭ᠌ ᠢ ᠬᠡᠷᠡᠭ᠍ᠯᠡᠨ᠎ᠡ ᠃</p>`,
	EditorTemplateDynamicName: `Динамик`,
	EditorTemplateEmptyPlaceholder: `{0} хоосон байна ...`,
	EditorTemplateStaticHint: `<p>ᠡᠨᠡ ᠬᠡᠪ ᠵᠠᠭᠪᠤᠷ ᠤᠨ ᠪᠤᠢ ᠪᠥᠬᠥᠢ ᠲᠣᠨᠣᠭ ᠲᠥᠰᠥᠪ ᠢ ᠪᠦᠷ ᠬᠠᠩᠭᠠᠭᠰᠠᠨ ᠪᠢᠴᠢᠭ᠌ ᠢ ᠬᠡᠷᠡᠭ᠍ᠯᠡᠨ᠎ᠡ ᠃</p>`,
	EditorTemplateStaticName: `Стобик`,
	EditorTemplateTeaserText: `Илүү удахгүй ирэх болно!`,
	EditorTt1: `Дээр байна`,
	EditorTt2: `Засварлах '<<<<{{0} </ em>' ...`,
	EditorTt3: `Өнгө засах ...`,
	EditorTt4: `'<<<<<{{0} </ em>' -г арилгах ...`,
	EditorTt5: `Зүйлийг арилгах`,
	EditorTt6: `дагах ...`,
	EditorTt7: `goto '<em> {0 {0} </ em>' ...`,
	EditorWatermark: `Түр хүлээнэ үү ...`,
	EditorWholeWordLabel: ` Бүхэл үг`,
	EditorWrapLabel: ` Эргэн тойронд ороосон`,

};