var UiStrings = {
	EditorAppendCloseLabel: `추가 마무리`,
	EditorAppendInlineModeLabel: `블록 활성화`,
	EditorAppendLineModeLabel: `인라인을 활성화합니다`,
	EditorAppendManualModeLabel: `토글 매뉴얼`,
	EditorAppendNonManualModeLabel: `토글 매뉴얼`,
	EditorAppendPauseLabel: `잠시 일시 중지하십시오`,
	EditorAppendPostLabel: `전에 전환하십시오`,
	EditorAppendPreLabel: `전에 전환하십시오`,
	EditorAppendResumeLabel: `부록을 재개하십시오`,
	EditorBgColorLabel: `배경색`,
	EditorClearAllLabel: `모든 것을 지우십시오`,
	EditorClipboardFormatsLabel: `클립 보드 형식`,
	EditorColorChooserTitle: `편집기 색상`,
	EditorConfirmNtfTitle: `확인하다`,
	EditorDeleteAllButtonText: `모두 삭제`,
	EditorDeleteAllTemplatesNtfText: `'{0}'의 모든 사용법을 삭제 하시겠습니까?

이 취소 할 수 없습니다!`,
	EditorEditTemplateDetailsLabel: `세부 사항을 편집하십시오`,
	EditorEditTemplateNameLabel: `이름`,
	EditorFindLabel: `찾다`,
	EditorFontColorLabel: `글꼴 색상`,
	EditorFormatPaintLabel: `형식 페인트`,
	EditorInSelectionLabel: ` 선택 중`,
	EditorInsertImageLabel: `이미지 삽입`,
	EditorInsertLinkLabel: `링크를 삽입하십시오`,
	EditorInsertVideoLabel: `비디오 삽입`,
	EditorLinkButtonText: `구하다`,
	EditorLinkLabel: `링크를 입력하십시오`,
	EditorLinkPlaceholder: `URL을 입력하십시오`,
	EditorMatchCaseLabel: ` 매치 케이스`,
	EditorNewTemplateLabel: `새로운 템플릿`,
	EditorNextTemplateLabel: `다음 템플릿`,
	EditorPasteButtonAppendBeginLabel: `추가 ...`,
	EditorPasteButtonLabel: `반죽`,
	EditorPasteButtonLabelMobile: `복사`,
	EditorPasteTemplateWatermark: `페이스트 텍스트를 입력하십시오 ...`,
	EditorPrevTemplateLabel: `이전 템플릿`,
	EditorRegExLabel: ` 정규 표현`,
	EditorReplaceAllLabel: `모두 다 바꿔`,
	EditorReplaceLabel: `바꾸다`,
	EditorTemplateContactHint: `<p>사용 가능한 연락처(fetcher 플러그인 필요)를 사용하여 이 필드는 이 문서 전체에서 이 템플릿의 모든 인스턴스에 사용되거나 나중에 참조될 모든 인스턴스에 사용됩니다.</p><p> 예를 들어 여기에서 전자 메일 주소를 선택하면 선택한 연락처의 전자 메일 필드가 이 문서의 모든 인스턴스에 사용됩니다.</p>`,
	EditorTemplateContactName: `연락하다`,
	EditorTemplateDateTimeCustomHint: `yy = 짧은 연도<br/>yyyy = 긴 연도<br/>M = 월(1-12)<br/>MM = 월(01-12)<br/>MMM = 월 약어 (Jan, Feb ... 12월)<br/>MMMM = 긴 달(1월, 2월 ... 12월)<br/>d = 일(1 - 31)<br/>dd = 일(01 - 31)<br/>ddd = 요일 (월요일, 화요일 ... 일요일)<br/>E = 단어의 짧은 요일 (Mon, Tue ... 일)<br/>D - 서수 (1일, 2일, 3일, 21일, 22일, 23일, 31일, 4일...)<br/>h = 오전/오후 시간(0-12)<br/>hh = 오전/오후 시간(00-12)<br/>H = 시간(0-23)<br/>HH = 시간(00-23)<br/>mm = 분<br/>ss = 초<br/>SSS = 밀리초<br/>a = AM/PM 마커<br/>p = 오전/오후 마커`,
	EditorTemplateDateTimeCustomLabel: `관습`,
	EditorTemplateDateTimeHint: `현재 날짜 및/또는 시간은 붙여 넣을 때 DateTime 템플릿으로 대체됩니다.`,
	EditorTemplateDateTimeName: `날짜 시간`,
	EditorTemplateDynamicHint: `<p>이 템플릿의 모든 항목은 제공된 텍스트를 사용합니다.</p>`,
	EditorTemplateDynamicName: `동적`,
	EditorTemplateEmptyPlaceholder: `{0}은 비어 있습니다 ...`,
	EditorTemplateStaticHint: `<p>이 템플릿의 모든 항목은 제공된 텍스트를 사용합니다.</p>`,
	EditorTemplateStaticName: `공전`,
	EditorTemplateTeaserText: `더 곧 출시 될 예정입니다!`,
	EditorTt1: `딸깍 하는 소리`,
	EditorTt2: `편집 '<em> {0} </em>'...`,
	EditorTt3: `색상 편집 ...`,
	EditorTt4: `'<em> {0} </em>'을 제거하십시오 ...`,
	EditorTt5: `항목을 제거하십시오`,
	EditorTt6: `따라야 ...`,
	EditorTt7: `goto '<em> {0} </em>'...`,
	EditorWatermark: `기다리세요...`,
	EditorWholeWordLabel: ` 전체 단어`,
	EditorWrapLabel: ` 줄 바꿈`,

};