var UiStrings = {
	EditorAppendCloseLabel: `Завршете ја додавањето`,
	EditorAppendInlineModeLabel: `Овозможете блок`,
	EditorAppendLineModeLabel: `Овозможи вметната`,
	EditorAppendManualModeLabel: `Прирачник за вклучување`,
	EditorAppendNonManualModeLabel: `Прирачник за вклучување`,
	EditorAppendPauseLabel: `Пауза додаток`,
	EditorAppendPostLabel: `Се менува пред тоа`,
	EditorAppendPreLabel: `Се менува пред тоа`,
	EditorAppendResumeLabel: `Продолжи додаток`,
	EditorBgColorLabel: `Боја на позадина`,
	EditorClearAllLabel: `Исчисти се`,
	EditorClipboardFormatsLabel: `Формати на таблата со исечоци`,
	EditorConfirmNtfTitle: `Потврди`,
	EditorDeleteAllButtonText: `Избришете ги сите`,
	EditorDeleteAllTemplatesNtfText: `Дали сте сигурни дека сакате да ги избришете сите употреби на '{0}'?

Тоа не може да се врати назад!`,
	EditorEditTemplateDetailsLabel: `Уреди детали`,
	EditorEditTemplateNameLabel: `Име`,
	EditorFindLabel: `Најдете`,
	EditorFontColorLabel: `Боја на фонтот`,
	EditorFormatPaintLabel: `Формат боја`,
	EditorInSelectionLabel: ` При избор`,
	EditorInsertImageLabel: `Вметнете слика`,
	EditorInsertLinkLabel: `Вметнете врска`,
	EditorInsertVideoLabel: `Вметнете видео`,
	EditorMatchCaseLabel: ` Случај за натпревар`,
	EditorNewTemplateLabel: `Нов образец`,
	EditorNextTemplateLabel: `Следен образец`,
	EditorPasteButtonAppendBeginLabel: `Додаток ...`,
	EditorPasteButtonLabel: `Залепи`,
	EditorPasteTemplateWatermark: `Внесете текст за паста ...`,
	EditorPrevTemplateLabel: `Претходен образец`,
	EditorRegExLabel: ` Редовно изразување`,
	EditorReplaceAllLabel: `Заменете ги сите`,
	EditorReplaceLabel: `Заменете`,
	EditorTemplateContactHint: `<p> Користење на достапни контакти (бара додаток на Fetcher) Ова поле ќе се користи за сите примери на овој образец низ овој документ или во кој било ќе биде наведено подоцна. </p> <p> Така, на пример, ако изберете адреса за е -пошта Тука тогаш полето за е -пошта на контакт што ќе го изберете ќе се користи за сите примери во овој документ. </p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = кратка година <br/> yyyy = долга година <br/> m = месец (1-12) <br/> mm = месец (01-12) <br/> mmm = месечна кратенка (јануари, февруари .. . Дек) <br/> mmmm = долг месец (јануари, февруари ... декември) <br/> d = ден (1 - 31) <br/> dd = ден (01 - 31) <br/> ddd = Ден на неделата со зборови (понеделник, вторник ... недела) <br/> e = краток ден во неделата со зборови (Пон, Втор ... Сонце) <br/> Д - Ден на редот (1 -ви, 2 -ри, 3-ти, 21-ви, 22-ри, 23-ти, 31-то, 4-ти ...) <br/> h = час во Ам/ПМ (0-12) <br/> hh = час во Ам/ПМ (00-12) <Бр/Бр/ > H = час во ден (0-23) <br/> hh = час во ден (00-23) <br/> mm = минута <br/> ss = втора <br/> sss = милисекунди <br/> A = AM/PM маркер <br/> p = a.m./p.m. маркер`,
	EditorTemplateDateTimeCustomLabel: `Обичај`,
	EditorTemplateDateTimeHint: `Тековниот датум и/или време ќе бидат заменети за шаблони за дата кога ќе бидат залепени.`,
	EditorTemplateDateTimeName: `Датум време`,
	EditorTemplateDynamicHint: `<p> Сите патеки на овој образец ќе го користат даден текст. </p>`,
	EditorTemplateDynamicName: `Динамичен`,
	EditorTemplateEmptyPlaceholder: `{0} е празен ...`,
	EditorTemplateStaticHint: `<p> Сите патеки на овој образец ќе го користат даден текст. </p>`,
	EditorTemplateStaticName: `Статички`,
	EditorTemplateTeaserText: `Повеќе наскоро!`,
	EditorWatermark: `Ве молам почекајте...`,
	EditorWholeWordLabel: ` Цел збор`,
	EditorWrapLabel: ` Завиткајте наоколу`,

};