var UiStrings = {
	EditorAppendCloseLabel: `சேர்ந்து முடிக்கவும்`,
	EditorAppendInlineModeLabel: `தொகுதியை இயக்கு`,
	EditorAppendLineModeLabel: `இன்லைன் இயக்கவும்`,
	EditorAppendManualModeLabel: `கையேட்டை மாற்றவும்`,
	EditorAppendNonManualModeLabel: `கையேட்டை மாற்றவும்`,
	EditorAppendPauseLabel: `இடைநிறுத்தம்`,
	EditorAppendPostLabel: `முன் மாற்று`,
	EditorAppendPreLabel: `முன் மாற்று`,
	EditorAppendResumeLabel: `மறுதொடக்கம் செய்யுங்கள்`,
	EditorBgColorLabel: `பின்னணி நிறம்`,
	EditorClearAllLabel: `அனைத்தையும் அழி`,
	EditorClipboardFormatsLabel: `கிளிப்போர்டு வடிவங்கள்`,
	EditorConfirmNtfTitle: `உறுதிப்படுத்தவும்`,
	EditorDeleteAllButtonText: `அனைத்தையும் நீக்கு`,
	EditorDeleteAllTemplatesNtfText: `'{0}' இன் அனைத்து பயன்பாடுகளையும் நீக்க விரும்புகிறீர்களா?

இதை முடிக்காமல் விட கூடாது!`,
	EditorEditTemplateDetailsLabel: `விவரங்களைத் திருத்தவும்`,
	EditorEditTemplateNameLabel: `பெயர்`,
	EditorFindLabel: `கண்டுபிடி`,
	EditorFontColorLabel: `எழுத்துரு நிறம்`,
	EditorFormatPaintLabel: `வடிவமைப்பு வண்ணப்பூச்சு`,
	EditorInSelectionLabel: ` தேர்வில்`,
	EditorInsertImageLabel: `படத்தைச் செருகவும்`,
	EditorInsertLinkLabel: `இணைப்பைச் செருகவும்`,
	EditorInsertVideoLabel: `வீடியோவைச் செருகவும்`,
	EditorMatchCaseLabel: ` போட்டி வழக்கு`,
	EditorNewTemplateLabel: `புதிய வார்ப்புரு`,
	EditorNextTemplateLabel: `அடுத்த வார்ப்புரு`,
	EditorPasteButtonAppendBeginLabel: `சேர்க்க ...`,
	EditorPasteButtonLabel: `ஒட்டவும்`,
	EditorPasteTemplateWatermark: `பேஸ்ட் உரையை உள்ளிடவும் ...`,
	EditorPrevTemplateLabel: `முந்தைய வார்ப்புரு`,
	EditorRegExLabel: ` வழக்கமான வெளிப்பாடு`,
	EditorReplaceAllLabel: `அனைத்தையும் மாற்று`,
	EditorReplaceLabel: `மாற்றவும்`,
	EditorTemplateContactHint: `<p> கிடைக்கக்கூடிய தொடர்புகளைப் பயன்படுத்துதல் (ஒரு ஃபெட்சர் சொருகி தேவைப்படுகிறது) இந்த ஆவணத்தின் அனைத்து நிகழ்வுகளுக்கும் இந்த புலம் பயன்படுத்தப்படும் அல்லது எந்தவொரு இடத்திலும் அது பின்னர் குறிப்பிடப்படும். </p> <p> எனவே மின்னஞ்சல் முகவரியைத் தேர்ந்தெடுத்தால் இங்கே நீங்கள் தேர்ந்தெடுத்த தொடர்பின் மின்னஞ்சல் புலம் இந்த ஆவணத்தில் உள்ள அனைத்து நிகழ்வுகளுக்கும் பயன்படுத்தப்படும். </p>`,
	EditorTemplateContactName: `தொடர்பு`,
	EditorTemplateDateTimeCustomHint: `yy = குறுகிய ஆண்டு <br/> yyyy = நீண்ட ஆண்டு <br/> m = மாதம் (1-12) <br/> மிமீ = மாதம் (01-12) <br/> mmm = மாத சுருக்கம் (ஜன, பிப்ரவரி .. . வார்த்தைகளில் வாரத்தின் நாள் (திங்கள், செவ்வாய் ... ஞாயிறு) <br/> E = வாரத்தின் குறுகிய நாள் வார்த்தைகளில் (திங்கள், செவ்வாய் ... சூரியன்) <br/> டி - ஆர்டினல் நாள் (1 வது, 2 வது, 3 வது, 21 வது, 22, 23, 23, 31 வது, 4 வது ...) <br/> எச் = மணிநேரம்/பி.எம் (0-12) <br/> hh = am/pm (00-12) <br/ . a = am/pm மார்க்கர் <br/> p = a.m./p.m. மார்க்கர்`,
	EditorTemplateDateTimeCustomLabel: `வழக்கம்`,
	EditorTemplateDateTimeHint: `தற்போதைய தேதி மற்றும்/அல்லது நேரம் தேதிநேர வார்ப்புருக்கள் ஒட்டப்படும் போது மாற்றாக மாற்றப்படும்.`,
	EditorTemplateDateTimeName: `தேதி நேரம்`,
	EditorTemplateDynamicHint: `<p> இந்த வார்ப்புருவின் அனைத்து நிகழ்வுகளும் வழங்கப்பட்ட உரையைப் பயன்படுத்தும். </p>`,
	EditorTemplateDynamicName: `மாறும்`,
	EditorTemplateEmptyPlaceholder: `{0} காலியாக உள்ளது ...`,
	EditorTemplateStaticHint: `<p> இந்த வார்ப்புருவின் அனைத்து நிகழ்வுகளும் வழங்கப்பட்ட உரையைப் பயன்படுத்தும். </p>`,
	EditorTemplateStaticName: `நிலையான`,
	EditorTemplateTeaserText: `மேலும் விரைவில் வருகிறது!`,
	EditorWatermark: `தயவுசெய்து காத்திருங்கள் ...`,
	EditorWholeWordLabel: ` முழு சொல்`,
	EditorWrapLabel: ` சுற்றி மடக்கு`,

};