var UiStrings = {
	EditorAppendCloseLabel: `Maliza kukabiliana`,
	EditorAppendInlineModeLabel: `Wezesha block`,
	EditorAppendLineModeLabel: `Wezesha inline`,
	EditorAppendManualModeLabel: `Kubadilisha mwongozo`,
	EditorAppendNonManualModeLabel: `Kubadilisha mwongozo`,
	EditorAppendPauseLabel: `Pause append`,
	EditorAppendPostLabel: `Kugeuza kabla`,
	EditorAppendPreLabel: `Kugeuza kabla`,
	EditorAppendResumeLabel: `Anza tena`,
	EditorBgColorLabel: `Rangi ya asili`,
	EditorClearAllLabel: `Futa zote`,
	EditorClipboardFormatsLabel: `Fomati za clipboard`,
	EditorColorChooserTitle: `Rangi ya Mhariri`,
	EditorConfirmNtfTitle: `Thibitisha`,
	EditorDeleteAllButtonText: `Futa yote`,
	EditorDeleteAllTemplatesNtfText: `Je! Una uhakika unataka kufuta matumizi yote ya '{0}'?

Hii haiwezi kutekelezwa!`,
	EditorEditTemplateDetailsLabel: `Hariri maelezo`,
	EditorEditTemplateNameLabel: `Jina`,
	EditorFindLabel: `Pata`,
	EditorFontColorLabel: `Rangi ya fonti`,
	EditorFormatPaintLabel: `Rangi ya muundo`,
	EditorInSelectionLabel: ` Katika uteuzi`,
	EditorInsertImageLabel: `Ingiza picha`,
	EditorInsertLinkLabel: `Ingiza kiunga`,
	EditorInsertVideoLabel: `Ingiza video`,
	EditorLinkButtonText: `Kuokoa`,
	EditorLinkLabel: `Ingiza kiunga`,
	EditorLinkPlaceholder: `Ingiza URL`,
	EditorMatchCaseLabel: ` Kesi ya mechi`,
	EditorNewTemplateLabel: `Template mpya`,
	EditorNextTemplateLabel: `Kiolezo kinachofuata`,
	EditorPasteButtonAppendBeginLabel: `Ongeza ...`,
	EditorPasteButtonLabel: `Bandika`,
	EditorPasteButtonLabelMobile: `Nakala`,
	EditorPasteTemplateWatermark: `Ingiza maandishi ...`,
	EditorPrevTemplateLabel: `Kiolezo cha zamani`,
	EditorRegExLabel: ` Kujieleza mara kwa mara`,
	EditorReplaceAllLabel: `Badilisha yote`,
	EditorReplaceLabel: `Badilisha`,
	EditorTemplateContactHint: `<p>Kutumia anwani zinazopatikana (inahitaji programu-jalizi ya fetcher) uwanja huu utatumika kwa matukio yote ya template hii katika hati hii au kwa yoyote itarejelewa baadaye.</p><p> Kwa hivyo kwa mfano ikiwa chagua anwani ya barua pepe hapa basi uwanja wa barua pepe wa mwasiliani unayechagua utatumika kwa matukio yote katika hati hii.</p>`,
	EditorTemplateContactName: `Wasiliana`,
	EditorTemplateDateTimeCustomHint: `yy = mwaka mfupi<br/>yyyy = mwaka mrefu<br/>M = mwezi (1-12)<br/>MM = mwezi (01-12)<br/>MMM = kifupi cha mwezi (Jan, Feb ... Dec)<br/>MMMM = mwezi mrefu (Januari, Februari ... ya Desemba)<br/>D = siku (1 - 31)<br/>dd = siku (01 - 31)<br/>ddd = siku ya wiki kwa maneno (Jumatatu, Jumanne ... Jumapili ya (Jumapili)<br/>E = siku fupi ya wiki kwa maneno (Mon, Tue ... Jua)<br/>D - Siku ya kawaida (1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = saa katika am / jioni (0-12)<br/>hh = saa katika am / pm (00-12)<br/>H = saa kwa siku (0-23)<br/>HH = saa kwa siku (00-23)<br/>mm = dakika<br/>ss = ya pili<br/>SSS = milliseconds<br/>a = alama ya AM / PM<br/>p = a.m./p.m. alama`,
	EditorTemplateDateTimeCustomLabel: `Desturi`,
	EditorTemplateDateTimeHint: `Tarehe ya sasa na/au wakati itabadilishwa kwa templeti za wakati wa wakati zinapowekwa.`,
	EditorTemplateDateTimeName: `Wakati wa tarehe`,
	EditorTemplateDynamicHint: `<p>Matukio yote ya kiolezo hiki yatatumia maandishi yaliyotolewa.</p>`,
	EditorTemplateDynamicName: `Nguvu`,
	EditorTemplateEmptyPlaceholder: `{0} haina kitu ...`,
	EditorTemplateStaticHint: `<p>Matukio yote ya kiolezo hiki yatatumia maandishi yaliyotolewa.</p>`,
	EditorTemplateStaticName: `Tuli`,
	EditorTemplateTeaserText: `Zaidi inakuja hivi karibuni!`,
	EditorTt1: `Bonyeza`,
	EditorTt2: `hariri '<em> {0} </em>' ...`,
	EditorTt3: `Hariri rangi ...`,
	EditorTt4: `Ondoa '<em> {0} </em>' ...`,
	EditorTt5: `Ondoa kipengee`,
	EditorTt6: `kufuata ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Tafadhali subiri...`,
	EditorWholeWordLabel: ` Neno lote`,
	EditorWrapLabel: ` Funga pande zote`,

};