var UiStrings = {
	EditorAppendCloseLabel: `បញ្ចប់ការបន្ថែម`,
	EditorAppendInlineModeLabel: `បើកដំណើរការប្លុក`,
	EditorAppendLineModeLabel: `បើកដំណើរការក្នុងជួរ`,
	EditorAppendManualModeLabel: `បិទបើកសៀវភៅណែនាំ`,
	EditorAppendNonManualModeLabel: `បិទបើកសៀវភៅណែនាំ`,
	EditorAppendPauseLabel: `ការផ្អាកផ្អាក`,
	EditorAppendPostLabel: `បិទបើកមុន`,
	EditorAppendPreLabel: `បិទបើកមុន`,
	EditorAppendResumeLabel: `ការបន្ថែមបន្តទៀត`,
	EditorBgColorLabel: `ពណ៌ផ្ទៃខាងក្រោយ`,
	EditorClearAllLabel: `លុបចេញ​ទាំងអស់`,
	EditorClipboardFormatsLabel: `ទំរង់ឃ្លិបបក`,
	EditorConfirmNtfTitle: `បហ្ជាក់`,
	EditorDeleteAllButtonText: `លុប​ទាំងអស់`,
	EditorDeleteAllTemplatesNtfText: `តើអ្នកពិតជាចង់លុបការប្រើប្រាស់ទាំងអស់នៃ '{0}' ទេ?

នេះមិនអាចធ្វើវិញបានទេ!`,
	EditorEditTemplateDetailsLabel: `កែសម្រួលព័ត៌មានលំអិត`,
	EditorEditTemplateNameLabel: `ឈ្ផោហ`,
	EditorFindLabel: `រកឃើញ`,
	EditorFontColorLabel: `ពណ៌ពុម្ពអក្សរ`,
	EditorFormatPaintLabel: `ធ្វើទ្រង់ទ្រាយថ្នាំលាបទ្រង់ទ្រាយ`,
	EditorInSelectionLabel: ` ក្នុងការជ្រើសរើស`,
	EditorInsertImageLabel: `បញ្ចូលរូបភាព`,
	EditorInsertLinkLabel: `បញ្ចូលតំណ`,
	EditorInsertVideoLabel: `បញ្ចូលវីដេអូ`,
	EditorMatchCaseLabel: ` ករណី​ការ​ប្រកួត`,
	EditorNewTemplateLabel: `គំរូថ្មី`,
	EditorNextTemplateLabel: `គំរូបន្ទាប់`,
	EditorPasteButtonAppendBeginLabel: `បន្ថែមទៀត ...`,
	EditorPasteButtonLabel: `រេនាយោហរការ`,
	EditorPasteTemplateWatermark: `បញ្ចូលអត្ថបទបិទភ្ជាប់ ...`,
	EditorPrevTemplateLabel: `គំរូមុន`,
	EditorRegExLabel: ` កន្សោមធម្មតា`,
	EditorReplaceAllLabel: `ជំនួសទាំងអស់`,
	EditorReplaceLabel: `ដាក់លើងវិញ`,
	EditorTemplateContactHint: `<p> ការប្រើប្រាស់ទំនាក់ទំនងដែលមាន (តម្រូវឱ្យមានកម្មវិធីជំនួយការទទួលយក) វាលនេះនឹងត្រូវបានប្រើសម្រាប់គ្រប់គំរូនៃគំរូនេះនៅទូទាំងឯកសារនេះឬនៅក្នុងអ្វីដែលវានឹងត្រូវបានយោងនៅពេលក្រោយ។ </ p> <p> ប្រសិនបើជ្រើសរើសអាសយដ្ឋានអ៊ីមែល នេះនៅទីនេះវាលអ៊ីម៉ែលនៃទំនាក់ទំនងដែលអ្នកជ្រើសរើសនឹងត្រូវបានប្រើសម្រាប់វត្ថុទាំងអស់នៅក្នុងឯកសារនេះ។ </ p>`,
	EditorTemplateContactName: `ការតាក់តង`,
	EditorTemplateDateTimeCustomHint: `ybr/> ybr/> ybr/> ybryy = broma មួយឆ្នាំ <br/> m = ខែ (1-12 MM = ខែ (01-12 អក្សរកាត់ MMM = ខែ ab, ។ ខែធ្នូ) <br/> ខែ unture (មករាកុម្ភៈ ... ខែធ្នូ) <br/> D = ថ្ងៃ (3-13) <br/> DD = ថ្ងៃ (01 - 3) <br/> DDD = ថ្ងៃនៃសប្តាហ៍នៅក្នុងពាក្យ (ថ្ងៃច័ន្ទថ្ងៃអង្គារ ... ថ្ងៃអាទិត្យ) <br/> អ៊ី = ថ្ងៃខ្លីនៃសប្តាហ៍នៅក្នុងពាក្យ (ច័ន្ទ, True) <br> ទី 1 ទី 3 ទី 21 ថ្ងៃទី 22 ទី 23, ទី 4 ទី 4 ... ) <br/> H = ម៉ោងនៅ AM / PM (0-12) <br /> ម៉ោង (00-12) <br / sm (00-12) > ម៉ោង H = ម៉ោងក្នុងមួយថ្ងៃ (0-23) <br/> HH = ម៉ោងក្នុងមួយថ្ងៃ (00> MM = នាទី <br/> អេសអេស = Milliseconds = MilliseConds = A = am សញ្ញាសម្គាល់សញ្ញាសម្គាល់ <br/> ទំ = a.m.m./p.m ។ សញ្ញាសម្គាល់`,
	EditorTemplateDateTimeCustomLabel: `តមន្យេមតមលាប់`,
	EditorTemplateDateTimeHint: `កាលបរិច្ឆេទបច្ចុប្បន្ននិង / ឬពេលវេលានឹងត្រូវបានជំនួសសម្រាប់គំរូ DETETINE នៅពេលពួកគេបានបិទភ្ជាប់។`,
	EditorTemplateDateTimeName: `ពេល​ណាត់ជួប`,
	EditorTemplateDynamicHint: `<p> ការកើតឡើងទាំងអស់នៃគំរូនេះនឹងប្រើអត្ថបទដែលបានផ្តល់។ </ p>`,
	EditorTemplateDynamicName: `ដេលក្ផានមងាង`,
	EditorTemplateEmptyPlaceholder: `{0} គឺទទេ ...`,
	EditorTemplateStaticHint: `<p> ការកើតឡើងទាំងអស់នៃគំរូនេះនឹងប្រើអត្ថបទដែលបានផ្តល់។ </ p>`,
	EditorTemplateStaticName: `ដេលឋិតរមដដែល`,
	EditorTemplateTeaserText: `ចូលមកឆាប់ៗនេះ!`,
	EditorWatermark: `សូមរង់ចាំ ...`,
	EditorWholeWordLabel: ` ពាក្យទាំងមូល`,
	EditorWrapLabel: ` រុំជុំវិញ`,

};