var UiStrings = {
	EditorAppendCloseLabel: `Завършете добавянето`,
	EditorAppendInlineModeLabel: `Активиране на блок`,
	EditorAppendLineModeLabel: `Активирайте вграденото`,
	EditorAppendManualModeLabel: `Ръководство за превключване`,
	EditorAppendNonManualModeLabel: `Ръководство за превключване`,
	EditorAppendPauseLabel: `Пауза Приложение`,
	EditorAppendPostLabel: `Превключвайте преди`,
	EditorAppendPreLabel: `Превключвайте преди`,
	EditorAppendResumeLabel: `Възобновете добавката`,
	EditorBgColorLabel: `Цвят на фона`,
	EditorClearAllLabel: `Изчисти всичко`,
	EditorClipboardFormatsLabel: `Формати на клипборд`,
	EditorColorChooserTitle: `Цвят на редактора`,
	EditorConfirmNtfTitle: `Потвърдете`,
	EditorDeleteAllButtonText: `Изтриване на всички`,
	EditorDeleteAllTemplatesNtfText: `Сигурни ли сте, че искате да изтриете всички употреби на '{0}'?

Това не може да бъде отменено!`,
	EditorEditTemplateDetailsLabel: `Редактирайте подробности`,
	EditorEditTemplateNameLabel: `Име`,
	EditorFindLabel: `намирам`,
	EditorFontColorLabel: `Цвят на шрифта`,
	EditorFormatPaintLabel: `Форматиране на боя`,
	EditorInSelectionLabel: ` В подбор`,
	EditorInsertImageLabel: `Поставете изображение`,
	EditorInsertLinkLabel: `Вмъкване на връзка`,
	EditorInsertVideoLabel: `Вмъкнете видео`,
	EditorLinkButtonText: `Запазете`,
	EditorLinkLabel: `Въведете връзка`,
	EditorLinkPlaceholder: `Въведете Url`,
	EditorMatchCaseLabel: ` Случай на съвпадение`,
	EditorNewTemplateLabel: `Нов шаблон`,
	EditorNextTemplateLabel: `Следващ шаблон`,
	EditorPasteButtonAppendBeginLabel: `Добавяне ...`,
	EditorPasteButtonLabel: `Поставете`,
	EditorPasteButtonLabelMobile: `копие`,
	EditorPasteTemplateWatermark: `Въведете текст на паста ...`,
	EditorPrevTemplateLabel: `Предишен шаблон`,
	EditorRegExLabel: ` Редовно изразяване`,
	EditorReplaceAllLabel: `Заменете всички`,
	EditorReplaceLabel: `Заменете`,
	EditorTemplateContactHint: `<p>Използване на наличните контакти (изисква fetcher плъгин) това поле ще се използва за всички екземпляри на този шаблон в този документ или във всеки от тях ще бъде посочен по-късно.</p><p> Така например, ако изберете имейл адрес тук, тогава имейл полето на контакта, който сте избрали, ще се използва за всички екземпляри в този документ.</p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = кратка година<br/>гггг = дълга година<br/>M = месец (1-12)<br/>MM = месец (01-12)<br/>MMM = месечно съкращение (Jan, Feb ... Дек)<br/>MMMM = дълъг месец (януари, февруари ... декември)<br/>d = ден (1 - 31)<br/>dd = ден (01 - 31)<br/>ddd = ден от седмицата в думи (понеделник, вторник ... неделя)<br/>E = кратък ден от седмицата в думи (Mon, Tue ... Слънце)<br/>D - Реден ден (1-ви, 2-ри, 3-ти, 21-ви, 22-ри, 23-ти, 31-ви, 4-ти...)<br/>h = час в am/pm (0-12)<br/>hh = час в am/pm (00-12)<br/>H = час в ден (0-23)<br/>HH = час в деня (00-23)<br/>mm = минута<br/>ss = секунда<br/>SSS = милисекунди<br/>a = AM/PM маркер<br/>p = маркер a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Персонализиран`,
	EditorTemplateDateTimeHint: `Текущата дата и/или часа ще бъдат заменени с шаблони за дата, когато са поставени.`,
	EditorTemplateDateTimeName: `Време за среща`,
	EditorTemplateDynamicHint: `<p>Всички събития на този шаблон ще използват предоставения текст.</p>`,
	EditorTemplateDynamicName: `Динамичен`,
	EditorTemplateEmptyPlaceholder: `{0} е празен ...`,
	EditorTemplateStaticHint: `<p>Всички събития на този шаблон ще използват предоставения текст.</p>`,
	EditorTemplateStaticName: `Статично`,
	EditorTemplateTeaserText: `Още скоро идват скоро!`,
	EditorTt1: `Кликнете`,
	EditorTt2: `редактиране на „<em>{0}</em>“ ...`,
	EditorTt3: `редактиране на цвят...`,
	EditorTt4: `премахнете „<em>{0}</em>“ ...`,
	EditorTt5: `Премахни артикул`,
	EditorTt6: `да последвам ...`,
	EditorTt7: `отидете на „<em>{0}</em>“ ...`,
	EditorWatermark: `Моля Изчакай...`,
	EditorWholeWordLabel: ` Цяла дума`,
	EditorWrapLabel: ` Обгърне`,

};