var UiStrings = {
	EditorAppendCloseLabel: `Terminar de agregar`,
	EditorAppendInlineModeLabel: `Bloque de habilitación`,
	EditorAppendLineModeLabel: `Habilitar en línea`,
	EditorAppendManualModeLabel: `Manual de al revés`,
	EditorAppendNonManualModeLabel: `Manual de al revés`,
	EditorAppendPauseLabel: `Pausa adjuntar`,
	EditorAppendPostLabel: `Alternar antes`,
	EditorAppendPreLabel: `Alternar antes`,
	EditorAppendResumeLabel: `Reanudar la anexión`,
	EditorBgColorLabel: `Color de fondo`,
	EditorClearAllLabel: `Limpiar todo`,
	EditorClipboardFormatsLabel: `Formatos de portapalones`,
	EditorColorChooserTitle: `Color del editor`,
	EditorConfirmNtfTitle: `Confirmar`,
	EditorDeleteAllButtonText: `Eliminar todos`,
	EditorDeleteAllTemplatesNtfText: `¿Estás seguro de que quieres eliminar todos los usos de '{0}'?

¡Esto no se puede deshacer!`,
	EditorEditTemplateDetailsLabel: `Editar detalles`,
	EditorEditTemplateNameLabel: `Nombre`,
	EditorFindLabel: `Encontrar`,
	EditorFontColorLabel: `Color de fuente`,
	EditorFormatPaintLabel: `Pintura de formato`,
	EditorInSelectionLabel: ` En selección`,
	EditorInsertImageLabel: `Insertar imagen`,
	EditorInsertLinkLabel: `Insertar el link`,
	EditorInsertVideoLabel: `Insertar video`,
	EditorLinkButtonText: `Ahorrar`,
	EditorLinkLabel: `Ingrese el enlace`,
	EditorLinkPlaceholder: `Introducir URL`,
	EditorMatchCaseLabel: ` Estuche`,
	EditorNewTemplateLabel: `Nueva plantilla`,
	EditorNextTemplateLabel: `Siguiente plantilla`,
	EditorPasteButtonAppendBeginLabel: `Adjuntar...`,
	EditorPasteButtonLabel: `Pegar`,
	EditorPasteButtonLabelMobile: `Copiar`,
	EditorPasteTemplateWatermark: `Ingrese el texto de pegar ...`,
	EditorPrevTemplateLabel: `Plantilla anterior`,
	EditorRegExLabel: ` Expresión regular`,
	EditorReplaceAllLabel: `Reemplaza todo`,
	EditorReplaceLabel: `Reemplazar`,
	EditorTemplateContactHint: `<p>Usando los contactos disponibles (requiere un complemento de búsqueda), este campo se utilizará para todas las instancias de esta plantilla en este documento o en cualquiera de las que se haga referencia más adelante.</p><p> Entonces, por ejemplo, si selecciona la dirección de correo electrónico aquí, el campo de correo electrónico del contacto que seleccione se utilizará para todas las instancias de este documento.</p>`,
	EditorTemplateContactName: `Contacto`,
	EditorTemplateDateTimeCustomHint: `yy = año corto<br/>aaaa = año largo<br/>M = mes (1-12)<br/>MM = mes (01-12)<br/>MMM = abreviatura del mes (enero, febrero ... Dic)<br/>MMMM = mes largo (enero, febrero ... Diciembre)<br/>d = día (1 - 31)<br/>dd = día (01 - 31)<br/>ddd = día de la semana en palabras (lunes, martes ... Domingo)<br/>E = día corto de la semana en palabras (lunes, martes ... Sol)<br/>D - Día ordinal (1º, 2º, 3º, 21º, 22º, 23º, 31º, 4º...)<br/>h = hora en a.m./p.m. (0-12)<br/>hh = hora en AM/PM (00-12)<br/>H = hora en el día (0-23)<br/>HH = hora en el día (00-23)<br/>mm = minuto<br/>ss = segundo<br/>SSS = milisegundos<br/>a = marcador AM/PM<br/>p = marcador a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Costumbre`,
	EditorTemplateDateTimeHint: `La fecha y/o hora actuales se sustituirán por plantillas de fecha y hora cuando se pegan.`,
	EditorTemplateDateTimeName: `Fecha y hora`,
	EditorTemplateDynamicHint: `<p>Todas las apariciones de esta plantilla utilizarán el texto proporcionado.</p>`,
	EditorTemplateDynamicName: `Dinámica`,
	EditorTemplateEmptyPlaceholder: `{0} está vacío ...`,
	EditorTemplateStaticHint: `<p>Todas las apariciones de esta plantilla utilizarán el texto proporcionado.</p>`,
	EditorTemplateStaticName: `Estático`,
	EditorTemplateTeaserText: `¡Más muy pronto!`,
	EditorTt1: `Hacer clic`,
	EditorTt2: `Editar '<em> {0} </em>' ...`,
	EditorTt3: `editar color ...`,
	EditorTt4: `Eliminar '<em> {0} </em>' ...`,
	EditorTt5: `remover el artículo`,
	EditorTt6: `seguir ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Espere por favor...`,
	EditorWholeWordLabel: ` Toda palabra`,
	EditorWrapLabel: ` Envolver alrededor`,

};