var UiStrings = {
	EditorAppendCloseLabel: `დასრულების დასრულება`,
	EditorAppendInlineModeLabel: `ბლოკის ჩართვა`,
	EditorAppendLineModeLabel: `ჩართეთ inline`,
	EditorAppendManualModeLabel: `გადარიცხვის სახელმძღვანელო`,
	EditorAppendNonManualModeLabel: `გადარიცხვის სახელმძღვანელო`,
	EditorAppendPauseLabel: `პაუზის დანართი`,
	EditorAppendPostLabel: `ადრე გადარიცხვა`,
	EditorAppendPreLabel: `ადრე გადარიცხვა`,
	EditorAppendResumeLabel: `განაახლეთ დანართი`,
	EditorBgColorLabel: `Ფონის ფერი`,
	EditorClearAllLabel: `Ყველაფრის გასუფთავება`,
	EditorClipboardFormatsLabel: `ბუფერული ფორმატები`,
	EditorColorChooserTitle: `რედაქტორის ფერი`,
	EditorConfirmNtfTitle: `დადასტურება`,
	EditorDeleteAllButtonText: `წაშალეთ ყველა`,
	EditorDeleteAllTemplatesNtfText: `დარწმუნებული ხართ, რომ გსურთ წაშალოთ '{0}' ყველა გამოყენება?

ეს არ შეიძლება გაუქმდეს!`,
	EditorEditTemplateDetailsLabel: `დეტალების რედაქტირება`,
	EditorEditTemplateNameLabel: `სახელი`,
	EditorFindLabel: `პოვნა`,
	EditorFontColorLabel: `Შრიფტის ფერი`,
	EditorFormatPaintLabel: `ფორმატის საღებავი`,
	EditorInSelectionLabel: ` შერჩევაში`,
	EditorInsertImageLabel: `გამოსახულების ჩასმა`,
	EditorInsertLinkLabel: `ჩადეთ ბმული`,
	EditorInsertVideoLabel: `ჩადეთ ვიდეო`,
	EditorLinkButtonText: `Გადარჩენა`,
	EditorLinkLabel: `შეიყვანეთ ბმული`,
	EditorLinkPlaceholder: `შეიყვანეთ URL`,
	EditorMatchCaseLabel: ` მატჩის საქმე`,
	EditorNewTemplateLabel: `ახალი შაბლონი`,
	EditorNextTemplateLabel: `შემდეგი შაბლონი`,
	EditorPasteButtonAppendBeginLabel: `დანართი ...`,
	EditorPasteButtonLabel: `პასი`,
	EditorPasteButtonLabelMobile: `ასლი`,
	EditorPasteTemplateWatermark: `შეიყვანეთ პასტის ტექსტი ...`,
	EditorPrevTemplateLabel: `წინა შაბლონი`,
	EditorRegExLabel: ` რეგულარული გამოხატულება`,
	EditorReplaceAllLabel: `შეცვალეთ ყველა`,
	EditorReplaceLabel: `შეცვლა`,
	EditorTemplateContactHint: `<p>ხელმისაწვდომი კონტაქტების გამოყენებით (მოითხოვს fetcher მოდულს) ეს ველი გამოყენებული იქნება ამ შაბლონის ყველა შემთხვევისთვის ამ დოკუმენტის გასწვრივ ან ნებისმიერ შემთხვევაში ის მოგვიანებით იქნება მითითებული.</p><p> მაგალითად, თუ აქ აირჩიეთ ელ.ფოსტის მისამართი, მაშინ თქვენ მიერ არჩეული კონტაქტის ელ.ფოსტის ველი გამოყენებული იქნება ამ დოკუმენტის ყველა შემთხვევისთვის.</p>`,
	EditorTemplateContactName: `კონტაქტი`,
	EditorTemplateDateTimeCustomHint: `yy = მოკლე წელი<br/>yyyy = ხანგრძლივი წელი<br/>M = თვე (1-12)<br/>MM = თვე (01-12)<br/>MMM = თვის აბრევიატურა (იან, თებ ... დეკ)<br/>MMMM = გრძელი თვე (იანვარი, თებერვალი ... დეკემბერი)<br/>დ = დღე (1 - 31)<br/>dd = დღე (01 - 31)<br/>ddd = კვირის დღე სიტყვებით (ორშაბათი, სამშაბათი ... კვირა)<br/>E = კვირის მოკლე დღე სიტყვებით (Mon, Tue ... მზე)<br/>D - რიგითი დღე (1, მე -2, მე -3, 21-ე, 22-ე, 23-ე, 31-ე, მე -4...)<br/>სთ = საათი am/pm (0-12)<br/>hh = საათი am/pm (00-12)<br/>H = საათი დღეში (0-23)<br/>HH = დღეში საათი (00-23)<br/>მმ = წუთი<br/>ss = მეორე<br/>SSS = მილიწამები<br/>ა = AM/PM მარკერი<br/>გვ = a.m./p.m. მარკერი`,
	EditorTemplateDateTimeCustomLabel: `ჩვეულება`,
	EditorTemplateDateTimeHint: `მიმდინარე თარიღი ან/და დრო შეიცვალა DateTime შაბლონებისთვის, როდესაც ისინი ჩასვით.`,
	EditorTemplateDateTimeName: `თარიღი დრო`,
	EditorTemplateDynamicHint: `<p>ამ შაბლონის ყველა მოვლენა გამოიყენებს მოცემულ ტექსტს.</p>`,
	EditorTemplateDynamicName: `დინამიური`,
	EditorTemplateEmptyPlaceholder: `{0} ცარიელია ...`,
	EditorTemplateStaticHint: `<p>ამ შაბლონის ყველა მოვლენა გამოიყენებს მოცემულ ტექსტს.</p>`,
	EditorTemplateStaticName: `სტატიკური`,
	EditorTemplateTeaserText: `Უფრო მეტი იქნება მალე!`,
	EditorTt1: `დააჭირეთ ღილაკს`,
	EditorTt2: `რედაქტირება '<em> {0} </em>' ...`,
	EditorTt3: `ფერის რედაქტირება ...`,
	EditorTt4: `ამოიღეთ '<em> {0} </em>' ...`,
	EditorTt5: `ამოიღეთ ელემენტი`,
	EditorTt6: `მიდევნება ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Გთხოვთ მოიცადოთ...`,
	EditorWholeWordLabel: ` მთელი სიტყვა`,
	EditorWrapLabel: ` გახეხეთ გარშემო`,

};