var UiStrings = {
	EditorAppendCloseLabel: `అనుబంధాన్ని పూర్తి చేయండి`,
	EditorAppendInlineModeLabel: `బ్లాక్‌ను ప్రారంభించండి`,
	EditorAppendLineModeLabel: `ఇన్లైన్‌ను ప్రారంభించండి`,
	EditorAppendManualModeLabel: `టోగుల్ మాన్యువల్`,
	EditorAppendNonManualModeLabel: `టోగుల్ మాన్యువల్`,
	EditorAppendPauseLabel: `PAUSE అనుబంధం`,
	EditorAppendPostLabel: `ముందు టోగుల్ చేయండి`,
	EditorAppendPreLabel: `ముందు టోగుల్ చేయండి`,
	EditorAppendResumeLabel: `పున ume ప్రారంభం అనుబంధం`,
	EditorBgColorLabel: `నేపథ్య రంగు`,
	EditorClearAllLabel: `అన్నీ క్లియర్ చేయండి`,
	EditorClipboardFormatsLabel: `క్లిప్‌బోర్డ్ ఫార్మాట్‌లు`,
	EditorConfirmNtfTitle: `నిర్ధారించండి`,
	EditorDeleteAllButtonText: `అన్నిటిని తొలిగించు`,
	EditorDeleteAllTemplatesNtfText: `మీరు '{0}' యొక్క అన్ని ఉపయోగాలను తొలగించాలనుకుంటున్నారా?

ఇది రద్దు చేయబడదు!`,
	EditorEditTemplateDetailsLabel: `వివరాలను సవరించండి`,
	EditorEditTemplateNameLabel: `పేరు`,
	EditorFindLabel: `కనుగొనండి`,
	EditorFontColorLabel: `ఫాంట్ కలర్`,
	EditorFormatPaintLabel: `ఫార్మాట్ పెయింట్`,
	EditorInSelectionLabel: ` ఎంపికలో`,
	EditorInsertImageLabel: `చిత్రాన్ని చొప్పించండి`,
	EditorInsertLinkLabel: `లింక్‌ను చొప్పించండి`,
	EditorInsertVideoLabel: `వీడియోను చొప్పించండి`,
	EditorMatchCaseLabel: ` మ్యాచ్ కేసు`,
	EditorNewTemplateLabel: `కొత్త టెంప్లేట్`,
	EditorNextTemplateLabel: `తదుపరి టెంప్లేట్`,
	EditorPasteButtonAppendBeginLabel: `అనుబంధం ...`,
	EditorPasteButtonLabel: `అతికించండి`,
	EditorPasteTemplateWatermark: `పేస్ట్ వచనాన్ని నమోదు చేయండి ...`,
	EditorPrevTemplateLabel: `మునుపటి టెంప్లేట్`,
	EditorRegExLabel: ` సాధారణ వ్యక్తీకరణ`,
	EditorReplaceAllLabel: `అన్నీ భర్తీ చేయండి`,
	EditorReplaceLabel: `భర్తీ`,
	EditorTemplateContactHint: `<p>లభ్యం అవుతున్న కాంటాక్ట్ లను ఉపయోగించి (గ్రహీత ప్లగిన్ అవసరం) ఈ పత్రం అంతటా ఈ టెంప్లేట్ యొక్క అన్ని సందర్భాల కొరకు ఈ ఫీల్డ్ ఉపయోగించబడుతుంది లేదా తరువాత రిఫరెన్స్ చేయబడుతుంది.</p><p> ఉదాహరణకు ఇక్కడ ఇమెయిల్ చిరునామాను ఎంచుకుంటే, మీరు ఎంచుకున్న కాంటాక్ట్ యొక్క ఇమెయిల్ ఫీల్డ్ ఈ డాక్యుమెంట్ లోని అన్ని సందర్భాలకు ఉపయోగించబడుతుంది.</p>`,
	EditorTemplateContactName: `సంప్రదించండి`,
	EditorTemplateDateTimeCustomHint: `y = స్వల్ప సంవత్సరం<br/>య్యాయ్ = దీర్ఘ సంవత్సరం<br/>మ = నెల (1-12)<br/>MM = నెల (01-12)<br/>ఎమ్ఎమ్ఎమ్ = నెల సంక్షిప్తీకరణ (జనవరి, ఫిబ్రవరి ... డిసెంబర్)<br/>MMMM = దీర్ఘ నెల (జనవరి, ఫిబ్రవరి ... డిసెంబర్)<br/>d = రోజు (1 - 31)<br/>dd = రోజు (01 - 31)<br/>ddd = వారంలోని రోజు మాటల్లో (సోమవారం, మంగళవారం ... ఆదివారం)<br/>ఇ = మాటల్లో చెప్పాలంటే వారం యొక్క చిన్న రోజు (సోమవారం, మంగళవారం ... సూర్యుడు)<br/>D - ఆర్డినల్ డే (1 వ, 2 వ, 3 వ, 21 వ, 22 వ, 23 వ, 31 వ, 4 వ ...)<br/>h = ఉదయం/pm లో గంట (0-12)<br/>hh = ఉదయం/pm లో గంట (00-12)<br/>H = రోజులో గంట (0-23)<br/>HH = రోజులో గంట (00-23)<br/>mm = నిమిషం<br/>ss = సెకండ్<br/>SSS = మిల్లీసెకన్లు<br/>a = AM/PM మార్కర్<br/>p = a.m./p.m. మార్కర్`,
	EditorTemplateDateTimeCustomLabel: `ఆచారం`,
	EditorTemplateDateTimeHint: `ప్రస్తుత తేదీ మరియు/లేదా సమయం డేట్‌టైమ్ టెంప్లేట్‌లకు అతికించబడినప్పుడు ప్రత్యామ్నాయం చేయబడుతుంది.`,
	EditorTemplateDateTimeName: `తేదీ సమయం`,
	EditorTemplateDynamicHint: `<p>ఈ టెంప్లెట్ యొక్క అన్ని సంఘటనలు అందించిన టెక్స్ట్ ను ఉపయోగిస్తాయి.</p>`,
	EditorTemplateDynamicName: `డైనమిక్`,
	EditorTemplateEmptyPlaceholder: `{0} ఖాళీగా ఉంది ...`,
	EditorTemplateStaticHint: `<p>ఈ టెంప్లెట్ యొక్క అన్ని సంఘటనలు అందించిన టెక్స్ట్ ను ఉపయోగిస్తాయి.</p>`,
	EditorTemplateStaticName: `స్టాటిక్`,
	EditorTemplateTeaserText: `త్వరలో మరిన్ని రాబోతున్నాయి!`,
	EditorWatermark: `దయచేసి వేచి ఉండండి ...`,
	EditorWholeWordLabel: ` మొత్తం పదం`,
	EditorWrapLabel: ` చుట్టూ చుట్టండి`,

};