var UiStrings = {
	EditorAppendCloseLabel: `ಸೇರಿಸುವುದನ್ನು ಮುಗಿಸಿ`,
	EditorAppendInlineModeLabel: `ಬ್ಲಾಕ್ ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ`,
	EditorAppendLineModeLabel: `ಇನ್ಲೈನ್ ​​ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ`,
	EditorAppendManualModeLabel: `ಕೈಪಿಡಿಯನ್ನು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendNonManualModeLabel: `ಕೈಪಿಡಿಯನ್ನು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendPauseLabel: `ವಿರಾಮ ಸೇರಿಸಿ`,
	EditorAppendPostLabel: `ಮೊದಲು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendPreLabel: `ಮೊದಲು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendResumeLabel: `ಪುನರಾರಂಭಿಸು`,
	EditorBgColorLabel: `ಹಿನ್ನೆಲೆ ಬಣ್ಣ`,
	EditorClearAllLabel: `ಎಲ್ಲವನ್ನೂ ತೆಗೆ`,
	EditorClipboardFormatsLabel: `ಕ್ಲಿಪ್‌ಬೋರ್ಡ್ ಸ್ವರೂಪಗಳು`,
	EditorConfirmNtfTitle: `ದೃ confirmಿಸು`,
	EditorDeleteAllButtonText: `ಎಲ್ಲಾ ಅಳಿಸಿ`,
	EditorDeleteAllTemplatesNtfText: `'{0}' ನ ಎಲ್ಲಾ ಬಳಕೆಗಳನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?

ಇದನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ!`,
	EditorEditTemplateDetailsLabel: `ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ`,
	EditorEditTemplateNameLabel: `ಹೆಸರು`,
	EditorFindLabel: `ಶೋಧನೆ`,
	EditorFontColorLabel: `ಪಂಜರ ಬಣ್ಣ`,
	EditorFormatPaintLabel: `ಸ್ವರೂಪದ ಬಣ್ಣ`,
	EditorInSelectionLabel: ` ಆಯ್ಕೆಯಲ್ಲಿ`,
	EditorInsertImageLabel: `ಚಿತ್ರವನ್ನು ಸೇರಿಸಿ`,
	EditorInsertLinkLabel: `ಲಿಂಕ್ ಸೇರಿಸಿ`,
	EditorInsertVideoLabel: `ವೀಡಿಯೊ ಸೇರಿಸಿ`,
	EditorMatchCaseLabel: ` ಪಂದ್ಯದ ಪ್ರಕರಣ`,
	EditorNewTemplateLabel: `ಹೊಸ ಟೆಂಪ್ಲೇಟ್`,
	EditorNextTemplateLabel: `ಮುಂದಿನ ಟೆಂಪ್ಲೇಟ್`,
	EditorPasteButtonAppendBeginLabel: `ಸೇರಿಸಿ ...`,
	EditorPasteButtonLabel: `ಅಂಟಿಸು`,
	EditorPasteTemplateWatermark: `ಪೇಸ್ಟ್ ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ ...`,
	EditorPrevTemplateLabel: `ಹಿಂದಿನ ಟೆಂಪ್ಲೇಟ್`,
	EditorRegExLabel: ` ನಿಯಮಿತ ಅಭಿವ್ಯಕ್ತಿ`,
	EditorReplaceAllLabel: `ಎಲ್ಲವನ್ನು ಬದಲಾಯಿಸಿ`,
	EditorReplaceLabel: `ಬದಲಾಗಿ`,
	EditorTemplateContactHint: `<p> ಲಭ್ಯವಿರುವ ಸಂಪರ್ಕಗಳನ್ನು ಬಳಸುವುದು (ಫೆಚರ್ ಪ್ಲಗಿನ್ ಅಗತ್ಯವಿದೆ) ಈ ಕ್ಷೇತ್ರವನ್ನು ಈ ಡಾಕ್ಯುಮೆಂಟ್‌ನಾದ್ಯಂತ ಈ ಟೆಂಪ್ಲೇಟ್‌ನ ಎಲ್ಲಾ ನಿದರ್ಶನಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಅಥವಾ ಯಾವುದನ್ನಾದರೂ ನಂತರ ಉಲ್ಲೇಖಿಸಲಾಗುತ್ತದೆ. </p> <p> ಆದ್ದರಿಂದ ಉದಾಹರಣೆಗೆ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ಆರಿಸಿದರೆ ಉದಾಹರಣೆಗೆ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ಆಯ್ಕೆಮಾಡಿದರೆ ಇಲ್ಲಿ ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಸಂಪರ್ಕದ ಇಮೇಲ್ ಕ್ಷೇತ್ರವನ್ನು ಈ ಡಾಕ್ಯುಮೆಂಟ್‌ನಲ್ಲಿನ ಎಲ್ಲಾ ನಿದರ್ಶನಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ. </p>`,
	EditorTemplateContactName: `ಸಂಪರ್ಕ`,
	EditorTemplateDateTimeCustomHint: `yy = ಸಣ್ಣ ವರ್ಷ <br/> yyyy = ದೀರ್ಘ ವರ್ಷ <br/> m = month (1-12) <br/> mm = ತಿಂಗಳು (01-12) <br/> mmm = ತಿಂಗಳ ಸಂಕ್ಷೇಪಣ (ಜನವರಿ, ಫೆಬ್ರವರಿ .. . ವಾರದ ದಿನ ಪದಗಳಲ್ಲಿ (ಸೋಮವಾರ, ಮಂಗಳವಾರ ... ಭಾನುವಾರ) <br/> ಇ = ವಾರದ ಸಣ್ಣ ದಿನ ಪದಗಳಲ್ಲಿ (ಸೋಮ, ಮಂಗಳ ... ಸೂರ್ಯ) <br/> ಡಿ - ಆರ್ಡಿನಲ್ ದಿನ (1, 2 ನೇ, 3 ನೇ, 21 ನೇ, 22, 23 ನೇ, 31, 4 ನೇ ...) > H = ದಿನದಲ್ಲಿ ಗಂಟೆ (0-23) <br/> HH = ದಿನದಲ್ಲಿ ಗಂಟೆ (00-23) A = AM/PM ಮಾರ್ಕರ್ <br/> p = a.m./p.m. ಗುರುತು`,
	EditorTemplateDateTimeCustomLabel: `ರೂ customಿ`,
	EditorTemplateDateTimeHint: `ಪ್ರಸ್ತುತ ದಿನಾಂಕ ಮತ್ತು/ಅಥವಾ ಸಮಯವನ್ನು ಅಂಟಿಸಿದಾಗ ಡೇಟೈಮ್ ಟೆಂಪ್ಲೆಟ್ಗಳಿಗೆ ಬದಲಿಸಲಾಗುತ್ತದೆ.`,
	EditorTemplateDateTimeName: `ದಿನಾಂಕ ಸಮಯ`,
	EditorTemplateDynamicHint: `<p> ಈ ಟೆಂಪ್ಲೇಟ್‌ನ ಎಲ್ಲಾ ಘಟನೆಗಳು ಒದಗಿಸಿದ ಪಠ್ಯವನ್ನು ಬಳಸುತ್ತವೆ. </p>`,
	EditorTemplateDynamicName: `ಭಗ್ನಾವಶೇಷಗಳ`,
	EditorTemplateEmptyPlaceholder: `{0} ಖಾಲಿಯಾಗಿದೆ ...`,
	EditorTemplateStaticHint: `<p> ಈ ಟೆಂಪ್ಲೇಟ್‌ನ ಎಲ್ಲಾ ಘಟನೆಗಳು ಒದಗಿಸಿದ ಪಠ್ಯವನ್ನು ಬಳಸುತ್ತವೆ. </p>`,
	EditorTemplateStaticName: `ಸ್ಥಿರವಾದ`,
	EditorTemplateTeaserText: `ಹೆಚ್ಚು ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!`,
	EditorWatermark: `ದಯಮಾಡಿ ನಿರೀಕ್ಷಿಸಿ...`,
	EditorWholeWordLabel: ` ಸಂಪೂರ್ಣ ಪದ`,
	EditorWrapLabel: ` ವೃತ್ತಾಕಾರವಾಗಿ ಸುತ್ತು`,

};