var UiStrings = {
	EditorAppendCloseLabel: `ପ୍ରୟୋଗ ସମାପ୍ତ କରନ୍ତୁ |`,
	EditorAppendInlineModeLabel: `ବ୍ଲକକୁ ସକ୍ଷମ କରନ୍ତୁ |`,
	EditorAppendLineModeLabel: `ଇନଲାଇନକୁ ସକ୍ଷମ କରନ୍ତୁ |`,
	EditorAppendManualModeLabel: `ମାନୁଆଲ୍ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendNonManualModeLabel: `ମାନୁଆଲ୍ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendPauseLabel: `ବିରତି ଆବେଦନ କରନ୍ତୁ |`,
	EditorAppendPostLabel: `ପୂର୍ବରୁ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendPreLabel: `ପୂର୍ବରୁ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendResumeLabel: `ଆବେଦନ ଆରମ୍ଭ କର |`,
	EditorBgColorLabel: `ପୃଷ୍ଠଭୂମି ରଙ୍ଗ`,
	EditorClearAllLabel: `ସମସ୍ତ ସଫା କରନ୍ତୁ |`,
	EditorClipboardFormatsLabel: `କ୍ଲିପବୋର୍ଡ ଫର୍ମାଟ୍ |`,
	EditorConfirmNtfTitle: `ନିଶ୍ଚିତ କର |`,
	EditorDeleteAllButtonText: `ସମସ୍ତ ବିଲୋପ କରନ୍ତୁ |`,
	EditorDeleteAllTemplatesNtfText: `ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ '{0}' ର ସମସ୍ତ ବ୍ୟବହାର ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?

ଏହାକୁ ପୂର୍ବବତ୍ କରାଯାଇପାରିବ ନାହିଁ!`,
	EditorEditTemplateDetailsLabel: `ବିବରଣୀଗୁଡିକ ସଂପାଦନ କରନ୍ତୁ |`,
	EditorEditTemplateNameLabel: `ନାମ`,
	EditorFindLabel: `ଖୋଜ |`,
	EditorFontColorLabel: `ଫଣ୍ଟ୍ ରଙ୍ଗ |`,
	EditorFormatPaintLabel: `ଫର୍ମାଟ୍ ରଙ୍ଗ`,
	EditorInSelectionLabel: ` ଚୟନ ରେ`,
	EditorInsertImageLabel: `ପ୍ରତିଛବି ସନ୍ନିବେଶ କରନ୍ତୁ |`,
	EditorInsertLinkLabel: `ଲିଙ୍କ୍ ସନ୍ନିବେଶ କରନ୍ତୁ |`,
	EditorInsertVideoLabel: `ଭିଡିଓ ସନ୍ନିବେଶ କରନ୍ତୁ |`,
	EditorMatchCaseLabel: ` ମ୍ୟାଚ୍ ମାମଲା |`,
	EditorNewTemplateLabel: `ନୂତନ ଟେମ୍ପଲେଟ୍`,
	EditorNextTemplateLabel: `ପରବର୍ତ୍ତୀ ଟେମ୍ପଲେଟ୍ |`,
	EditorPasteButtonAppendBeginLabel: `ଯୋଡ ...`,
	EditorPasteButtonLabel: `ପେଷ୍ଟ କରନ୍ତୁ |`,
	EditorPasteTemplateWatermark: `ପେଷ୍ଟ ଟେକ୍ସଟ୍ ପ୍ରବେଶ କରନ୍ତୁ ...`,
	EditorPrevTemplateLabel: `ପୂର୍ବ ଟେମ୍ପଲେଟ୍ |`,
	EditorRegExLabel: ` ନିୟମିତ ଅଭିବ୍ୟକ୍ତି |`,
	EditorReplaceAllLabel: `ସମସ୍ତଙ୍କୁ ବଦଳାନ୍ତୁ |`,
	EditorReplaceLabel: `ବଦଳାନ୍ତୁ`,
	EditorTemplateContactHint: `<p>ଉପଲବ୍ଧ ସମ୍ପର୍କଗୁଡିକ ବ୍ୟବହାର କରି (ଏକ ଫ୍ଲାଚର୍ ପ୍ଲଗଇନ୍ ଆବଶ୍ୟକ କରେ) ଏହି କ୍ଷେତ୍ର ଏହି ଦସ୍ତାବିଜରେ ଏହି ଟେମ୍ପଲେଟ୍ ର ସମସ୍ତ ଉଦାହରଣ ପାଇଁ ବ୍ୟବହୃତ ହେବ କିମ୍ବା ଏହା ପରେ ଉଲ୍ଲେଖ କରାଯିବ।</p><p> ତେଣୁ ଉଦାହରଣ ସ୍ୱରୂପ ଯଦି ଏଠାରେ ଇମେଲ୍ ଠିକଣା ଚୟନ କରନ୍ତୁ ତେବେ ଆପଣ ଚୟନ କରିଥିବା ସମ୍ପର୍କର ଇମେଲ୍ ଫିଲ୍ଡ ଏହି ଦସ୍ତାବିଜରେ ଥିବା ସମସ୍ତ ଉଦାହରଣ ପାଇଁ ବ୍ୟବହୃତ ହେବ।</p>`,
	EditorTemplateContactName: `ଯୋଗାଯୋଗ କରନ୍ତୁ |`,
	EditorTemplateDateTimeCustomHint: `y = କ୍ଷୁଦ୍ର ବର୍ଷ<br/>yyy = ଦୀର୍ଘ ବର୍ଷ<br/>M = ମାସ (1-12)<br/>MM = ମାସ (01-12)<br/>MMM = ମାସ ସଂକ୍ଷେପ (ଜାନୁଆରୀ, ଫେବୃଆରୀ ... ଡିସେମ୍ବର)<br/>MMMM = ଦୀର୍ଘ ମାସ (ଜାନୁଆରୀ, ଫେବୃଆରୀ ... ଡିସେମ୍ବର)<br/>d = ଦିନ (1 - 31)<br/>dd = ଦିନ (01 - 31)<br/>ddd = ଶବ୍ଦରେ ସପ୍ତାହର ଦିନ (ସୋମବାର, ମଙ୍ଗଳବାର ... ରବିବାର)<br/>ଇ = ଶବ୍ଦରେ ସପ୍ତାହର ସଂକ୍ଷିପ୍ତ ଦିନ (ମୋନ୍, ଟୁଇ ... ସୂର୍ଯ୍ୟ)<br/>ଡି - ଅର୍ଡିନାଲ ଦିନ (ପ୍ରଥମ, ଦ୍ବିତୀୟ, ତୃତୀୟ, ୨୧, ୨୨, ୨୩, ୩୧, ୪ର୍ଥ...)<br/>h = am/pm ରେ ଘଣ୍ଟା (0-12)<br/>hh = am/pm ରେ ଘଣ୍ଟା (00-12)<br/>H = ଦିନର ଘଣ୍ଟା (0-23)<br/>HH = ଦିନର ଘଣ୍ଟା (00-23)<br/>mm = ମିନିଟ୍<br/>ss = ଦ୍ୱିତୀୟ<br/>SSS = milliseconds<br/>a = AM/PM ମାର୍କର<br/>p = a.m./p.m. ମାର୍କର`,
	EditorTemplateDateTimeCustomLabel: `କଷ୍ଟମ୍`,
	EditorTemplateDateTimeHint: `ସାମ୍ପ୍ରତିକ ତାରିଖ ଏବଂ / କିମ୍ବା ସମୟ ପେଷ୍ଟ ହୋଇଥିବାବେଳେ ତାରିଖ ଟେମ୍ପଲେଟ୍ ପାଇଁ ବଦଳାଯିବ |`,
	EditorTemplateDateTimeName: `ତାରିଖ ସମୟ`,
	EditorTemplateDynamicHint: `<p>ଏହି ଟେମ୍ପଲେଟ୍ ର ସମସ୍ତ ଘଟଣାପ୍ରଦାନ କରାଯାଇଥିବା ଟେକ୍ସଟ୍ ବ୍ୟବହାର କରିବ।</p>`,
	EditorTemplateDynamicName: `ଗତିଶୀଳତା |`,
	EditorTemplateEmptyPlaceholder: `{0} ଖାଲି ...`,
	EditorTemplateStaticHint: `<p>ଏହି ଟେମ୍ପଲେଟ୍ ର ସମସ୍ତ ଘଟଣାପ୍ରଦାନ କରାଯାଇଥିବା ଟେକ୍ସଟ୍ ବ୍ୟବହାର କରିବ।</p>`,
	EditorTemplateStaticName: `ପରିସଂଖ୍ୟାନ`,
	EditorTemplateTeaserText: `ଶୀଘ୍ର ଅଧିକ ଦେଖାଯିବ!`,
	EditorWatermark: `ଦୟାକରି ଅପେକ୍ଷା କର...`,
	EditorWholeWordLabel: ` ପୁରା ଟର୍ମସୀ`,
	EditorWrapLabel: ` ଚାରିଆଡ଼େ ଗୁଡ଼ାଇ ରଖ |`,

};