var UiStrings = {
	EditorAppendCloseLabel: `Ավարտեք հավելվածը`,
	EditorAppendInlineModeLabel: `Միացնել բլոկը`,
	EditorAppendLineModeLabel: `Միացնել inline- ը`,
	EditorAppendManualModeLabel: `Փոփոխել ձեռնարկը`,
	EditorAppendNonManualModeLabel: `Փոփոխել ձեռնարկը`,
	EditorAppendPauseLabel: `Դադարացրեք հավելված`,
	EditorAppendPostLabel: `Անցնել նախկինում`,
	EditorAppendPreLabel: `Անցնել նախկինում`,
	EditorAppendResumeLabel: `Վերսկսել հավելվածը`,
	EditorBgColorLabel: `Ֆոնի գույնը`,
	EditorClearAllLabel: `Մաքրել բոլորը`,
	EditorClipboardFormatsLabel: `Clipboard- ի ձեւաչափերը`,
	EditorConfirmNtfTitle: `Հաստատել`,
	EditorDeleteAllButtonText: `Delete նջել բոլորը`,
	EditorDeleteAllTemplatesNtfText: `Համոզված եք, որ ցանկանում եք ջնջել «{0}» -ի բոլոր օգտագործումը:

Սա չի կարող վերացնել:`,
	EditorEditTemplateDetailsLabel: `Խմբագրել Մանրամասները`,
	EditorEditTemplateNameLabel: `Անուն`,
	EditorFindLabel: `Գտնել`,
	EditorFontColorLabel: `Տառատեսակի գույնը`,
	EditorFormatPaintLabel: `Ձեւաչափի ներկ`,
	EditorInSelectionLabel: ` Ընտրության մեջ`,
	EditorInsertImageLabel: `Տեղադրեք պատկերը`,
	EditorInsertLinkLabel: `Տեղադրեք հղումը`,
	EditorInsertVideoLabel: `Տեղադրեք տեսանյութը`,
	EditorMatchCaseLabel: ` Համընկնում`,
	EditorNewTemplateLabel: `Նոր ձեւանմուշ`,
	EditorNextTemplateLabel: `Հաջորդ ձեւանմուշը`,
	EditorPasteButtonAppendBeginLabel: `Հավելված ...`,
	EditorPasteButtonLabel: `Մածուկ`,
	EditorPasteTemplateWatermark: `Մուտքագրեք մածուկի տեքստը ...`,
	EditorPrevTemplateLabel: `Նախորդ ձեւանմուշ`,
	EditorRegExLabel: ` Պարբերաբար արտահայտում`,
	EditorReplaceAllLabel: `Փոխարինել բոլորը`,
	EditorReplaceLabel: `Փոխարինել`,
	EditorTemplateContactHint: `<p>Օգտագործելով մատչելի կոնտակտներ (պահանջվում է fetcher plugin) այս դաշտը կօգտագործվի այս մոդելի բոլոր դեպքերի համար այս փաստաթղթում կամ ցանկացած դեպքում այն կներկայացվի ավելի ուշ:</p><p> Այսպիսով, օրինակ, եթե այստեղ ընտրեք էլփոստի հասցեն, ապա ձեր ընտրած կապի էլփոստի դաշտը կօգտագործվի այս փաստաթղթում բոլոր դեպքերի համար:</p>`,
	EditorTemplateContactName: `Կապ`,
	EditorTemplateDateTimeCustomHint: `yy = կարճ տարի<br/>yyy = երկար տարի<br/>Մ = ամիս (1-12)<br/>ՄՄ = ամիս (01-12)<br/>MMM = ամսվա հապավում (Jan, Feb ... Դեկ)<br/>MMMM = երկար ամիս (հունվար, փետրվար ... դեկտեմբեր)<br/>դ = օր (1 - 31)<br/>dd = օր (01 - 31)<br/>ddd = շաբաթվա օրը բառերով (երկուշաբթի, երեքշաբթի ... Կիրակի)<br/>E = շաբաթվա կարճ օրը բառերով (Մոն, Tue ... Արեւ)<br/>Դ - Օրդինատուրայի օր (1-ին, 2-րդ, 3-րդ, 21-րդ, 22-րդ, 23-րդ, 31-րդ, 4-րդ...)<br/>h = ժամը am/pm-ում (0-12)<br/>hh = ժամը am/pm-ում (00-12)<br/>H = ժամ օրվա մեջ (0-23)<br/>HH = ժամ ցերեկային (00-23)<br/>մմ = րոպե<br/>ss = երկրորդ<br/>SSS = milliseconds<br/>ա = AM/PM մարկեր<br/>p = a.m./p.m. մարկեր`,
	EditorTemplateDateTimeCustomLabel: `Մաքսատուրք`,
	EditorTemplateDateTimeHint: `Ընթացիկ ամսաթիվը եւ (կամ) ժամանակը կփոխարինվի DateTime ձեւանմուշների համար, երբ դրանք տեղադրվեն:`,
	EditorTemplateDateTimeName: `Ամսաթիվ ժամանակ`,
	EditorTemplateDynamicHint: `<p>Այս կաղապարի բոլոր տեղի ունեցողները կօգտագործեն տրված տեքստը:</p>`,
	EditorTemplateDynamicName: `Դինամիկ`,
	EditorTemplateEmptyPlaceholder: `{0} դատարկ է ...`,
	EditorTemplateStaticHint: `<p>Այս կաղապարի բոլոր տեղի ունեցողները կօգտագործեն տրված տեքստը:</p>`,
	EditorTemplateStaticName: `Ստատիկ`,
	EditorTemplateTeaserText: `Ավելի շուտ շուտ կգա:`,
	EditorWatermark: `Խնդրում ենք սպասել...`,
	EditorWholeWordLabel: ` Ամբողջ բառը`,
	EditorWrapLabel: ` Փաթեթավորեք շուրջը`,

};