var UiStrings = {
	EditorAppendCloseLabel: `ઉમેરવાનું સમાપ્ત કરો`,
	EditorAppendInlineModeLabel: `સક્ષમ કરો અવરોધિત`,
	EditorAppendLineModeLabel: `ઇનલાઇનને સક્ષમ કરો`,
	EditorAppendManualModeLabel: `ટોકલ મેન મેન્યુઅલ`,
	EditorAppendNonManualModeLabel: `ટોકલ મેન મેન્યુઅલ`,
	EditorAppendPauseLabel: `સંલગ્ન કરવું`,
	EditorAppendPostLabel: `પહેલાં ટ gle ગલ કરવું`,
	EditorAppendPreLabel: `પહેલાં ટ gle ગલ કરવું`,
	EditorAppendResumeLabel: `ફરી શરૂ કરવું`,
	EditorBgColorLabel: `પૃષ્ઠભૂમિ રંગ`,
	EditorClearAllLabel: `બધું સાફ કરો`,
	EditorClipboardFormatsLabel: `ક્લિપબોર્ડ ફોર્મેટ્સ`,
	EditorConfirmNtfTitle: `પુષ્ટિ આપવી`,
	EditorDeleteAllButtonText: `બધું કાઢી નાંખો`,
	EditorDeleteAllTemplatesNtfText: `શું તમે ખરેખર '{0}' ના બધા ઉપયોગોને કા delete ી નાખવા માંગો છો?

આ પૂર્વવત્ કરી શકાતું નથી!`,
	EditorEditTemplateDetailsLabel: `વિગતો સંપાદિત કરો`,
	EditorEditTemplateNameLabel: `નામ`,
	EditorFindLabel: `શોધો`,
	EditorFontColorLabel: `ફ ont ન્ટ રંગ`,
	EditorFormatPaintLabel: `ફોર્મેટ`,
	EditorInSelectionLabel: ` પસંદગીની`,
	EditorInsertImageLabel: `છબી દાખલ કરો`,
	EditorInsertLinkLabel: `લિંક દાખલ કરો`,
	EditorInsertVideoLabel: `વિડિઓ દાખલ કરો`,
	EditorMatchCaseLabel: ` મેચ કેસ`,
	EditorNewTemplateLabel: `નવું નમૂના`,
	EditorNextTemplateLabel: `આગલું નમૂના`,
	EditorPasteButtonAppendBeginLabel: `જોડો ...`,
	EditorPasteButtonLabel: `આંચકો`,
	EditorPasteTemplateWatermark: `પેસ્ટ ટેક્સ્ટ દાખલ કરો ...`,
	EditorPrevTemplateLabel: `પાછલું નમૂના`,
	EditorRegExLabel: ` નિયમિત સમીકરણ`,
	EditorReplaceAllLabel: `બધા બદલો`,
	EditorReplaceLabel: `બદલવું`,
	EditorTemplateContactHint: `<p> ઉપલબ્ધ સંપર્કોનો ઉપયોગ કરીને (ફેચર પ્લગઇનની જરૂર છે) આ ક્ષેત્રનો ઉપયોગ આ દસ્તાવેજમાં આ નમૂનાના બધા દાખલાઓ માટે કરવામાં આવશે અથવા કોઈપણમાં તેનો સંદર્ભ પછીથી કરવામાં આવશે. </p> <p> તેથી ઉદાહરણ તરીકે જો ઇમેઇલ સરનામું પસંદ કરો અહીં પછી તમે પસંદ કરેલા સંપર્કના ઇમેઇલ ફીલ્ડનો ઉપયોગ આ દસ્તાવેજના બધા દાખલાઓ માટે કરવામાં આવશે. </p>`,
	EditorTemplateContactName: `સંપર્ક`,
	EditorTemplateDateTimeCustomHint: `yy = ટૂંકા વર્ષ <br/> yyyy = લાંબા વર્ષ <br/> મી = મહિનો (1-12) <br/> મીમી = મહિનો (01-12) <br/> એમએમએમ = મહિનો સંક્ષેપ (જાન્યુ, ફેબ્રુઆરી .. . ડિસે) <br/> એમએમએમએમ = લાંબા મહિનો (જાન્યુઆરી, ફેબ્રુઆરી ... ડિસેમ્બર) <br/> ડી = દિવસ (1 - 31) <br/> ડીડી = દિવસ (01 - 31) <br/> ડીડીડી = શબ્દોમાં અઠવાડિયાનો દિવસ (સોમવાર, મંગળવાર ... રવિવાર) <br/> ઇ = અઠવાડિયાના ટૂંકા દિવસ શબ્દો (સોમ, મંગળ ... સૂર્ય) <br/> ડી - ઓર્ડિનલ ડે (1 લી, 2 જી, 3 જી, 21 મી, 22, 23, 31 મી, 4 થી ...) <br/> એચ = એએમ/પીએમ (0-12) માં કલાક <br/> એચએચ = એએમ/પીએમ (00-12) <બીઆર/ > એચ = દિવસમાં કલાક (0-23) <br/> એચએચ = દિવસમાં કલાક (00-23) <br/> મીમી = મિનિટ <br/> એસએસ = સેકન્ડ <br/> એસએસએસ = મિલિસેકન્ડ્સ <br/> a = am/pm માર્કર <br/> p = a.m./p.m. નિશાનીક`,
	EditorTemplateDateTimeCustomLabel: `રિવાજ`,
	EditorTemplateDateTimeHint: `વર્તમાન તારીખ અને/અથવા સમય જ્યારે પેસ્ટ કરવામાં આવે ત્યારે ડેટટાઇમ નમૂનાઓ માટે બદલવામાં આવશે.`,
	EditorTemplateDateTimeName: `તારીખ સમય`,
	EditorTemplateDynamicHint: `<p> આ નમૂનાની બધી ઘટનાઓ પ્રદાન કરેલા ટેક્સ્ટનો ઉપયોગ કરશે. </p>`,
	EditorTemplateDynamicName: `ગતિશીલ`,
	EditorTemplateEmptyPlaceholder: `{0 empty ખાલી છે ...`,
	EditorTemplateStaticHint: `<p> આ નમૂનાની બધી ઘટનાઓ પ્રદાન કરેલા ટેક્સ્ટનો ઉપયોગ કરશે. </p>`,
	EditorTemplateStaticName: `સ્થિર`,
	EditorTemplateTeaserText: `વધુ જલ્દી આવે છે!`,
	EditorWatermark: `મહેરબાની કરી રાહ જુવો...`,
	EditorWholeWordLabel: ` સંપૂર્ણ શબ્દ`,
	EditorWrapLabel: ` આજુબાજુ વીંટાળો`,

};