var UiStrings = {
	EditorAppendCloseLabel: `Završite dodavanje`,
	EditorAppendInlineModeLabel: `Omogućiti blok`,
	EditorAppendLineModeLabel: `Omogućite inline`,
	EditorAppendManualModeLabel: `Prebacite priručnik`,
	EditorAppendNonManualModeLabel: `Prebacite priručnik`,
	EditorAppendPauseLabel: `Pauzirajte dodatak`,
	EditorAppendPostLabel: `Prebacivati ​​se prije`,
	EditorAppendPreLabel: `Prebacivati ​​se prije`,
	EditorAppendResumeLabel: `Nastavite doprinositi`,
	EditorBgColorLabel: `Boja pozadine`,
	EditorClearAllLabel: `Očistiti sve`,
	EditorClipboardFormatsLabel: `Rezultati međuspremnika`,
	EditorConfirmNtfTitle: `Potvrditi`,
	EditorDeleteAllButtonText: `Izbrisati sve`,
	EditorDeleteAllTemplatesNtfText: `Jeste li sigurni da želite izbrisati sve upotrebe '{0}'?

Ovo se ne može poništiti!`,
	EditorEditTemplateDetailsLabel: `Uređivanje detalja`,
	EditorEditTemplateNameLabel: `Ime`,
	EditorFindLabel: `Pronaći`,
	EditorFontColorLabel: `Boja fonta`,
	EditorFormatPaintLabel: `Format Boja`,
	EditorInSelectionLabel: ` U izboru`,
	EditorInsertImageLabel: `Umetni sliku`,
	EditorInsertLinkLabel: `Umetni vezu`,
	EditorInsertVideoLabel: `Umetnite video`,
	EditorMatchCaseLabel: ` Slučaj podudaranja`,
	EditorNewTemplateLabel: `Novi predložak`,
	EditorNextTemplateLabel: `Sljedeći predložak`,
	EditorPasteButtonAppendBeginLabel: `Dodavanje ...`,
	EditorPasteButtonLabel: `Zalijepiti`,
	EditorPasteTemplateWatermark: `Unesite Paste za paste ...`,
	EditorPrevTemplateLabel: `Prethodni predložak`,
	EditorRegExLabel: ` Redovni izraz`,
	EditorReplaceAllLabel: `Zamijenite sve`,
	EditorReplaceLabel: `Zamijeniti`,
	EditorTemplateContactHint: `<p> Korištenje dostupnih kontakata (zahtijeva dodatak za dohvaćanje) Ovo polje će se koristiti za sve instance ovog predloška u ovom dokumentu ili u bilo kojem slučaju, referencirat će se kasnije. </ p> <p> tako na primjer ako odaberite adresu e-pošte Evo tada će se polje e-pošte kontakt odabrati za sve slučajeve u ovom dokumentu. </ p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kratka godina <br/> yyyy = dugačka godina <br/> m = mjesec (1-12) <br/> mm = mjesec (01-12) <br/> mmm = mjesečna skraćenica (januar, februar .. . Dec) <br/> mmmm = dugi mjesec (januar, februar ... decembar) <br/> d = dan (1 - 31) <br/> dd = dan (01 - 31) <br/> ddd = Dan u sedmici riječi (ponedjeljak, utorak ... nedjelja) <br/> E = kratak dan u sedmici riječi (pon, utočište ... sunce) <br/> D - ordinalni dan (1., 2., 2., 3., 21., 22., 23., 31., 4. ...) <br/> H = sat u AM / PM (0-12) <br/> HH = sat / pm (00-12) <br / br / > H = sat u danu (0-23) <br/> HH = sat dnevno (00-23) <br/> mm = minuta <br/> ss = sekunda <br/> sss = milisekundi <br/> A = AM / PM marker <br/> p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Običaj`,
	EditorTemplateDateTimeHint: `Trenutni datum i / ili vrijeme bit će supstituirani za predloške dateTime kada su zalijepili.`,
	EditorTemplateDateTimeName: `Datum Vrijeme`,
	EditorTemplateDynamicHint: `<p> Sva pojava ovog predloška koristit će navedeni tekst. </ p>`,
	EditorTemplateDynamicName: `Dinamičan`,
	EditorTemplateEmptyPlaceholder: `{0} je prazan ...`,
	EditorTemplateStaticHint: `<p> Sva pojava ovog predloška koristit će navedeni tekst. </ p>`,
	EditorTemplateStaticName: `Statički`,
	EditorTemplateTeaserText: `Više dolazi uskoro!`,
	EditorWatermark: `Molimo pričekajte ...`,
	EditorWholeWordLabel: ` Cijela riječ`,
	EditorWrapLabel: ` Smota`,

};