var UiStrings = {
	EditorAppendCloseLabel: `Dokončiť prítomnosť`,
	EditorAppendInlineModeLabel: `Povoliť blok`,
	EditorAppendLineModeLabel: `Povoliť`,
	EditorAppendManualModeLabel: `Prepínanie`,
	EditorAppendNonManualModeLabel: `Prepínanie`,
	EditorAppendPauseLabel: `Pozastaviť`,
	EditorAppendPostLabel: `Prepnúť predtým`,
	EditorAppendPreLabel: `Prepnúť predtým`,
	EditorAppendResumeLabel: `Pokračovať`,
	EditorBgColorLabel: `Farba pozadia`,
	EditorClearAllLabel: `Zmazať všetko`,
	EditorClipboardFormatsLabel: `Formát schránky`,
	EditorColorChooserTitle: `Editor`,
	EditorConfirmNtfTitle: `Potvrdiť`,
	EditorDeleteAllButtonText: `Vymazať všetko`,
	EditorDeleteAllTemplatesNtfText: `Ste si istí, že chcete odstrániť všetky použitia '{0}'?

To nie je možné vrátiť späť!`,
	EditorEditTemplateDetailsLabel: `Úpravy detailov`,
	EditorEditTemplateNameLabel: `názov`,
	EditorFindLabel: `Nájsť`,
	EditorFontColorLabel: `Farba písma`,
	EditorFormatPaintLabel: `Farby formátu`,
	EditorInSelectionLabel: ` Výber`,
	EditorInsertImageLabel: `Vložiť obrázok`,
	EditorInsertLinkLabel: `Vložiť odkaz`,
	EditorInsertVideoLabel: `Vložiť video`,
	EditorLinkButtonText: `Uložiť`,
	EditorLinkLabel: `Zadajte odkaz`,
	EditorLinkPlaceholder: `Zadajte adresu URL`,
	EditorMatchCaseLabel: ` Zápas`,
	EditorNewTemplateLabel: `Nový šablóna`,
	EditorNextTemplateLabel: `Ďalšia šablóna`,
	EditorPasteButtonAppendBeginLabel: `Pripojiť ...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteButtonLabelMobile: `Kopírovať`,
	EditorPasteTemplateWatermark: `Zadajte text pasty ...`,
	EditorPrevTemplateLabel: `Predchádzajúca šablóna`,
	EditorRegExLabel: ` Pravidelný výraz`,
	EditorReplaceAllLabel: `Nahradiť všetko`,
	EditorReplaceLabel: `Nahradiť`,
	EditorTemplateContactHint: `<p>Pri použití dostupných kontaktov (vyžaduje sa doplnok na získanie kreditu) sa toto pole použije pre všetky inštancie tejto šablóny v tomto dokumente alebo v akomkoľvek prípade, na ktorý sa bude neskôr odkazovať.</p><p> Napríklad, ak tu vyberiete e-mailovú adresu, e-mailové pole vybraného kontaktu sa použije pre všetky inštancie v tomto dokumente.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = krátky rok<br/>rrrr = dlhý rok<br/>M = mesiac (1-12)<br/>MM = mesiac (01-12)<br/>MMM = skratka mesiaca (január, február ... decembra)<br/>MMMM = dlhý mesiac (január, február ... decembra)<br/>d = deň (1 - 31)<br/>dd = deň (01 - 31)<br/>ddd = deň v týždni slovami (pondelok, utorok ... Nedeľa)<br/>E = krátky deň v týždni slovami (Po, Ut ... Slnko)<br/>D - Radový deň (1., 2., 3., 21., 22., 23., 31., 4...)<br/>h = hodina v dopoludnia/popoludní (0-12)<br/>hh = hodina v dopoludnia/popoludní (00-12)<br/>H = hodina za deň (0-23)<br/>HH = hodina za deň (00-23)<br/>mm = minúta<br/>ss = druhá<br/>SSS = milisekundy<br/>a = značka AM/PM<br/>p = značka a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Zvyk`,
	EditorTemplateDateTimeHint: `Aktuálny dátum a/alebo čas sa nahradia šablónou datetime, keď sú vložené.`,
	EditorTemplateDateTimeName: `Dátum Čas`,
	EditorTemplateDynamicHint: `<p>Všetky výskyty tejto šablóny budú používať poskytnutý text.</p>`,
	EditorTemplateDynamicName: `Dynamika`,
	EditorTemplateEmptyPlaceholder: `{0} je prázdny ...`,
	EditorTemplateStaticHint: `<p>Všetky výskyty tejto šablóny budú používať poskytnutý text.</p>`,
	EditorTemplateStaticName: `Statický`,
	EditorTemplateTeaserText: `Viac čoskoro!`,
	EditorTt1: `Kliknutie`,
	EditorTt2: `edit '<em> {0} </em>' ...`,
	EditorTt3: `Upraviť farbu ...`,
	EditorTt4: `Odstrániť '<em> {0} </em>' ...`,
	EditorTt5: `Odstrániť položku`,
	EditorTt6: `nasledovať ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Prosím čakajte...`,
	EditorWholeWordLabel: ` Celé slovo`,
	EditorWrapLabel: ` Zabaliť sa`,

};