var UiStrings = {
	EditorAppendCloseLabel: `Terminar de agregar`,
	EditorAppendInlineModeLabel: `Bloque de habilitación`,
	EditorAppendLineModeLabel: `Habilitar en línea`,
	EditorAppendManualModeLabel: `Manual de al revés`,
	EditorAppendNonManualModeLabel: `Manual de al revés`,
	EditorAppendPauseLabel: `Pausa adjuntar`,
	EditorAppendPostLabel: `Alternar antes`,
	EditorAppendPreLabel: `Alternar antes`,
	EditorAppendResumeLabel: `Reanudar la anexión`,
	EditorBgColorLabel: `Color de fondo`,
	EditorClearAllLabel: `Limpiar todo`,
	EditorClipboardFormatsLabel: `Formatos de portapalones`,
	EditorConfirmNtfTitle: `Confirmar`,
	EditorDeleteAllButtonText: `Eliminar todos`,
	EditorDeleteAllTemplatesNtfText: `¿Estás seguro de que quieres eliminar todos los usos de '{0}'?

¡Esto no se puede deshacer!`,
	EditorEditTemplateDetailsLabel: `Editar detalles`,
	EditorEditTemplateNameLabel: `Nombre`,
	EditorFindLabel: `Encontrar`,
	EditorFontColorLabel: `Color de fuente`,
	EditorFormatPaintLabel: `Pintura de formato`,
	EditorInSelectionLabel: ` En selección`,
	EditorInsertImageLabel: `Insertar imagen`,
	EditorInsertLinkLabel: `Insertar el link`,
	EditorInsertVideoLabel: `Insertar video`,
	EditorMatchCaseLabel: ` Estuche`,
	EditorNewTemplateLabel: `Nueva plantilla`,
	EditorNextTemplateLabel: `Siguiente plantilla`,
	EditorPasteButtonAppendBeginLabel: `Adjuntar...`,
	EditorPasteButtonLabel: `Pegar`,
	EditorPasteTemplateWatermark: `Ingrese el texto de pegar ...`,
	EditorPrevTemplateLabel: `Plantilla anterior`,
	EditorRegExLabel: ` Expresión regular`,
	EditorReplaceAllLabel: `Reemplaza todo`,
	EditorReplaceLabel: `Reemplazar`,
	EditorTemplateContactHint: `<p> Uso de los contactos disponibles (requiere un complemento de Fetcher) Este campo se utilizará para todas las instancias de esta plantilla en este documento o en cualquiera de ellos se referenciará más adelante. </p> <p> Entonces, por ejemplo, si seleccione la dirección de correo electrónico Aquí, entonces el campo de correo electrónico del contacto que selecciona se utilizará para todas las instancias en este documento. </p>`,
	EditorTemplateContactName: `Contacto`,
	EditorTemplateDateTimeCustomHint: `yy = año corto <br/> yyyy = año largo <br/> m = mes (1-12) <br/> mm = mes (01-12) <br/> mmm = mes abreviatura (enero, febrero .. . Dic) <br/> mmmm = mes largo (enero, febrero ... diciembre) <br/> d = día (1 - 31) <br/> dd = día (01 - 31) <br/> ddd = Día de la semana en palabras (lunes, martes ... domingo) <br/> e = día corto de la semana en palabras (lunes, martes ... sol) <br/> d - día ordinal (1, segundo, 2º, 3er, 21, 22, 23, 31, 4º ...) <br/> H = hora en AM/PM (0-12) <br/> HH = hora en AM/PM (00-12) <Br/ > H = hora en el día (0-23) <br/> HH = hora en el día (00-23) <br/> mm = minuto <br/> ss = segundo <br/> sss = milisegundos <br/> A = AM/PM Marker <br/> P = A.M./p.m. marcador`,
	EditorTemplateDateTimeCustomLabel: `Costumbre`,
	EditorTemplateDateTimeHint: `La fecha y/o hora actuales se sustituirán por plantillas de fecha y hora cuando se pegan.`,
	EditorTemplateDateTimeName: `Fecha y hora`,
	EditorTemplateDynamicHint: `<p> Todas las ocurrencias de esta plantilla utilizarán el texto proporcionado. </p>`,
	EditorTemplateDynamicName: `Dinámica`,
	EditorTemplateEmptyPlaceholder: `{0} está vacío ...`,
	EditorTemplateStaticHint: `<p> Todas las ocurrencias de esta plantilla utilizarán el texto proporcionado. </p>`,
	EditorTemplateStaticName: `Estático`,
	EditorTemplateTeaserText: `¡Más muy pronto!`,
	EditorWatermark: `Espere por favor...`,
	EditorWholeWordLabel: ` Toda palabra`,
	EditorWrapLabel: ` Envolver alrededor`,

};