var UiStrings = {
	EditorAppendCloseLabel: `समाप्ति समाप्त करना`,
	EditorAppendInlineModeLabel: `ब्लॉक सक्षम करें`,
	EditorAppendLineModeLabel: `इनलाइन सक्षम करें`,
	EditorAppendManualModeLabel: `टॉगल मैनुअल`,
	EditorAppendNonManualModeLabel: `टॉगल मैनुअल`,
	EditorAppendPauseLabel: `विराम दें`,
	EditorAppendPostLabel: `पहले टॉगल करें`,
	EditorAppendPreLabel: `पहले टॉगल करें`,
	EditorAppendResumeLabel: `फिर से शुरू करें`,
	EditorBgColorLabel: `पृष्ठभूमि का रंग`,
	EditorClearAllLabel: `सभी साफ करें`,
	EditorClipboardFormatsLabel: `क्लिपबोर्ड प्रारूप`,
	EditorColorChooserTitle: `संपादक रंग`,
	EditorConfirmNtfTitle: `पुष्टि करना`,
	EditorDeleteAllButtonText: `सभी हटा दो`,
	EditorDeleteAllTemplatesNtfText: `क्या आप सुनिश्चित हैं कि आप '{0}' के सभी उपयोगों को हटाना चाहते हैं?

इसे असंपादित नहीं किया जा सकता है!`,
	EditorEditTemplateDetailsLabel: `विवरण संपादित करें`,
	EditorEditTemplateNameLabel: `नाम`,
	EditorFindLabel: `खोजो`,
	EditorFontColorLabel: `लिपि का रंग`,
	EditorFormatPaintLabel: `प्रारूप पेंट`,
	EditorInSelectionLabel: ` चयन में`,
	EditorInsertImageLabel: `चित्र डालें`,
	EditorInsertLinkLabel: `लिंक डालें`,
	EditorInsertVideoLabel: `वीडियो डालें`,
	EditorLinkButtonText: `बचाना`,
	EditorLinkLabel: `लिंक दर्ज करें`,
	EditorLinkPlaceholder: `यू आर एल दर्ज करो`,
	EditorMatchCaseLabel: ` मामले मिलाएं`,
	EditorNewTemplateLabel: `नया टेम्पलेट`,
	EditorNextTemplateLabel: `अगला टेम्पलेट`,
	EditorPasteButtonAppendBeginLabel: `जोड़ें ...`,
	EditorPasteButtonLabel: `पेस्ट करें`,
	EditorPasteTemplateWatermark: `पेस्ट टेक्स्ट दर्ज करें ...`,
	EditorPrevTemplateLabel: `पिछला टेम्पलेट`,
	EditorRegExLabel: ` नियमित अभिव्यक्ति`,
	EditorReplaceAllLabel: `सबको बदली करें`,
	EditorReplaceLabel: `प्रतिस्थापित करें`,
	EditorTemplateContactHint: `<p>उपलब्ध संपर्कों का उपयोग करना (एक फ़ेचर प्लगइन की आवश्यकता है) इस फ़ील्ड का उपयोग इस दस्तावेज़ में इस टेम्पलेट के सभी आवृत्तियों के लिए किया जाएगा या किसी भी में इसे बाद में संदर्भित किया जाएगा।</p><p> इसलिए उदाहरण के लिए यदि यहां ईमेल पते का चयन करें तो आपके द्वारा चुने गए संपर्क की ईमेल फ़ील्ड का उपयोग इस दस्तावेज़ में सभी उदाहरणों के लिए किया जाएगा।</p>`,
	EditorTemplateContactName: `संपर्क`,
	EditorTemplateDateTimeCustomHint: `yy = लघु वर्ष<br/>yyyy = लंबा वर्ष<br/>M = महीना (1-12)<br/>MM = महीना (01-12)<br/>एमएमएम = महीने का संक्षिप्त नाम (जनवरी, फरवरी ... दिसंबर)<br/>एमएमएमएम = लंबा महीना (जनवरी, फरवरी ... दिसंबर)<br/>d = दिन (1 - 31)<br/>डीडी = दिन (01 - 31)<br/>ddd = शब्दों में सप्ताह का दिन (सोमवार, मंगलवार ... रविवार)<br/>E = शब्दों में सप्ताह का छोटा दिन (सोम, मंगल... रवि)<br/>D - साधारण दिन (पहला, दूसरा, तीसरा, 21वां, 22वां, 23वां, 31वां, चौथा ...)<br/>h = am/pm में घंटा (0-12)<br/>hh = am/pm में घंटा (00-12)<br/>H = दिन में घंटा (0-23)<br/>HH = दिन में घंटा (00-23)<br/>मिमी = मिनट<br/>ss = सेकंड<br/>एसएसएस = मिलीसेकंड<br/>a = AM/PM मार्कर<br/>पी = एएम/पीएम मार्कर`,
	EditorTemplateDateTimeCustomLabel: `रिवाज़`,
	EditorTemplateDateTimeHint: `वर्तमान तिथि और/या समय को डेटाइम टेम्प्लेट के लिए प्रतिस्थापित किया जाएगा जब वे चिपकाए जाते हैं।`,
	EditorTemplateDateTimeName: `दिनांक समय`,
	EditorTemplateDynamicHint: `<p>इस टेम्पलेट की सभी घटनाएं प्रदान किए गए पाठ का उपयोग करेंगी।</p>`,
	EditorTemplateDynamicName: `गतिशील`,
	EditorTemplateEmptyPlaceholder: `{0} खाली है ...`,
	EditorTemplateStaticHint: `<p>इस टेम्पलेट की सभी घटनाएं प्रदान किए गए पाठ का उपयोग करेंगी।</p>`,
	EditorTemplateStaticName: `स्थिर`,
	EditorTemplateTeaserText: `अधिक जल्द ही आ रहा!`,
	EditorTt1: `क्लिक`,
	EditorTt2: `संपादित करें '<em> {0} </em>' ...`,
	EditorTt3: `रंग संपादित करें ...`,
	EditorTt4: `निकालें '<em> {0} </em>' ...`,
	EditorTt5: `वस्तु निकालें`,
	EditorTt6: `अनुकरण करना ...`,
	EditorTt7: `गोटो '<em> {0} </em>' ...`,
	EditorWatermark: `कृपया प्रतीक्षा करें...`,
	EditorWholeWordLabel: ` पूरा शब्द`,
	EditorWrapLabel: ` चारों ओर लपेट दो`,

};