var UiStrings = {
	EditorAppendCloseLabel: `समाप्ति समाप्त करना`,
	EditorAppendInlineModeLabel: `ब्लॉक सक्षम करें`,
	EditorAppendLineModeLabel: `इनलाइन सक्षम करें`,
	EditorAppendManualModeLabel: `टॉगल मैनुअल`,
	EditorAppendNonManualModeLabel: `टॉगल मैनुअल`,
	EditorAppendPauseLabel: `विराम दें`,
	EditorAppendPostLabel: `पहले टॉगल करें`,
	EditorAppendPreLabel: `पहले टॉगल करें`,
	EditorAppendResumeLabel: `फिर से शुरू करें`,
	EditorBgColorLabel: `पृष्ठभूमि का रंग`,
	EditorClearAllLabel: `सभी साफ करें`,
	EditorClipboardFormatsLabel: `क्लिपबोर्ड प्रारूप`,
	EditorConfirmNtfTitle: `पुष्टि करना`,
	EditorDeleteAllButtonText: `सभी हटा दो`,
	EditorDeleteAllTemplatesNtfText: `क्या आप सुनिश्चित हैं कि आप '{0}' के सभी उपयोगों को हटाना चाहते हैं?

इसे असंपादित नहीं किया जा सकता है!`,
	EditorEditTemplateDetailsLabel: `विवरण संपादित करें`,
	EditorEditTemplateNameLabel: `नाम`,
	EditorFindLabel: `खोजो`,
	EditorFontColorLabel: `लिपि का रंग`,
	EditorFormatPaintLabel: `प्रारूप पेंट`,
	EditorInSelectionLabel: ` चयन में`,
	EditorInsertImageLabel: `चित्र डालें`,
	EditorInsertLinkLabel: `लिंक डालें`,
	EditorInsertVideoLabel: `वीडियो डालें`,
	EditorMatchCaseLabel: ` मामले मिलाएं`,
	EditorNewTemplateLabel: `नया टेम्पलेट`,
	EditorNextTemplateLabel: `अगला टेम्पलेट`,
	EditorPasteButtonAppendBeginLabel: `जोड़ें ...`,
	EditorPasteButtonLabel: `पेस्ट करें`,
	EditorPasteTemplateWatermark: `पेस्ट टेक्स्ट दर्ज करें ...`,
	EditorPrevTemplateLabel: `पिछला टेम्पलेट`,
	EditorRegExLabel: ` नियमित अभिव्यक्ति`,
	EditorReplaceAllLabel: `सबको बदली करें`,
	EditorReplaceLabel: `प्रतिस्थापित करें`,
	EditorTemplateContactHint: `<p> उपलब्ध संपर्कों का उपयोग करना (एक फ़ीचर प्लगइन की आवश्यकता है) इस फ़ील्ड का उपयोग इस दस्तावेज़ में इस टेम्पलेट के सभी उदाहरणों के लिए किया जाएगा या किसी भी समय बाद में संदर्भित किया जाएगा। </p> <p> तो उदाहरण के लिए यदि ईमेल पते का चयन करें तो यहाँ तब आपके द्वारा चुने गए संपर्क का ईमेल फ़ील्ड इस दस्तावेज़ में सभी उदाहरणों के लिए उपयोग किया जाएगा। </p>`,
	EditorTemplateContactName: `संपर्क`,
	EditorTemplateDateTimeCustomHint: `yy = लघु वर्ष <br/> yyyy = लंबा वर्ष <br/> m = माह (1-12) <br/> mm = माह (01-12) <br/> mmm = महीने का संक्षिप्त नाम (जन, फरवरी ।। । दिसंबर) <br/> mmmm = लंबा महीना (जनवरी, फरवरी ... दिसंबर) <br/> d = दिन (1 - 31) <br/> dd = day (01 - 31) <br/> ddd = शब्द में सप्ताह का दिन (सोमवार, मंगलवार ... रविवार) <br/> e = शब्द में सप्ताह का छोटा दिन (सोम, टीयू ... सूर्य) <br/> डी - ऑर्डिनल डे (1, 2, 2, 3, 21 वीं, 22 वीं, 23 वीं, 31 वीं, चौथी ...) <br/> एच = घंटे में एएम/पीएम (0-12) <br/> एचएच = घंटे में एएम/पीएम (00-12) <ब्र/ > एच = दिन में घंटे (0-23) <br/> एचएच = दिन में दिन (00-23) <br/> मिमी = मिनट <br/> एसएस = दूसरा <br/> एसएसएस = मिलीसेकंड <br/> a = am/pm मार्कर <br/> p = a.m./p.m। निशान`,
	EditorTemplateDateTimeCustomLabel: `रिवाज़`,
	EditorTemplateDateTimeHint: `वर्तमान तिथि और/या समय को डेटाइम टेम्प्लेट के लिए प्रतिस्थापित किया जाएगा जब वे चिपकाए जाते हैं।`,
	EditorTemplateDateTimeName: `दिनांक समय`,
	EditorTemplateDynamicHint: `<p> इस टेम्पलेट के सभी घटनाएं प्रदान किए गए पाठ का उपयोग करेंगे। </p>`,
	EditorTemplateDynamicName: `गतिशील`,
	EditorTemplateEmptyPlaceholder: `{0} खाली है ...`,
	EditorTemplateStaticHint: `<p> इस टेम्पलेट के सभी घटनाएं प्रदान किए गए पाठ का उपयोग करेंगे। </p>`,
	EditorTemplateStaticName: `स्थिर`,
	EditorTemplateTeaserText: `अधिक जल्द ही आ रहा!`,
	EditorWatermark: `कृपया प्रतीक्षा करें...`,
	EditorWholeWordLabel: ` पूरा शब्द`,
	EditorWrapLabel: ` चारों ओर लपेट दो`,

};