var UiStrings = {
	EditorAppendCloseLabel: `ສໍາເລັດການເພີ່ມເຕີມ`,
	EditorAppendInlineModeLabel: `ເປີດໃຊ້ງານ`,
	EditorAppendLineModeLabel: `ເປີດສາຍ`,
	EditorAppendManualModeLabel: `ຄູ່ມືສະຫຼັບ`,
	EditorAppendNonManualModeLabel: `ຄູ່ມືສະຫຼັບ`,
	EditorAppendPauseLabel: `ຢຸດຊົ່ວຄາວ`,
	EditorAppendPostLabel: `ສະຫຼັບກ່ອນ`,
	EditorAppendPreLabel: `ສະຫຼັບກ່ອນ`,
	EditorAppendResumeLabel: `ຊິ້ງຂໍ້ມູນ`,
	EditorBgColorLabel: `ສີພື້ນຫລັງ`,
	EditorClearAllLabel: `ລ້າງທັງຫມົດ`,
	EditorClipboardFormatsLabel: `ຮູບແບບ clipboard`,
	EditorColorChooserTitle: `ສີຂອງບັນນາທິການ`,
	EditorConfirmNtfTitle: `ຢືນຢັນ`,
	EditorDeleteAllButtonText: `ລົບ​ທັງ​ຫມົດ`,
	EditorDeleteAllTemplatesNtfText: `ທ່ານແນ່ໃຈບໍ່ວ່າທ່ານຕ້ອງການລຶບການນໍາໃຊ້ທັງຫມົດຂອງ '{0}'?

ນີ້​ບໍ່​ສາ​ມາດ​ຍົກ​ເລີກ​ໄດ້!`,
	EditorEditTemplateDetailsLabel: `ແກ້ໄຂລາຍລະອຽດ`,
	EditorEditTemplateNameLabel: `ຊື່`,
	EditorFindLabel: `ຊອກ`,
	EditorFontColorLabel: `ສີຕົວອັກສອນ`,
	EditorFormatPaintLabel: `ສີຮູບແບບ`,
	EditorInSelectionLabel: ` ໃນການເລືອກ`,
	EditorInsertImageLabel: `ໃສ່ຮູບ`,
	EditorInsertLinkLabel: `ໃສ່ລິ້ງ`,
	EditorInsertVideoLabel: `ໃສ່ວິດີໂອ`,
	EditorLinkButtonText: `ປະຢັດ`,
	EditorLinkLabel: `ໃສ່ລິ້ງ`,
	EditorLinkPlaceholder: `ໃສ່ URL`,
	EditorMatchCaseLabel: ` ເປົ້າກໍລະນີແຂ່ງຂັນ`,
	EditorNewTemplateLabel: `ແມ່ແບບໃຫມ່`,
	EditorNextTemplateLabel: `ແມ່ແບບຕໍ່ໄປ`,
	EditorPasteButtonAppendBeginLabel: `ເພີ່ມເຕີມ ...`,
	EditorPasteButtonLabel: `ວາງໄວ້`,
	EditorPasteTemplateWatermark: `ໃສ່ຂໍ້ຄວາມທີ່ວາງໄວ້ ...`,
	EditorPrevTemplateLabel: `ແມ່ແບບຜ່ານມາ`,
	EditorRegExLabel: ` ການສະແດງອອກເປັນປະຈໍາ`,
	EditorReplaceAllLabel: `ທົດແທນທັງຫມົດ`,
	EditorReplaceLabel: `ປ່ຽນແທນ`,
	EditorTemplateContactHint: `<p>ການນໍາໃຊ້ການຕິດຕໍ່ທີ່ມີຢູ່ (ຮຽກຮ້ອງplugin fetcher) ທົ່ງນານີ້ຈະຖືກນໍາໃຊ້ສໍາລັບທຸກກໍລະນີຂອງtemplate ນີ້ໃນເອກະສານນີ້ຫຼືໃນສິ່ງໃດກໍຕາມທີ່ມັນຈະໄດ້ຮັບການອ້າງອີງໃນເວລາຕໍ່ມາ.</p><p> ດັ່ງນັ້ນຕົວຢ່າງຖ້າເລືອກທີ່ຢູ່ອີເມວທີ່ນີ້ແລ້ວເຂດອີເມວຂອງຜູ້ຕິດຕໍ່ທີ່ທ່ານເລືອກຈະຖືກນໍາໃຊ້ສໍາລັບທຸກກໍລະນີໃນເອກະສານນີ້.</p>`,
	EditorTemplateContactName: `ຕິດຕໍ່`,
	EditorTemplateDateTimeCustomHint: `yy = ປີສັ້ນ<br/>yyyy = ປີຍາວ<br/>M = ເດືອນ (1-12)<br/>MM = ເດືອນ (01-12)<br/>MMM = ເດືອນ abbreviation (Jan, Feb ... Dec)<br/>MMMM = ເດືອນຍາວ (ມັງກອນ, ກຸມພາ ... ເດືອນທັນວາ)<br/>d = ມື້ (1 - 31)<br/>dd = ມື້ (01 - 31)<br/>ddd = ມື້ຂອງອາທິດໃນຄໍາສັບ (ວັນຈັນ, ອັງຄານ ... ວັນອາທິດ)<br/>E = ມື້ສັ້ນຂອງອາທິດເປັນຄໍາສັບ (Mon, Tue ... ດວງອາທິດ)<br/>D - ວັນພິທີການ (ທີ 1, 2nd, 3rd, 21st, 22nd, 23rd, 31st, 4th...)<br/>h = ຊົ່ວໂມງໃນ am/pm (0-12)<br/>hh = ຊົ່ວໂມງໃນ am/pm (00-12)<br/>H = ຊົ່ວໂມງໃນມື້ (0-23)<br/>HH = ຊົ່ວໂມງໃນມື້ (00-23)<br/>mm = ນາທີ<br/>ss = ທີສອງ<br/>SSS = milliseconds<br/>a = ເຄື່ອງຫມາຍ AM/PM<br/>p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `ປະເພນີ`,
	EditorTemplateDateTimeHint: `ວັນທີປະຈຸບັນແລະ / ຫຼືເວລາຈະຖືກທົດແທນສໍາລັບແມ່ແບບທີ່ກໍານົດໃນເວລາທີ່ພວກມັນຖືກວາງໄວ້.`,
	EditorTemplateDateTimeName: `ເວລາວັນທີ`,
	EditorTemplateDynamicHint: `<p>ທັງຫມົດທີ່ເກີດຂຶ້ນຂອງtemplate ນີ້ຈະໃຊ້ຂໍ້ຄວາມທີ່ສະຫນອງໃຫ້.</p>`,
	EditorTemplateDynamicName: `Dynamic`,
	EditorTemplateEmptyPlaceholder: `{0} ແມ່ນຫວ່າງເປົ່າ ...`,
	EditorTemplateStaticHint: `<p>ທັງຫມົດທີ່ເກີດຂຶ້ນຂອງtemplate ນີ້ຈະໃຊ້ຂໍ້ຄວາມທີ່ສະຫນອງໃຫ້.</p>`,
	EditorTemplateStaticName: `ສະຖິດ`,
	EditorTemplateTeaserText: `ອີກໃນໄວໆນີ້ຈະມາເຖິງໃນໄວໆນີ້!`,
	EditorTt1: `ກົດ`,
	EditorTt2: `ແກ້ໄຂ '_ em> {0} </ em>' ...`,
	EditorTt3: `ດັດແກ້ສີ ...`,
	EditorTt4: `ເອົາ '<em> {0} </ em>' ...`,
	EditorTt5: `ເອົາລາຍການ`,
	EditorTt6: `ຕິດ​ຕາມ ...`,
	EditorTt7: `GOTO '<em> {0} </ em>' ...`,
	EditorWatermark: `ກະ​ລຸ​ນາ​ລໍ​ຖ້າ...`,
	EditorWholeWordLabel: ` ຕາທັງຫມົດ`,
	EditorWrapLabel: ` ຫໍ່ປະມານ`,

};