var UiStrings = {
	EditorAppendCloseLabel: `ውድእ ውድእ 2019።`,
	EditorAppendInlineModeLabel: `ብሎክ ኣንቅሕ .`,
	EditorAppendLineModeLabel: `ኣብ መስመር ምኽኣል`,
	EditorAppendManualModeLabel: `ቶግለ ማንዋል`,
	EditorAppendNonManualModeLabel: `ቶግለ ማንዋል`,
	EditorAppendPauseLabel: `ኣብ መመላእታ ዕረፍቲ 2019`,
	EditorAppendPostLabel: `ቅድሚ ሕጂ ቶግለ`,
	EditorAppendPreLabel: `ቅድሚ ሕጂ ቶግለ`,
	EditorAppendResumeLabel: `ሪዝዩም ኣብ ምውሳኽ`,
	EditorBgColorLabel: `ድሕረ ባይታ ሕብሪ`,
	EditorClearAllLabel: `ኩሉ ኣጽርዮ`,
	EditorClipboardFormatsLabel: `ቅርጺ ቅንጥብጣብ ሰሌዳ`,
	EditorConfirmNtfTitle: `ኣረጋግፅ`,
	EditorDeleteAllButtonText: `ንኹሉ ምድምሳስ .`,
	EditorDeleteAllTemplatesNtfText: `ኩሉ ኣጠቓቕማ '{0}' ክትድምስሶ ከም እትደሊ ርግጸኛ ዲኻ?

እዚ ኽትከውን ኣይክእልን እዩ!`,
	EditorEditTemplateDetailsLabel: `ዝርዝር ኣርትዕ`,
	EditorEditTemplateNameLabel: `ሽም`,
	EditorFindLabel: `ርኸብ`,
	EditorFontColorLabel: `ቅርጺ ፊደላት`,
	EditorFormatPaintLabel: `ፎርማት ቀለም .`,
	EditorInSelectionLabel: ` ኣብ ምምራጽ`,
	EditorInsertImageLabel: `ምስሊ ምእታው`,
	EditorInsertLinkLabel: `ናይ ምእታው መላግቦ`,
	EditorInsertVideoLabel: `ቪድዮ ምእታው`,
	EditorMatchCaseLabel: ` ምትእስሳር ኬዝ`,
	EditorNewTemplateLabel: `ሓድሽ ቅጥዒ`,
	EditorNextTemplateLabel: `ዝቕጽል ቅጥዒ`,
	EditorPasteButtonAppendBeginLabel: `ምውሳኽ...`,
	EditorPasteButtonLabel: `ምልጣፍ .`,
	EditorPasteTemplateWatermark: `ጽሑፍ ምልጣፍ ኣእቱ...`,
	EditorPrevTemplateLabel: `ቅድሚ ሕጂ ዝነበረ ቅጥዒ`,
	EditorRegExLabel: ` ስሩዕ መግለጺ`,
	EditorReplaceAllLabel: `ንኹሉ ምትካእ .`,
	EditorReplaceLabel: `ምትካእ`,
	EditorTemplateContactHint: `<p>ምብጻሕ ዝርከቡ ርክባት (Fetcher Plugin Requires Requires) እዚ ዓውዲ እዚ ንኹሉ ኣጋጣሚታት ናይዚ ቅጥዒ ኣብ መላእ እዚ ሰነድ ወይ ኣብ ዝኾነ ኣብ ዝኾነ ይኹን ኣብ ድሒሩ ዝውከስ ክኸውን እዩ።</p><p> ስለዚ ንኣብነት ኢመይል ኣድራሻ ምረጽ ኣብዚ ድሕሪኡ እቲ ዝመረጽካዮ ናይ ኢመይል ቦታ ንኹሉ ኣጋጣሚታት ኣብዚ ሰነድ ክውዕል እዩ።</p>`,
	EditorTemplateContactName: `መርከቢ`,
	EditorTemplateDateTimeCustomHint: `YY = ሓጺር ዓመት<br/>yyyy = ነዊሕ ዓመት<br/>m = ወርሒ (1-12)<br/>mm = ወርሒ (01-12)<br/>MMM = ወርሒ ኣሕጽሮተ ቃል (Jan, Feb .. .cc)<br/>MMMMM = ነዊሕ ወርሒ (ጥሪ፣ ለካቲት ... ታሕሳስ)<br/>d = መዓልቲ (1 - 31)<br/>dd = መዓልቲ (01 - 31)<br/>ddd = መዓልቲ ናይ ሰሙን ብቓላት (ሰኑይ፣ ሰሉስ ... ሰንበት)<br/>e = ሓጺር መዓልቲ ናይ ሰሙን ብቓላት (ሰኑይ፣ ሰሉስ ... ጸሓይ)<br/>d - ስርዓታዊ መዓልቲ (1ይ፣ 2ይ፣ 3ይ፣ 21፣ 22፣ 23ይ፣ 31፣ 4ይ...)<br/>h = ሰዓት ኣብ AM/PM (0-12)<br/>hh = ሰዓት ኣብ AM/PM (00-12)<br/ >H = ሰዓት ኣብ መዓልቲ (0-23)<br/>hh = ሰዓት ኣብ መዓልቲ (00-23)<br/>mm = ደቒቕ<br/>ss = ካልኣይ<br/>sss = ሚሊሰከንድ<br/> A = AM/PM ምልክት<br/>p = a.m./p.m. ማርከር`,
	EditorTemplateDateTimeCustomLabel: `ቅቡል ልምዲ`,
	EditorTemplateDateTimeHint: `እቲ ናይ ሕጂ ዕለትን/ወይ ግዜን ምስ ዝለጠፉ ንናይ ዕለት ግዜ ቅጥዒታት ክትክእ እዩ።`,
	EditorTemplateDateTimeName: `ናይ ዕለት ሰዓት`,
	EditorTemplateDynamicHint: `<P>ኩሉ ተርእዮታት ናይዚ ቅጥዒ ነቲ ዝቐረበ ጽሑፍ ክጥቀመሉ እዩ።</p>`,
	EditorTemplateDynamicName: `ዳይናሚክ`,
	EditorTemplateEmptyPlaceholder: `{0} ባዶ እዩ...`,
	EditorTemplateStaticHint: `<P>ኩሉ ተርእዮታት ናይዚ ቅጥዒ ነቲ ዝቐረበ ጽሑፍ ክጥቀመሉ እዩ።</p>`,
	EditorTemplateStaticName: `ስታቲክ .`,
	EditorTemplateTeaserText: `ተወሳኺ ኣብ ቀረባ እዋን!`,
	EditorWatermark: `በጃኹም ተጸበዩ...`,
	EditorWholeWordLabel: ` ምሉእ ቃል`,
	EditorWrapLabel: ` ኣብ ዙርያኡ ምጥቕላል .`,

};