var UiStrings = {
	EditorAppendCloseLabel: `Fullfør å legge til`,
	EditorAppendInlineModeLabel: `Aktiver blokkering`,
	EditorAppendLineModeLabel: `Aktiver inline`,
	EditorAppendManualModeLabel: `Vekslehåndbok`,
	EditorAppendNonManualModeLabel: `Vekslehåndbok`,
	EditorAppendPauseLabel: `Pause vedlegg`,
	EditorAppendPostLabel: `Veksle før`,
	EditorAppendPreLabel: `Veksle før`,
	EditorAppendResumeLabel: `Fortsett vedlegg`,
	EditorBgColorLabel: `Bakgrunnsfarge`,
	EditorClearAllLabel: `Rydd alt`,
	EditorClipboardFormatsLabel: `Utklippstavleformater`,
	EditorConfirmNtfTitle: `Bekrefte`,
	EditorDeleteAllButtonText: `Slette alle`,
	EditorDeleteAllTemplatesNtfText: `Er du sikker på at du vil slette alle bruksområder av '{0}'?

Dette kan ikke angres!`,
	EditorEditTemplateDetailsLabel: `Rediger detaljer`,
	EditorEditTemplateNameLabel: `Navn`,
	EditorFindLabel: `Finne`,
	EditorFontColorLabel: `Skriftfarge`,
	EditorFormatPaintLabel: `Formatmaling`,
	EditorInSelectionLabel: ` I utvalg`,
	EditorInsertImageLabel: `Sett inn bilde`,
	EditorInsertLinkLabel: `Sett inn lenken`,
	EditorInsertVideoLabel: `Sett inn video`,
	EditorMatchCaseLabel: ` Match -sak`,
	EditorNewTemplateLabel: `Ny mal`,
	EditorNextTemplateLabel: `Neste mal`,
	EditorPasteButtonAppendBeginLabel: `Legg til ...`,
	EditorPasteButtonLabel: `Lim inn`,
	EditorPasteTemplateWatermark: `Skriv inn limtekst ...`,
	EditorPrevTemplateLabel: `Forrige mal`,
	EditorRegExLabel: ` Vanlig uttrykk`,
	EditorReplaceAllLabel: `Erstatt alle`,
	EditorReplaceLabel: `Erstatte`,
	EditorTemplateContactHint: `<p> Bruke tilgjengelige kontakter (krever en fetcher -plugin) Dette feltet vil bli brukt i alle forekomster av denne malen på tvers av dette dokumentet eller i hvilken som helst det vil bli referert til senere. </p> <p> Så for eksempel hvis velg e -postadresse Her vil e -postfeltet til kontakten du velger bli brukt i alle tilfeller i dette dokumentet. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kort år <br/> yyyy = langt år <br/> m = måned (1-12) <br/> mm = måned (01-12) <br/> mmm = måned Forkortelse (jan, februar .. . Desember) <br/> mmmm = lang måned (januar, februar ... desember) <br/> d = dag (1 - 31) <br/> dd = dag (01 - 31) <br/> DDD = Ukens dag med ord (mandag, tirsdag ... søndag) <br/> e = kort ukedag i ord (man, tirs ... sol) <br/> D - Ordinal dag (1., 2., 3., 21., 22., 23., 31., 4. ...) <br/> h = time i AM/PM (0-12) <br/> HH = time i AM/PM (00-12) <Br/ > H = time i dagen (0-23) <br/> hh = time på dagen (00-23) <br/> mm = minutt <br/> ss = sekund <br/> sss = millisekunder <br/> a = am/pm markør <br/> p = A.M./P.M. markør`,
	EditorTemplateDateTimeCustomLabel: `Tilpasset`,
	EditorTemplateDateTimeHint: `Gjeldende dato og/eller tid vil bli erstattet av datetime -maler når de limes inn.`,
	EditorTemplateDateTimeName: `Dato tid`,
	EditorTemplateDynamicHint: `<p> Alle forekomster av denne malen vil bruke den medfølgende teksten. </p>`,
	EditorTemplateDynamicName: `Dynamisk`,
	EditorTemplateEmptyPlaceholder: `{0} er tom ...`,
	EditorTemplateStaticHint: `<p> Alle forekomster av denne malen vil bruke den medfølgende teksten. </p>`,
	EditorTemplateStaticName: `Statisk`,
	EditorTemplateTeaserText: `Mer kommer snart!`,
	EditorWatermark: `Vennligst vent...`,
	EditorWholeWordLabel: ` Hele verden`,
	EditorWrapLabel: ` Pakk rundt`,

};