var UiStrings = {
	EditorAppendCloseLabel: `Befejezi a mellékletet`,
	EditorAppendInlineModeLabel: `Engedélyezze a blokkot`,
	EditorAppendLineModeLabel: `Engedélyezze az inline -t`,
	EditorAppendManualModeLabel: `Váltókézés`,
	EditorAppendNonManualModeLabel: `Váltókézés`,
	EditorAppendPauseLabel: `Szüneteltesse a mellékletet`,
	EditorAppendPostLabel: `Váltás előtt`,
	EditorAppendPreLabel: `Váltás előtt`,
	EditorAppendResumeLabel: `Folytassa a függeléket`,
	EditorBgColorLabel: `Háttérszín`,
	EditorClearAllLabel: `Mindent kitöröl`,
	EditorClipboardFormatsLabel: `Vágólap formátumai`,
	EditorConfirmNtfTitle: `megerősít`,
	EditorDeleteAllButtonText: `Mindet törölni`,
	EditorDeleteAllTemplatesNtfText: `Biztos benne, hogy törölni akarja a '{0}' összes felhasználását?

Ezt nem lehet visszacsinálni!`,
	EditorEditTemplateDetailsLabel: `Részletek szerkesztése`,
	EditorEditTemplateNameLabel: `Név`,
	EditorFindLabel: `megtalálja`,
	EditorFontColorLabel: `Betű szín`,
	EditorFormatPaintLabel: `Formátumfesték`,
	EditorInSelectionLabel: ` Válogatáskor`,
	EditorInsertImageLabel: `Beilleszteni a képet`,
	EditorInsertLinkLabel: `Helyezze be a linket`,
	EditorInsertVideoLabel: `Beilleszteni a videót`,
	EditorMatchCaseLabel: ` Mérkőzés esetén`,
	EditorNewTemplateLabel: `Új sablon`,
	EditorNextTemplateLabel: `Következő sablon`,
	EditorPasteButtonAppendBeginLabel: `Mellékel...`,
	EditorPasteButtonLabel: `Paszta`,
	EditorPasteTemplateWatermark: `Írja be a paszta szöveget ...`,
	EditorPrevTemplateLabel: `Előző sablon`,
	EditorRegExLabel: ` Reguláris kifejezés`,
	EditorReplaceAllLabel: `Cserélje ki az összeset`,
	EditorReplaceLabel: `Cserél`,
	EditorTemplateContactHint: `<p> A rendelkezésre álló névjegyek használata (Fetcher plugin szükséges) Ezt a mezőt a sablon minden példányához használják a dokumentumon keresztül, vagy bármelyiken később hivatkozunk. Itt, akkor a kiválasztott kapcsolattartó e -mail mezőt a dokumentum minden példányához használják. </p>`,
	EditorTemplateContactName: `Kapcsolatba lépni`,
	EditorTemplateDateTimeCustomHint: `yy = rövid év <br/> yyyy = hosszú év <br/> m = hónap (1-12) <br/> mm = hónap (01-12) <br/> mmm = hónap rövidítés (január, február .. . DEC) <br/> mmmm = hosszú hónap (január, február ... december) <br/> d = nap (1 - 31) <br/> dd = nap (01 - 31) <br/> ddd = A hét napja szavakkal (hétfő, kedd ... vasárnap) <br/> e = a hét rövid napja szavakban (hétfő, kedd ... nap) 3., 21., 22., 23., 31., 4., 4.) <br/> H = óra AM/PM-ben (0-12) <br/> HH = óra AM/PM-ben (00-12) <BR/ > H = óra a napon (0-23) <br/> hh = óra a napon (00-23) <br/> mm = perc <br/> ss = második <br/> sss = milliszekundum <br/> A = AM/PM marker <br/> p = A.M./P.M. jelző`,
	EditorTemplateDateTimeCustomLabel: `Egyedi`,
	EditorTemplateDateTimeHint: `Az aktuális dátumot és/vagy az időt helyettesítik a DateTime sablonok beillesztésekor.`,
	EditorTemplateDateTimeName: `Dátum idő`,
	EditorTemplateDynamicHint: `<p> Ennek a sablonnak az összes eseménye a megadott szöveget fogja használni. </p>`,
	EditorTemplateDynamicName: `Dinamikus`,
	EditorTemplateEmptyPlaceholder: `{0} üres ...`,
	EditorTemplateStaticHint: `<p> Ennek a sablonnak az összes eseménye a megadott szöveget fogja használni. </p>`,
	EditorTemplateStaticName: `Statikus`,
	EditorTemplateTeaserText: `Hamarosan még több jön!`,
	EditorWatermark: `Kérlek várj...`,
	EditorWholeWordLabel: ` Egész világ`,
	EditorWrapLabel: ` Körbeteker`,

};