var UiStrings = {
	EditorAppendCloseLabel: `Finire l'avvio`,
	EditorAppendInlineModeLabel: `Abilita blocco`,
	EditorAppendLineModeLabel: `Abilita in linea`,
	EditorAppendManualModeLabel: `Manuale a disattivazione`,
	EditorAppendNonManualModeLabel: `Manuale a disattivazione`,
	EditorAppendPauseLabel: `Pausa aggiungi`,
	EditorAppendPostLabel: `Attiva alterni prima`,
	EditorAppendPreLabel: `Attiva alterni prima`,
	EditorAppendResumeLabel: `Riprendi l'append`,
	EditorBgColorLabel: `Colore di sfondo`,
	EditorClearAllLabel: `Cancella tutto`,
	EditorClipboardFormatsLabel: `Formati degli appunti`,
	EditorConfirmNtfTitle: `Confermare`,
	EditorDeleteAllButtonText: `Cancella tutto`,
	EditorDeleteAllTemplatesNtfText: `Sei sicuro di voler eliminare tutti gli usi di '{0}'?

Questo non può essere annullato!`,
	EditorEditTemplateDetailsLabel: `Modifica i dettagli`,
	EditorEditTemplateNameLabel: `Nome`,
	EditorFindLabel: `Trovare`,
	EditorFontColorLabel: `Colore del carattere`,
	EditorFormatPaintLabel: `Formato di vernice`,
	EditorInSelectionLabel: ` In selezione`,
	EditorInsertImageLabel: `Inserire l'immagine`,
	EditorInsertLinkLabel: `Inserisci il collegamento`,
	EditorInsertVideoLabel: `Inserire video`,
	EditorMatchCaseLabel: ` Match Case`,
	EditorNewTemplateLabel: `Nuovo modello`,
	EditorNextTemplateLabel: `Modello successivo`,
	EditorPasteButtonAppendBeginLabel: `Aggiungere...`,
	EditorPasteButtonLabel: `Impasto`,
	EditorPasteTemplateWatermark: `Immettere il testo in pasta ...`,
	EditorPrevTemplateLabel: `Modello precedente`,
	EditorRegExLabel: ` Espressione regolare`,
	EditorReplaceAllLabel: `Sostituisci tutto`,
	EditorReplaceLabel: `Sostituire`,
	EditorTemplateContactHint: `<p> Utilizzo dei contatti disponibili (richiede un plug -in Fetcher) Questo campo verrà utilizzato per tutte le istanze di questo modello su questo documento o in qualsiasi altro verrà fatto riferimento in seguito. </p> <p> Quindi, ad esempio, se seleziona l'indirizzo e -mail Ecco quindi il campo e -mail del contatto che seleziona verrà utilizzato per tutte le istanze in questo documento. </p>`,
	EditorTemplateContactName: `Contatto`,
	EditorTemplateDateTimeCustomHint: `yy = corto anno <br/> yyyy = lungo anno <br/> m = mese (1-12) <br/> mm = mese (01-12) <br/> mmm = Abbreviazione del mese (gennaio, febbraio .. . Dec) <br/> mmmm = lungo mese (gennaio, febbraio ... dicembre) <br/> d = day (1 - 31) <br/> dd = day (01 - 31) <br/> ddd = Giorno della settimana in parole (lunedì, martedì ... domenica) <br/> e = breve giorno della settimana in parole (lun, mar ... sole) <br/> d - giorno ordinale (1 °, 2 °, 3 °, 21 °, 22 °, 23 °, 31 °, 4 ° ...) <br/> H = ora in AM/PM (0-12) <br/> hh = ora in AM/PM (00-12) <Br/ > H = ora in giorno (0-23) <br/> hh = ora in giorno (00-23) <br/> mm = minuto <br/> ss = secondo <br/> sss = milliseconds <br/> A = marcatore AM/PM <br/> p = A.M./P.M. marcatore`,
	EditorTemplateDateTimeCustomLabel: `Costume`,
	EditorTemplateDateTimeHint: `La data e/o l'ora correnti saranno sostituiti con i modelli DateTime quando vengono incollati.`,
	EditorTemplateDateTimeName: `Appuntamento`,
	EditorTemplateDynamicHint: `<p> Tutti gli eventi di questo modello utilizzeranno il testo fornito. </p>`,
	EditorTemplateDynamicName: `Dinamico`,
	EditorTemplateEmptyPlaceholder: `{0} è vuoto ...`,
	EditorTemplateStaticHint: `<p> Tutti gli eventi di questo modello utilizzeranno il testo fornito. </p>`,
	EditorTemplateStaticName: `Statico`,
	EditorTemplateTeaserText: `Maggiori informazioni tra breve!`,
	EditorWatermark: `Attendere prego...`,
	EditorWholeWordLabel: ` Parola intera`,
	EditorWrapLabel: ` Arrotolare`,

};