var UiStrings = {
	EditorAppendCloseLabel: `Selesai`,
	EditorAppendInlineModeLabel: `Dayakan blok`,
	EditorAppendLineModeLabel: `Dayakan sebaris`,
	EditorAppendManualModeLabel: `Manual togol`,
	EditorAppendNonManualModeLabel: `Manual togol`,
	EditorAppendPauseLabel: `Jeda tambah`,
	EditorAppendPostLabel: `Togol sebelum ini`,
	EditorAppendPreLabel: `Togol sebelum ini`,
	EditorAppendResumeLabel: `Resume tambah`,
	EditorBgColorLabel: `Warna latar belakang`,
	EditorClearAllLabel: `Kosongkan semua`,
	EditorClipboardFormatsLabel: `Format papan klip`,
	EditorConfirmNtfTitle: `Mengesahkan`,
	EditorDeleteAllButtonText: `Memadam semua`,
	EditorDeleteAllTemplatesNtfText: `Adakah anda pasti mahu memadam semua penggunaan '{0}'?

Perkara ini tidak boleh diubah!`,
	EditorEditTemplateDetailsLabel: `Edit perincian`,
	EditorEditTemplateNameLabel: `Nama`,
	EditorFindLabel: `Cari`,
	EditorFontColorLabel: `Warna fon`,
	EditorFormatPaintLabel: `Format cat`,
	EditorInSelectionLabel: ` Dalam pemilihan`,
	EditorInsertImageLabel: `Masukkan imej`,
	EditorInsertLinkLabel: `Masukkan pautan`,
	EditorInsertVideoLabel: `Masukkan video`,
	EditorMatchCaseLabel: ` Kes perlawanan`,
	EditorNewTemplateLabel: `Templat baru`,
	EditorNextTemplateLabel: `Templat seterusnya`,
	EditorPasteButtonAppendBeginLabel: `Tambah ...`,
	EditorPasteButtonLabel: `Tampal`,
	EditorPasteTemplateWatermark: `Masukkan teks tampal ...`,
	EditorPrevTemplateLabel: `Templat sebelumnya`,
	EditorRegExLabel: ` Ekspresi biasa`,
	EditorReplaceAllLabel: `Ganti semua`,
	EditorReplaceLabel: `Menggantikan`,
	EditorTemplateContactHint: `<p> Menggunakan kenalan yang ada (memerlukan plugin perap) medan ini akan digunakan untuk semua contoh templat ini merentasi dokumen ini atau di mana -mana ia akan dirujuk di kemudian hari. </P> <p> Di sini kemudian medan e -mel kenalan yang anda pilih akan digunakan untuk semua contoh dalam dokumen ini. </P>`,
	EditorTemplateContactName: `Hubungi`,
	EditorTemplateDateTimeCustomHint: `yy = tahun pendek <br/> yyyy = tahun panjang <br/> m = bulan (1-12) <br/> mm = bulan (01-12) <br/> mmm = bulan singkatan (Jan, Feb .. . Dec) <br/> mmmm = bulan panjang (Januari, Februari ... Disember) <br/> d = hari (1 - 31) <br/> dd = hari (01 - 31) <br/> ddd = hari dalam seminggu dalam kata -kata (Isnin, Selasa ... Ahad) <br/> e = hari pendek minggu dalam kata -kata (mon, tue ... sun) <br/> d - hari ordinal (1st, 2nd, 3, 21, 22, 23, 31, 4 ...) <br/> h = jam di am/pm (0-12) <br/> hh = jam di am/pm (00-12) <br/ > H = jam sehari (0-23) <br/> hh = jam dalam hari (00-23) <br/> mm = minit <br/> ss = kedua <br/> sss = milliseconds <br/> a = am/pm penanda <br/> p = a.m./p.m. penanda`,
	EditorTemplateDateTimeCustomLabel: `Adat`,
	EditorTemplateDateTimeHint: `Tarikh dan/atau masa semasa akan digantikan untuk template datetime apabila mereka disisipkan.`,
	EditorTemplateDateTimeName: `Masa tarikh`,
	EditorTemplateDynamicHint: `<p> Semua kejadian templat ini akan menggunakan teks yang disediakan. </P>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} kosong ...`,
	EditorTemplateStaticHint: `<p> Semua kejadian templat ini akan menggunakan teks yang disediakan. </P>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Lebih banyak lagi akan datang!`,
	EditorWatermark: `Sila tunggu...`,
	EditorWholeWordLabel: ` Keseluruhan perkataan`,
	EditorWrapLabel: ` Membungkus`,

};