var UiStrings = {
	EditorAppendCloseLabel: `Dokončiť prítomnosť`,
	EditorAppendInlineModeLabel: `Povoliť blok`,
	EditorAppendLineModeLabel: `Povoliť`,
	EditorAppendManualModeLabel: `Prepínanie`,
	EditorAppendNonManualModeLabel: `Prepínanie`,
	EditorAppendPauseLabel: `Pozastaviť`,
	EditorAppendPostLabel: `Prepnúť predtým`,
	EditorAppendPreLabel: `Prepnúť predtým`,
	EditorAppendResumeLabel: `Pokračovať`,
	EditorBgColorLabel: `Farba pozadia`,
	EditorClearAllLabel: `Zmazať všetko`,
	EditorClipboardFormatsLabel: `Formát schránky`,
	EditorConfirmNtfTitle: `Potvrdiť`,
	EditorDeleteAllButtonText: `Vymazať všetko`,
	EditorDeleteAllTemplatesNtfText: `Ste si istí, že chcete odstrániť všetky použitia '{0}'?

To nie je možné vrátiť späť!`,
	EditorEditTemplateDetailsLabel: `Úpravy detailov`,
	EditorEditTemplateNameLabel: `názov`,
	EditorFindLabel: `Nájsť`,
	EditorFontColorLabel: `Farba písma`,
	EditorFormatPaintLabel: `Farby formátu`,
	EditorInSelectionLabel: ` Výber`,
	EditorInsertImageLabel: `Vložiť obrázok`,
	EditorInsertLinkLabel: `Vložiť odkaz`,
	EditorInsertVideoLabel: `Vložiť video`,
	EditorMatchCaseLabel: ` Zápas`,
	EditorNewTemplateLabel: `Nový šablóna`,
	EditorNextTemplateLabel: `Ďalšia šablóna`,
	EditorPasteButtonAppendBeginLabel: `Pripojiť ...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteTemplateWatermark: `Zadajte text pasty ...`,
	EditorPrevTemplateLabel: `Predchádzajúca šablóna`,
	EditorRegExLabel: ` Pravidelný výraz`,
	EditorReplaceAllLabel: `Nahradiť všetko`,
	EditorReplaceLabel: `Nahradiť`,
	EditorTemplateContactHint: `<p> Používanie dostupných kontaktov (vyžaduje doplnok Fetcher) Toto pole sa použije pre všetky inštancie tejto šablóny v tomto dokumente alebo v akomkoľvek, na čo sa bude odkazovať neskôr. </p> <p> Tu sa tu použije e -mailové pole kontaktu, ktorý vyberiete, pre všetky inštancie v tomto dokumente. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `rr = krátky rok <br/> rrrr = dlhý rok <br/> m = mesiac (1-12) <br/> mm = mesiac (01-12) <br/> mmm = mesiac skratka (január, február .. . December) <br/> mmmm = dlhý mesiac (január, február ... december) <br/> d = deň (1 - 31) <br/> dd = deň (01 - 31) <br/> ddd = Deň týždňa slovami (pondelok, utorok ... nedeľa) <br/> e = krátky deň v týždni slovami (Mon, Ut ... slnko) <br/> d - Ordinal Day (1., 2., 3., 21., 22., 23., 31., 4. ...) <br/> h = hodina v AM/PM (0-12) <br/> HH = hodina v AM/PM (00-12) <BR/ > H = hodina v dennom (0-23) <br/> hh = hodina v dennom (00-23) <br/> mm = minúta <br/> ss = sekunda <br/> sss = miliseConds <br/> A = AM/PM Marker <br/> p = a.m./p.m. značka`,
	EditorTemplateDateTimeCustomLabel: `Zvyk`,
	EditorTemplateDateTimeHint: `Aktuálny dátum a/alebo čas sa nahradia šablónou datetime, keď sú vložené.`,
	EditorTemplateDateTimeName: `Dátum Čas`,
	EditorTemplateDynamicHint: `<p> Všetky výskyty tejto šablóny použijú poskytnutý text. </p>`,
	EditorTemplateDynamicName: `Dynamika`,
	EditorTemplateEmptyPlaceholder: `{0} je prázdny ...`,
	EditorTemplateStaticHint: `<p> Všetky výskyty tejto šablóny použijú poskytnutý text. </p>`,
	EditorTemplateStaticName: `Statický`,
	EditorTemplateTeaserText: `Viac čoskoro!`,
	EditorWatermark: `Prosím čakajte...`,
	EditorWholeWordLabel: ` Celé slovo`,
	EditorWrapLabel: ` Zabaliť sa`,

};