var UiStrings = {
	EditorAppendCloseLabel: `Eklemeyi bitir`,
	EditorAppendInlineModeLabel: `Bloğu Etkinleştir`,
	EditorAppendLineModeLabel: `Satır içi etkinleştir`,
	EditorAppendManualModeLabel: `Başlangıç ​​Kılavuzu`,
	EditorAppendNonManualModeLabel: `Başlangıç ​​Kılavuzu`,
	EditorAppendPauseLabel: `Duraklat eklemek`,
	EditorAppendPostLabel: `Daha önce geçiş yap`,
	EditorAppendPreLabel: `Daha önce geçiş yap`,
	EditorAppendResumeLabel: `Özgeçmiş Ekle`,
	EditorBgColorLabel: `Arka plan rengi`,
	EditorClearAllLabel: `Hepsini temizle`,
	EditorClipboardFormatsLabel: `Pano Biçimleri`,
	EditorColorChooserTitle: `Editör rengi`,
	EditorConfirmNtfTitle: `Onaylamak`,
	EditorDeleteAllButtonText: `Hepsini sil`,
	EditorDeleteAllTemplatesNtfText: `'{0}' in tüm kullanımlarını silmek istediğinizden emin misiniz?

Bu geri alınamaz!`,
	EditorEditTemplateDetailsLabel: `Detayları düzenle`,
	EditorEditTemplateNameLabel: `İsim`,
	EditorFindLabel: `Bulmak`,
	EditorFontColorLabel: `Yazı rengi`,
	EditorFormatPaintLabel: `Biçim Boyası`,
	EditorInSelectionLabel: ` Seçimde`,
	EditorInsertImageLabel: `Resim ekle`,
	EditorInsertLinkLabel: `Bağlantı Ekle`,
	EditorInsertVideoLabel: `Video ekle`,
	EditorLinkButtonText: `Kaydetmek`,
	EditorLinkLabel: `Bağlantı girin`,
	EditorLinkPlaceholder: `URL girin`,
	EditorMatchCaseLabel: ` Kibrit kasası`,
	EditorNewTemplateLabel: `Yeni şablon`,
	EditorNextTemplateLabel: `Sonraki Şablon`,
	EditorPasteButtonAppendBeginLabel: `Ek ...`,
	EditorPasteButtonLabel: `Yapıştırmak`,
	EditorPasteButtonLabelMobile: `Kopya`,
	EditorPasteTemplateWatermark: `Macun metnine girin ...`,
	EditorPrevTemplateLabel: `Önceki Şablon`,
	EditorRegExLabel: ` Düzenli ifade`,
	EditorReplaceAllLabel: `Hepsini değiştir`,
	EditorReplaceLabel: `Yer değiştirmek`,
	EditorTemplateContactHint: `<p>Mevcut kişileri kullanarak (bir alıcı eklentisi gerektirir) bu alan, bu şablonun bu belgedeki tüm örnekleri için veya daha sonra başvurulacak herhangi bir örnek için kullanılacaktır.</p><p> Örneğin, burada e-posta adresini seçerseniz, seçtiğiniz kişinin e-posta alanı bu belgedeki tüm örnekler için kullanılacaktır.</p>`,
	EditorTemplateContactName: `Temas etmek`,
	EditorTemplateDateTimeCustomHint: `yy = kısa yıl<br/>yyyy = uzun yıl<br/>M = ay (1-12)<br/>MM = ay (01-12)<br/>MMM = ay kısaltması (Ocak, Şubat ... Aralık)<br/>MMMM = uzun ay (Ocak, Şubat... Aralık)<br/>d = gün (1 - 31)<br/>dd = gün (01 - 31)<br/>ddd = kelimelerle haftanın günü (Pazartesi, Salı ... Pazar)<br/>E = kelimelerle haftanın kısa günü (Pzt, Sal ... Güneş)<br/>D - Sıra günü (1., 2., 3., 21., 22., 23., 31., 4...)<br/>h =/pm cinsinden saat (0-12)<br/>hh =/pm cinsinden saat (00-12)<br/>H = gündeki saat (0-23)<br/>HH = gün içindeki saat (00-23)<br/>mm = dakika<br/>ss = saniye<br/>SSS = milisaniye<br/>a =/PM işaretçisi<br/>p = a.m./p.m. işaretçisi`,
	EditorTemplateDateTimeCustomLabel: `Gelenek`,
	EditorTemplateDateTimeHint: `Mevcut tarih ve/veya saat, yapıştırıldıklarında DateTime şablonları için değiştirilecektir.`,
	EditorTemplateDateTimeName: `Tarih saati`,
	EditorTemplateDynamicHint: `<p>Bu şablonun tüm oluşumları sağlanan metni kullanacaktır.</p>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} boş ...`,
	EditorTemplateStaticHint: `<p>Bu şablonun tüm oluşumları sağlanan metni kullanacaktır.</p>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Daha fazlası yakında!`,
	EditorTt1: `Tıklamak`,
	EditorTt2: `Düzenle '<em> {0} </em>' ...`,
	EditorTt3: `Renk düzenleyin ...`,
	EditorTt4: `Kaldır '<em> {0} </em>' ...`,
	EditorTt5: `öğeyi kaldırmak`,
	EditorTt6: `takip etmek ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Lütfen bekleyin...`,
	EditorWholeWordLabel: ` Tüm dünya`,
	EditorWrapLabel: ` Etrafına sarmak`,

};