var UiStrings = {
	EditorAppendCloseLabel: `Whakaoti i te Apiti`,
	EditorAppendInlineModeLabel: `Whakahohe Poraka`,
	EditorAppendLineModeLabel: `Whakahohe i roto`,
	EditorAppendManualModeLabel: `Toggle Topggle`,
	EditorAppendNonManualModeLabel: `Toggle Topggle`,
	EditorAppendPauseLabel: `Te taapiri mo te taapiri`,
	EditorAppendPostLabel: `Tuhinga o mua`,
	EditorAppendPreLabel: `Tuhinga o mua`,
	EditorAppendResumeLabel: `Taapiri taapiri`,
	EditorBgColorLabel: `Tae papamuri`,
	EditorClearAllLabel: `Horoia katoa`,
	EditorClipboardFormatsLabel: `Nga Puka Takahi`,
	EditorConfirmNtfTitle: `Whakaū`,
	EditorDeleteAllButtonText: `Mukua te katoa`,
	EditorDeleteAllTemplatesNtfText: `Kei te hiahia koe ki te muku i nga waahanga katoa o te '{0}'?

Kaore e taea te whakakore!`,
	EditorEditTemplateDetailsLabel: `Whakatika Taipitopito`,
	EditorEditTemplateNameLabel: `Ingoa`,
	EditorFindLabel: `Kite`,
	EditorFontColorLabel: `Tae momotuhi`,
	EditorFormatPaintLabel: `Pepa Hōp`,
	EditorInSelectionLabel: ` I te kowhiringa`,
	EditorInsertImageLabel: `Whakauruhia te Whakaahua`,
	EditorInsertLinkLabel: `Whakauruhia he hononga`,
	EditorInsertVideoLabel: `Whakauruhia he ataata`,
	EditorMatchCaseLabel: ` Taka whakataetae`,
	EditorNewTemplateLabel: `Tātauira Hou`,
	EditorNextTemplateLabel: `Panuku`,
	EditorPasteButtonAppendBeginLabel: `Tāpiri ...`,
	EditorPasteButtonLabel: `Whakapiri`,
	EditorPasteTemplateWatermark: `Whakauruhia te tuhinga whakapiri ...`,
	EditorPrevTemplateLabel: `Tuhinga o mua`,
	EditorRegExLabel: ` Whakapuakitanga auau`,
	EditorReplaceAllLabel: `Whakakapihia te katoa`,
	EditorReplaceLabel: `Whakakapi`,
	EditorTemplateContactHint: `<p> Ma te whakamahi i nga hoapaki e waatea ana (me tono te waahi Fetcret) tenei mara mo nga wa katoa o tenei tuhinga, i roto i tetahi korero ka tohua mena ka tohua te wahitau imeera I konei ka whakamahia te mara imeera o te whakapā ka tohua e koe mo nga waa katoa o tenei tuhinga. </ p>`,
	EditorTemplateContactName: `Whakapā`,
	EditorTemplateDateTimeCustomHint: `YY = Tau poto <br/> Yyyy = Long <br/> MM = MM = MMP = MMBER (JAN, FOB .. . Dec) <br/> mmmm = roa (marama roa (Hui-tanguru, Hui-tanguru ... Hakihea) <ber/>) Ra o te wiki i roto i nga kupu (Mane, Rātapu ... Rātapu) 3th, 21st, 22nd, 23th, 31st, 4th ...) <br/> HA = HM (0-12) <br/> HAH (00-12) <BR / > H = Hutahi i te ra (0-23) <br/> HH = haora i te ra (00-23) <br/> <br/> <br/> (milliseconds <br/> A = am / pm tohu <br/> p = a.m./p.m. tohu`,
	EditorTemplateDateTimeCustomLabel: `Ritenga`,
	EditorTemplateDateTimeHint: `Ko te ra o naianei me / te waa ranei ka whakakapihia mo nga tauira o te waa ka oti te whakakii.`,
	EditorTemplateDateTimeName: `Te wa`,
	EditorTemplateDynamicHint: `<p> Ko nga ahuatanga katoa o tenei tauira ka whakamahi i te tuhinga kua whakaratohia. </ p>`,
	EditorTemplateDynamicName: `Huatau`,
	EditorTemplateEmptyPlaceholder: `{0} he waatea ...`,
	EditorTemplateStaticHint: `<p> Ko nga ahuatanga katoa o tenei tauira ka whakamahi i te tuhinga kua whakaratohia. </ p>`,
	EditorTemplateStaticName: `Pūmahara`,
	EditorTemplateTeaserText: `Ka hoki mai ano!`,
	EditorWatermark: `Tatari koa ...`,
	EditorWholeWordLabel: ` Kupu katoa`,
	EditorWrapLabel: ` Takai`,

};