var UiStrings = {
	EditorAppendCloseLabel: `Termine de anexar`,
	EditorAppendInlineModeLabel: `Ativar bloco`,
	EditorAppendLineModeLabel: `Ativar embutido`,
	EditorAppendManualModeLabel: `Alternar manual`,
	EditorAppendNonManualModeLabel: `Alternar manual`,
	EditorAppendPauseLabel: `Pausa anexa`,
	EditorAppendPostLabel: `Alternar antes`,
	EditorAppendPreLabel: `Alternar antes`,
	EditorAppendResumeLabel: `Retomar anexar`,
	EditorBgColorLabel: `Cor de fundo`,
	EditorClearAllLabel: `Limpar tudo`,
	EditorClipboardFormatsLabel: `Formatos da área de transferência`,
	EditorConfirmNtfTitle: `confirme`,
	EditorDeleteAllButtonText: `Exclua tudo`,
	EditorDeleteAllTemplatesNtfText: `Tem certeza de que deseja excluir todos os usos de '{0}'?

Isto não pode ser desfeito!`,
	EditorEditTemplateDetailsLabel: `Editar Detalhes`,
	EditorEditTemplateNameLabel: `Nome`,
	EditorFindLabel: `Encontrar`,
	EditorFontColorLabel: `Cor da fonte`,
	EditorFormatPaintLabel: `Formato tinta`,
	EditorInSelectionLabel: ` Na seleção`,
	EditorInsertImageLabel: `Inserir Imagem`,
	EditorInsertLinkLabel: `Insira o link`,
	EditorInsertVideoLabel: `Insira o vídeo`,
	EditorMatchCaseLabel: ` Caso de compatibilidade`,
	EditorNewTemplateLabel: `Novo modelo`,
	EditorNextTemplateLabel: `Próximo modelo`,
	EditorPasteButtonAppendBeginLabel: `Acrescentar...`,
	EditorPasteButtonLabel: `Colar`,
	EditorPasteTemplateWatermark: `Digite o texto da pasta ...`,
	EditorPrevTemplateLabel: `Modelo anterior`,
	EditorRegExLabel: ` Expressão regular`,
	EditorReplaceAllLabel: `Substitua tudo`,
	EditorReplaceLabel: `Substituir`,
	EditorTemplateContactHint: `<p> Usando contatos disponíveis (requer um plug -in Fetcher), este campo será usado para todas as instâncias deste modelo neste documento ou em qualquer um será referenciado posteriormente. </p> <p> Por exemplo, se selecionar endereço de email Aqui, então o campo de email do contato que você selecionar será usado para todas as instâncias neste documento. </p>`,
	EditorTemplateContactName: `Contato`,
	EditorTemplateDateTimeCustomHint: `yy = ano curto <br/> yyyy = longo ano <br/> m = mês (1-12) <br/> mm = mês (01-12) <br/> mmm = abreviatura do mês (janeiro, fevereiro .. . Dez) <br/> mmmm = longo mês (janeiro, fevereiro ... dezembro) <br/> d = dia (1 - 31) <br/> dd = dia (01 - 31) <br/> ddd = Dia da semana em palavras (segunda -feira, terça -feira ... domingo) <br/> e = curto dia da semana em palavras (seg, ter ... sol) <br/> D - Dia ordinal (1º, 2º, 3º, 21, 22, 23, 31, 4º ...) <br/> h = hora em am/pm (0-12) <br/> hh = hora em am/pm (00-12) <br/ > H = hora no dia (0-23) <br/> hh = hora no dia (00-23) <br/> mm = minuto <br/> ss = segundo <br/> sss = milissegundos <br/> A = AM/PM Marcador <br/> p = A.M./P.M. marcador`,
	EditorTemplateDateTimeCustomLabel: `Personalizado`,
	EditorTemplateDateTimeHint: `A data atual e/ou a hora serão substituídas por modelos de datetime quando forem colados.`,
	EditorTemplateDateTimeName: `Data hora`,
	EditorTemplateDynamicHint: `<p> Todas as ocorrências deste modelo usarão o texto fornecido. </p>`,
	EditorTemplateDynamicName: `Dinâmico`,
	EditorTemplateEmptyPlaceholder: `{0} está vazio ...`,
	EditorTemplateStaticHint: `<p> Todas as ocorrências deste modelo usarão o texto fornecido. </p>`,
	EditorTemplateStaticName: `Estático`,
	EditorTemplateTeaserText: `Mais em breve!`,
	EditorWatermark: `Por favor, aguarde...`,
	EditorWholeWordLabel: ` Palavra inteira`,
	EditorWrapLabel: ` Envolver em torno`,

};