var UiStrings = {
	EditorAppendCloseLabel: `Pabeigt pievienošanos`,
	EditorAppendInlineModeLabel: `Iespējot bloku`,
	EditorAppendLineModeLabel: `Iespējot inline`,
	EditorAppendManualModeLabel: `Pārslēgt rokasgrāmatu`,
	EditorAppendNonManualModeLabel: `Pārslēgt rokasgrāmatu`,
	EditorAppendPauseLabel: `Pauze Pievienot`,
	EditorAppendPostLabel: `Pārslēgt iepriekš`,
	EditorAppendPreLabel: `Pārslēgt iepriekš`,
	EditorAppendResumeLabel: `Atsākt pievienoties`,
	EditorBgColorLabel: `Fona krāsa`,
	EditorClearAllLabel: `Iztīrīt visu`,
	EditorClipboardFormatsLabel: `Starpliktuves formāti`,
	EditorConfirmNtfTitle: `Apstiprināt`,
	EditorDeleteAllButtonText: `Dzēst visus`,
	EditorDeleteAllTemplatesNtfText: `Vai esat pārliecināts, ka vēlaties izdzēst visus “{0}” lietojumus?

To nevar atsaukt!`,
	EditorEditTemplateDetailsLabel: `Rediģēt informāciju`,
	EditorEditTemplateNameLabel: `Nosaukt`,
	EditorFindLabel: `Atrast`,
	EditorFontColorLabel: `Fonta krāsa`,
	EditorFormatPaintLabel: `Formāta krāsa`,
	EditorInSelectionLabel: ` Atlasē`,
	EditorInsertImageLabel: `Ievietojiet attēlu`,
	EditorInsertLinkLabel: `Ievietot saiti`,
	EditorInsertVideoLabel: `Ievietot video`,
	EditorMatchCaseLabel: ` Atbilstība`,
	EditorNewTemplateLabel: `Jauna veidne`,
	EditorNextTemplateLabel: `Nākamā veidne`,
	EditorPasteButtonAppendBeginLabel: `Pievienot ...`,
	EditorPasteButtonLabel: `Pastā`,
	EditorPasteTemplateWatermark: `Ievadiet pastas tekstu ...`,
	EditorPrevTemplateLabel: `Iepriekšējā veidne`,
	EditorRegExLabel: ` Regulāra izteiksme`,
	EditorReplaceAllLabel: `Nomainīt visu`,
	EditorReplaceLabel: `Aizvietot`,
	EditorTemplateContactHint: `<p> Izmantojot pieejamos kontaktus (nepieciešams, lai atnestu spraudnis) Šis lauks tiks izmantots visiem šīs veidnes gadījumiem visā šajā dokumentā vai jebkurā gadījumā, uz kuru tas tiks norādīts vēlāk. </p> <p> Tātad, piemēram, atlasiet e -pasta adresi, ja atlasiet e -pasta adresi Šeit jūsu izvēlētā kontakta e -pasta lauks tiks izmantots visiem šajā dokumentā. </p>`,
	EditorTemplateContactName: `Saskare`,
	EditorTemplateDateTimeCustomHint: `yy = īss gads <br/> yigyy = garais gads <br/> m = mēnesis (1-12) <br/> mm = mēnesis (01-12) <br/> mmm = mēneša saīsinājums (janvāris, februāris .. . Dec) <br/> mmmm = ilgs mēnesis (janvāris, februāris ... decembris) <br/> d = diena (1 - 31) <br/> dd = diena (01 - 31) <br/> ddd = Nedēļas diena vārdos (pirmdiena, otrdiena ... svētdiena) <br/> e = īsa nedēļas diena vārdos (pirmdiena, otrā ... saule) <br/> D - Ordinālā diena (1., 2., 3., 21., 22., 23., 31., 4. ...) <br/> H = stunda am/pm (0-12) <br/> hh = stunda am/pm (00-12) <br/ > H = stunda dienā (0-23) <br/> HH = stunda dienā (00-23) <br/> mm = minūte <br/> ss = otrais <br/> sss = milisekundes <br/> a = am/pm marķieris <br/> p = a.m./p.m. marķieris`,
	EditorTemplateDateTimeCustomLabel: `Paraža`,
	EditorTemplateDateTimeHint: `Pašreizējais datums un/vai laiks tiks aizstāts ar datuma laika veidnēm, kad tās tiks ielīmētas.`,
	EditorTemplateDateTimeName: `Datums Laiks`,
	EditorTemplateDynamicHint: `<p> Visos šīs veidnes gadījumos tiks izmantots sniegtais teksts. </p>`,
	EditorTemplateDynamicName: `Dinamisks`,
	EditorTemplateEmptyPlaceholder: `{0} ir tukšs ...`,
	EditorTemplateStaticHint: `<p> Visos šīs veidnes gadījumos tiks izmantots sniegtais teksts. </p>`,
	EditorTemplateStaticName: `Statisks`,
	EditorTemplateTeaserText: `Vairāk drīzumā!`,
	EditorWatermark: `Lūdzu uzgaidiet...`,
	EditorWholeWordLabel: ` Vesels vārds`,
	EditorWrapLabel: ` Aptīt`,

};