var UiStrings = {
	EditorAppendCloseLabel: `Tispiċċa l-apping`,
	EditorAppendInlineModeLabel: `Enable Block`,
	EditorAppendLineModeLabel: `Jippermettu inline`,
	EditorAppendManualModeLabel: `Toggle Manwal`,
	EditorAppendNonManualModeLabel: `Toggle Manwal`,
	EditorAppendPauseLabel: `Nieqaf append`,
	EditorAppendPostLabel: `Toggle qabel`,
	EditorAppendPreLabel: `Toggle qabel`,
	EditorAppendResumeLabel: `Ibda mill-ġdid append`,
	EditorBgColorLabel: `Kulur fl-isfond`,
	EditorClearAllLabel: `Żbarazza kollox`,
	EditorClipboardFormatsLabel: `Formati tal-clipboard`,
	EditorColorChooserTitle: `Kulur tal-Editur`,
	EditorConfirmNtfTitle: `Ikkonferma`,
	EditorDeleteAllButtonText: `Ħassar kollox`,
	EditorDeleteAllTemplatesNtfText: `Int żgur li trid tħassar l-użi kollha ta '' {0} '?

Dan ma jistax jitneħħa!`,
	EditorEditTemplateDetailsLabel: `Editja d-dettalji`,
	EditorEditTemplateNameLabel: `Isem`,
	EditorFindLabel: `Sib`,
	EditorFontColorLabel: `Kulur tat-tipa`,
	EditorFormatPaintLabel: `Format taż-żebgħa`,
	EditorInSelectionLabel: ` Fl-għażla`,
	EditorInsertImageLabel: `Daħħal l-immaġni`,
	EditorInsertLinkLabel: `Daħħal link`,
	EditorInsertVideoLabel: `Daħħal vidjow`,
	EditorLinkButtonText: `Ħlief`,
	EditorLinkLabel: `Daħħal link`,
	EditorLinkPlaceholder: `Daħħal URL`,
	EditorMatchCaseLabel: ` Każ tal-partita`,
	EditorNewTemplateLabel: `Mudell ġdid`,
	EditorNextTemplateLabel: `Mudell li jmiss`,
	EditorPasteButtonAppendBeginLabel: `Append ...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteButtonLabelMobile: `Kopja`,
	EditorPasteTemplateWatermark: `Daħħal it-test tal-pejst ...`,
	EditorPrevTemplateLabel: `Mudell preċedenti`,
	EditorRegExLabel: ` Espressjoni regolari`,
	EditorReplaceAllLabel: `Ibdel kollox`,
	EditorReplaceLabel: `Ibdel`,
	EditorTemplateContactHint: `<p>Bl-użu ta' kuntatti disponibbli (jeħtieġ plugin tal-fetcher) dan il-qasam se jintuża għall-każijiet kollha ta' dan il-mudell f'dan id-dokument kollu jew fi kwalunkwe wieħed minnhom se jiġi referenzjat aktar tard.</p><p> Allura per eżempju jekk tagħżel l-indirizz elettroniku hawn allura l-qasam tal-email tal-kuntatt li tagħżel se jintuża għall-istanzi kollha f'dan id-dokument.</p>`,
	EditorTemplateContactName: `Kuntatt`,
	EditorTemplateDateTimeCustomHint: `yy = sena qasira<br/>ssss = sena twila<br/>M = xahar (1-12)<br/>MM = xahar (01-12)<br/>MMM = abbrevjazzjoni tax-xahar (Jan, Frar ... Diċembru)<br/>MMMM = xahar twil (Jannar, Frar ... Diċembru)<br/>d = jum (1 - 31)<br/>DD = jum (01 - 31)<br/>ddd = jum tal-ġimgħa bil-kliem (it-Tnejn, it-Tlieta ... Il-Ħadd)<br/>E = jum qasir tal-ġimgħa fi kliem (Mon, Tue ... Xemx)<br/>D - Jum ordinali (l-1, it-2, it-3, il-21, it-22, it-23, il-31, ir-4 ...)<br/>h = siegħa f'am/pm (0-12)<br/>hh = siegħa f'am/pm (00-12)<br/>H = siegħa f'jum (0-23)<br/>HH = siegħa fil-ġurnata (00-23)<br/>mm = minuta<br/>ss = it-tieni<br/>SSS = millisekondi<br/>a = Markatur AM/PM<br/>p = a.m./p.m. markatur`,
	EditorTemplateDateTimeCustomLabel: `Drawwa`,
	EditorTemplateDateTimeHint: `Id-data kurrenti u / jew il-ħin jiġu sostitwiti għal mudelli ta 'datetime meta jiġu mwaħħlin.`,
	EditorTemplateDateTimeName: `Ħin tad-data`,
	EditorTemplateDynamicHint: `<p>L-okkorrenzi kollha ta' dan il-mudell se jużaw it-test ipprovdut.</p>`,
	EditorTemplateDynamicName: `Dinamiku`,
	EditorTemplateEmptyPlaceholder: `{0} huwa vojt ...`,
	EditorTemplateStaticHint: `<p>L-okkorrenzi kollha ta' dan il-mudell se jużaw it-test ipprovdut.</p>`,
	EditorTemplateStaticName: `Statiku`,
	EditorTemplateTeaserText: `Aktar ġej dalwaqt!`,
	EditorTt1: `Ikklikkja`,
	EditorTt2: `Edit "<em> {0} </em>" ...`,
	EditorTt3: `Editja l-kulur ...`,
	EditorTt4: `Neħħi '<em> {0} </em>' ...`,
	EditorTt5: `neħħi l-oġġett`,
	EditorTt6: `issegwi ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Stenna...`,
	EditorWholeWordLabel: ` Kelma sħiħa`,
	EditorWrapLabel: ` Kebbeb`,

};