var UiStrings = {
	EditorAppendCloseLabel: `Закінчити додавання`,
	EditorAppendInlineModeLabel: `Увімкнути блок`,
	EditorAppendLineModeLabel: `Увімкнути вбудовано`,
	EditorAppendManualModeLabel: `Посібник з перемикання`,
	EditorAppendNonManualModeLabel: `Посібник з перемикання`,
	EditorAppendPauseLabel: `Пауза додає`,
	EditorAppendPostLabel: `Перемикатися до`,
	EditorAppendPreLabel: `Перемикатися до`,
	EditorAppendResumeLabel: `Відновити додаток`,
	EditorBgColorLabel: `Колір фону`,
	EditorClearAllLabel: `Очистити все`,
	EditorClipboardFormatsLabel: `Формати буфера обміну`,
	EditorColorChooserTitle: `Колір редактора`,
	EditorConfirmNtfTitle: `Підтверджувати`,
	EditorDeleteAllButtonText: `Видалити все`,
	EditorDeleteAllTemplatesNtfText: `Ви впевнені, що хочете видалити всі використання '{0}'?

Це не може бути скасоване!`,
	EditorEditTemplateDetailsLabel: `Редагувати деталі`,
	EditorEditTemplateNameLabel: `Назва`,
	EditorFindLabel: `Знаходити`,
	EditorFontColorLabel: `Шрифт`,
	EditorFormatPaintLabel: `Форма фарба`,
	EditorInSelectionLabel: ` У виборі`,
	EditorInsertImageLabel: `Вставте зображення`,
	EditorInsertLinkLabel: `Вставте посилання`,
	EditorInsertVideoLabel: `Вставити відео`,
	EditorLinkButtonText: `Заощадити`,
	EditorLinkLabel: `Введіть посилання`,
	EditorLinkPlaceholder: `Введіть URL -адресу`,
	EditorMatchCaseLabel: ` Справа з відповідності`,
	EditorNewTemplateLabel: `Новий шаблон`,
	EditorNextTemplateLabel: `Наступний шаблон`,
	EditorPasteButtonAppendBeginLabel: `Додайте ...`,
	EditorPasteButtonLabel: `Пасти`,
	EditorPasteButtonLabelMobile: `Копіювати`,
	EditorPasteTemplateWatermark: `Введіть текст вставки ...`,
	EditorPrevTemplateLabel: `Попередній шаблон`,
	EditorRegExLabel: ` Регулярний вираз`,
	EditorReplaceAllLabel: `Замініть усі`,
	EditorReplaceLabel: `Замінити`,
	EditorTemplateContactHint: `<p>Використовуючи доступні контакти (потрібен плагін отримання), це поле буде використано для всіх екземплярів цього шаблону в цьому документі або в будь-якому з них, на які він буде посилатися пізніше.</p><p> Так, наприклад, якщо тут вибрано адресу електронної пошти, поле електронної пошти вибраного вами контакту буде використано для всіх екземплярів у цьому документі.</p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = короткий рік<br/>рррр = довгий рік<br/>М = місяць (1-12)<br/>ММ = місяць (01-12)<br/>МММ = абревіатура місяця (січень, лютий ... грудень)<br/>ММММ = довгий місяць (січень, лютий ... Грудень)<br/>d = день (1 - 31)<br/>dd = день (01 - 31)<br/>ddd = день тижня прописом (понеділок, вівторок ... Неділя)<br/>Е = короткий день тижня прописом (Пн, Вт ... Сонце)<br/>D - порядковий день (1-й, 2-й, 3-й, 21-й, 22-й, 23-й, 31-й, 4-й...)<br/>h = година в ранку/вечора (0-12)<br/>hh = година в ранку/вечора (00-12)<br/>H = година в добі (0-23)<br/>HH = година в добі (00-23)<br/>мм = хвилина<br/>ss = секунда<br/>SSS = мілісекунди<br/>a = маркер AM/PM<br/>p = маркер a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Звичайний`,
	EditorTemplateDateTimeHint: `Поточна дата та/або час буде замінена на шаблони DateTime, коли вони вставляються.`,
	EditorTemplateDateTimeName: `Дата, час`,
	EditorTemplateDynamicHint: `<p>Усі входження цього шаблону використовуватимуть наданий текст.</p>`,
	EditorTemplateDynamicName: `Динамічний`,
	EditorTemplateEmptyPlaceholder: `{0} порожній ...`,
	EditorTemplateStaticHint: `<p>Усі входження цього шаблону використовуватимуть наданий текст.</p>`,
	EditorTemplateStaticName: `Статичний`,
	EditorTemplateTeaserText: `Більше скоро!`,
	EditorTt1: `Клацати`,
	EditorTt2: `редагувати '<em> {0} </em>' ...`,
	EditorTt3: `Редагувати колір ...`,
	EditorTt4: `Видалити '<em> {0} </em>' ...`,
	EditorTt5: `Видаліть елемент`,
	EditorTt6: `слідувати ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Зачекайте ...`,
	EditorWholeWordLabel: ` Ціле слово`,
	EditorWrapLabel: ` Обгортати`,

};