var UiStrings = {
	EditorAppendCloseLabel: `Qo'shilishni tugatish`,
	EditorAppendInlineModeLabel: `Blokni yoqing`,
	EditorAppendLineModeLabel: `Imkoniyatni yoqish`,
	EditorAppendManualModeLabel: `Qo'llanmani almashtirish`,
	EditorAppendNonManualModeLabel: `Qo'llanmani almashtirish`,
	EditorAppendPauseLabel: `PAUSE APRENSI`,
	EditorAppendPostLabel: `Oldin almashtiring`,
	EditorAppendPreLabel: `Oldin almashtiring`,
	EditorAppendResumeLabel: `Davom etishni davom ettiring`,
	EditorBgColorLabel: `Orqa rang`,
	EditorClearAllLabel: `Hammasini tozalamoq`,
	EditorClipboardFormatsLabel: `Clipboard formatlari`,
	EditorConfirmNtfTitle: `Tasdiqlamoq`,
	EditorDeleteAllButtonText: `Barchasini o'chiring`,
	EditorDeleteAllTemplatesNtfText: `Haqiqatan ham '{0}' ning barcha qo'llanilishini o'chirmoqchimisiz?

Bu bekor qilinmaydi!`,
	EditorEditTemplateDetailsLabel: `Tafsilotlarni tahrirlash`,
	EditorEditTemplateNameLabel: `Ism`,
	EditorFindLabel: `Topmoq`,
	EditorFontColorLabel: `Shrift rangi`,
	EditorFormatPaintLabel: `Format bo'yoq`,
	EditorInSelectionLabel: ` Tanlovda`,
	EditorInsertImageLabel: `Rasmni joylashtiring`,
	EditorInsertLinkLabel: `Havolani joylashtiring`,
	EditorInsertVideoLabel: `Video joylashtiring`,
	EditorMatchCaseLabel: ` Uchrashuv ishi`,
	EditorNewTemplateLabel: `Yangi shablon`,
	EditorNextTemplateLabel: `Keyingi shablon`,
	EditorPasteButtonAppendBeginLabel: `Ilova ...`,
	EditorPasteButtonLabel: `Pastroq qilmoq`,
	EditorPasteTemplateWatermark: `Foree matnini kiriting ...`,
	EditorPrevTemplateLabel: `Oldingi shablon`,
	EditorRegExLabel: ` Muntazam ifoda`,
	EditorReplaceAllLabel: `Barchasini almashtiring`,
	EditorReplaceLabel: `Almashtirmoq`,
	EditorTemplateContactHint: `Mavjud kontaktlar yordamida ushbu shablonning barcha holatlari uchun ishlatilishi mumkin. Ushbu hujjatda ushbu shablonning barcha holatlari uchun ishlatilishi mumkin. </ p> < Keyin siz tanlagan kontaktning elektron pochta maydoni ushbu hujjatdagi barcha instansiyalar uchun foydalaniladi. </ p>`,
	EditorTemplateContactName: `Aloqa`,
	EditorTemplateDateTimeCustomHint: `yy = qisqa yil <br/> C = Oy (1-12) <br/> 1-11-1. oylik (Yan, fevral .. <br/> DD = kun (01 - 31) (01 - 31) <br/> ddd = kun (01 - 31). Haftaning kunida (dushanba, seshanba ... yakshanba) <br = Haftaning qisqa kuni (Sare ... Sun) <br/> Ord, 2-chi, 3-chi, 21-chi, 23-chi, 31-chi ...) <br-11 soat soat (0-12) (00-12) > H = kun davomida (0-23) <br-__ 1 soat davomida (00-23) (00-23). A = Am / Pm Marker <br/> P = A.M./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Odat`,
	EditorTemplateDateTimeHint: `Joriy sana va / yoki vaqtni ular to'xtatilganda ma'lumotlar uzatish uchun almashtiriladi.`,
	EditorTemplateDateTimeName: `Sana vaqti`,
	EditorTemplateDynamicHint: `<p> Ushbu shablonning barcha holatlari taqdim etilgan matndan foydalanadi. </ p>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} bo'sh ...`,
	EditorTemplateStaticHint: `<p> Ushbu shablonning barcha holatlari taqdim etilgan matndan foydalanadi. </ p>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Tez orada yana keladi!`,
	EditorWatermark: `Iltimos kuting...`,
	EditorWholeWordLabel: ` Butun so'z`,
	EditorWrapLabel: ` O'rash`,

};