var UiStrings = {
	EditorAppendCloseLabel: `ውድእ ውድእ 2019።`,
	EditorAppendInlineModeLabel: `ብሎክ ኣንቅሕ .`,
	EditorAppendLineModeLabel: `ኣብ መስመር ምኽኣል`,
	EditorAppendManualModeLabel: `ቶግለ ማንዋል`,
	EditorAppendNonManualModeLabel: `ቶግለ ማንዋል`,
	EditorAppendPauseLabel: `ኣብ መመላእታ ዕረፍቲ 2019`,
	EditorAppendPostLabel: `ቅድሚ ሕጂ ቶግለ`,
	EditorAppendPreLabel: `ቅድሚ ሕጂ ቶግለ`,
	EditorAppendResumeLabel: `ሪዝዩም ኣብ ምውሳኽ`,
	EditorBgColorLabel: `ድሕረ ባይታ ሕብሪ`,
	EditorClearAllLabel: `ኩሉ ኣጽርዮ`,
	EditorClipboardFormatsLabel: `ቅርጺ ቅንጥብጣብ ሰሌዳ`,
	EditorColorChooserTitle: `ሕብሪ ኣርታዒ`,
	EditorConfirmNtfTitle: `ኣረጋግፅ`,
	EditorDeleteAllButtonText: `ንኹሉ ምድምሳስ .`,
	EditorDeleteAllTemplatesNtfText: `ኩሉ ኣጠቓቕማ '{0}' ክትድምስሶ ከም እትደሊ ርግጸኛ ዲኻ?

እዚ ኽትከውን ኣይክእልን እዩ!`,
	EditorEditTemplateDetailsLabel: `ዝርዝር ኣርትዕ`,
	EditorEditTemplateNameLabel: `ሽም`,
	EditorFindLabel: `ርኸብ`,
	EditorFontColorLabel: `ቅርጺ ፊደላት`,
	EditorFormatPaintLabel: `ፎርማት ቀለም .`,
	EditorInSelectionLabel: ` ኣብ ምምራጽ`,
	EditorInsertImageLabel: `ምስሊ ምእታው`,
	EditorInsertLinkLabel: `ናይ ምእታው መላግቦ`,
	EditorInsertVideoLabel: `ቪድዮ ምእታው`,
	EditorLinkButtonText: `ምቑጣብ`,
	EditorLinkLabel: `ሊንክ ኣእትዉ`,
	EditorLinkPlaceholder: `URL ኣእትዉ`,
	EditorMatchCaseLabel: ` ምትእስሳር ኬዝ`,
	EditorNewTemplateLabel: `ሓድሽ ቅጥዒ`,
	EditorNextTemplateLabel: `ዝቕጽል ቅጥዒ`,
	EditorPasteButtonAppendBeginLabel: `ምውሳኽ...`,
	EditorPasteButtonLabel: `ምልጣፍ .`,
	EditorPasteTemplateWatermark: `ጽሑፍ ምልጣፍ ኣእቱ...`,
	EditorPrevTemplateLabel: `ቅድሚ ሕጂ ዝነበረ ቅጥዒ`,
	EditorRegExLabel: ` ስሩዕ መግለጺ`,
	EditorReplaceAllLabel: `ንኹሉ ምትካእ .`,
	EditorReplaceLabel: `ምትካእ`,
	EditorTemplateContactHint: `<p>እዚ ዓውዲ እዚ በቲ ኽርከብ ዝከኣል ኣድራሻታት (ናይ ፈልቸር ፕላግ የድልዮ) ገይርካ ኣብ ኵሉ ኣጋጣሚታት ናይዚ ንድፊ እዚ ኣብ ብምሉኡ እዚ ሰነድ እዚ ወይ ኣብ ዝዀነ ይኹን ጸኒሑ ክጥቀስ ኢዩ።</p><p> ስለዚ ንኣብነት ኣብዚ ኢ-መይል ኣድራሻ እንተ መሪጽካ እቲ ዝመረጽካዮ ኣድራሻ ኢ-መይል ንዅሉ እቲ ኣብዚ ሰነድ እዚ ዘሎ ኣጋጣሚታት ክትጥቀመሉ ኢኻ።</p>`,
	EditorTemplateContactName: `መርከቢ`,
	EditorTemplateDateTimeCustomHint: `yy = ሓጺር ዓመት<br/>yyy = ነዊሕ ዓመት<br/>መ = ወርሒ (1-12)<br/>MM = ወርሒ (01-12)<br/>ኤም. ኤም. = ወርሒ ሕጽር ዝበለ (Jan, Feb ... ታሕ.<br/>MMMM = ነዊሕ ወርሒ (ጥሪ ለካቲት ... ታሕሳስ)<br/>d = መዓልቲ (1 - 31)<br/>dd = መዓልቲ (01 - 31)<br/>ddd = መዓልቲ እታ ሰሙን ብቓላት (ሰኑይ ሰሉስ ... ሰንበት)<br/>E = ሓጻር መዓልቲ እታ ሰሙን ብቓላት (Mon, Tue ... ጸሓይ)<br/>ዲ - ኦርዲናል መዓልቲ (1ይ 2ይ 3ይ መበል 21 መበል 22 መበል 23 መበል 31 4...)<br/>h = ሰዓት ኣብ ኣም/ምሸት (0-12)<br/>hh = ሰዓት ኣብ ኣም/ምሸት (00-12)<br/>H = ሰዓት ኣብ መዓልቲ (0-23)<br/>HH = ሰዓት ኣብ መዓልቲ (00-23)<br/>mm = ደቒቕ<br/>ss = ካልኣይ<br/>ኤስ. ኤስ. = ሚሊ ሰከንድ<br/>a = AM/PM ምልክት<br/>p = a.m. /p.m. ምልክት`,
	EditorTemplateDateTimeCustomLabel: `ቅቡል ልምዲ`,
	EditorTemplateDateTimeHint: `እቲ ናይ ሕጂ ዕለትን/ወይ ግዜን ምስ ዝለጠፉ ንናይ ዕለት ግዜ ቅጥዒታት ክትክእ እዩ።`,
	EditorTemplateDateTimeName: `ናይ ዕለት ሰዓት`,
	EditorTemplateDynamicHint: `<p>ኵሉ እቲ ኣብዛ ንድፊ እዚኣ ዚፍጸም ነገራት ነቲ እተዋህበ ጽሑፍ ኪጥቀመሉ እዩ።</p>`,
	EditorTemplateDynamicName: `ዳይናሚክ`,
	EditorTemplateEmptyPlaceholder: `{0} ባዶ እዩ...`,
	EditorTemplateStaticHint: `<p>ኵሉ እቲ ኣብዛ ንድፊ እዚኣ ዚፍጸም ነገራት ነቲ እተዋህበ ጽሑፍ ኪጥቀመሉ እዩ።</p>`,
	EditorTemplateStaticName: `ስታቲክ .`,
	EditorTemplateTeaserText: `ተወሳኺ ኣብ ቀረባ እዋን!`,
	EditorTt1: `ጠውቑ`,
	EditorTt2: `ምእራም '<em>{0}</em>' ...`,
	EditorTt3: `ሕብሪ ኣርትዕ ...`,
	EditorTt4: `'<em>{0}</em>' ...`,
	EditorTt5: `ኣቕሓ ኣወግድ`,
	EditorTt6: `ንምክትታል ...`,
	EditorTt7: `ጎቶ '<em>{0}</em>' ...`,
	EditorWatermark: `በጃኹም ተጸበዩ...`,
	EditorWholeWordLabel: ` ምሉእ ቃል`,
	EditorWrapLabel: ` ኣብ ዙርያኡ ምጥቕላል .`,

};