var UiStrings = {
	EditorAppendCloseLabel: `จบท้าย`,
	EditorAppendInlineModeLabel: `เปิดใช้งานบล็อก`,
	EditorAppendLineModeLabel: `เปิดใช้งาน Inline`,
	EditorAppendManualModeLabel: `คู่มือการสลับ`,
	EditorAppendNonManualModeLabel: `คู่มือการสลับ`,
	EditorAppendPauseLabel: `หยุดชั่วคราว`,
	EditorAppendPostLabel: `สลับมาก่อน`,
	EditorAppendPreLabel: `สลับมาก่อน`,
	EditorAppendResumeLabel: `ภาคผนวกกลับมาทำงาน`,
	EditorBgColorLabel: `สีพื้นหลัง`,
	EditorClearAllLabel: `ลบทั้งหมด`,
	EditorClipboardFormatsLabel: `รูปแบบคลิปบอร์ด`,
	EditorConfirmNtfTitle: `ยืนยัน`,
	EditorDeleteAllButtonText: `ลบทั้งหมด`,
	EditorDeleteAllTemplatesNtfText: `แน่ใจหรือว่าต้องการลบการใช้งานทั้งหมดของ '{0}'?

สิ่งนี้ไม่สามารถยกเลิกได้!`,
	EditorEditTemplateDetailsLabel: `แก้ไขรายละเอียด`,
	EditorEditTemplateNameLabel: `ชื่อ`,
	EditorFindLabel: `หา`,
	EditorFontColorLabel: `สีตัวอักษร`,
	EditorFormatPaintLabel: `รูปแบบสี`,
	EditorInSelectionLabel: ` ในการเลือก`,
	EditorInsertImageLabel: `แทรกภาพ`,
	EditorInsertLinkLabel: `แทรกลิงค์`,
	EditorInsertVideoLabel: `แทรกวิดีโอ`,
	EditorMatchCaseLabel: ` เคสจับคู่`,
	EditorNewTemplateLabel: `เทมเพลตใหม่`,
	EditorNextTemplateLabel: `เทมเพลตถัดไป`,
	EditorPasteButtonAppendBeginLabel: `ผนวก...`,
	EditorPasteButtonLabel: `แปะ`,
	EditorPasteTemplateWatermark: `ป้อนข้อความ Paste ...`,
	EditorPrevTemplateLabel: `เทมเพลตก่อนหน้า`,
	EditorRegExLabel: ` การแสดงออกปกติ`,
	EditorReplaceAllLabel: `แทนที่ทั้งหมด`,
	EditorReplaceLabel: `แทนที่`,
	EditorTemplateContactHint: `<p> การใช้ผู้ติดต่อที่มีอยู่ (ต้องใช้ปลั๊กอินดึงข้อมูล) ฟิลด์นี้จะใช้สำหรับทุกอินสแตนซ์ของเทมเพลตนี้ในเอกสารนี้หรือในใด ๆ จะมีการอ้างอิงในภายหลัง </p> <p> ตัวอย่างเช่นหากเลือกที่อยู่อีเมล ที่นี่ฟิลด์อีเมลของผู้ติดต่อที่คุณเลือกจะถูกใช้สำหรับทุกอินสแตนซ์ในเอกสารนี้ </p>`,
	EditorTemplateContactName: `ติดต่อ`,
	EditorTemplateDateTimeCustomHint: `yy = ปีสั้น ๆ <br/> yyyy = ปีที่ยาวนาน <br/> m = เดือน (1-12) <br/> mm = เดือน (01-12) <br/> mmm = ตัวย่อเดือน (มกราคม, ก.พ. .. . ธ.ค. ) <br/> mmmm = เดือนที่ยาวนาน (มกราคม, กุมภาพันธ์ ... ธันวาคม) <br/> d = วัน (1 - 31) <br/> dd = วัน (01 - 31) <br/> ddd = วันของสัปดาห์ด้วยคำพูด (วันจันทร์, วันอังคาร ... วันอาทิตย์) <br/> e = วันสั้น ๆ ของสัปดาห์ด้วยคำพูด (จันทร์, อังคาร ... ดวงอาทิตย์) <br/> D - วันที่ 1 (1, 2nd, 3, 21, 22, 23, 31st, 4 ... ) <br/> h = ชั่วโมงใน AM/PM (0-12) <br/> HH = ชั่วโมงใน AM/PM (00-12) <Br/ > h = ชั่วโมงในแต่ละวัน (0-23) <br/> hh = ชั่วโมงในวัน (00-23) <br/> mm = นาที <br/> ss = วินาที <br/> sss = มิลลิวินาที <br/> A = AM/PM marker <br/> P = A.M./P.M เครื่องทำเครื่องหมาย`,
	EditorTemplateDateTimeCustomLabel: `กำหนดเอง`,
	EditorTemplateDateTimeHint: `วันที่และ/หรือเวลาปัจจุบันจะถูกแทนที่สำหรับเทมเพลต dateTime เมื่อวาง`,
	EditorTemplateDateTimeName: `วันเวลา`,
	EditorTemplateDynamicHint: `<p> การเกิดขึ้นทั้งหมดของเทมเพลตนี้จะใช้ข้อความที่ให้มา </p>`,
	EditorTemplateDynamicName: `พลวัต`,
	EditorTemplateEmptyPlaceholder: `{0} ว่างเปล่า ...`,
	EditorTemplateStaticHint: `<p> การเกิดขึ้นทั้งหมดของเทมเพลตนี้จะใช้ข้อความที่ให้มา </p>`,
	EditorTemplateStaticName: `คงที่`,
	EditorTemplateTeaserText: `เพิ่มเติมเร็ว ๆ นี้!`,
	EditorWatermark: `โปรดรอ...`,
	EditorWholeWordLabel: ` ทั้งคำ`,
	EditorWrapLabel: ` ห่อรอบ ๆ`,

};