var UiStrings = {
	EditorAppendCloseLabel: `Terminați apariția`,
	EditorAppendInlineModeLabel: `Activați bloc`,
	EditorAppendLineModeLabel: `Activați inline`,
	EditorAppendManualModeLabel: `Manual de comutare`,
	EditorAppendNonManualModeLabel: `Manual de comutare`,
	EditorAppendPauseLabel: `Pauză anexa`,
	EditorAppendPostLabel: `Comutați înainte`,
	EditorAppendPreLabel: `Comutați înainte`,
	EditorAppendResumeLabel: `Reluați anexa`,
	EditorBgColorLabel: `Culoare de fundal`,
	EditorClearAllLabel: `Curata tot`,
	EditorClipboardFormatsLabel: `Formate clipboard`,
	EditorConfirmNtfTitle: `A confirma`,
	EditorDeleteAllButtonText: `Sterge tot`,
	EditorDeleteAllTemplatesNtfText: `Ești sigur că vrei să ștergeți toate utilizările „{0}”?

Acest lucru nu poate fi anulat!`,
	EditorEditTemplateDetailsLabel: `Editează detaliile`,
	EditorEditTemplateNameLabel: `Nume`,
	EditorFindLabel: `Găsi`,
	EditorFontColorLabel: `Culoarea fontului`,
	EditorFormatPaintLabel: `Format vopsea`,
	EditorInSelectionLabel: ` În selecție`,
	EditorInsertImageLabel: `Introduceți imaginea`,
	EditorInsertLinkLabel: `Introduceți legătura`,
	EditorInsertVideoLabel: `Introduceți videoclipuri`,
	EditorMatchCaseLabel: ` Caz de potrivire`,
	EditorNewTemplateLabel: `Șablon nou`,
	EditorNextTemplateLabel: `Următorul șablon`,
	EditorPasteButtonAppendBeginLabel: `Adăuga...`,
	EditorPasteButtonLabel: `Pastă`,
	EditorPasteTemplateWatermark: `Introduceți textul paste ...`,
	EditorPrevTemplateLabel: `Șablon anterior`,
	EditorRegExLabel: ` Expresie uzuala`,
	EditorReplaceAllLabel: `Înlocuiește-le pe toate`,
	EditorReplaceLabel: `A inlocui`,
	EditorTemplateContactHint: `<p> Utilizarea contactelor disponibile (necesită un plugin Fetcher) Acest câmp va fi utilizat pentru toate instanțele acestui șablon din acest document sau în orice acesta va fi referit mai târziu. </p> <p> Deci, de exemplu, dacă selectați adresa de e -mail Aici, apoi câmpul de e -mail al contactului selectat va fi utilizat pentru toate instanțele din acest document. </p>`,
	EditorTemplateContactName: `a lua legatura`,
	EditorTemplateDateTimeCustomHint: `yy = an scurt <br/> yyyy = an lung <br/> m = lună (1-12) <br/> mm = lună (01-12) <br/> mmm = luna prescurtare (ianuarie, februarie .. . Dec) <br/> mmmm = luna lungă (ianuarie, februarie ... decembrie) <br/> d = zi (1 - 31) <br/> dd = zi (01 - 31) <br/> ddd = Ziua săptămânii în cuvinte (luni, marți ... duminică) <br/> e = ziua scurtă a săptămânii în cuvinte (mon, tu ... soare) <br/> d - zi ordinală (prima, a 2 -a, 3, 21, 22, 23, 31, 4 ...) <br/> h = oră în AM/PM (0-12) <br/> hh = oră în AM/PM (00-12) <Br/Br/ > H = oră în zi (0-23) <br/> hh = oră în zi (00-23) <br/> mm = minut/br/> ss = al doilea <br/> sss = miliseconds <br/> A = AM/PM Marker <br/> p = a.m./p.m. Marker`,
	EditorTemplateDateTimeCustomLabel: `Personalizat`,
	EditorTemplateDateTimeHint: `Data și/sau ora curente vor fi înlocuite cu șabloanele de date de date atunci când sunt lipite.`,
	EditorTemplateDateTimeName: `Ora datei`,
	EditorTemplateDynamicHint: `<p> Toate evenimentele acestui șablon vor folosi textul furnizat. </p>`,
	EditorTemplateDynamicName: `Dinamic`,
	EditorTemplateEmptyPlaceholder: `{0} este gol ...`,
	EditorTemplateStaticHint: `<p> Toate evenimentele acestui șablon vor folosi textul furnizat. </p>`,
	EditorTemplateStaticName: `Static`,
	EditorTemplateTeaserText: `Mai multe în curând!`,
	EditorWatermark: `Va rugam asteptati...`,
	EditorWholeWordLabel: ` Intregul cuvant`,
	EditorWrapLabel: ` Înfășurați -vă`,

};