var UiStrings = {
	EditorAppendCloseLabel: `Baigti pridėti`,
	EditorAppendInlineModeLabel: `Įgalinti bloką`,
	EditorAppendLineModeLabel: `Įgalinti įterpimą`,
	EditorAppendManualModeLabel: `Perjunkite vadovą`,
	EditorAppendNonManualModeLabel: `Perjunkite vadovą`,
	EditorAppendPauseLabel: `Pauzė priedas`,
	EditorAppendPostLabel: `Perjungti anksčiau`,
	EditorAppendPreLabel: `Perjungti anksčiau`,
	EditorAppendResumeLabel: `Atnaujinti priedą`,
	EditorBgColorLabel: `Fono spalva`,
	EditorClearAllLabel: `Išvalyti viską`,
	EditorClipboardFormatsLabel: `Iškarpų formatai`,
	EditorColorChooserTitle: `Redaktoriaus spalva`,
	EditorConfirmNtfTitle: `Patvirtinti`,
	EditorDeleteAllButtonText: `Ištrinti viską`,
	EditorDeleteAllTemplatesNtfText: `Ar tikrai norite ištrinti visus „{0}“ naudojimo būdus?

Tai negali būti panaikinta!`,
	EditorEditTemplateDetailsLabel: `Redaguoti išsamią informaciją`,
	EditorEditTemplateNameLabel: `vardas`,
	EditorFindLabel: `Rasti`,
	EditorFontColorLabel: `Šrifto spalva`,
	EditorFormatPaintLabel: `Formato dažai`,
	EditorInSelectionLabel: ` Atrankoje`,
	EditorInsertImageLabel: `Įterpkite vaizdą`,
	EditorInsertLinkLabel: `Įterpti nuorodą`,
	EditorInsertVideoLabel: `Įterpti vaizdo įrašą`,
	EditorLinkButtonText: `Sutaupyti`,
	EditorLinkLabel: `Įveskite nuorodą`,
	EditorLinkPlaceholder: `Įveskite URL`,
	EditorMatchCaseLabel: ` Rungtynių atvejis`,
	EditorNewTemplateLabel: `Naujas šablonas`,
	EditorNextTemplateLabel: `Kitas šablonas`,
	EditorPasteButtonAppendBeginLabel: `Pridėkite ...`,
	EditorPasteButtonLabel: `Įklijuoti`,
	EditorPasteTemplateWatermark: `Įveskite įklijavimo tekstą ...`,
	EditorPrevTemplateLabel: `Ankstesnis šablonas`,
	EditorRegExLabel: ` Įprasta išraiška`,
	EditorReplaceAllLabel: `Pakeiskite visus`,
	EditorReplaceLabel: `Pakeiskite`,
	EditorTemplateContactHint: `<p>Naudojant galimus kontaktus (reikalingas fetcher papildinys), šis laukas bus naudojamas visiems šio šablono egzemplioriams šiame dokumente arba bet kuriame, kuriame jis bus nurodytas vėliau.</p><p> Pavyzdžiui, jei čia pasirinkite el. pašto adresą, pasirinkto kontakto el. pašto laukas bus naudojamas visiems šio dokumento atvejams.</p>`,
	EditorTemplateContactName: `kontaktas`,
	EditorTemplateDateTimeCustomHint: `yy = trumpi metai<br/>yyyy = ilgi metai<br/>M = mėnuo (1-12)<br/>MM = mėnuo (01-12)<br/>MMM = mėnesio santrumpa (sausis, vasaris ... Gruodis)<br/>MMMM = ilgas mėnuo (sausis, vasaris ... Gruodis)<br/>d = diena (1 - 31)<br/>dd = diena (01-31)<br/>ddd = savaitės diena žodžiais (pirmadienis, antradienis ... Sekmadienis)<br/>E = trumpa savaitės diena žodžiais (Pirmadienis, Antradienis ... Saulė)<br/>D - Ordino diena (1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = valanda am/pm (0–12)<br/>hh = valanda am/pm (00-12)<br/>H = valanda per dieną (0–23)<br/>HH = valanda per dieną (00–23)<br/>mm = minutė<br/>ss = sekundė<br/>SSS = milisekundės<br/>a = AM/PM žymeklis<br/>p = a.m./p.m. žymeklis`,
	EditorTemplateDateTimeCustomLabel: `Paprotys`,
	EditorTemplateDateTimeHint: `Dabartinė data ir (arba) laikas bus pakeistas į „Datetime“ šablonus, kai jie bus įklijuojami.`,
	EditorTemplateDateTimeName: `Datos laikas`,
	EditorTemplateDynamicHint: `<p>Visuose šio šablono įvykiuose bus naudojamas pateiktas tekstas.</p>`,
	EditorTemplateDynamicName: `Dinamiškas`,
	EditorTemplateEmptyPlaceholder: `{0} tuščias ...`,
	EditorTemplateStaticHint: `<p>Visuose šio šablono įvykiuose bus naudojamas pateiktas tekstas.</p>`,
	EditorTemplateStaticName: `Statinis`,
	EditorTemplateTeaserText: `Greitai bus daugiau!`,
	EditorTt1: `Spustelėkite`,
	EditorTt2: `Redaguoti '<em> {0} </em>' ...`,
	EditorTt3: `Redaguoti spalvą ...`,
	EditorTt4: `Pašalinti '<em> {0} </em>' ...`,
	EditorTt5: `pašalinti daiktą`,
	EditorTt6: `Sekti ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Prašau palauk...`,
	EditorWholeWordLabel: ` Visas žodis`,
	EditorWrapLabel: ` Apvynioti`,

};