var UiStrings = {
	EditorAppendCloseLabel: `Pabeigt pievienošanos`,
	EditorAppendInlineModeLabel: `Iespējot bloku`,
	EditorAppendLineModeLabel: `Iespējot inline`,
	EditorAppendManualModeLabel: `Pārslēgt rokasgrāmatu`,
	EditorAppendNonManualModeLabel: `Pārslēgt rokasgrāmatu`,
	EditorAppendPauseLabel: `Pauze Pievienot`,
	EditorAppendPostLabel: `Pārslēgt iepriekš`,
	EditorAppendPreLabel: `Pārslēgt iepriekš`,
	EditorAppendResumeLabel: `Atsākt pievienoties`,
	EditorBgColorLabel: `Fona krāsa`,
	EditorClearAllLabel: `Iztīrīt visu`,
	EditorClipboardFormatsLabel: `Starpliktuves formāti`,
	EditorConfirmNtfTitle: `Apstiprināt`,
	EditorDeleteAllButtonText: `Dzēst visus`,
	EditorDeleteAllTemplatesNtfText: `Vai esat pārliecināts, ka vēlaties izdzēst visus “{0}” lietojumus?

To nevar atsaukt!`,
	EditorEditTemplateDetailsLabel: `Rediģēt informāciju`,
	EditorEditTemplateNameLabel: `Nosaukt`,
	EditorFindLabel: `Atrast`,
	EditorFontColorLabel: `Fonta krāsa`,
	EditorFormatPaintLabel: `Formāta krāsa`,
	EditorInSelectionLabel: ` Atlasē`,
	EditorInsertImageLabel: `Ievietojiet attēlu`,
	EditorInsertLinkLabel: `Ievietot saiti`,
	EditorInsertVideoLabel: `Ievietot video`,
	EditorMatchCaseLabel: ` Atbilstība`,
	EditorNewTemplateLabel: `Jauna veidne`,
	EditorNextTemplateLabel: `Nākamā veidne`,
	EditorPasteButtonAppendBeginLabel: `Pievienot ...`,
	EditorPasteButtonLabel: `Pastā`,
	EditorPasteTemplateWatermark: `Ievadiet pastas tekstu ...`,
	EditorPrevTemplateLabel: `Iepriekšējā veidne`,
	EditorRegExLabel: ` Regulāra izteiksme`,
	EditorReplaceAllLabel: `Nomainīt visu`,
	EditorReplaceLabel: `Aizvietot`,
	EditorTemplateContactHint: `<p>Izmantojot pieejamās kontaktpersonas (nepieciešams ienesuma spraudnis), šis lauks tiks izmantots visiem šīs veidnes gadījumiem visā šajā dokumentā vai jebkurā citā, uz kuru vēlāk tiks sniegta atsauce.</p><p> Tā, piemēram, ja šeit atlasiet e-pasta adresi, tad atlasītā kontaktpersonas e-pasta lauks tiks izmantots visiem šī dokumenta gadījumiem.</p>`,
	EditorTemplateContactName: `Saskare`,
	EditorTemplateDateTimeCustomHint: `yy = īss gads<br/>gggg = garš gads<br/>M = mēnesis (1-12)<br/>MM = mēnesis (01-12)<br/>MMM = mēneša saīsinājums (Jan, Feb ... decembrī)<br/>MMMM = garais mēnesis (janvāris, februāris ... decembrī)<br/>d = diena (1 - 31)<br/>dd = diena (01 - 31)<br/>ddd = nedēļas diena vārdos (pirmdiena, otrdiena ... Svētdiena)<br/>E = īsa nedēļas diena vārdos (Mon, Tue ... Saule)<br/>D - Kārtas diena (1., 2., 3., 21., 22., 23., 31., 4.)<br/>h = stunda am/pm (0-12)<br/>hh = stunda am/pm (00-12)<br/>H = stunda dienā (0-23)<br/>HH = stunda dienā (00-23)<br/>mm = minūte<br/>ss = sekunde<br/>SSS = milisekundes<br/>a = AM/PM marķieris<br/>p = a.m./p.m. marķieris`,
	EditorTemplateDateTimeCustomLabel: `Paraža`,
	EditorTemplateDateTimeHint: `Pašreizējais datums un/vai laiks tiks aizstāts ar datuma laika veidnēm, kad tās tiks ielīmētas.`,
	EditorTemplateDateTimeName: `Datums Laiks`,
	EditorTemplateDynamicHint: `<p>Visās šīs veidnes parādīšanās reizēs tiks izmantots norādītais teksts.</p>`,
	EditorTemplateDynamicName: `Dinamisks`,
	EditorTemplateEmptyPlaceholder: `{0} ir tukšs ...`,
	EditorTemplateStaticHint: `<p>Visās šīs veidnes parādīšanās reizēs tiks izmantots norādītais teksts.</p>`,
	EditorTemplateStaticName: `Statisks`,
	EditorTemplateTeaserText: `Vairāk drīzumā!`,
	EditorWatermark: `Lūdzu uzgaidiet...`,
	EditorWholeWordLabel: ` Vesels vārds`,
	EditorWrapLabel: ` Aptīt`,

};