var UiStrings = {
	EditorAppendCloseLabel: `এপ্লাইড শেষ কৰক`,
	EditorAppendInlineModeLabel: `ব্লক সামৰ্থবান কৰক`,
	EditorAppendLineModeLabel: `ইনলাইন সামৰ্থবান কৰক`,
	EditorAppendManualModeLabel: `টগল মেনুৱেল`,
	EditorAppendNonManualModeLabel: `টগল মেনুৱেল`,
	EditorAppendPauseLabel: `বিৰতিৰ সংযোজন`,
	EditorAppendPostLabel: `টগল আগতে`,
	EditorAppendPreLabel: `টগল আগতে`,
	EditorAppendResumeLabel: `ৰিজ্যুম এপেণ্ড`,
	EditorBgColorLabel: `রঙ`,
	EditorClearAllLabel: `সকলো পৰিষ্কাৰ কৰক`,
	EditorClipboardFormatsLabel: `ক্লিপবোৰ্ড ফৰ্মেটসমূহ`,
	EditorConfirmNtfTitle: `নিশ্চিত`,
	EditorDeleteAllButtonText: `সকলো মচি পেলাওক`,
	EditorDeleteAllTemplatesNtfText: `আপুনি নিশ্চিত নেকি যে আপুনি '{0}' ৰ সকলো ব্যৱহাৰ মচি পেলাব বিচাৰে?

এইটোক পুনৰ কৰিব নোৱাৰি!`,
	EditorEditTemplateDetailsLabel: `বিৱৰণ সম্পাদনা কৰক`,
	EditorEditTemplateNameLabel: `নাম`,
	EditorFindLabel: `সন্ধান কৰা`,
	EditorFontColorLabel: `ফন্ট ৰঙৰ ৰং`,
	EditorFormatPaintLabel: `ফৰ্মেট পেইন্ট`,
	EditorInSelectionLabel: ` নিৰ্বাচনত`,
	EditorInsertImageLabel: `ছবি সন্নিবিষ্ট কৰক`,
	EditorInsertLinkLabel: `লিংক সন্নিবিষ্ট কৰক`,
	EditorInsertVideoLabel: `ভিডিঅ' সন্নিবিষ্ট কৰক`,
	EditorMatchCaseLabel: ` মেচ কেছ`,
	EditorNewTemplateLabel: `নতুন টেমপ্লেট`,
	EditorNextTemplateLabel: `পৰৱৰ্তী সাঁচ`,
	EditorPasteButtonAppendBeginLabel: `append...`,
	EditorPasteButtonLabel: `পেষ্ট কৰক`,
	EditorPasteTemplateWatermark: `লিখনী পেষ্ট কৰক...`,
	EditorPrevTemplateLabel: `পূৰ্বৰ সাঁচ`,
	EditorRegExLabel: ` নিয়মিত অভিব্যক্তি`,
	EditorReplaceAllLabel: `সকলো সলনি কৰক`,
	EditorReplaceLabel: `প্ৰৰ্তিস্থাপন কৰা`,
	EditorTemplateContactHint: `<p>উপলব্ধ সম্পৰ্কসমূহ ব্যৱহাৰ কৰি (ফেচাৰ প্লাগিনৰ প্ৰয়োজন) এই ফিল্ডটো এই ডকুমেণ্টত এই টেমপ্লেটৰ সকলো উদাহৰণৰ বাবে ব্যৱহাৰ কৰা হ'ব বা যিকোনো এটাত ইয়াক পিছত উল্লেখ কৰা হ'ব।</p><p> গতিকে উদাহৰণ স্বৰূপে যদি ইয়াত ইমেইল ঠিকনা বাছনি কৰক তেন্তে আপুনি বাছনি কৰা সম্পৰ্কৰ ইমেইল ক্ষেত্ৰটো এই ডকুমেণ্টৰ সকলো উদাহৰণৰ বাবে ব্যৱহাৰ কৰা হ'ব।</p>`,
	EditorTemplateContactName: `যোগাযোগ কৰক`,
	EditorTemplateDateTimeCustomHint: `য় = চমু বছৰ<br/>য়িয়ি = দীঘলীয়া বছৰ<br/>ম = মাহ (1-12)<br/>এমএম = মাহ (01-12)<br/>এমএমএম = মাহৰ সংক্ষিপ্তৰূপ (জানুৱাৰী, ফেব্ৰুৱাৰী ... ডিচেম্বৰ)<br/>এমএমএমএম = দীঘলীয়া মাহ (জানুৱাৰী, ফেব্ৰুৱাৰী ... ডিচেম্বৰ)<br/>ঘ = দিন (1 - 31)<br/>ডিডি = দিন (01 - 31)<br/>ডিডিডি = সপ্তাহৰ দিনটো শব্দত (সোমবাৰে, মঙলবাৰে... দেওবাৰ)<br/>ই = সপ্তাহৰ চমু দিন শব্দত (সোম, মঙ্গল... সূৰ্য)<br/>ডি - অৰ্ডিনেল দিন (প্ৰথম, দ্বিতীয়, তৃতীয়, 21, 22, 23, 31, 4ৰ্থ...)<br/>হ = ৰাতিপুৱা/সন্ধিয়া ঘণ্টা (0-12)<br/>হ = ৰাতিপুৱা/সন্ধিয়া ঘণ্টা (00-12)<br/>হ = দিনত ঘণ্টা (0-23)<br/>এইচএইচ = দিনত ঘণ্টা (00-23)<br/>মিমি = মিনিট<br/>এছএছ = দ্বিতীয়<br/>এছ.এছ.এছ. = মিলিছেকেণ্ড<br/>ক = এএম/পিএম মাৰ্কাৰ<br/>প = এ.এম./পি.এম. মাৰ্কাৰ`,
	EditorTemplateDateTimeCustomLabel: `অনুকুলন কৰা`,
	EditorTemplateDateTimeHint: `বৰ্তমান তাৰিখ আৰু/বা সময় তাৰিখ সময় সাঁচসমূহৰ বাবে প্ৰতিস্থাপন কৰা হ'ব যেতিয়া সিহত পেষ্ট কৰা হয়।`,
	EditorTemplateDateTimeName: `তাৰিখৰ সময়`,
	EditorTemplateDynamicHint: `<p>এই টেমপ্লেটৰ সকলো ঘটনাই প্ৰদান কৰা পাঠ ব্যৱহাৰ কৰিব।</p>`,
	EditorTemplateDynamicName: `ডাইনামিক`,
	EditorTemplateEmptyPlaceholder: `{0} খালী...`,
	EditorTemplateStaticHint: `<p>এই টেমপ্লেটৰ সকলো ঘটনাই প্ৰদান কৰা পাঠ ব্যৱহাৰ কৰিব।</p>`,
	EditorTemplateStaticName: `ষ্টেটিক`,
	EditorTemplateTeaserText: `অতি সোনকালে আহিবলগীয়া আৰু অধিক!`,
	EditorWatermark: `অনুগ্ৰহ কৰি অপেক্ষা কৰক...`,
	EditorWholeWordLabel: ` গোটেই শব্দ`,
	EditorWrapLabel: ` চাৰিওফালে মেৰিয়াই লওক`,

};