var UiStrings = {
	EditorAppendCloseLabel: `Selesai Menambahkan`,
	EditorAppendInlineModeLabel: `Aktifkan blok`,
	EditorAppendLineModeLabel: `Aktifkan inline`,
	EditorAppendManualModeLabel: `Toggle Manual`,
	EditorAppendNonManualModeLabel: `Toggle Manual`,
	EditorAppendPauseLabel: `Jeda Tambahkan`,
	EditorAppendPostLabel: `Beralih sebelumnya`,
	EditorAppendPreLabel: `Beralih sebelumnya`,
	EditorAppendResumeLabel: `Lanjutkan menambahkan`,
	EditorBgColorLabel: `Warna latar belakang`,
	EditorClearAllLabel: `Bersihkan semua`,
	EditorClipboardFormatsLabel: `Format clipboard`,
	EditorConfirmNtfTitle: `Mengonfirmasi`,
	EditorDeleteAllButtonText: `Hapus semua`,
	EditorDeleteAllTemplatesNtfText: `Apakah Anda yakin ingin menghapus semua penggunaan '{0}'?

Ini tidak dapat dibatalkan!`,
	EditorEditTemplateDetailsLabel: `Edit detail`,
	EditorEditTemplateNameLabel: `Nama`,
	EditorFindLabel: `Menemukan`,
	EditorFontColorLabel: `Warna huruf`,
	EditorFormatPaintLabel: `Format cat`,
	EditorInSelectionLabel: ` Dalam seleksi`,
	EditorInsertImageLabel: `Masukkan gambar`,
	EditorInsertLinkLabel: `Masukkan tautan`,
	EditorInsertVideoLabel: `Sisipkan video`,
	EditorMatchCaseLabel: ` Kasing pertandingan`,
	EditorNewTemplateLabel: `Template baru`,
	EditorNextTemplateLabel: `Template berikutnya`,
	EditorPasteButtonAppendBeginLabel: `Menambahkan...`,
	EditorPasteButtonLabel: `Tempel`,
	EditorPasteTemplateWatermark: `Masukkan teks pasta ...`,
	EditorPrevTemplateLabel: `Template sebelumnya`,
	EditorRegExLabel: ` Ekspresi reguler`,
	EditorReplaceAllLabel: `Menggantikan semua`,
	EditorReplaceLabel: `Mengganti`,
	EditorTemplateContactHint: `<p> Menggunakan kontak yang tersedia (memerlukan plugin fetcher) Bidang ini akan digunakan untuk semua contoh templat ini di seluruh dokumen ini atau di mana pun akan direferensikan di nanti. </p> <p> Jadi misalnya jika memilih alamat email Di sini kemudian bidang email dari kontak yang Anda pilih akan digunakan untuk semua contoh dalam dokumen ini. </p>`,
	EditorTemplateContactName: `Kontak`,
	EditorTemplateDateTimeCustomHint: `yy = tahun pendek <br/> yyyy = tahun panjang <br/> m = bulan (1-12) <br/> mm = bulan (01-12) <br/> mmm = singkatan bulan (Jan, Feb .. . Dec) <br/> mmmm = bulan panjang (Januari, Februari ... Desember) <br/> d = hari (1 - 31) <br/> dd = hari (01 - 31) <br/> ddd = Day of the Week in Words (Senin, Selasa ... Minggu) <br/> E = Hari Pendek dalam seminggu dalam kata -kata (Sen, Sel ... matahari) <br/> D - Hari Ordinal (1, 2, 3, 21, 22, 23, 31, 4 ...) <br/> h = jam dalam AM/PM (0-12) <br/> hh = jam dalam AM/pm (00-12) <br/ > H = jam demi hari (0-23) <br/> hh = jam demi hari (00-23) <br/> mm = menit <br/> ss = kedua <br/> sss = milidetik <br/> A = AM/PM Marker <br/> p = a.m./p.m. penanda`,
	EditorTemplateDateTimeCustomLabel: `Kebiasaan`,
	EditorTemplateDateTimeHint: `Tanggal dan/atau waktu saat ini akan diganti dengan template datetime saat ditempel.`,
	EditorTemplateDateTimeName: `Tanggal Waktu`,
	EditorTemplateDynamicHint: `<p> Semua kejadian templat ini akan menggunakan teks yang disediakan. </p>`,
	EditorTemplateDynamicName: `Dinamis`,
	EditorTemplateEmptyPlaceholder: `{0} kosong ...`,
	EditorTemplateStaticHint: `<p> Semua kejadian templat ini akan menggunakan teks yang disediakan. </p>`,
	EditorTemplateStaticName: `Statis`,
	EditorTemplateTeaserText: `Selebihnya datang segera!`,
	EditorWatermark: `Harap tunggu...`,
	EditorWholeWordLabel: ` Seluruh kata`,
	EditorWrapLabel: ` Membungkus`,

};