var UiStrings = {
	EditorAppendCloseLabel: `Slutföra`,
	EditorAppendInlineModeLabel: `Aktivera block`,
	EditorAppendLineModeLabel: `Aktivera inline`,
	EditorAppendManualModeLabel: `Växla manual`,
	EditorAppendNonManualModeLabel: `Växla manual`,
	EditorAppendPauseLabel: `Pausa bifogas`,
	EditorAppendPostLabel: `Växla innan`,
	EditorAppendPreLabel: `Växla innan`,
	EditorAppendResumeLabel: `Återuppta`,
	EditorBgColorLabel: `Bakgrundsfärg`,
	EditorClearAllLabel: `Rensa alla`,
	EditorClipboardFormatsLabel: `Urklippsformat`,
	EditorColorChooserTitle: `Redaktörsfärg`,
	EditorConfirmNtfTitle: `Bekräfta`,
	EditorDeleteAllButtonText: `Radera allt`,
	EditorDeleteAllTemplatesNtfText: `Är du säker på att du vill ta bort alla användningar av '{0}'?

Detta kan inte göras ogjort!`,
	EditorEditTemplateDetailsLabel: `Redigera detaljer`,
	EditorEditTemplateNameLabel: `namn`,
	EditorFindLabel: `Hitta`,
	EditorFontColorLabel: `Fontfärg`,
	EditorFormatPaintLabel: `Formatfärg`,
	EditorInSelectionLabel: ` I urval`,
	EditorInsertImageLabel: `Infoga bild`,
	EditorInsertLinkLabel: `Infoga länk`,
	EditorInsertVideoLabel: `Infoga video`,
	EditorLinkButtonText: `Spara`,
	EditorLinkLabel: `Ange länken`,
	EditorLinkPlaceholder: `Skriv in URL`,
	EditorMatchCaseLabel: ` Liknande fall`,
	EditorNewTemplateLabel: `Ny mall`,
	EditorNextTemplateLabel: `Nästa mall`,
	EditorPasteButtonAppendBeginLabel: `Bifoga...`,
	EditorPasteButtonLabel: `Klistra`,
	EditorPasteButtonLabelMobile: `Kopiera`,
	EditorPasteTemplateWatermark: `Ange pasta text ...`,
	EditorPrevTemplateLabel: `Föregående mall`,
	EditorRegExLabel: ` Vanligt uttryck`,
	EditorReplaceAllLabel: `Ersätt alla`,
	EditorReplaceLabel: `Byta ut`,
	EditorTemplateContactHint: `<p>Med hjälp av tillgängliga kontakter (kräver ett hämtningsplugin) kommer det här fältet att användas för alla instanser av den här mallen i det här dokumentet eller i alla som det kommer att refereras till senare.</p><p> Om du till exempel väljer e-postadress här kommer e-postfältet för den kontakt du väljer att användas för alla förekomster i det här dokumentet.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kort år<br/>yyyy = långt år<br/>M = månad (1-12)<br/>MM = månad (01-12)<br/>MMM = månadsförkortning (jan, feb ... Dec)<br/>MMMM = lång månad (januari, februari ... december)<br/>d = dag (1 - 31)<br/>dd = dag (01 - 31)<br/>ddd = veckodag i ord (måndag, tisdag ... Söndag)<br/>E = kort veckodag i ord (mån, tis ... Sön)<br/>D - Ordningsdag (1:a, 2:a, 3:e, 21:a, 22:a, 23:e, 31:a, 4:e...)<br/>h = timme i am/pm (0-12)<br/>hh = timme i am/pm (00-12)<br/>H = timme på dagen (0-23)<br/>HH = timme på dagen (00-23)<br/>mm = minut<br/>ss = sekund<br/>SSS = millisekunder<br/>a = AM/PM-markör<br/>p = a.m./p.m. markör`,
	EditorTemplateDateTimeCustomLabel: `Beställnings`,
	EditorTemplateDateTimeHint: `Det aktuella datumet och/eller tiden kommer att ersättas med DateTime -mallar när de klistras in.`,
	EditorTemplateDateTimeName: `Datum Tid`,
	EditorTemplateDynamicHint: `<p>Alla förekomster av den här mallen kommer att använda den angivna texten.</p>`,
	EditorTemplateDynamicName: `Dynamisk`,
	EditorTemplateEmptyPlaceholder: `{0} är tomt ...`,
	EditorTemplateStaticHint: `<p>Alla förekomster av den här mallen kommer att använda den angivna texten.</p>`,
	EditorTemplateStaticName: `Statisk`,
	EditorTemplateTeaserText: `Mer kommer snart!`,
	EditorTt1: `Klick`,
	EditorTt2: `redigera '<em> {0} </em>' ...`,
	EditorTt3: `Redigera färg ...`,
	EditorTt4: `Ta bort '<em> {0} </em>' ...`,
	EditorTt5: `ta bort sak`,
	EditorTt6: `att följa ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Vänta...`,
	EditorWholeWordLabel: ` Hela världen`,
	EditorWrapLabel: ` Vira runt`,

};