var UiStrings = {
	EditorAppendCloseLabel: `అనుబంధాన్ని పూర్తి చేయండి`,
	EditorAppendInlineModeLabel: `బ్లాక్‌ను ప్రారంభించండి`,
	EditorAppendLineModeLabel: `ఇన్లైన్‌ను ప్రారంభించండి`,
	EditorAppendManualModeLabel: `టోగుల్ మాన్యువల్`,
	EditorAppendNonManualModeLabel: `టోగుల్ మాన్యువల్`,
	EditorAppendPauseLabel: `PAUSE అనుబంధం`,
	EditorAppendPostLabel: `ముందు టోగుల్ చేయండి`,
	EditorAppendPreLabel: `ముందు టోగుల్ చేయండి`,
	EditorAppendResumeLabel: `పున ume ప్రారంభం అనుబంధం`,
	EditorBgColorLabel: `నేపథ్య రంగు`,
	EditorClearAllLabel: `అన్నీ క్లియర్ చేయండి`,
	EditorClipboardFormatsLabel: `క్లిప్‌బోర్డ్ ఫార్మాట్‌లు`,
	EditorConfirmNtfTitle: `నిర్ధారించండి`,
	EditorDeleteAllButtonText: `అన్నిటిని తొలిగించు`,
	EditorDeleteAllTemplatesNtfText: `మీరు '{0}' యొక్క అన్ని ఉపయోగాలను తొలగించాలనుకుంటున్నారా?

ఇది రద్దు చేయబడదు!`,
	EditorEditTemplateDetailsLabel: `వివరాలను సవరించండి`,
	EditorEditTemplateNameLabel: `పేరు`,
	EditorFindLabel: `కనుగొనండి`,
	EditorFontColorLabel: `ఫాంట్ కలర్`,
	EditorFormatPaintLabel: `ఫార్మాట్ పెయింట్`,
	EditorInSelectionLabel: ` ఎంపికలో`,
	EditorInsertImageLabel: `చిత్రాన్ని చొప్పించండి`,
	EditorInsertLinkLabel: `లింక్‌ను చొప్పించండి`,
	EditorInsertVideoLabel: `వీడియోను చొప్పించండి`,
	EditorMatchCaseLabel: ` మ్యాచ్ కేసు`,
	EditorNewTemplateLabel: `కొత్త టెంప్లేట్`,
	EditorNextTemplateLabel: `తదుపరి టెంప్లేట్`,
	EditorPasteButtonAppendBeginLabel: `అనుబంధం ...`,
	EditorPasteButtonLabel: `అతికించండి`,
	EditorPasteTemplateWatermark: `పేస్ట్ వచనాన్ని నమోదు చేయండి ...`,
	EditorPrevTemplateLabel: `మునుపటి టెంప్లేట్`,
	EditorRegExLabel: ` సాధారణ వ్యక్తీకరణ`,
	EditorReplaceAllLabel: `అన్నీ భర్తీ చేయండి`,
	EditorReplaceLabel: `భర్తీ`,
	EditorTemplateContactHint: `<p> అందుబాటులో ఉన్న పరిచయాలను ఉపయోగించడం (ఫెచర్ ప్లగ్ఇన్ అవసరం) ఈ ఫీల్డ్ ఈ పత్రం అంతటా ఈ టెంప్లేట్ యొక్క అన్ని సందర్భాలకు ఉపయోగించబడుతుంది లేదా ఏదైనా తరువాత సూచించబడుతుంది. </p> <p> కాబట్టి ఉదాహరణకు ఇమెయిల్ చిరునామాను ఎంచుకుంటే ఇక్కడ మీరు ఎంచుకున్న పరిచయం యొక్క ఇమెయిల్ ఫీల్డ్ ఈ పత్రంలోని అన్ని సందర్భాలకు ఉపయోగించబడుతుంది. </p>`,
	EditorTemplateContactName: `సంప్రదించండి`,
	EditorTemplateDateTimeCustomHint: `yy = చిన్న సంవత్సరం <br/> yyyyy = లాంగ్ ఇయర్ <br/> M = నెల (1-12) <br/> mm = నెల (01-12) <br/> mmm = నెల సంక్షిప్తీకరణ (జనవరి, ఫిబ్రవరి .. . పదాలలో వారపు రోజు (సోమవారం, మంగళవారం ... ఆదివారం) <br/> ఇ = వారపు చిన్న రోజు పదాలలో 3 వ, 21 వ, 22 వ, 23 వ, 31 వ, 4 వ ...) <br/> హెచ్ = am/pm (0-12) లో గంట (0-12) <br/> am/pm (00-12) <br/ . a = am/pm మార్కర్ <br/> p = a.m./p.m. మార్కర్`,
	EditorTemplateDateTimeCustomLabel: `ఆచారం`,
	EditorTemplateDateTimeHint: `ప్రస్తుత తేదీ మరియు/లేదా సమయం డేట్‌టైమ్ టెంప్లేట్‌లకు అతికించబడినప్పుడు ప్రత్యామ్నాయం చేయబడుతుంది.`,
	EditorTemplateDateTimeName: `తేదీ సమయం`,
	EditorTemplateDynamicHint: `<p> ఈ టెంప్లేట్ యొక్క అన్నీ అందించిన వచనాన్ని ఉపయోగిస్తాయి. </p>`,
	EditorTemplateDynamicName: `డైనమిక్`,
	EditorTemplateEmptyPlaceholder: `{0} ఖాళీగా ఉంది ...`,
	EditorTemplateStaticHint: `<p> ఈ టెంప్లేట్ యొక్క అన్నీ అందించిన వచనాన్ని ఉపయోగిస్తాయి. </p>`,
	EditorTemplateStaticName: `స్టాటిక్`,
	EditorTemplateTeaserText: `త్వరలో మరిన్ని రాబోతున్నాయి!`,
	EditorWatermark: `దయచేసి వేచి ఉండండి ...`,
	EditorWholeWordLabel: ` మొత్తం పదం`,
	EditorWrapLabel: ` చుట్టూ చుట్టండి`,

};