var UiStrings = {
	EditorAppendCloseLabel: `לסיים את הוספת`,
	EditorAppendInlineModeLabel: `אפשר בלוק`,
	EditorAppendLineModeLabel: `אפשר מינון`,
	EditorAppendManualModeLabel: `מדריך לחלק`,
	EditorAppendNonManualModeLabel: `מדריך לחלק`,
	EditorAppendPauseLabel: `הוספה הוספה`,
	EditorAppendPostLabel: `לעבור לפני כן`,
	EditorAppendPreLabel: `לעבור לפני כן`,
	EditorAppendResumeLabel: `לחדש את הוספה`,
	EditorBgColorLabel: `צבע רקע`,
	EditorClearAllLabel: `לנקות הכל`,
	EditorClipboardFormatsLabel: `פורמטים של לוח`,
	EditorColorChooserTitle: `צבע עורך`,
	EditorConfirmNtfTitle: `לְאַשֵׁר`,
	EditorDeleteAllButtonText: `מחק הכל`,
	EditorDeleteAllTemplatesNtfText: `האם אתה בטוח שאתה רוצה למחוק את כל השימושים של '{0}'?

אי אפשר לבטל את זה!`,
	EditorEditTemplateDetailsLabel: `לערוך את הפרטים`,
	EditorEditTemplateNameLabel: `שֵׁם`,
	EditorFindLabel: `למצוא`,
	EditorFontColorLabel: `צבע גופן`,
	EditorFormatPaintLabel: `פורמט צבע`,
	EditorInSelectionLabel: ` בבחירה`,
	EditorInsertImageLabel: `הוסף תמונה`,
	EditorInsertLinkLabel: `הכנס קישור`,
	EditorInsertVideoLabel: `הכנס וידאו`,
	EditorLinkButtonText: `להציל`,
	EditorLinkLabel: `הזן קישור`,
	EditorLinkPlaceholder: `הזן כתובת אתר`,
	EditorMatchCaseLabel: ` מקרה התאמה`,
	EditorNewTemplateLabel: `תבנית חדשה`,
	EditorNextTemplateLabel: `התבנית הבאה`,
	EditorPasteButtonAppendBeginLabel: `לְצַרֵף...`,
	EditorPasteButtonLabel: `לְהַדבִּיק`,
	EditorPasteButtonLabelMobile: `עותק`,
	EditorPasteTemplateWatermark: `הזן טקסט הדבק ...`,
	EditorPrevTemplateLabel: `תבנית קודמת`,
	EditorRegExLabel: ` הבעה רגילה`,
	EditorReplaceAllLabel: `החלף הכל`,
	EditorReplaceLabel: `החלף`,
	EditorTemplateContactHint: `<p>באמצעות אנשי קשר זמינים (דורש תוסף fetcher) שדה זה ישמש עבור כל המופעים של תבנית זו במסמך זה או בכל אחד מהם הוא יופנה מאוחר יותר.</p><p> כך, לדוגמה, אם תבחר כתובת דוא"ל כאן, שדה הדוא"ל של איש הקשר שתבחר ישמש עבור כל המופעים במסמך זה.</p>`,
	EditorTemplateContactName: `איש קשר`,
	EditorTemplateDateTimeCustomHint: `yy = שנה קצרה<br/>yyyy = שנה ארוכה<br/>M = חודש (1-12)<br/>MM = חודש (01-12)<br/>MMM = קיצור חודש (ינואר, פברואר ... דצמ')<br/>MMMM = חודש ארוך (ינואר, פברואר ... דצמבר)<br/>d = יום (1 - 31)<br/>DD = יום (01 - 31)<br/>ddd = יום בשבוע במילים (שני, שלישי ... יום ראשון)<br/>E = יום קצר בשבוע במילים (שני, שלישי ... א')<br/>D - יום רגיל (1, 2, 3, 21, 22, 23, 31, 4...)<br/>h = שעה בבוקר/בערב (0-12)<br/>hh = שעה בבוקר/בערב (00-12)<br/>H = שעה ביום (0-23)<br/>HH = שעה ביום (00-23)<br/>מ"מ = דקה<br/>SS = שנייה<br/>SSS = אלפיות שנייה<br/>a = סמן AM/PM<br/>p = סמן a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `המותאם אישית`,
	EditorTemplateDateTimeHint: `התאריך ו/או השעה הנוכחיים יחליפו תבניות של תאריך תאריך כאשר הם מודבקים.`,
	EditorTemplateDateTimeName: `תאריך שעה`,
	EditorTemplateDynamicHint: `<p>כל המופעים של תבנית זו ישתמשו בטקסט שסופק.</p>`,
	EditorTemplateDynamicName: `דִינָמִי`,
	EditorTemplateEmptyPlaceholder: `{0} ריק ...`,
	EditorTemplateStaticHint: `<p>כל המופעים של תבנית זו ישתמשו בטקסט שסופק.</p>`,
	EditorTemplateStaticName: `סטָטִי`,
	EditorTemplateTeaserText: `עוד בקרוב!`,
	EditorTt1: `נְקִישָׁה`,
	EditorTt2: `ערוך '<em> {0} </em>' ...`,
	EditorTt3: `ערוך צבע ...`,
	EditorTt4: `הסר '<em> {0} </em>' ...`,
	EditorTt5: `הסר פריט`,
	EditorTt6: `לעקוב ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `המתן בבקשה...`,
	EditorWholeWordLabel: ` כל העולם`,
	EditorWrapLabel: ` לעטוף`,

};