var UiStrings = {
	EditorAppendCloseLabel: `Viimeistellä`,
	EditorAppendInlineModeLabel: `Ottaa käyttöön lohko`,
	EditorAppendLineModeLabel: `Ottaa käyttöön`,
	EditorAppendManualModeLabel: `Vaihtaa käsikirja`,
	EditorAppendNonManualModeLabel: `Vaihtaa käsikirja`,
	EditorAppendPauseLabel: `Tauko`,
	EditorAppendPostLabel: `Kypsyä ennen`,
	EditorAppendPreLabel: `Kypsyä ennen`,
	EditorAppendResumeLabel: `Jatkaa liitettä`,
	EditorBgColorLabel: `Taustaväri`,
	EditorClearAllLabel: `Tyhjennä`,
	EditorClipboardFormatsLabel: `Leikepöydän muodot`,
	EditorColorChooserTitle: `Toimittajan väri`,
	EditorConfirmNtfTitle: `Vahvistaa`,
	EditorDeleteAllButtonText: `Poista kaikki`,
	EditorDeleteAllTemplatesNtfText: `Oletko varma, että haluat poistaa kaikki '{0}' käytöt?

Tätä ei voi peruuttaa!`,
	EditorEditTemplateDetailsLabel: `Muokkaa yksityiskohtia`,
	EditorEditTemplateNameLabel: `Nimi`,
	EditorFindLabel: `löytö`,
	EditorFontColorLabel: `Fontin väri`,
	EditorFormatPaintLabel: `Muotoilla maali`,
	EditorInSelectionLabel: ` Valinnassa`,
	EditorInsertImageLabel: `Lisätä kuva`,
	EditorInsertLinkLabel: `Aseta linkki`,
	EditorInsertVideoLabel: `Lisää video`,
	EditorLinkButtonText: `Tallentaa`,
	EditorLinkLabel: `Antaa linkki`,
	EditorLinkPlaceholder: `Syötä URL`,
	EditorMatchCaseLabel: ` Kotelo`,
	EditorNewTemplateLabel: `Uusi malli`,
	EditorNextTemplateLabel: `Seuraava malli`,
	EditorPasteButtonAppendBeginLabel: `Liitä ...`,
	EditorPasteButtonLabel: `Liittää`,
	EditorPasteTemplateWatermark: `Kirjoita liitä teksti ...`,
	EditorPrevTemplateLabel: `Aikaisempi malli`,
	EditorRegExLabel: ` Tavallinen ilme`,
	EditorReplaceAllLabel: `Korvaa kaikki`,
	EditorReplaceLabel: `Korvata`,
	EditorTemplateContactHint: `<p>Käytettävissä olevien yhteystietojen avulla (vaatii fetcher-laajennuksen) tätä kenttää käytetään kaikissa tämän mallin esiintymissä tässä asiakirjassa tai missä tahansa, johon siihen viitataan myöhemmin.</p><p> Jos esimerkiksi valitset sähköpostiosoitteen tässä, valitsemasi yhteyshenkilön sähköpostikenttää käytetään kaikissa tämän asiakirjan esiintymissä.</p>`,
	EditorTemplateContactName: `Ottaa yhteyttä`,
	EditorTemplateDateTimeCustomHint: `yy = lyhyt vuosi<br/>v = pitkä vuosi<br/>M = kuukausi (1-12)<br/>MM = kuukausi (01-12)<br/>MMM = kuukauden lyhenne (tammikuu, helmikuu ... Joulukuu)<br/>MMMM = pitkä kuukausi (tammikuu, helmikuu ... Joulukuu)<br/>d = päivä (1 - 31)<br/>dd = päivä (01 - 31)<br/>ddd = viikonpäivä sanoin (maanantai, tiistai ... sunnuntai)<br/>E = lyhyt viikonpäivä sanoin (ma, ti ... Aurinko)<br/>D - järjestyspäivä (1., 2., 3., 21., 22., 23., 31., 4.)<br/>h = tunti aamupäivällä (0-12)<br/>hh = tunti aamupäivällä (00-12)<br/>H = tunti päivässä (0-23)<br/>HH = tunti päivässä (00-23)<br/>mm = minuutti<br/>ss = sekunti<br/>SSS = millisekuntia<br/>a = AM/PM-merkki<br/>p = AM/PM-merkki`,
	EditorTemplateDateTimeCustomLabel: `Mukautettu`,
	EditorTemplateDateTimeHint: `Nykyinen päivämäärä ja/tai aika korvataan DateTime -malleissa, kun ne on liitetty.`,
	EditorTemplateDateTimeName: `Treffiaika`,
	EditorTemplateDynamicHint: `<p>Kaikissa tämän mallin esiintymissä käytetään annettua tekstiä.</p>`,
	EditorTemplateDynamicName: `Dynaaminen`,
	EditorTemplateEmptyPlaceholder: `{0} on tyhjä ...`,
	EditorTemplateStaticHint: `<p>Kaikissa tämän mallin esiintymissä käytetään annettua tekstiä.</p>`,
	EditorTemplateStaticName: `Staattinen`,
	EditorTemplateTeaserText: `Lisää tulossa pian!`,
	EditorTt1: `Klikkaus`,
	EditorTt2: `muokkaa '<em> {0} </em>' ...`,
	EditorTt3: `Muokkaa väriä ...`,
	EditorTt4: `Poista '<em> {0} </em>' ...`,
	EditorTt5: `Poista esine`,
	EditorTt6: `seurata ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Odota...`,
	EditorWholeWordLabel: ` Koko maailma`,
	EditorWrapLabel: ` Kietoa`,

};