var UiStrings = {
	EditorAppendCloseLabel: `Voltooi toevoegen`,
	EditorAppendInlineModeLabel: `Schakel blok in`,
	EditorAppendLineModeLabel: `Schakel inline in`,
	EditorAppendManualModeLabel: `Schakelhandleiding`,
	EditorAppendNonManualModeLabel: `Schakelhandleiding`,
	EditorAppendPauseLabel: `Pauzeer toevoegen`,
	EditorAppendPostLabel: `Schakel eerder in`,
	EditorAppendPreLabel: `Schakel eerder in`,
	EditorAppendResumeLabel: `Hervatten toevoegen`,
	EditorBgColorLabel: `Achtergrond kleur`,
	EditorClearAllLabel: `Wis alles`,
	EditorClipboardFormatsLabel: `Klembordformaten`,
	EditorConfirmNtfTitle: `Bevestigen`,
	EditorDeleteAllButtonText: `Verwijder alles`,
	EditorDeleteAllTemplatesNtfText: `Weet u zeker dat u alle gebruik van '{0}' wilt verwijderen?

Dit kan niet ongedaan gemaakt worden!`,
	EditorEditTemplateDetailsLabel: `Details bewerken`,
	EditorEditTemplateNameLabel: `Naam`,
	EditorFindLabel: `Vinden`,
	EditorFontColorLabel: `Lettertype kleur`,
	EditorFormatPaintLabel: `Formaat verf`,
	EditorInSelectionLabel: ` In selectie`,
	EditorInsertImageLabel: `Voeg afbeelding in`,
	EditorInsertLinkLabel: `Voeg link in`,
	EditorInsertVideoLabel: `Video invoegen`,
	EditorMatchCaseLabel: ` Match case`,
	EditorNewTemplateLabel: `Nieuwe sjabloon`,
	EditorNextTemplateLabel: `Volgende sjabloon`,
	EditorPasteButtonAppendBeginLabel: `Toevoegen ...`,
	EditorPasteButtonLabel: `Plakken`,
	EditorPasteTemplateWatermark: `Voer tekst in plakken ...`,
	EditorPrevTemplateLabel: `Vorige sjabloon`,
	EditorRegExLabel: ` Regelmatige expressie`,
	EditorReplaceAllLabel: `Vervang alles`,
	EditorReplaceLabel: `Vervangen`,
	EditorTemplateContactHint: `<p> Beschikbare contacten gebruiken (vereist een fetcher -plug -in) Dit veld wordt gebruikt voor alle instanties van deze sjabloon in dit document of in een andere wordt er later naar verwezen. </p> <p> Dus bijvoorbeeld als selecteer e -mailadres selecteert Hier dan wordt het e -mailveld van het contact dat u selecteert voor alle instanties in dit document gebruikt. </p>`,
	EditorTemplateContactName: `Contact`,
	EditorTemplateDateTimeCustomHint: `yy = kort jaar <br/> yyyy = lang jaar <br/> m = maand (1-12) <br/> mm = maand (01-12) <br/> mmm = maand afkorting (jan, februari .. . Dec) <br/> mmmm = lange maand (januari, februari ... december) <br/> d = dag (1 - 31) <br/> dd = dag (01 - 31) <br/> ddd = Dag van de week in woorden (maandag, dinsdag ... zondag) <br/> e = korte dag van de week in woorden (ma, di ... zon) <br/> d - Ordinal Day (1e, 2e, 3e, 21e, 22e, 23e, 31e, 4e ...) <br/> h = uur in AM/PM (0-12) <br/> HH = uur in AM/PM (00-12) <Br/ > H = uur in dag (0-23) <br/> hh = uur in dag (00-23) <br/> mm = minuut <br/> ss = tweede <br/> sss = milliseconden <br/> A = AM/PM -marker <br/> P = A.M./P.M. markeerstift`,
	EditorTemplateDateTimeCustomLabel: `Aangepast`,
	EditorTemplateDateTimeHint: `De huidige datum en/of tijd worden vervangen door datetime -sjablonen wanneer ze worden geplakt.`,
	EditorTemplateDateTimeName: `Datum Tijd`,
	EditorTemplateDynamicHint: `<p> Alle gebeurtenissen van deze sjabloon zullen de opgegeven tekst gebruiken. </p>`,
	EditorTemplateDynamicName: `Dynamisch`,
	EditorTemplateEmptyPlaceholder: `{0} is leeg ...`,
	EditorTemplateStaticHint: `<p> Alle gebeurtenissen van deze sjabloon zullen de opgegeven tekst gebruiken. </p>`,
	EditorTemplateStaticName: `Statisch`,
	EditorTemplateTeaserText: `Binnenkort meer!`,
	EditorWatermark: `Even geduld aub...`,
	EditorWholeWordLabel: ` Hele wereld`,
	EditorWrapLabel: ` Omwikkelen`,

};