var UiStrings = {
	EditorAppendCloseLabel: `যোগদান শেষ`,
	EditorAppendInlineModeLabel: `ব্লক সক্ষম করুন`,
	EditorAppendLineModeLabel: `ইনলাইন সক্ষম করুন`,
	EditorAppendManualModeLabel: `টগল ম্যানুয়াল`,
	EditorAppendNonManualModeLabel: `টগল ম্যানুয়াল`,
	EditorAppendPauseLabel: `বিরতি সংযোজন`,
	EditorAppendPostLabel: `আগে টগল করুন`,
	EditorAppendPreLabel: `আগে টগল করুন`,
	EditorAppendResumeLabel: `পুনরায় সংযুক্তি`,
	EditorBgColorLabel: `পেছনের রং`,
	EditorClearAllLabel: `সব পরিষ্কার করে দাও`,
	EditorClipboardFormatsLabel: `ক্লিপবোর্ড ফর্ম্যাট`,
	EditorConfirmNtfTitle: `নিশ্চিত করুন`,
	EditorDeleteAllButtonText: `সব মুছে ফেলুন`,
	EditorDeleteAllTemplatesNtfText: `আপনি কি নিশ্চিত যে আপনি '{0}' এর সমস্ত ব্যবহার মুছতে চান?

এটা অসম্পূর্ণ থাকতে পারে না!`,
	EditorEditTemplateDetailsLabel: `তথ্য সংশোধন কর`,
	EditorEditTemplateNameLabel: `নাম`,
	EditorFindLabel: `অনুসন্ধান`,
	EditorFontColorLabel: `ফন্টের রং`,
	EditorFormatPaintLabel: `ফর্ম্যাট পেইন্ট`,
	EditorInSelectionLabel: ` নির্বাচন`,
	EditorInsertImageLabel: `চিত্র sert োকান`,
	EditorInsertLinkLabel: `লিঙ্ক sert োকান`,
	EditorInsertVideoLabel: `ভিডিও sert োকান`,
	EditorMatchCaseLabel: ` ম্যাচ ক্ষেত্রে`,
	EditorNewTemplateLabel: `নতুন টেম্পলেট`,
	EditorNextTemplateLabel: `পরবর্তী টেম্পলেট`,
	EditorPasteButtonAppendBeginLabel: `সংযোজন ...`,
	EditorPasteButtonLabel: `আটকান`,
	EditorPasteTemplateWatermark: `পেস্ট পাঠ্য প্রবেশ করুন ...`,
	EditorPrevTemplateLabel: `পূর্ববর্তী টেম্পলেট`,
	EditorRegExLabel: ` নিয়মিত অভিব্যক্তি`,
	EditorReplaceAllLabel: `সমস্ত প্রতিস্থাপন`,
	EditorReplaceLabel: `প্রতিস্থাপন`,
	EditorTemplateContactHint: `<p> উপলভ্য পরিচিতিগুলি ব্যবহার করে (একটি ফেচার প্লাগইন প্রয়োজন) এই ক্ষেত্রটি এই দস্তাবেজ জুড়ে এই টেমপ্লেটের সমস্ত দৃষ্টান্তের জন্য বা এটি পরে উল্লেখ করা হবে </</p> <p> সুতরাং উদাহরণস্বরূপ যদি ইমেল ঠিকানা নির্বাচন করুন এখানে আপনি যে যোগাযোগটি নির্বাচন করেছেন তার ইমেল ক্ষেত্রটি এই দস্তাবেজের সমস্ত দৃষ্টান্তের জন্য ব্যবহার করা হবে </</p>`,
	EditorTemplateContactName: `যোগাযোগ`,
	EditorTemplateDateTimeCustomHint: `yy = স্বল্প বছর <br/> yyyy = দীর্ঘ বছর <br/> এম = মাস (1-12) <br/> মিমি = মাস (01-12) <br/> মিমি = মাসের সংক্ষেপণ (জানু, ফেব্রুয়ারী .. । ডিসেম্বর) <br/> মিমিএম = দীর্ঘ মাস (জানুয়ারী, ফেব্রুয়ারি ... ডিসেম্বর) <br/> ডি = দিন (1 - 31) <br/> ডিডি = দিন (01 - 31) <br/> ডিডিডি = কথায় সপ্তাহের দিন (সোমবার, মঙ্গলবার ... রবিবার) <br/> ই = সপ্তাহের সংক্ষিপ্ত দিন শব্দের (সোমবার, মঙ্গল ... সূর্য) <br/> ডি - অর্ডিনাল ডে (1 ম, দ্বিতীয়, তৃতীয়, 21 তম, 22 তম, 23 তম, 31 তম, চতুর্থ ...) <br/> এইচ = ঘন্টা সময় এএম/পিএম (0-12) <br/> এইচ = ঘন্টা এএম/প্রধানমন্ত্রী (00-12) <বিআর/ > এইচ = দিনে ঘন্টা (0-23) <br/> এইচএইচ = দিনে ঘন্টা (00-23) <br/> মিমি = মিনিট <br/> এসএস = দ্বিতীয় <br/> এসএসএস = মিলিসেকেন্ডস <br/> এ = এএম/পিএম মার্কার <br/> পি = এ.এম./পি.এম. চিহ্নিতকারী`,
	EditorTemplateDateTimeCustomLabel: `কাস্টম`,
	EditorTemplateDateTimeHint: `বর্তমান তারিখ এবং/অথবা সময়টি ডেটটাইম টেম্পলেটগুলি পেস্ট করার সময় প্রতিস্থাপন করা হবে।`,
	EditorTemplateDateTimeName: `তারিখ সময়`,
	EditorTemplateDynamicHint: `<p> এই টেমপ্লেটের সমস্ত ঘটনা প্রদত্ত পাঠ্য ব্যবহার করবে </</p>`,
	EditorTemplateDynamicName: `গতিশীল`,
	EditorTemplateEmptyPlaceholder: `{0} খালি ...`,
	EditorTemplateStaticHint: `<p> এই টেমপ্লেটের সমস্ত ঘটনা প্রদত্ত পাঠ্য ব্যবহার করবে </</p>`,
	EditorTemplateStaticName: `স্থির`,
	EditorTemplateTeaserText: `আরও শীঘ্রই আসছে!`,
	EditorWatermark: `অনুগ্রহপূর্বক অপেক্ষা করুন...`,
	EditorWholeWordLabel: ` সমগ্র শব্দ`,
	EditorWrapLabel: ` চারপাশে মোড়ানো`,

};