var UiStrings = {
	EditorAppendCloseLabel: `Закончить добавление`,
	EditorAppendInlineModeLabel: `Включить блок`,
	EditorAppendLineModeLabel: `Включить встроенный`,
	EditorAppendManualModeLabel: `Перевернуть руководство`,
	EditorAppendNonManualModeLabel: `Перевернуть руководство`,
	EditorAppendPauseLabel: `Пауза добавить`,
	EditorAppendPostLabel: `Перевернуть раньше`,
	EditorAppendPreLabel: `Перевернуть раньше`,
	EditorAppendResumeLabel: `Резюме добавить`,
	EditorBgColorLabel: `Фоновый цвет`,
	EditorClearAllLabel: `Очистить все`,
	EditorClipboardFormatsLabel: `Форматы буфера обмена`,
	EditorConfirmNtfTitle: `Подтверждать`,
	EditorDeleteAllButtonText: `Удалить все`,
	EditorDeleteAllTemplatesNtfText: `Вы уверены, что хотите удалить все использование '{0}'?

Это не может быть отменено!`,
	EditorEditTemplateDetailsLabel: `Редактировать детали`,
	EditorEditTemplateNameLabel: `Имя`,
	EditorFindLabel: `Находить`,
	EditorFontColorLabel: `Цвет шрифта`,
	EditorFormatPaintLabel: `Формат краски`,
	EditorInSelectionLabel: ` В отборе`,
	EditorInsertImageLabel: `Вставьте изображение`,
	EditorInsertLinkLabel: `Вставьте ссылку`,
	EditorInsertVideoLabel: `Вставить видео`,
	EditorMatchCaseLabel: ` Учитывать регистр`,
	EditorNewTemplateLabel: `Новый шаблон`,
	EditorNextTemplateLabel: `Следующий шаблон`,
	EditorPasteButtonAppendBeginLabel: `Добавить ...`,
	EditorPasteButtonLabel: `Вставить`,
	EditorPasteTemplateWatermark: `Введите текст вставки ...`,
	EditorPrevTemplateLabel: `Предыдущий шаблон`,
	EditorRegExLabel: ` Регулярное выражение`,
	EditorReplaceAllLabel: `Заменить все`,
	EditorReplaceLabel: `Заменять`,
	EditorTemplateContactHint: `<p> Использование доступных контактов (требуется плагин Fetcher). Это поле будет использоваться для всех экземпляров этого шаблона в этом документе или в любом случае, на которое оно будет упомянуто позже. </p> <p> Так, например, если выберите адрес электронной почты Здесь, тогда поле электронной почты выбранного вами контакта будет использоваться для всех экземпляров в этом документе. </p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = короткий год <br/> yyyy = долгий год <br/> m = месяц (1-12) <br/> мм = месяц (01-12) <br/> ммм = месяц аббревиатура (январь, февраль .. . Dec) <br/> мммм = долгий месяц (январь, февраль ... декабрь) <br/> d = день (1 - 31) <br/> dd = день (01 - 31) <br/> ddd = День недели в словах (понедельник, вторник ... воскресенье) <br/> e = короткий день недели в словах (Mon, вт ... Солнце) <br/> D - Орденский день (1 -й, 2 -й, 3-й, 21-й, 22-й, 23-й, 31-й, 4-й ...) <br/> h = час в AM/PM (0-12) <br/> Hh = час в AM/PM (00-12) <Br/ > H = час в день (0-23) <br/> Hh = час в день (00-23) <br/> mm = минута <br/> ss = второй <br/> sss = миллисекунд <br/> a = am/pm маркер <br/> p = a.m./p.m. маркер`,
	EditorTemplateDateTimeCustomLabel: `Обычай`,
	EditorTemplateDateTimeHint: `Текущая дата и/или время будут заменены шаблонами DateTime, когда они вставлены.`,
	EditorTemplateDateTimeName: `Время даты`,
	EditorTemplateDynamicHint: `<p> Все происшествия этого шаблона будут использовать предоставленный текст. </p>`,
	EditorTemplateDynamicName: `Динамика`,
	EditorTemplateEmptyPlaceholder: `{0} пусто ...`,
	EditorTemplateStaticHint: `<p> Все происшествия этого шаблона будут использовать предоставленный текст. </p>`,
	EditorTemplateStaticName: `Статический`,
	EditorTemplateTeaserText: `Продолжение следует!`,
	EditorWatermark: `Пожалуйста, подождите...`,
	EditorWholeWordLabel: ` Целое слово`,
	EditorWrapLabel: ` Обернуть вокруг`,

};