var UiStrings = {
	EditorAppendCloseLabel: `ማቃጠል ጨርስ`,
	EditorAppendInlineModeLabel: `ብሎክ አንቃ`,
	EditorAppendLineModeLabel: `ውስጤን አንቃ`,
	EditorAppendManualModeLabel: `መመሪያን ይቀያይሩ`,
	EditorAppendNonManualModeLabel: `መመሪያን ይቀያይሩ`,
	EditorAppendPauseLabel: `ለአፍታ አቁም`,
	EditorAppendPostLabel: `ከዚህ በፊት ይቀያይሩ`,
	EditorAppendPreLabel: `ከዚህ በፊት ይቀያይሩ`,
	EditorAppendResumeLabel: `ከቆመበት ቀጥል`,
	EditorBgColorLabel: `የጀርባ ቀለም`,
	EditorClearAllLabel: `ሁሉንም ያፅዱ`,
	EditorClipboardFormatsLabel: `የቅንጥብ ሰሌዳ ቅርፀቶች`,
	EditorConfirmNtfTitle: `አረጋግጥ`,
	EditorDeleteAllButtonText: `ሁሉንም ሰርዝ`,
	EditorDeleteAllTemplatesNtfText: `እርግጠኛ ነዎት የ "{0} 'ን መድረስ እንደሚፈልጉ እርግጠኛ ነዎት?

ይህ ሊቀለበስ አይችልም!`,
	EditorEditTemplateDetailsLabel: `ዝርዝሮችን ያርትዑ`,
	EditorEditTemplateNameLabel: `ስም`,
	EditorFindLabel: `ይፈልጉ`,
	EditorFontColorLabel: `የቅርጸ-ቁምፊ ቀለም`,
	EditorFormatPaintLabel: `ቅርጸት ቀለም`,
	EditorInSelectionLabel: ` በምርጫ ውስጥ`,
	EditorInsertImageLabel: `ምስልን ያስገቡ`,
	EditorInsertLinkLabel: `አገናኝ ያስገቡ`,
	EditorInsertVideoLabel: `ቪዲዮ ያስገቡ`,
	EditorMatchCaseLabel: ` የግጥሚያ ጉዳይ`,
	EditorNewTemplateLabel: `አዲስ አብነት`,
	EditorNextTemplateLabel: `የሚቀጥለው ንድፍ`,
	EditorPasteButtonAppendBeginLabel: `ተማርኩ ...`,
	EditorPasteButtonLabel: `ፓስተር`,
	EditorPasteTemplateWatermark: `የመለጠጥ ጽሑፍ ያስገቡ ...`,
	EditorPrevTemplateLabel: `ያለፈው አብነት`,
	EditorRegExLabel: ` መደበኛ አገላለጽ`,
	EditorReplaceAllLabel: `ሁሉንም ይተኩ`,
	EditorReplaceLabel: `ይተኩ`,
	EditorTemplateContactHint: `የሚገኙ እውቂያዎችን በመጠቀም (የፍርድ ቤት ተሰኪዎችን ይፈልጋል) ይህ መስክ በዚህ ሰነድ ውስጥ ወይም በሌላ ሰነድ ውስጥ ለሚጠቀሱ ሁሉ ጥቅም ላይ ይውላል. </ p> <p> ለምሳሌ ኢሜል አድራሻን ይምረጡ እርስዎ የሚከተሏቸው የኢሜል መስክ በዚህ ሰነድ ውስጥ ለሁሉም አጋጣሚዎች ጥቅም ላይ ይውላሉ. </ p>`,
	EditorTemplateContactName: `እውቂያ`,
	EditorTemplateDateTimeCustomHint: `አይ = አጭር ዓመት <br/> yyyy/h/200) <br/> <br/11 . የሳምንቱ ቀን በቃላት (ሰኞ, ማክሰኞ ... እሑድ). 3, 21 ኛው, 22 ኛ, 23 ኛ, 23 ቀን ... > H = ሰዓት (0-23) ቀን (0-23) በ <ኤ.ቢ.ኤል. = HH = HH = MM = SS = SS = SS = CRE = SSR = ሚሊሴኮንዶች A = AM / EM / PM Carker <br/ti/h = p = am./p.m. ምልክት ማድረጊያ`,
	EditorTemplateDateTimeCustomLabel: `ብጁ`,
	EditorTemplateDateTimeHint: `የወቅቱ ቀን እና / ወይም ጊዜ ሲለቁ ለቀጣዩ ጊዜው አብነት ይተካሉ.`,
	EditorTemplateDateTimeName: `የቀን ሰዓት`,
	EditorTemplateDynamicHint: `የዚህ አብነት ሁሉም መሠረቶች የተሰጠውን ጽሑፍ ይጠቀማሉ. </ p>`,
	EditorTemplateDynamicName: `ተለዋዋጭ`,
	EditorTemplateEmptyPlaceholder: `{0} ባዶ ነው ...`,
	EditorTemplateStaticHint: `የዚህ አብነት ሁሉም መሠረቶች የተሰጠውን ጽሑፍ ይጠቀማሉ. </ p>`,
	EditorTemplateStaticName: `የማይንቀሳቀስ`,
	EditorTemplateTeaserText: `በቅርቡ ይመጣል!`,
	EditorWatermark: `ቆይ በናተህ...`,
	EditorWholeWordLabel: ` ሙሉ ቃል`,
	EditorWrapLabel: ` መጠቅለል`,

};