var UiStrings = {
	EditorAppendCloseLabel: `ئادرېسنى تاماملاڭ`,
	EditorAppendInlineModeLabel: `چەكلەش`,
	EditorAppendLineModeLabel: `ئىقتىدارنى قوزغىتىڭ`,
	EditorAppendManualModeLabel: `قوللانما`,
	EditorAppendNonManualModeLabel: `قوللانما`,
	EditorAppendPauseLabel: `توختىتىش`,
	EditorAppendPostLabel: `To toggle`,
	EditorAppendPreLabel: `To toggle`,
	EditorAppendResumeLabel: `چېكىنىش`,
	EditorBgColorLabel: `تەگلىك رەڭگى`,
	EditorClearAllLabel: `ھەممىنى تازىلاش`,
	EditorClipboardFormatsLabel: `چاپلاش تاختىسى`,
	EditorConfirmNtfTitle: `جەزملەشتۈرۈڭ`,
	EditorDeleteAllButtonText: `ھەممىنى ئۆچۈرۈڭ`,
	EditorDeleteAllTemplatesNtfText: `«{0}» نىڭ بارلىق ئىشلىتىشلىرىنى ئۆچۈرمەكچىمۇ?

بۇنى ئەمەلدىن قالدۇرغىلى بولمايدۇ!`,
	EditorEditTemplateDetailsLabel: `تەپسىلاتلارنى تەھرىرلەڭ`,
	EditorEditTemplateNameLabel: `Name`,
	EditorFindLabel: `تېپىش`,
	EditorFontColorLabel: `خەت نۇسخىسىنى`,
	EditorFormatPaintLabel: `فورماتى`,
	EditorInSelectionLabel: ` تاللاشتا`,
	EditorInsertImageLabel: `رەسىم قىستۇرۇش`,
	EditorInsertLinkLabel: `ئۇلىنىش قىستۇرۇش`,
	EditorInsertVideoLabel: `سىن قىستۇرۇش`,
	EditorMatchCaseLabel: ` ماسلاشتۇرۇش دېلوسى`,
	EditorNewTemplateLabel: `يېڭى قېلىپ`,
	EditorNextTemplateLabel: `كېيىنكى قېلىپ`,
	EditorPasteButtonAppendBeginLabel: `قوشۇلدى ...`,
	EditorPasteButtonLabel: `چاپلاڭ`,
	EditorPasteTemplateWatermark: `چاپلاش تېكىستىنى كىرگۈزۈڭ ...`,
	EditorPrevTemplateLabel: `ئىلگىرىكى قېلىپ`,
	EditorRegExLabel: ` دائىملىق ئىپادىلەش`,
	EditorReplaceAllLabel: `بارلىق ئالماشتۇرۇڭ`,
	EditorReplaceLabel: `ئالماشتۇرۇش`,
	EditorTemplateContactHint: `<p> بار بولغان ئالاقىسىنى ئىشلىتىش (ھامىلى قىستۇرما تەلەپ قىلىدۇ) بۇ ئويۇننىڭ بۇ قېلىپتىكىسى ياكى ھەر قانداق ۋاقىتتا پايدىلىنىدۇ. </ P> <P> مەسىلەن ئېلېكترونلۇق خەت ئادرېسىنى تاللاڭ بۇ يەردە ئۇنداقتا سىز ئالاقىلىشىشنىڭ ئېلېكترونلۇق خەت مەيدانى بۇ ھۆججەتتىكى بارلىق ئەھۋاللارغا ئىشلىتىلىدۇ. </ p>`,
	EditorTemplateContactName: `ئالاقىلىشىڭ`,
	EditorTemplateDateTimeCustomHint: `YY = قىسقىچە يىل <br/> yyyy = ئۇزۇن يىل <br//> mm = mm = mm = mm = ئاي قىسقارتىش (1-ئاينىڭ 19-كۈنى) . DEM. <br/> mmm> ئۇزۇن ئاي (1-ئايدىن باشلاپ) <br/> (1 - 31 - 31) <br/> DDD = ھەپتىلىك كۈنى (دۈشەنبە, سەيشەنبە ... يەكشەنبە) <br/>. 3-نومۇر 21-نومۇر, 22-چېسلا, 31-چېسلا ...) <br/> AM / HHM = سائەتتە HH / HG (00-12) <br / > H = سائەتتە سائەت (0-23) <br/> HH = mm = mm = mm = sss = SSS = CRSSCOMS <br/> A = AM / PM ماركىسىدىن تۆۋەنلەيدۇ. مارك`,
	EditorTemplateDateTimeCustomLabel: `ئادەت`,
	EditorTemplateDateTimeHint: `نۆۋەتتىكى چېسلا ۋە ياكى ۋاقىت چاپلانغان ۋاقىتتا ۋاقىت تېمىسىدا ۋاقىت چىقىرىۋېتىلىدۇ.`,
	EditorTemplateDateTimeName: `چېسلا ۋاقتى`,
	EditorTemplateDynamicHint: `<p> بۇ قېلىپنىڭ بارلىق تولۇقلمارىلىرى تەمىنلەنگەن تېكىستنى ئىشلىتىدۇ. </ p>`,
	EditorTemplateDynamicName: `ھەرىكەتچان`,
	EditorTemplateEmptyPlaceholder: `{0}} قۇرۇق ...`,
	EditorTemplateStaticHint: `<p> بۇ قېلىپنىڭ بارلىق تولۇقلمارىلىرى تەمىنلەنگەن تېكىستنى ئىشلىتىدۇ. </ p>`,
	EditorTemplateStaticName: `تۇراقلىق`,
	EditorTemplateTeaserText: `تېخىمۇ كۆپ كېلىدۇ!`,
	EditorWatermark: `ساقلاپ تۇرۇڭ ...`,
	EditorWholeWordLabel: ` پۈتۈن سۆز`,
	EditorWrapLabel: ` ئوراش`,

};