var UiStrings = {
	EditorAppendCloseLabel: `Voltooi by`,
	EditorAppendInlineModeLabel: `Aktiveer blok`,
	EditorAppendLineModeLabel: `Aktiveer inline`,
	EditorAppendManualModeLabel: `Skakelhandleiding`,
	EditorAppendNonManualModeLabel: `Skakelhandleiding`,
	EditorAppendPauseLabel: `Pouse voeg by`,
	EditorAppendPostLabel: `Wissel voor`,
	EditorAppendPreLabel: `Wissel voor`,
	EditorAppendResumeLabel: `Hervat bygevoeg`,
	EditorBgColorLabel: `Agtergrondkleur`,
	EditorClearAllLabel: `Duidelik alles`,
	EditorClipboardFormatsLabel: `Knipbordformate`,
	EditorColorChooserTitle: `Redakteurskleur`,
	EditorConfirmNtfTitle: `Bevestig`,
	EditorDeleteAllButtonText: `Vee alles uit`,
	EditorDeleteAllTemplatesNtfText: `Is u seker dat u alle gebruike van '{0}' wil uitvee?

Dit kan nie ongedaan gemaak word nie!`,
	EditorEditTemplateDetailsLabel: `Redigeer besonderhede`,
	EditorEditTemplateNameLabel: `Naam`,
	EditorFindLabel: `Vind`,
	EditorFontColorLabel: `Lettertipe kleur`,
	EditorFormatPaintLabel: `Formaat verf`,
	EditorInSelectionLabel: ` In seleksie`,
	EditorInsertImageLabel: `Voeg beeld in`,
	EditorInsertLinkLabel: `Voeg skakel in`,
	EditorInsertVideoLabel: `Voeg video in`,
	EditorLinkButtonText: `Red`,
	EditorLinkLabel: `Voer skakel in`,
	EditorLinkPlaceholder: `Voer URL in`,
	EditorMatchCaseLabel: ` Vuurhoutjie doos`,
	EditorNewTemplateLabel: `Nuwe sjabloon`,
	EditorNextTemplateLabel: `Volgende sjabloon`,
	EditorPasteButtonAppendBeginLabel: `Voeg ...`,
	EditorPasteButtonLabel: `Plak`,
	EditorPasteTemplateWatermark: `Voer plak teks in ...`,
	EditorPrevTemplateLabel: `Vorige sjabloon`,
	EditorRegExLabel: ` Gewone uitdrukking`,
	EditorReplaceAllLabel: `Vervang alles`,
	EditorReplaceLabel: `Vervang`,
	EditorTemplateContactHint: `<p>Met behulp van beskikbare kontakte (benodig 'n fetcher-inprop) sal hierdie veld gebruik word vir alle gevalle van hierdie sjabloon in hierdie dokument of in enige plek waarna later verwys sal word.</p><p> As u byvoorbeeld e-posadres hier kies, sal die e-posveld van die kontak wat u kies, vir alle gevalle in hierdie dokument gebruik word.</p>`,
	EditorTemplateContactName: `Kontak`,
	EditorTemplateDateTimeCustomHint: `yy = kort jaar<br/>yyyy = lang jaar<br/>M = maand (1-12)<br/>MM = maand (01-12)<br/>MMM = maand afkorting (Jan, Feb ... Des)<br/>MMMM = lang maand (Januarie, Februarie ... Desember)<br/>d = dag (1 - 31)<br/>dd = dag (01 - 31)<br/>ddd = dag van die week in woorde (Maandag, Dinsdag ... Sondag)<br/>E = kort dag van die week in woorde (Ma, Di ... Son)<br/>D - Ordinale dag (1ste, 2de, 3de, 21ste, 22ste, 23ste, 31ste, 4de...)<br/>h = uur in am/pm (0-12)<br/>hh = uur in vm/nm (00-12)<br/>H = uur in dag (0-23)<br/>HH = uur in dag (00-23)<br/>mm = minuut<br/>ss = tweede<br/>SSS = millisekondes<br/>a = AM/PM merker<br/>p = a.m./p.m. merker`,
	EditorTemplateDateTimeCustomLabel: `Gebruik`,
	EditorTemplateDateTimeHint: `Die huidige datum en/of tyd sal vervang word met die datumsjablone wanneer dit geplak word.`,
	EditorTemplateDateTimeName: `Datum Tyd`,
	EditorTemplateDynamicHint: `<p>Alle voorkomste van hierdie sjabloon sal die verskafde teks gebruik.</p>`,
	EditorTemplateDynamicName: `Dinamies`,
	EditorTemplateEmptyPlaceholder: `{0} is leeg ...`,
	EditorTemplateStaticHint: `<p>Alle voorkomste van hierdie sjabloon sal die verskafde teks gebruik.</p>`,
	EditorTemplateStaticName: `Staties`,
	EditorTemplateTeaserText: `Meer kom binnekort!`,
	EditorTt1: `Klik`,
	EditorTt2: `wysig '<em>{0}</em>' ...`,
	EditorTt3: `wysig kleur...`,
	EditorTt4: `verwyder '<em>{0}</em>' ...`,
	EditorTt5: `item verwyder`,
	EditorTt6: `te volg...`,
	EditorTt7: `gaan na '<em>{0}</em>' ...`,
	EditorWatermark: `Wag asseblief...`,
	EditorWholeWordLabel: ` Hele woord`,
	EditorWrapLabel: ` Wrap rond`,

};