var UiStrings = {
	EditorAppendCloseLabel: `Dokončit připojení`,
	EditorAppendInlineModeLabel: `Povolit blok`,
	EditorAppendLineModeLabel: `Povolit inline`,
	EditorAppendManualModeLabel: `Přepínač`,
	EditorAppendNonManualModeLabel: `Přepínač`,
	EditorAppendPauseLabel: `Pozastavte připojení`,
	EditorAppendPostLabel: `Přepínat dříve`,
	EditorAppendPreLabel: `Přepínat dříve`,
	EditorAppendResumeLabel: `Pokračovat v připojení`,
	EditorBgColorLabel: `Barva pozadí`,
	EditorClearAllLabel: `Vymazat vše`,
	EditorClipboardFormatsLabel: `Formáty schránky`,
	EditorConfirmNtfTitle: `Potvrdit`,
	EditorDeleteAllButtonText: `Smazat všechny`,
	EditorDeleteAllTemplatesNtfText: `Jste si jisti, že chcete odstranit všechna využití '{0}'?

To nelze vrátit zpět!`,
	EditorEditTemplateDetailsLabel: `Upravit detaily`,
	EditorEditTemplateNameLabel: `název`,
	EditorFindLabel: `Nalézt`,
	EditorFontColorLabel: `Barva fontu`,
	EditorFormatPaintLabel: `Formát barvy`,
	EditorInSelectionLabel: ` Při výběru`,
	EditorInsertImageLabel: `Vložte obrázek`,
	EditorInsertLinkLabel: `Vložte odkaz`,
	EditorInsertVideoLabel: `Vložte video`,
	EditorMatchCaseLabel: ` Shodný případ`,
	EditorNewTemplateLabel: `Nová šablona`,
	EditorNextTemplateLabel: `Další šablona`,
	EditorPasteButtonAppendBeginLabel: `Připojit...`,
	EditorPasteButtonLabel: `Vložit`,
	EditorPasteTemplateWatermark: `Zadejte text vložení ...`,
	EditorPrevTemplateLabel: `Předchozí šablona`,
	EditorRegExLabel: ` Regulární výraz`,
	EditorReplaceAllLabel: `Vyměnit vše`,
	EditorReplaceLabel: `Nahradit`,
	EditorTemplateContactHint: `<p>Při použití dostupných kontaktů (vyžaduje zásuvný modul pro načítání) bude toto pole použito pro všechny instance této šablony v tomto dokumentu nebo v jakémkoli dokumentu, ve kterém se bude odkazovat později.</p><p> Pokud tedy například zde vyberete e-mailovou adresu, použije se pole e-mailu vybraného kontaktu pro všechny výskyty v tomto dokumentu.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = krátký rok<br/>yyyy = dlouhý rok<br/>M = měsíc (1-12)<br/>MM = měsíc (01-12)<br/>MMM = zkratka měsíce (leden, únor ... Prosinec)<br/>MMMM = dlouhý měsíc (leden, únor ... Prosinec)<br/>d = den (1 - 31)<br/>dd = den (01 - 31)<br/>ddd = den v týdnu ve slovech (pondělí, úterý ... Neděle)<br/>E = krátký den v týdnu vyjádřený slovy (Po, Út ... Slunce)<br/>D - Pořadové číslo (1., 2., 3., 21., 22., 23., 31., 4....)<br/>h = hodina v dopoledne/odpoledne (0-12)<br/>hh = hodina v dopoledne/odpoledne (00-12)<br/>H = hodina ve dni (0-23)<br/>HH = hodina ve dni (00-23)<br/>mm = minuta<br/>ss = sekunda<br/>SSS = milisekundy<br/>a = značka AM/PM<br/>p = značka dopoledne/odpoledne`,
	EditorTemplateDateTimeCustomLabel: `Zvyk`,
	EditorTemplateDateTimeHint: `Aktuální datum a/nebo čas bude nahrazen šablonami DateTime, když jsou vloženy.`,
	EditorTemplateDateTimeName: `Čas schůzky`,
	EditorTemplateDynamicHint: `<p>Všechny výskyty této šablony budou používat poskytnutý text.</p>`,
	EditorTemplateDynamicName: `Dynamický`,
	EditorTemplateEmptyPlaceholder: `{0} je prázdný ...`,
	EditorTemplateStaticHint: `<p>Všechny výskyty této šablony budou používat poskytnutý text.</p>`,
	EditorTemplateStaticName: `Statický`,
	EditorTemplateTeaserText: `Více již brzy!`,
	EditorWatermark: `Prosím, čekejte...`,
	EditorWholeWordLabel: ` Celý svět`,
	EditorWrapLabel: ` Obalit`,

};