var UiStrings = {
	EditorAppendCloseLabel: `Закончить добавление`,
	EditorAppendInlineModeLabel: `Включить блок`,
	EditorAppendLineModeLabel: `Включить встроенный`,
	EditorAppendManualModeLabel: `Перевернуть руководство`,
	EditorAppendNonManualModeLabel: `Перевернуть руководство`,
	EditorAppendPauseLabel: `Пауза добавить`,
	EditorAppendPostLabel: `Перевернуть раньше`,
	EditorAppendPreLabel: `Перевернуть раньше`,
	EditorAppendResumeLabel: `Резюме добавить`,
	EditorBgColorLabel: `Фоновый цвет`,
	EditorClearAllLabel: `Очистить все`,
	EditorClipboardFormatsLabel: `Форматы буфера обмена`,
	EditorColorChooserTitle: `Редактор цвет`,
	EditorConfirmNtfTitle: `Подтверждать`,
	EditorDeleteAllButtonText: `Удалить все`,
	EditorDeleteAllTemplatesNtfText: `Вы уверены, что хотите удалить все использование '{0}'?

Это не может быть отменено!`,
	EditorEditTemplateDetailsLabel: `Редактировать детали`,
	EditorEditTemplateNameLabel: `Имя`,
	EditorFindLabel: `Находить`,
	EditorFontColorLabel: `Цвет шрифта`,
	EditorFormatPaintLabel: `Формат краски`,
	EditorInSelectionLabel: ` В отборе`,
	EditorInsertImageLabel: `Вставьте изображение`,
	EditorInsertLinkLabel: `Вставьте ссылку`,
	EditorInsertVideoLabel: `Вставить видео`,
	EditorLinkButtonText: `Сохранять`,
	EditorLinkLabel: `Введите ссылку`,
	EditorLinkPlaceholder: `Введите URL`,
	EditorMatchCaseLabel: ` Учитывать регистр`,
	EditorNewTemplateLabel: `Новый шаблон`,
	EditorNextTemplateLabel: `Следующий шаблон`,
	EditorPasteButtonAppendBeginLabel: `Добавить ...`,
	EditorPasteButtonLabel: `Вставить`,
	EditorPasteTemplateWatermark: `Введите текст вставки ...`,
	EditorPrevTemplateLabel: `Предыдущий шаблон`,
	EditorRegExLabel: ` Регулярное выражение`,
	EditorReplaceAllLabel: `Заменить все`,
	EditorReplaceLabel: `Заменять`,
	EditorTemplateContactHint: `<p>При использовании доступных контактов (требуется плагин fetcher) это поле будет использоваться для всех экземпляров этого шаблона в этом документе или в любом другом документе, на который он будет ссылаться позже.</p><p> Так, например, если здесь выбран адрес электронной почты, то поле электронной почты выбранного вами контакта будет использоваться для всех экземпляров в этом документе.</p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = короткий год<br/>yyyy = длинный год<br/>M = месяц (1-12)<br/>MM = месяц (01-12)<br/>МММ = аббревиатура месяца (январь, фев ... Дек)<br/>ММММ = длинный месяц (январь, февраль... Декабрь)<br/>d = день (1 - 31)<br/>дд = день (01 - 31)<br/>ddd = день недели прописью (понедельник, вторник... Воскресенье)<br/>E = короткий день недели прописью (Пн, Вт ... Вс)<br/>D - Порядковый день (1-й, 2-й, 3-й, 21-й, 22-й, 23-й, 31-й, 4-й...)<br/>h = час в AM/PM (0-12)<br/>hh = час в AM/PM (00-12)<br/>H = час в сутках (0-23)<br/>HH = час в сутках (00-23)<br/>мм = минута<br/>ss = секунда<br/>SSS = миллисекунды<br/>a = маркер AM/PM<br/>p = маркер a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Обычай`,
	EditorTemplateDateTimeHint: `Текущая дата и/или время будут заменены шаблонами DateTime, когда они вставлены.`,
	EditorTemplateDateTimeName: `Время даты`,
	EditorTemplateDynamicHint: `<p>Все вхождения этого шаблона будут использовать предоставленный текст.</p>`,
	EditorTemplateDynamicName: `Динамика`,
	EditorTemplateEmptyPlaceholder: `{0} пусто ...`,
	EditorTemplateStaticHint: `<p>Все вхождения этого шаблона будут использовать предоставленный текст.</p>`,
	EditorTemplateStaticName: `Статический`,
	EditorTemplateTeaserText: `Продолжение следует!`,
	EditorTt1: `Нажимать`,
	EditorTt2: `Изменить '<em> {0} </em>' ...`,
	EditorTt3: `Редактировать цвет ...`,
	EditorTt4: `Удалить '<em> {0} </em>' ...`,
	EditorTt5: `Убрать предмет`,
	EditorTt6: `следить ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Пожалуйста, подождите...`,
	EditorWholeWordLabel: ` Целое слово`,
	EditorWrapLabel: ` Обернуть вокруг`,

};