var UiStrings = {
	EditorAppendCloseLabel: `Tapusin ang pagdidikit`,
	EditorAppendInlineModeLabel: `Paganahin ang block`,
	EditorAppendLineModeLabel: `Paganahin ang Inline`,
	EditorAppendManualModeLabel: `Manu -manong Toggle`,
	EditorAppendNonManualModeLabel: `Manu -manong Toggle`,
	EditorAppendPauseLabel: `I -pause ang append`,
	EditorAppendPostLabel: `Toggle dati`,
	EditorAppendPreLabel: `Toggle dati`,
	EditorAppendResumeLabel: `Ipagpatuloy ang append`,
	EditorBgColorLabel: `Kulay ng background`,
	EditorClearAllLabel: `Alisin lahat`,
	EditorClipboardFormatsLabel: `Mga format ng clipboard`,
	EditorConfirmNtfTitle: `Kumpirmahin`,
	EditorDeleteAllButtonText: `Tanggalin ang lahat`,
	EditorDeleteAllTemplatesNtfText: `Sigurado ka bang nais mong tanggalin ang lahat ng mga paggamit ng '{0}'?

Hindi ito maaalis!`,
	EditorEditTemplateDetailsLabel: `Edit ng mga detalye`,
	EditorEditTemplateNameLabel: `Pangalan`,
	EditorFindLabel: `Hanapin`,
	EditorFontColorLabel: `Kulay ng font`,
	EditorFormatPaintLabel: `Format na pintura`,
	EditorInSelectionLabel: ` Sa pagpili`,
	EditorInsertImageLabel: `Ipasok ang imahe`,
	EditorInsertLinkLabel: `INSERT LINK`,
	EditorInsertVideoLabel: `Ipasok ang video`,
	EditorMatchCaseLabel: ` Kaso sa tugma`,
	EditorNewTemplateLabel: `Bagong template`,
	EditorNextTemplateLabel: `Susunod na template`,
	EditorPasteButtonAppendBeginLabel: `Idagdag ...`,
	EditorPasteButtonLabel: `I -paste`,
	EditorPasteTemplateWatermark: `Ipasok ang text ng i -paste ...`,
	EditorPrevTemplateLabel: `Nakaraang template`,
	EditorRegExLabel: ` Regular na expression`,
	EditorReplaceAllLabel: `Palitan ang lahat`,
	EditorReplaceLabel: `Palitan`,
	EditorTemplateContactHint: `<p> gamit ang mga magagamit na contact (nangangailangan ng isang fetcher plugin) ang patlang na ito ay gagamitin para sa lahat ng mga pagkakataon ng template na ito sa buong dokumentong ito o sa anumang ito ay mai -refer sa ibang pagkakataon. </p> <p> Kaya halimbawa kung piliin ang email address Narito pagkatapos ang larangan ng email ng contact na iyong pinili ay gagamitin para sa lahat ng mga pagkakataon sa dokumentong ito. </p>`,
	EditorTemplateContactName: `Makipag -ugnay`,
	EditorTemplateDateTimeCustomHint: `yy = maikling taon <br/> yyyy = mahabang taon <br/> m = buwan (1-12) <br/> mm = buwan (01-12) . Dis) <br/> mmmm = mahabang buwan (Enero, Pebrero ... Disyembre) <br/> d = araw (1 - 31) Araw ng Linggo sa Mga Salita (Lunes, Martes ... Linggo) <br/> e = Maikling Araw ng Linggo sa Mga Salita (Mon, Tue ... Araw) Ika-3, ika-21, ika-22, ika-23, ika-31, ika-4 ...) > H = oras sa araw (0-23) <br/> hh = oras sa araw (00-23) <br/> mm = minuto <br/> ss = pangalawa A = AM/PM marker <br/> p = a.m./p.m. pananda`,
	EditorTemplateDateTimeCustomLabel: `Pasadya`,
	EditorTemplateDateTimeHint: `Ang kasalukuyang petsa at/o oras ay mapapalitan para sa mga template ng dateTime kapag sila ay na -paste.`,
	EditorTemplateDateTimeName: `Oras ng petsa`,
	EditorTemplateDynamicHint: `<p> Lahat ng mga pangyayari ng template na ito ay gagamitin ang ibinigay na teksto. </p>`,
	EditorTemplateDynamicName: `Dynamic`,
	EditorTemplateEmptyPlaceholder: `{0} ay walang laman ...`,
	EditorTemplateStaticHint: `<p> Lahat ng mga pangyayari ng template na ito ay gagamitin ang ibinigay na teksto. </p>`,
	EditorTemplateStaticName: `Static`,
	EditorTemplateTeaserText: `Mas malapit na!`,
	EditorWatermark: `Mangyaring maghintay ...`,
	EditorWholeWordLabel: ` Buong salita`,
	EditorWrapLabel: ` Balutin`,

};