var UiStrings = {
	EditorAppendCloseLabel: `Завршете ја додавањето`,
	EditorAppendInlineModeLabel: `Овозможете блок`,
	EditorAppendLineModeLabel: `Овозможи вметната`,
	EditorAppendManualModeLabel: `Прирачник за вклучување`,
	EditorAppendNonManualModeLabel: `Прирачник за вклучување`,
	EditorAppendPauseLabel: `Пауза додаток`,
	EditorAppendPostLabel: `Се менува пред тоа`,
	EditorAppendPreLabel: `Се менува пред тоа`,
	EditorAppendResumeLabel: `Продолжи додаток`,
	EditorBgColorLabel: `Боја на позадина`,
	EditorClearAllLabel: `Исчисти се`,
	EditorClipboardFormatsLabel: `Формати на таблата со исечоци`,
	EditorColorChooserTitle: `Боја на уредникот`,
	EditorConfirmNtfTitle: `Потврди`,
	EditorDeleteAllButtonText: `Избришете ги сите`,
	EditorDeleteAllTemplatesNtfText: `Дали сте сигурни дека сакате да ги избришете сите употреби на '{0}'?

Тоа не може да се врати назад!`,
	EditorEditTemplateDetailsLabel: `Уреди детали`,
	EditorEditTemplateNameLabel: `Име`,
	EditorFindLabel: `Најдете`,
	EditorFontColorLabel: `Боја на фонтот`,
	EditorFormatPaintLabel: `Формат боја`,
	EditorInSelectionLabel: ` При избор`,
	EditorInsertImageLabel: `Вметнете слика`,
	EditorInsertLinkLabel: `Вметнете врска`,
	EditorInsertVideoLabel: `Вметнете видео`,
	EditorLinkButtonText: `Зачувај`,
	EditorLinkLabel: `Внесете врска`,
	EditorLinkPlaceholder: `Внесете URL`,
	EditorMatchCaseLabel: ` Случај за натпревар`,
	EditorNewTemplateLabel: `Нов образец`,
	EditorNextTemplateLabel: `Следен образец`,
	EditorPasteButtonAppendBeginLabel: `Додаток ...`,
	EditorPasteButtonLabel: `Залепи`,
	EditorPasteTemplateWatermark: `Внесете текст за паста ...`,
	EditorPrevTemplateLabel: `Претходен образец`,
	EditorRegExLabel: ` Редовно изразување`,
	EditorReplaceAllLabel: `Заменете ги сите`,
	EditorReplaceLabel: `Заменете`,
	EditorTemplateContactHint: `<p>Користејќи ги достапните контакти (бара приклучок за фетиш) ова поле ќе се користи за сите случаи на овој шаблон низ овој документ или во било кој ќе биде референциран подоцна.</p><p> На пример, ако изберете email адреса тука тогаш полето на е-поштата на контактот што ќе го изберете ќе се користи за сите инстанци во овој документ.</p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `Yy = кратка година<br/>Yyyy = долга година<br/>М = месец (1-12)<br/>ММ = месец (01-12)<br/>MMM = месец кратенка (Jan, Feb ... Дек)<br/>ММММ = долг месец (јануари, февруари ... Декември)<br/>d = ден (1 - 31)<br/>dd = ден (01 - 31)<br/>ddd = ден од неделата со зборови (понеделник, вторник ... Недела)<br/>E = краток ден од неделата со зборови (Mon, Tue ... Сонце)<br/>D - Обичен ден (1-ви, 2-ри, 3-ти, 21-ви, 22-ри, 23-ти, 31-ви, 4-ти...)<br/>h = час во ам/pm (0-12)<br/>hh = час во ам/pm (00-12)<br/>H = час во денот (0-23)<br/>HH = час во денот (00-23)<br/>мм = минута<br/>ss = втор<br/>SSS = милисекунди<br/>a = AM/PM маркер<br/>p = a.m./p.m. маркер`,
	EditorTemplateDateTimeCustomLabel: `Обичај`,
	EditorTemplateDateTimeHint: `Тековниот датум и/или време ќе бидат заменети за шаблони за дата кога ќе бидат залепени.`,
	EditorTemplateDateTimeName: `Датум време`,
	EditorTemplateDynamicHint: `<p>Сите појави на овој шаблон ќе го користат обезбедениот текст.</p>`,
	EditorTemplateDynamicName: `Динамичен`,
	EditorTemplateEmptyPlaceholder: `{0} е празен ...`,
	EditorTemplateStaticHint: `<p>Сите појави на овој шаблон ќе го користат обезбедениот текст.</p>`,
	EditorTemplateStaticName: `Статички`,
	EditorTemplateTeaserText: `Повеќе наскоро!`,
	EditorTt1: `Кликнете`,
	EditorTt2: `Уреди '<em> {0} </em>' ...`,
	EditorTt3: `уреди боја ...`,
	EditorTt4: `Отстрани '<em> {0} </em>' ...`,
	EditorTt5: `Отстранете ја ставката`,
	EditorTt6: `да следи ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Ве молам почекајте...`,
	EditorWholeWordLabel: ` Цел збор`,
	EditorWrapLabel: ` Завиткајте наоколу`,

};