var UiStrings = {
	EditorAppendCloseLabel: `Tapusin ang pagdidikit`,
	EditorAppendInlineModeLabel: `Paganahin ang block`,
	EditorAppendLineModeLabel: `Paganahin ang Inline`,
	EditorAppendManualModeLabel: `Manu -manong Toggle`,
	EditorAppendNonManualModeLabel: `Manu -manong Toggle`,
	EditorAppendPauseLabel: `I -pause ang append`,
	EditorAppendPostLabel: `Toggle dati`,
	EditorAppendPreLabel: `Toggle dati`,
	EditorAppendResumeLabel: `Ipagpatuloy ang append`,
	EditorBgColorLabel: `Kulay ng background`,
	EditorClearAllLabel: `Alisin lahat`,
	EditorClipboardFormatsLabel: `Mga format ng clipboard`,
	EditorColorChooserTitle: `Kulay ng editor`,
	EditorConfirmNtfTitle: `Kumpirmahin`,
	EditorDeleteAllButtonText: `Tanggalin ang lahat`,
	EditorDeleteAllTemplatesNtfText: `Sigurado ka bang nais mong tanggalin ang lahat ng mga paggamit ng '{0}'?

Hindi ito maaalis!`,
	EditorEditTemplateDetailsLabel: `Edit ng mga detalye`,
	EditorEditTemplateNameLabel: `Pangalan`,
	EditorFindLabel: `Hanapin`,
	EditorFontColorLabel: `Kulay ng font`,
	EditorFormatPaintLabel: `Format na pintura`,
	EditorInSelectionLabel: ` Sa pagpili`,
	EditorInsertImageLabel: `Ipasok ang imahe`,
	EditorInsertLinkLabel: `INSERT LINK`,
	EditorInsertVideoLabel: `Ipasok ang video`,
	EditorLinkButtonText: `I -save`,
	EditorLinkLabel: `Ipasok ang link`,
	EditorLinkPlaceholder: `Ilagay ang URL`,
	EditorMatchCaseLabel: ` Kaso sa tugma`,
	EditorNewTemplateLabel: `Bagong template`,
	EditorNextTemplateLabel: `Susunod na template`,
	EditorPasteButtonAppendBeginLabel: `Idagdag ...`,
	EditorPasteButtonLabel: `I -paste`,
	EditorPasteButtonLabelMobile: `Kopya`,
	EditorPasteTemplateWatermark: `Ipasok ang text ng i -paste ...`,
	EditorPrevTemplateLabel: `Nakaraang template`,
	EditorRegExLabel: ` Regular na expression`,
	EditorReplaceAllLabel: `Palitan ang lahat`,
	EditorReplaceLabel: `Palitan`,
	EditorTemplateContactHint: `<p>Gamit ang magagamit na mga contact (nangangailangan ng isang fetcher plugin) ang patlang na ito ay gagamitin para sa lahat ng mga pagkakataon ng template na ito sa buong dokumentong ito o sa anumang ito ay sanggunian sa mamaya.</p><p> Kaya halimbawa kung piliin ang email address dito pagkatapos ay ang email field ng contact na iyong pinili ay gagamitin para sa lahat ng mga pagkakataon sa dokumentong ito.</p>`,
	EditorTemplateContactName: `Makipag -ugnay`,
	EditorTemplateDateTimeCustomHint: `yy = maikling taon<br/>yyyy = mahaba ang taon<br/>M = buwan (1-12)<br/>MM = buwan (01 12)<br/>MMM = buwan na pagdadaglat (Enero, Peb ... Dec)<br/>MMMM = mahabang buwan (Enero, Pebrero ... Disyembre)<br/>d = araw (1 - 31)<br/>dd = araw (01 - 31)<br/>ddd = araw ng linggo sa mga salita (Lunes, Martes ... Linggo)<br/>E = maikling araw ng linggo sa mga salita (Mon, Tue ... Sun)<br/>D - Ordinal day (1st, 2nd, 3rd, 21st, 22nd, 23rd, 31st, 4th...)<br/>h = oras sa am/pm (0-12)<br/>hh = oras sa am/pm (00-12)<br/>H = oras sa araw (0-23)<br/>HH = oras sa araw (00-23)<br/>mm = minuto<br/>ss = pangalawa<br/>SSS = milliseconds<br/>a = AM / PM marker<br/>p = marker ng a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Pasadya`,
	EditorTemplateDateTimeHint: `Ang kasalukuyang petsa at/o oras ay mapapalitan para sa mga template ng dateTime kapag sila ay na -paste.`,
	EditorTemplateDateTimeName: `Oras ng petsa`,
	EditorTemplateDynamicHint: `<p>Ang lahat ng mga pangyayari ng template na ito ay gagamitin ang ibinigay na teksto.</p>`,
	EditorTemplateDynamicName: `Dynamic`,
	EditorTemplateEmptyPlaceholder: `{0} ay walang laman ...`,
	EditorTemplateStaticHint: `<p>Ang lahat ng mga pangyayari ng template na ito ay gagamitin ang ibinigay na teksto.</p>`,
	EditorTemplateStaticName: `Static`,
	EditorTemplateTeaserText: `Mas malapit na!`,
	EditorTt1: `Mag -click`,
	EditorTt2: `I -edit ang '<em> {0} </em>' ...`,
	EditorTt3: `I -edit ang Kulay ...`,
	EditorTt4: `Alisin ang '<em> {0} </em>' ...`,
	EditorTt5: `Alisin ang item`,
	EditorTt6: `upang sundin ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Mangyaring maghintay ...`,
	EditorWholeWordLabel: ` Buong salita`,
	EditorWrapLabel: ` Balutin`,

};