var UiStrings = {
	EditorAppendCloseLabel: `完成添加`,
	EditorAppendInlineModeLabel: `啟用塊`,
	EditorAppendLineModeLabel: `啟用內聯`,
	EditorAppendManualModeLabel: `切換手冊`,
	EditorAppendNonManualModeLabel: `切換手冊`,
	EditorAppendPauseLabel: `暫停附加`,
	EditorAppendPostLabel: `切換之前`,
	EditorAppendPreLabel: `切換之前`,
	EditorAppendResumeLabel: `簡歷附加`,
	EditorBgColorLabel: `背景顏色`,
	EditorClearAllLabel: `清除全部`,
	EditorClipboardFormatsLabel: `剪貼板格式`,
	EditorConfirmNtfTitle: `確認`,
	EditorDeleteAllButtonText: `刪除所有`,
	EditorDeleteAllTemplatesNtfText: `您確定要刪除“ {0}”的所有用法？

這不能被撤消！`,
	EditorEditTemplateDetailsLabel: `編輯詳細信息`,
	EditorEditTemplateNameLabel: `姓名`,
	EditorFindLabel: `尋找`,
	EditorFontColorLabel: `字體顏色`,
	EditorFormatPaintLabel: `格式塗料`,
	EditorInSelectionLabel: ` 在選擇中`,
	EditorInsertImageLabel: `插入圖像`,
	EditorInsertLinkLabel: `插入鏈接`,
	EditorInsertVideoLabel: `插入視頻`,
	EditorMatchCaseLabel: ` 相符`,
	EditorNewTemplateLabel: `新模板`,
	EditorNextTemplateLabel: `下一個模板`,
	EditorPasteButtonAppendBeginLabel: `附加...`,
	EditorPasteButtonLabel: `粘貼`,
	EditorPasteTemplateWatermark: `輸入糊狀文字...`,
	EditorPrevTemplateLabel: `以前的模板`,
	EditorRegExLabel: ` 正則表達式`,
	EditorReplaceAllLabel: `全部替換`,
	EditorReplaceLabel: `代替`,
	EditorTemplateContactHint: `<p>使用可用的聯繫人（需要一個fetcher插件）此字段將用於本文檔的所有模板的所有實例，或者在以後將在任何文檔中引用任何內容。</p> <p>，例如，如果選擇選擇電子郵件地址在這裡，您選擇的聯繫人的電子郵件字段將用於本文檔中的所有實例。</p>`,
	EditorTemplateContactName: `接觸`,
	EditorTemplateDateTimeCustomHint: `yy =短期<br/> yyyy = long y yyy <br/> m =月（1-12）<br/> mm =月（01-12）<br/> mmm =月縮寫（2月1日， 1月。 。一周中的一周（星期一，星期二...星期日）<br/>第三，21日，22日，23日，第31，第4頁...） > h =每天的小時（0-23）<br/> hh = hh = hh = hH = hH = hh = hH <br/> mm = minute <br/> ss = second <br/> sss = milliseconds <br/> a = am /pm標記<br/> p = a.m./p.m。標記`,
	EditorTemplateDateTimeCustomLabel: `風俗`,
	EditorTemplateDateTimeHint: `當前日期和/或時間將粘貼時DateTime模板。`,
	EditorTemplateDateTimeName: `約會時間`,
	EditorTemplateDynamicHint: `<p>此模板的所有發生都將使用提供的文本。</p>`,
	EditorTemplateDynamicName: `動態的`,
	EditorTemplateEmptyPlaceholder: `{0}是空...`,
	EditorTemplateStaticHint: `<p>此模板的所有發生都將使用提供的文本。</p>`,
	EditorTemplateStaticName: `靜止的`,
	EditorTemplateTeaserText: `更多即將推出！`,
	EditorWatermark: `請稍等...`,
	EditorWholeWordLabel: ` 整個詞`,
	EditorWrapLabel: ` 環繞`,

};