var UiStrings = {
	EditorAppendCloseLabel: `जोडणे समाप्त`,
	EditorAppendInlineModeLabel: `ब्लॉक सक्षम करा`,
	EditorAppendLineModeLabel: `इनलाइन सक्षम करा`,
	EditorAppendManualModeLabel: `मॅन्युअल टॉगल`,
	EditorAppendNonManualModeLabel: `मॅन्युअल टॉगल`,
	EditorAppendPauseLabel: `विराम द्या`,
	EditorAppendPostLabel: `आधी टॉगल`,
	EditorAppendPreLabel: `आधी टॉगल`,
	EditorAppendResumeLabel: `पुन्हा सुरू करा`,
	EditorBgColorLabel: `पार्श्वभूमी रंग`,
	EditorClearAllLabel: `सर्व साफ करा`,
	EditorClipboardFormatsLabel: `क्लिपबोर्ड स्वरूप`,
	EditorColorChooserTitle: `संपादक रंग`,
	EditorConfirmNtfTitle: `पुष्टी`,
	EditorDeleteAllButtonText: `सर्व हटवा`,
	EditorDeleteAllTemplatesNtfText: `आपणास खात्री आहे की आपण '{0}' चे सर्व उपयोग हटवू इच्छिता?

हे पूर्ववत केले जाऊ शकत नाही!`,
	EditorEditTemplateDetailsLabel: `तपशील संपादित करा`,
	EditorEditTemplateNameLabel: `नाव`,
	EditorFindLabel: `शोधणे`,
	EditorFontColorLabel: `फॉन्टचा रंग`,
	EditorFormatPaintLabel: `स्वरूप पेंट`,
	EditorInSelectionLabel: ` निवडीमध्ये`,
	EditorInsertImageLabel: `प्रतिमा घाला`,
	EditorInsertLinkLabel: `दुवा घाला`,
	EditorInsertVideoLabel: `व्हिडिओ घाला`,
	EditorLinkButtonText: `जतन करा`,
	EditorLinkLabel: `दुवा प्रविष्ट करा`,
	EditorLinkPlaceholder: `URL प्रविष्ट करा`,
	EditorMatchCaseLabel: ` सामना केस`,
	EditorNewTemplateLabel: `नवीन टेम्पलेट`,
	EditorNextTemplateLabel: `पुढील टेम्पलेट`,
	EditorPasteButtonAppendBeginLabel: `जोडा ...`,
	EditorPasteButtonLabel: `पेस्ट करा`,
	EditorPasteTemplateWatermark: `पेस्ट मजकूर प्रविष्ट करा ...`,
	EditorPrevTemplateLabel: `मागील टेम्पलेट`,
	EditorRegExLabel: ` नियमित अभिव्यक्ती`,
	EditorReplaceAllLabel: `सर्व बदला`,
	EditorReplaceLabel: `पुनर्स्थित करा`,
	EditorTemplateContactHint: `<p>उपलब्ध संपर्कांचा वापर करून (फेचर प्लगइन आवश्यक आहे) हे क्षेत्र या दस्तऐवजातील या टेम्पलेटच्या सर्व उदाहरणांसाठी वापरले जाईल किंवा नंतर संदर्भित केले जाईल.</p><p> तर उदाहरणार्थ, जर येथे ईमेल पत्ता निवडला तर आपण निवडलेल्या संपर्काचे ईमेल क्षेत्र या दस्तऐवजातील सर्व घटनांसाठी वापरले जाईल.</p>`,
	EditorTemplateContactName: `संपर्क`,
	EditorTemplateDateTimeCustomHint: `yy = अल्प वर्ष<br/>यिय = दीर्घ वर्ष<br/>म = महिना (१-१२)<br/>मिमी = महिना (01-12)<br/>एमएमएम = महिना संक्षिप्त रूप (जानेवारी, फेब्रुवारी ... डिसेंबर)<br/>एमएमएमएम = दीर्घ महिना (जानेवारी, फेब्रुवारी ... डिसेंबर)<br/>ड = दिवस (1 - 31)<br/>डीडी = दिवस (01 - 31)<br/>डीडीडी = आठवड्याचा दिवस शब्दात (सोमवार, मंगळवार ... रविवार)<br/>ई = शब्दात आठवड्याचा छोटा दिवस (मोन, तू... सूर्य)<br/>ड - क्रमिक दिवस (पहिला, दुसरा, तिसरा, २१, २२, २३, ३१, ४...)<br/>ह = सकाळी /संध्याकाळी तास (०-१२)<br/>एचएच = सकाळी /संध्याकाळी तास (००-१२)<br/>ह = दिवसातील तास (०-२३)<br/>एचएच = दिवसातील तास (००-२३)<br/>मिमी = मिनिट<br/>ss = सेकंद<br/>एसएसएस = मिलीसेकंद<br/>ए = एएम / पीएम मार्कर<br/>पी = ए.एम./पी.एम. मार्कर`,
	EditorTemplateDateTimeCustomLabel: `सानुकूल`,
	EditorTemplateDateTimeHint: `सध्याची तारीख आणि/किंवा वेळ पेस्ट केल्यावर डेटटाइम टेम्पलेट्ससाठी बदलली जाईल.`,
	EditorTemplateDateTimeName: `तारीख वेळ`,
	EditorTemplateDynamicHint: `<p>या साच्याच्या सर्व घटना प्रदान केलेल्या मजकुराचा वापर करतील.</p>`,
	EditorTemplateDynamicName: `डायनॅमिक`,
	EditorTemplateEmptyPlaceholder: `{0} रिक्त आहे...`,
	EditorTemplateStaticHint: `<p>या साच्याच्या सर्व घटना प्रदान केलेल्या मजकुराचा वापर करतील.</p>`,
	EditorTemplateStaticName: `स्थिर`,
	EditorTemplateTeaserText: `अधिक लवकरच येत आहे!`,
	EditorTt1: `क्लिक करा`,
	EditorTt2: `'<em> {0} </em>' संपादित करा ...`,
	EditorTt3: `रंग संपादित करा ...`,
	EditorTt4: `'<em> {0} </em>' काढा ...`,
	EditorTt5: `आयटम काढा`,
	EditorTt6: `अनुसरण ...`,
	EditorTt7: `गोटो '<em> {0} </em>' ...`,
	EditorWatermark: `कृपया थांबा...`,
	EditorWholeWordLabel: ` संपूर्ण शब्द`,
	EditorWrapLabel: ` भोवती गुंडाळा`,

};