var UiStrings = {
	EditorAppendCloseLabel: `ضمیمه کردن`,
	EditorAppendInlineModeLabel: `بلوک را فعال کنید`,
	EditorAppendLineModeLabel: `Inline را فعال کنید`,
	EditorAppendManualModeLabel: `دفترچه راهنما`,
	EditorAppendNonManualModeLabel: `دفترچه راهنما`,
	EditorAppendPauseLabel: `مکث ضمیمه`,
	EditorAppendPostLabel: `قبل از`,
	EditorAppendPreLabel: `قبل از`,
	EditorAppendResumeLabel: `رزومه ضمیمه`,
	EditorBgColorLabel: `رنگ پس زمینه`,
	EditorClearAllLabel: `همه را پاک کن`,
	EditorClipboardFormatsLabel: `قالب های کلیپ بورد`,
	EditorConfirmNtfTitle: `تایید`,
	EditorDeleteAllButtonText: `همه را حذف کنید`,
	EditorDeleteAllTemplatesNtfText: `آیا مطمئن هستید که می خواهید تمام کاربردهای "{0}" را حذف کنید؟

این قابل بازگشت نیست!`,
	EditorEditTemplateDetailsLabel: `جزئیات ویرایش`,
	EditorEditTemplateNameLabel: `نام`,
	EditorFindLabel: `پیدا کردن`,
	EditorFontColorLabel: `رنگ فونت`,
	EditorFormatPaintLabel: `رنگ قالب`,
	EditorInSelectionLabel: ` در انتخاب`,
	EditorInsertImageLabel: `درج تصویر`,
	EditorInsertLinkLabel: `پیوند`,
	EditorInsertVideoLabel: `وارد کردن فیلم`,
	EditorMatchCaseLabel: ` مورد تطبیق`,
	EditorNewTemplateLabel: `الگوی جدید`,
	EditorNextTemplateLabel: `الگوی بعدی`,
	EditorPasteButtonAppendBeginLabel: `ضمیمه ...`,
	EditorPasteButtonLabel: `خمیر`,
	EditorPasteTemplateWatermark: `متن خمیر را وارد کنید ...`,
	EditorPrevTemplateLabel: `الگوی قبلی`,
	EditorRegExLabel: ` عبارت منظم`,
	EditorReplaceAllLabel: `جایگزین همه`,
	EditorReplaceLabel: `جایگزین کردن`,
	EditorTemplateContactHint: `<p> با استفاده از مخاطبین موجود (به افزونه Fetcher نیاز دارد) این قسمت برای تمام موارد این الگوی در این سند یا در هر مورد در بعداً مورد استفاده قرار می گیرد. </p> <p> بنابراین به عنوان مثال اگر آدرس ایمیل را انتخاب کنید در اینجا قسمت ایمیل مخاطبی که انتخاب می کنید برای همه موارد موجود در این سند استفاده می شود. </p>`,
	EditorTemplateContactName: `مخاطب`,
	EditorTemplateDateTimeCustomHint: `yy = سال کوتاه <br/> yyyy = سال طولانی <br/> m = ماه (1-12) <br/> mm = ماه (01-12) <br/> mmm = مخفف ماه (ژانویه ، فوریه .. دسامبر) <br/> mmmm = ماه طولانی (ژانویه ، فوریه ... دسامبر) <br/> d = روز (1 - 31) <br/> dd = روز (01 - 31) <br/> ddd = روز هفته کلمات (دوشنبه ، سه شنبه ... یکشنبه) <br/> e = روز کوتاه هفته در کلمات (دوشنبه ، سه شنبه ... خورشید) <br/> d - روز سفارش (اول ، 2 ، 3 ، 21 ، 22 ، 23 ، 31 ، 4 ...) <br/> h = ساعت در am/pm (0-12) <br/> hh = ساعت در am/pm (00-12) <br/ > H = ساعت در روز (0-23) <br/> HH = ساعت در روز (00-23) <br/> mm = دقیقه <br/> ss = دوم <br/> sss = میلی ثانیه <br/> A = Am/PM نشانگر <br/> P = A.M./P.M. نشانگر`,
	EditorTemplateDateTimeCustomLabel: `سفارشی`,
	EditorTemplateDateTimeHint: `تاریخ و/یا زمان فعلی در هنگام چسباندن برای الگوهای DateTime جایگزین می شود.`,
	EditorTemplateDateTimeName: `زمان قرار`,
	EditorTemplateDynamicHint: `<p> تمام اتفاقات این الگوی از متن ارائه شده استفاده می کند. </p>`,
	EditorTemplateDynamicName: `پویا`,
	EditorTemplateEmptyPlaceholder: `{0} خالی است ...`,
	EditorTemplateStaticHint: `<p> تمام اتفاقات این الگوی از متن ارائه شده استفاده می کند. </p>`,
	EditorTemplateStaticName: `ثابت`,
	EditorTemplateTeaserText: `به زودی!`,
	EditorWatermark: `لطفا صبر کنید...`,
	EditorWholeWordLabel: ` کلمه کلیدی`,
	EditorWrapLabel: ` پیچیدن`,

};