var UiStrings = {
	EditorAppendCloseLabel: `Selesai`,
	EditorAppendInlineModeLabel: `Dayakan blok`,
	EditorAppendLineModeLabel: `Dayakan sebaris`,
	EditorAppendManualModeLabel: `Manual togol`,
	EditorAppendNonManualModeLabel: `Manual togol`,
	EditorAppendPauseLabel: `Jeda tambah`,
	EditorAppendPostLabel: `Togol sebelum ini`,
	EditorAppendPreLabel: `Togol sebelum ini`,
	EditorAppendResumeLabel: `Resume tambah`,
	EditorBgColorLabel: `Warna latar belakang`,
	EditorClearAllLabel: `Kosongkan semua`,
	EditorClipboardFormatsLabel: `Format papan klip`,
	EditorColorChooserTitle: `Warna editor`,
	EditorConfirmNtfTitle: `Mengesahkan`,
	EditorDeleteAllButtonText: `Memadam semua`,
	EditorDeleteAllTemplatesNtfText: `Adakah anda pasti mahu memadam semua penggunaan '{0}'?

Perkara ini tidak boleh diubah!`,
	EditorEditTemplateDetailsLabel: `Edit perincian`,
	EditorEditTemplateNameLabel: `Nama`,
	EditorFindLabel: `Cari`,
	EditorFontColorLabel: `Warna fon`,
	EditorFormatPaintLabel: `Format cat`,
	EditorInSelectionLabel: ` Dalam pemilihan`,
	EditorInsertImageLabel: `Masukkan imej`,
	EditorInsertLinkLabel: `Masukkan pautan`,
	EditorInsertVideoLabel: `Masukkan video`,
	EditorLinkButtonText: `Simpan`,
	EditorLinkLabel: `Masukkan pautan`,
	EditorLinkPlaceholder: `Masukkan url`,
	EditorMatchCaseLabel: ` Kes perlawanan`,
	EditorNewTemplateLabel: `Templat baru`,
	EditorNextTemplateLabel: `Templat seterusnya`,
	EditorPasteButtonAppendBeginLabel: `Tambah ...`,
	EditorPasteButtonLabel: `Tampal`,
	EditorPasteTemplateWatermark: `Masukkan teks tampal ...`,
	EditorPrevTemplateLabel: `Templat sebelumnya`,
	EditorRegExLabel: ` Ekspresi biasa`,
	EditorReplaceAllLabel: `Ganti semua`,
	EditorReplaceLabel: `Menggantikan`,
	EditorTemplateContactHint: `<p>Menggunakan kenalan yang tersedia (memerlukan plugin fetcher) medan ini akan digunakan untuk semua kejadian templat ini merentasi dokumen ini atau dalam mana-mana ia akan dirujuk kemudian.</p><p> Jadi sebagai contoh jika pilih alamat e-mel di sini maka medan e-mel kenalan yang anda pilih akan digunakan untuk semua keadaan dalam dokumen ini.</p>`,
	EditorTemplateContactName: `Hubungi`,
	EditorTemplateDateTimeCustomHint: `yy = tahun pendek<br/>yyyy = tahun panjang<br/>M = bulan (1-12)<br/>MM = bulan (01-12)<br/>MMM = singkatan bulan (Jan, Feb ... Disember)<br/>MMMM = bulan panjang (Januari, Februari ... Disember)<br/>d = hari (1 - 31)<br/>dd = hari (01 - 31)<br/>ddd = hari dalam seminggu dalam perkataan (Isnin, Selasa ... Ahad)<br/>E = hari pendek dalam seminggu dalam perkataan (Isnin, Tue ... Ahad)<br/>D - Hari ordinal (1, ke-2, ke-3, ke-21, ke-22, ke-23, ke-31, ke-4...)<br/>h = jam dalam am/pm (0-12)<br/>HH = jam dalam AM/PM (00-12)<br/>H = jam dalam hari (0-23)<br/>HH = jam dalam sehari (00-23)<br/>mm = minit<br/>ss = saat<br/>SSS = milisaat<br/>a = Penanda AM / PM<br/>p = a.m./p.m. penanda`,
	EditorTemplateDateTimeCustomLabel: `Adat`,
	EditorTemplateDateTimeHint: `Tarikh dan/atau masa semasa akan digantikan untuk template datetime apabila mereka disisipkan.`,
	EditorTemplateDateTimeName: `Masa tarikh`,
	EditorTemplateDynamicHint: `<p>Semua kejadian templat ini akan menggunakan teks yang disediakan.</p>`,
	EditorTemplateDynamicName: `Dinamik`,
	EditorTemplateEmptyPlaceholder: `{0} kosong ...`,
	EditorTemplateStaticHint: `<p>Semua kejadian templat ini akan menggunakan teks yang disediakan.</p>`,
	EditorTemplateStaticName: `Statik`,
	EditorTemplateTeaserText: `Lebih banyak lagi akan datang!`,
	EditorTt1: `Klik`,
	EditorTt2: `edit '<em> {0} </em>' ...`,
	EditorTt3: `edit warna ...`,
	EditorTt4: `Keluarkan '<em> {0} </em>' ...`,
	EditorTt5: `Keluarkan item`,
	EditorTt6: `ikut ...`,
	EditorTt7: `Goto '<em> {0} </em>' ...`,
	EditorWatermark: `Sila tunggu...`,
	EditorWholeWordLabel: ` Keseluruhan perkataan`,
	EditorWrapLabel: ` Membungkus`,

};