var UiStrings = {
	EditorAppendCloseLabel: `ಸೇರಿಸುವುದನ್ನು ಮುಗಿಸಿ`,
	EditorAppendInlineModeLabel: `ಬ್ಲಾಕ್ ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ`,
	EditorAppendLineModeLabel: `ಇನ್ಲೈನ್ ​​ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ`,
	EditorAppendManualModeLabel: `ಕೈಪಿಡಿಯನ್ನು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendNonManualModeLabel: `ಕೈಪಿಡಿಯನ್ನು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendPauseLabel: `ವಿರಾಮ ಸೇರಿಸಿ`,
	EditorAppendPostLabel: `ಮೊದಲು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendPreLabel: `ಮೊದಲು ಟಾಗಲ್ ಮಾಡಿ`,
	EditorAppendResumeLabel: `ಪುನರಾರಂಭಿಸು`,
	EditorBgColorLabel: `ಹಿನ್ನೆಲೆ ಬಣ್ಣ`,
	EditorClearAllLabel: `ಎಲ್ಲವನ್ನೂ ತೆಗೆ`,
	EditorClipboardFormatsLabel: `ಕ್ಲಿಪ್‌ಬೋರ್ಡ್ ಸ್ವರೂಪಗಳು`,
	EditorColorChooserTitle: `ಸಂಪಾದಕ ಬಣ್ಣ`,
	EditorConfirmNtfTitle: `ದೃ confirmಿಸು`,
	EditorDeleteAllButtonText: `ಎಲ್ಲಾ ಅಳಿಸಿ`,
	EditorDeleteAllTemplatesNtfText: `'{0}' ನ ಎಲ್ಲಾ ಬಳಕೆಗಳನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?

ಇದನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ!`,
	EditorEditTemplateDetailsLabel: `ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ`,
	EditorEditTemplateNameLabel: `ಹೆಸರು`,
	EditorFindLabel: `ಶೋಧನೆ`,
	EditorFontColorLabel: `ಪಂಜರ ಬಣ್ಣ`,
	EditorFormatPaintLabel: `ಸ್ವರೂಪದ ಬಣ್ಣ`,
	EditorInSelectionLabel: ` ಆಯ್ಕೆಯಲ್ಲಿ`,
	EditorInsertImageLabel: `ಚಿತ್ರವನ್ನು ಸೇರಿಸಿ`,
	EditorInsertLinkLabel: `ಲಿಂಕ್ ಸೇರಿಸಿ`,
	EditorInsertVideoLabel: `ವೀಡಿಯೊ ಸೇರಿಸಿ`,
	EditorLinkButtonText: `ಉಳಿಸು`,
	EditorLinkLabel: `ಲಿಂಕ್ ಅನ್ನು ನಮೂದಿಸಿ`,
	EditorLinkPlaceholder: `URL ಅನ್ನು ನಮೂದಿಸಿ`,
	EditorMatchCaseLabel: ` ಪಂದ್ಯದ ಪ್ರಕರಣ`,
	EditorNewTemplateLabel: `ಹೊಸ ಟೆಂಪ್ಲೇಟ್`,
	EditorNextTemplateLabel: `ಮುಂದಿನ ಟೆಂಪ್ಲೇಟ್`,
	EditorPasteButtonAppendBeginLabel: `ಸೇರಿಸಿ ...`,
	EditorPasteButtonLabel: `ಅಂಟಿಸು`,
	EditorPasteButtonLabelMobile: `ನಕಲು`,
	EditorPasteTemplateWatermark: `ಪೇಸ್ಟ್ ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ ...`,
	EditorPrevTemplateLabel: `ಹಿಂದಿನ ಟೆಂಪ್ಲೇಟ್`,
	EditorRegExLabel: ` ನಿಯಮಿತ ಅಭಿವ್ಯಕ್ತಿ`,
	EditorReplaceAllLabel: `ಎಲ್ಲವನ್ನು ಬದಲಾಯಿಸಿ`,
	EditorReplaceLabel: `ಬದಲಾಗಿ`,
	EditorTemplateContactHint: `<p>ಲಭ್ಯವಿರುವ ಸಂಪರ್ಕಗಳನ್ನು ಬಳಸಿಕೊಂಡು (ಫೆಚರ್ ಪ್ಲಗಿನ್ ಅಗತ್ಯವಿದೆ) ಈ ಫೀಲ್ಡ್ ಅನ್ನು ಈ ದಾಖಲೆಯಾದ್ಯಂತ ಈ ಟೆಂಪ್ಲೇಟ್ ನ ಎಲ್ಲಾ ಸಂದರ್ಭಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಅಥವಾ ನಂತರ ಉಲ್ಲೇಖಿಸಲಾಗುವ ಯಾವುದರಲ್ಲಾದರೂ.</p><p> ಆದ್ದರಿಂದ ಉದಾಹರಣೆಗೆ ಇಲ್ಲಿ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ಆಯ್ಕೆ ಮಾಡಿದರೆ, ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಸಂಪರ್ಕದ ಇಮೇಲ್ ಕ್ಷೇತ್ರವನ್ನು ಈ ದಾಖಲೆಯಲ್ಲಿನ ಎಲ್ಲಾ ಸಂದರ್ಭಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ.</p>`,
	EditorTemplateContactName: `ಸಂಪರ್ಕ`,
	EditorTemplateDateTimeCustomHint: `yy = ಅಲ್ಪ ವರ್ಷ<br/>yyyy = ದೀರ್ಘ ವರ್ಷ<br/>M = ತಿಂಗಳು (1-12)<br/>ಮಿಮೀ = ತಿಂಗಳು (01-12)<br/>MMM = ತಿಂಗಳ ಸಂಕ್ಷಿಪ್ತ ರೂಪ (ಜನವರಿ, ಫೆಬ್ರವರಿ ... ಡಿಸೆಂಬರ್)<br/>MMMM = ದೀರ್ಘ ತಿಂಗಳು (ಜನವರಿ, ಫೆಬ್ರವರಿ ... ಡಿಸೆಂಬರ್)<br/>d = ದಿನ (1 - 31)<br/>DD = ದಿನ (01 - 31)<br/>ಡಿಡಿಡಿ = ಪದಗಳಲ್ಲಿ ವಾರದ ದಿನ (ಸೋಮವಾರ, ಮಂಗಳವಾರ ... ಭಾನುವಾರ)<br/>E = ಪದಗಳಲ್ಲಿ ವಾರದ ಸಣ್ಣ ದಿನ (ಸೋಮವಾರ, ಮಂಗಳವಾರ ... ಸೂರ್ಯ)<br/>ಡಿ - ಆರ್ಡಿನಲ್ ದಿನ (1 ನೇ, 2 ನೇ, 3 ನೇ, 21 ನೇ, 22 ನೇ, 23 ನೇ, 31 ನೇ, 4 ನೇ...)<br/>h = AM/PM ನಲ್ಲಿ ಗಂಟೆ (0-12)<br/>hh = AM/PM ನಲ್ಲಿ ಗಂಟೆ (00-12)<br/>H = ದಿನದಲ್ಲಿ ಒಂದು ಗಂಟೆ (0-23)<br/>HH = ದಿನದಲ್ಲಿ ಒಂದು ಗಂಟೆ (00-23)<br/>ಮಿಮೀ = ನಿಮಿಷ<br/>SS = ಸೆಕೆಂಡ್<br/>SSS = ಮಿಲಿಸೆಕೆಂಡುಗಳು<br/>a = AM/PM ಮಾರ್ಕರ್<br/>p = a.m./p.m. ಮಾರ್ಕರ್`,
	EditorTemplateDateTimeCustomLabel: `ರೂ customಿ`,
	EditorTemplateDateTimeHint: `ಪ್ರಸ್ತುತ ದಿನಾಂಕ ಮತ್ತು/ಅಥವಾ ಸಮಯವನ್ನು ಅಂಟಿಸಿದಾಗ ಡೇಟೈಮ್ ಟೆಂಪ್ಲೆಟ್ಗಳಿಗೆ ಬದಲಿಸಲಾಗುತ್ತದೆ.`,
	EditorTemplateDateTimeName: `ದಿನಾಂಕ ಸಮಯ`,
	EditorTemplateDynamicHint: `<p>ಈ ಟೆಂಪ್ಲೇಟ್ ನ ಎಲ್ಲಾ ಘಟನೆಗಳು ಒದಗಿಸಿದ ಪಠ್ಯವನ್ನು ಬಳಸುತ್ತವೆ.</p>`,
	EditorTemplateDynamicName: `ಭಗ್ನಾವಶೇಷಗಳ`,
	EditorTemplateEmptyPlaceholder: `{0} ಖಾಲಿಯಾಗಿದೆ ...`,
	EditorTemplateStaticHint: `<p>ಈ ಟೆಂಪ್ಲೇಟ್ ನ ಎಲ್ಲಾ ಘಟನೆಗಳು ಒದಗಿಸಿದ ಪಠ್ಯವನ್ನು ಬಳಸುತ್ತವೆ.</p>`,
	EditorTemplateStaticName: `ಸ್ಥಿರವಾದ`,
	EditorTemplateTeaserText: `ಹೆಚ್ಚು ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!`,
	EditorTt1: `ಕ್ಲಿಕ್`,
	EditorTt2: `'<em> {0} </em>' ಅನ್ನು ಸಂಪಾದಿಸಿ ...`,
	EditorTt3: `ಬಣ್ಣವನ್ನು ಸಂಪಾದಿಸಿ ...`,
	EditorTt4: `'<em> {0} </em>' ಅನ್ನು ತೆಗೆದುಹಾಕಿ ...`,
	EditorTt5: `ಐಟಂ ತೆಗೆದುಹಾಕಿ`,
	EditorTt6: `ಅನುಸರಿಸಲು ...`,
	EditorTt7: `ಗೊಟೊ '<em> {0} </em>' ...`,
	EditorWatermark: `ದಯಮಾಡಿ ನಿರೀಕ್ಷಿಸಿ...`,
	EditorWholeWordLabel: ` ಸಂಪೂರ್ಣ ಪದ`,
	EditorWrapLabel: ` ವೃತ್ತಾಕಾರವಾಗಿ ಸುತ್ತು`,

};