var UiStrings = {
	EditorAppendCloseLabel: `Acaba de afegir`,
	EditorAppendInlineModeLabel: `Activar el bloc`,
	EditorAppendLineModeLabel: `Activa en línia`,
	EditorAppendManualModeLabel: `Manual de commutació`,
	EditorAppendNonManualModeLabel: `Manual de commutació`,
	EditorAppendPauseLabel: `Pausa Append`,
	EditorAppendPostLabel: `Commutació abans`,
	EditorAppendPreLabel: `Commutació abans`,
	EditorAppendResumeLabel: `Reprendre l’append`,
	EditorBgColorLabel: `Color de fons`,
	EditorClearAllLabel: `Esborrar tot`,
	EditorClipboardFormatsLabel: `Formats de porta -retalls`,
	EditorColorChooserTitle: `Color de l'editor`,
	EditorConfirmNtfTitle: `Confirmar`,
	EditorDeleteAllButtonText: `Eliminar tots`,
	EditorDeleteAllTemplatesNtfText: `Esteu segur que voleu eliminar tots els usos de '{0}'?

Això no es pot desfer!`,
	EditorEditTemplateDetailsLabel: `Editeu els detalls`,
	EditorEditTemplateNameLabel: `Nom`,
	EditorFindLabel: `Trobar`,
	EditorFontColorLabel: `Color de la lletra`,
	EditorFormatPaintLabel: `Format de pintura`,
	EditorInSelectionLabel: ` En selecció`,
	EditorInsertImageLabel: `Inseriu la imatge`,
	EditorInsertLinkLabel: `Enllaç d'inserció`,
	EditorInsertVideoLabel: `Inseriu el vídeo`,
	EditorLinkButtonText: `Estalviar`,
	EditorLinkLabel: `Introduïu l'enllaç`,
	EditorLinkPlaceholder: `Introduïu l'URL`,
	EditorMatchCaseLabel: ` Caixa de coincidència`,
	EditorNewTemplateLabel: `Plantilla nova`,
	EditorNextTemplateLabel: `Plantilla següent`,
	EditorPasteButtonAppendBeginLabel: `Append ...`,
	EditorPasteButtonLabel: `Pastar`,
	EditorPasteButtonLabelMobile: `Còpia`,
	EditorPasteTemplateWatermark: `Introduïu el text de pasta ...`,
	EditorPrevTemplateLabel: `Plantilla anterior`,
	EditorRegExLabel: ` Expressió normal`,
	EditorReplaceAllLabel: `Substituïu -ho tot`,
	EditorReplaceLabel: `Tornar a col·locar`,
	EditorTemplateContactHint: `<p>Utilitzant els contactes disponibles (requereix un connector d'obtenció), aquest camp s'utilitzarà per a totes les instàncies d'aquesta plantilla en aquest document o en qualsevol en què es farà referència més endavant.</p><p> Així, per exemple, si seleccioneu l'adreça de correu electrònic aquí, el camp de correu electrònic del contacte que seleccioneu s'utilitzarà per a totes les instàncies d'aquest document.</p>`,
	EditorTemplateContactName: `Contacte`,
	EditorTemplateDateTimeCustomHint: `yy = any curt<br/>yyyy = any llarg<br/>M = mes (1-12)<br/>MM = mes (01-12)<br/>MMM = abreviatura de mes (gener, febrer ... Des)<br/>MMMM = mes llarg (gener, febrer... Desembre)<br/>d = dia (1 - 31)<br/>dd = dia (01 - 31)<br/>ddd = dia de la setmana en paraules (dilluns, dimarts... Diumenge)<br/>E = dia curt de la setmana en paraules (dll, dm... Sol)<br/>D - Dia ordinal (1r, 2n, 3r, 21, 22, 23, 31, 4t...)<br/>h = hora a am/pm (0-12)<br/>hh = hora a am/pm (00-12)<br/>H = hora al dia (0-23)<br/>HH = hora al dia (00-23)<br/>mm = minut<br/>ss = segon<br/>SSS = mil·lisegons<br/>a = marcador AM/PM<br/>p = marcador a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Costum`,
	EditorTemplateDateTimeHint: `La data i/o hora actuals es substituiran per les plantilles de DateTime quan siguin enganxades.`,
	EditorTemplateDateTimeName: `Data i hora`,
	EditorTemplateDynamicHint: `<p>Totes les ocurrències d'aquesta plantilla utilitzaran el text proporcionat.</p>`,
	EditorTemplateDynamicName: `Dinàmic`,
	EditorTemplateEmptyPlaceholder: `{0} està buit ...`,
	EditorTemplateStaticHint: `<p>Totes les ocurrències d'aquesta plantilla utilitzaran el text proporcionat.</p>`,
	EditorTemplateStaticName: `Estàtic`,
	EditorTemplateTeaserText: `Aviat, més!`,
	EditorTt1: `Feu clic`,
	EditorTt2: `edita '<em>{0}</em>'...`,
	EditorTt3: `edita el color...`,
	EditorTt4: `elimina "<em>{0}</em>"...`,
	EditorTt5: `eliminar l'element`,
	EditorTt6: `seguir ...`,
	EditorTt7: `anar a "<em>{0}</em>"...`,
	EditorWatermark: `Si us plau, espereu ...`,
	EditorWholeWordLabel: ` Paraula sencera`,
	EditorWrapLabel: ` Embolicar`,

};