var UiStrings = {
	EditorAppendCloseLabel: `Тәмамлау`,
	EditorAppendInlineModeLabel: `Блокны кушу`,
	EditorAppendLineModeLabel: `Йомшаклау`,
	EditorAppendManualModeLabel: `Кулланма`,
	EditorAppendNonManualModeLabel: `Кулланма`,
	EditorAppendPauseLabel: `Пауза кушымтасы`,
	EditorAppendPostLabel: `Моңа кадәр`,
	EditorAppendPreLabel: `Моңа кадәр`,
	EditorAppendResumeLabel: `Резюме кушымтасы`,
	EditorBgColorLabel: `Фон төсе`,
	EditorClearAllLabel: `Барысын да чистарту`,
	EditorClipboardFormatsLabel: `Такталар форматлары`,
	EditorConfirmNtfTitle: `Раслагыз`,
	EditorDeleteAllButtonText: `Барысын да бетерү`,
	EditorDeleteAllTemplatesNtfText: `"{0}" барлык кулланмаларны бетерергә телисезме?

Моны кире кайтарып булмый!`,
	EditorEditTemplateDetailsLabel: `Детальләрне үзгәртү`,
	EditorEditTemplateNameLabel: `Исем`,
	EditorFindLabel: `Табу`,
	EditorFontColorLabel: `Шрифт төсе`,
	EditorFormatPaintLabel: `Буяу Буяу`,
	EditorInSelectionLabel: ` Сайлауда`,
	EditorInsertImageLabel: `Рәсем кертү`,
	EditorInsertLinkLabel: `Ссылка салу`,
	EditorInsertVideoLabel: `Видео кертегез`,
	EditorMatchCaseLabel: ` Матч эше`,
	EditorNewTemplateLabel: `Яңа шаблон`,
	EditorNextTemplateLabel: `Киләсе шаблон`,
	EditorPasteButtonAppendBeginLabel: `Кушымта ...`,
	EditorPasteButtonLabel: `Паста`,
	EditorPasteTemplateWatermark: `Паста текстын кертегез ...`,
	EditorPrevTemplateLabel: `Элеккеге шаблон`,
	EditorRegExLabel: ` Регуляр белдерү`,
	EditorReplaceAllLabel: `Барысын да алыштырыгыз`,
	EditorReplaceLabel: `Алыштырыгыз`,
	EditorTemplateContactHint: `<p>Булган контактларны кулланып (шпр.-флэш таләп итә) бу кыр шушы документ аша бу шаблийның барлык инҗирләре өчен яки аннан соң да искә алыначак.</p><p> Мәсәлән, монда электрон почта адресын сайласа, сайлаган контактның электрон кыры бу документтагы барлык очраклар өчен кулланылыр.</p>`,
	EditorTemplateContactName: `Контакт`,
	EditorTemplateDateTimeCustomHint: `yy = кыска ел<br/>yyy = озын ел<br/>M = ае (1-12)<br/>MM = ае (01-12)<br/>MMM = ай аббревиатурасы (Ян, февраль... Декабрь)<br/>MMM = озын ай (гыйнвар, февраль... Декабрь)<br/>d = көн (1 — 31)<br/>dd = көн (01 — 31)<br/>ddd = атна көне сүз белән (дүшәмбе, сишәмбе... Якшәмбе)<br/>E = атнаның кыска көне сүз белән (Мон, Ту... Кояш)<br/>D - Ординал көне (1-нче, 2-нче, 3-нче, 21-нче, 22-нче, 23 нче, 31-нче, 4-нче...)<br/>h = сәгать сәгать / сәгатьтә (0-12)<br/>hh = сәгать сәгатьтә / сәгатьтә (00-12)<br/>H = сәгать (0-23)<br/>HH = сәгать (00-23)<br/>мм = минут<br/>ss = икенче<br/>SSS = миллисекондлар<br/>a = AM / PM маркеры<br/>p = a.m./ p.m. маркер`,
	EditorTemplateDateTimeCustomLabel: `Гадәт`,
	EditorTemplateDateTimeHint: `Агымдагы датада һәм / яки вакыт ябык булганда даталы шаблоннар өчен алыштырылачак.`,
	EditorTemplateDateTimeName: `Дата вакыты`,
	EditorTemplateDynamicHint: `<p>Бу шаблийның барысы да китерелгән текстны кулланыр.</p>`,
	EditorTemplateDynamicName: `Динамик`,
	EditorTemplateEmptyPlaceholder: `{0} буш ...`,
	EditorTemplateStaticHint: `<p>Бу шаблийның барысы да китерелгән текстны кулланыр.</p>`,
	EditorTemplateStaticName: `Статик`,
	EditorTemplateTeaserText: `Тиздән тагын да күбрәк якынлаша!`,
	EditorWatermark: `Зинһар, көтегез...`,
	EditorWholeWordLabel: ` Бөтен сүз`,
	EditorWrapLabel: ` Урлау`,

};