var UiStrings = {
	EditorAppendCloseLabel: `যোগদান শেষ`,
	EditorAppendInlineModeLabel: `ব্লক সক্ষম করুন`,
	EditorAppendLineModeLabel: `ইনলাইন সক্ষম করুন`,
	EditorAppendManualModeLabel: `টগল ম্যানুয়াল`,
	EditorAppendNonManualModeLabel: `টগল ম্যানুয়াল`,
	EditorAppendPauseLabel: `বিরতি সংযোজন`,
	EditorAppendPostLabel: `আগে টগল করুন`,
	EditorAppendPreLabel: `আগে টগল করুন`,
	EditorAppendResumeLabel: `পুনরায় সংযুক্তি`,
	EditorBgColorLabel: `পেছনের রং`,
	EditorClearAllLabel: `সব পরিষ্কার করে দাও`,
	EditorClipboardFormatsLabel: `ক্লিপবোর্ড ফর্ম্যাট`,
	EditorColorChooserTitle: `সম্পাদক রঙ`,
	EditorConfirmNtfTitle: `নিশ্চিত করুন`,
	EditorDeleteAllButtonText: `সব মুছে ফেলুন`,
	EditorDeleteAllTemplatesNtfText: `আপনি কি নিশ্চিত যে আপনি '{0}' এর সমস্ত ব্যবহার মুছতে চান?

এটা অসম্পূর্ণ থাকতে পারে না!`,
	EditorEditTemplateDetailsLabel: `তথ্য সংশোধন কর`,
	EditorEditTemplateNameLabel: `নাম`,
	EditorFindLabel: `অনুসন্ধান`,
	EditorFontColorLabel: `ফন্টের রং`,
	EditorFormatPaintLabel: `ফর্ম্যাট পেইন্ট`,
	EditorInSelectionLabel: ` নির্বাচন`,
	EditorInsertImageLabel: `চিত্র sert োকান`,
	EditorInsertLinkLabel: `লিঙ্ক sert োকান`,
	EditorInsertVideoLabel: `ভিডিও sert োকান`,
	EditorLinkButtonText: `সংরক্ষণ`,
	EditorLinkLabel: `লিঙ্ক লিখুন`,
	EditorLinkPlaceholder: `ইউআরএল দিন`,
	EditorMatchCaseLabel: ` ম্যাচ ক্ষেত্রে`,
	EditorNewTemplateLabel: `নতুন টেম্পলেট`,
	EditorNextTemplateLabel: `পরবর্তী টেম্পলেট`,
	EditorPasteButtonAppendBeginLabel: `সংযোজন ...`,
	EditorPasteButtonLabel: `আটকান`,
	EditorPasteButtonLabelMobile: `অনুলিপি`,
	EditorPasteTemplateWatermark: `পেস্ট পাঠ্য প্রবেশ করুন ...`,
	EditorPrevTemplateLabel: `পূর্ববর্তী টেম্পলেট`,
	EditorRegExLabel: ` নিয়মিত অভিব্যক্তি`,
	EditorReplaceAllLabel: `সমস্ত প্রতিস্থাপন`,
	EditorReplaceLabel: `প্রতিস্থাপন`,
	EditorTemplateContactHint: `<p>উপলভ্য পরিচিতিগুলি ব্যবহার করে (একটি ফেচার প্লাগইন প্রয়োজন) এই ক্ষেত্রটি এই দস্তাবেজ জুড়ে এই টেমপ্লেটের সমস্ত উদাহরণের জন্য ব্যবহার করা হবে বা যে কোনও ক্ষেত্রে এটি পরে উল্লেখ করা হবে।</p><p> সুতরাং উদাহরণস্বরূপ, যদি এখানে ইমেল ঠিকানা নির্বাচন করা হয় তবে আপনার নির্বাচন করা পরিচিতির ইমেল ক্ষেত্রটি এই দস্তাবেজের সমস্ত দৃষ্টান্তের জন্য ব্যবহৃত হবে।</p>`,
	EditorTemplateContactName: `যোগাযোগ`,
	EditorTemplateDateTimeCustomHint: `y = সংক্ষিপ্ত বছর<br/>yyyy = দীর্ঘ বছর<br/>এম = মাস (১-১২)<br/>এম এম = মাস (০১-১২)<br/>এমএমএম = মাস সংক্ষেপণ (জানুয়ারী, ফেব্রুয়ারী ... ডিসেম্বর)<br/>এমএমএমএম = দীর্ঘ মাস (জানুয়ারি, ফেব্রুয়ারি ... ডিসেম্বর)<br/>d = দিন (১ - ৩১)<br/>dd = দিন (01 - 31)<br/>ডিডিডি = কথায় কথায় সপ্তাহের দিন (সোমবার, মঙ্গলবার... রবিবার)<br/>E = কথায় কথায় সপ্তাহের ছোট দিন (সোম, মঙ্গল... সূর্য)<br/>ডি - অর্ডিনাল দিন (১ম, ২য়, ৩য়, ২১তম, ২২তম, ২৩তম, ৩১তম, ৪র্থ...)<br/>এইচ = এএম / পিএম ঘন্টা (0-12)<br/>এইচএইচ = এএম/পিএম ঘন্টা (00-12)<br/>H = দিনে ঘন্টা (0-23)<br/>HH = দিনে ঘন্টা (00-23)<br/>মিমি = মিনিট<br/>এসএস = সেকেন্ড<br/>SSS = মিলিসেকেন্ড<br/>a = AM/PM চিহ্নিতকারী<br/>পি = এএম / পিএম চিহ্নিতকারী`,
	EditorTemplateDateTimeCustomLabel: `কাস্টম`,
	EditorTemplateDateTimeHint: `বর্তমান তারিখ এবং/অথবা সময়টি ডেটটাইম টেম্পলেটগুলি পেস্ট করার সময় প্রতিস্থাপন করা হবে।`,
	EditorTemplateDateTimeName: `তারিখ সময়`,
	EditorTemplateDynamicHint: `<p>এই টেমপ্লেটের সমস্ত ঘটনা প্রদত্ত পাঠ্য ব্যবহার করবে।</p>`,
	EditorTemplateDynamicName: `গতিশীল`,
	EditorTemplateEmptyPlaceholder: `{0} খালি ...`,
	EditorTemplateStaticHint: `<p>এই টেমপ্লেটের সমস্ত ঘটনা প্রদত্ত পাঠ্য ব্যবহার করবে।</p>`,
	EditorTemplateStaticName: `স্থির`,
	EditorTemplateTeaserText: `আরও শীঘ্রই আসছে!`,
	EditorTt1: `ক্লিক`,
	EditorTt2: `'<em>{0}</em>' সম্পাদনা করুন ...`,
	EditorTt3: `রঙ সম্পাদনা করুন...`,
	EditorTt4: `'<em>{0}</em>' সরান...`,
	EditorTt5: `আইটেম অপসারণ`,
	EditorTt6: `অনুসরণ করতে...`,
	EditorTt7: `'<em>{0}</em>' এ যান ...`,
	EditorWatermark: `অনুগ্রহপূর্বক অপেক্ষা করুন...`,
	EditorWholeWordLabel: ` সমগ্র শব্দ`,
	EditorWrapLabel: ` চারপাশে মোড়ানো`,

};