var UiStrings = {
	EditorAppendCloseLabel: `לסיים את הוספת`,
	EditorAppendInlineModeLabel: `אפשר בלוק`,
	EditorAppendLineModeLabel: `אפשר מינון`,
	EditorAppendManualModeLabel: `מדריך לחלק`,
	EditorAppendNonManualModeLabel: `מדריך לחלק`,
	EditorAppendPauseLabel: `הוספה הוספה`,
	EditorAppendPostLabel: `לעבור לפני כן`,
	EditorAppendPreLabel: `לעבור לפני כן`,
	EditorAppendResumeLabel: `לחדש את הוספה`,
	EditorBgColorLabel: `צבע רקע`,
	EditorClearAllLabel: `לנקות הכל`,
	EditorClipboardFormatsLabel: `פורמטים של לוח`,
	EditorConfirmNtfTitle: `לְאַשֵׁר`,
	EditorDeleteAllButtonText: `מחק הכל`,
	EditorDeleteAllTemplatesNtfText: `האם אתה בטוח שאתה רוצה למחוק את כל השימושים של '{0}'?

אי אפשר לבטל את זה!`,
	EditorEditTemplateDetailsLabel: `לערוך את הפרטים`,
	EditorEditTemplateNameLabel: `שֵׁם`,
	EditorFindLabel: `למצוא`,
	EditorFontColorLabel: `צבע גופן`,
	EditorFormatPaintLabel: `פורמט צבע`,
	EditorInSelectionLabel: ` בבחירה`,
	EditorInsertImageLabel: `הוסף תמונה`,
	EditorInsertLinkLabel: `הכנס קישור`,
	EditorInsertVideoLabel: `הכנס וידאו`,
	EditorMatchCaseLabel: ` מקרה התאמה`,
	EditorNewTemplateLabel: `תבנית חדשה`,
	EditorNextTemplateLabel: `התבנית הבאה`,
	EditorPasteButtonAppendBeginLabel: `לְצַרֵף...`,
	EditorPasteButtonLabel: `לְהַדבִּיק`,
	EditorPasteTemplateWatermark: `הזן טקסט הדבק ...`,
	EditorPrevTemplateLabel: `תבנית קודמת`,
	EditorRegExLabel: ` הבעה רגילה`,
	EditorReplaceAllLabel: `החלף הכל`,
	EditorReplaceLabel: `החלף`,
	EditorTemplateContactHint: `<p> שימוש באנשי קשר זמינים (דורש תוסף Fetcher) שדה זה ישמש לכל המקרים של תבנית זו על פני מסמך זה או בכל אחד אז אז שדה הדואר האלקטרוני של ה- Contact You Select ישמש לכל המקרים במסמך זה. </p>`,
	EditorTemplateContactName: `איש קשר`,
	EditorTemplateDateTimeCustomHint: `YY = שנה קצרה <br/> yyyy = שנה ארוכה <br/> m = חודש (1-12) <br/> mm = חודש (01-12) <br/> mmm = קיצור חודש (ינואר, פברואר .. . דצמבר) <br/> mmmm = חודש ארוך (ינואר, פברואר ... דצמבר) <br/> d = יום (1 ​​- 31) <br/> dd = יום (01 - 31) <br/> ddd = יום השבוע במילים (שני, שלישי ... יום ראשון) <br/> e = יום קצר בשבוע במילים (יום שני, יום שלישי ... שמש) <br/> D - יום רגיל (1, 2nd, 3, 21, 22nd, 23, 31, 4 ...) <br/> h = שעה בשעה/pm (0-12) <br/> hh = שעה בשעה/pm (00-12) <br/ > H = שעה ביום (0-23) <br/> hh = שעה ביום (00-23) <br/> mm = דקה <br/> ss = שני <br/> sss = אלפיות שניות <br/> A = AM/PM סמן <br/> p = a.m./p.m. סַמָן`,
	EditorTemplateDateTimeCustomLabel: `המותאם אישית`,
	EditorTemplateDateTimeHint: `התאריך ו/או השעה הנוכחיים יחליפו תבניות של תאריך תאריך כאשר הם מודבקים.`,
	EditorTemplateDateTimeName: `תאריך שעה`,
	EditorTemplateDynamicHint: `<p> כל ההופעות של תבנית זו ישתמשו בטקסט המסופק. </p>`,
	EditorTemplateDynamicName: `דִינָמִי`,
	EditorTemplateEmptyPlaceholder: `{0} ריק ...`,
	EditorTemplateStaticHint: `<p> כל ההופעות של תבנית זו ישתמשו בטקסט המסופק. </p>`,
	EditorTemplateStaticName: `סטָטִי`,
	EditorTemplateTeaserText: `עוד בקרוב!`,
	EditorWatermark: `המתן בבקשה...`,
	EditorWholeWordLabel: ` כל העולם`,
	EditorWrapLabel: ` לעטוף`,

};