var UiStrings = {
	EditorAppendCloseLabel: `ପ୍ରୟୋଗ ସମାପ୍ତ କରନ୍ତୁ |`,
	EditorAppendInlineModeLabel: `ବ୍ଲକକୁ ସକ୍ଷମ କରନ୍ତୁ |`,
	EditorAppendLineModeLabel: `ଇନଲାଇନକୁ ସକ୍ଷମ କରନ୍ତୁ |`,
	EditorAppendManualModeLabel: `ମାନୁଆଲ୍ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendNonManualModeLabel: `ମାନୁଆଲ୍ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendPauseLabel: `ବିରତି ଆବେଦନ କରନ୍ତୁ |`,
	EditorAppendPostLabel: `ପୂର୍ବରୁ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendPreLabel: `ପୂର୍ବରୁ ଟୋଗଲ୍ କରନ୍ତୁ |`,
	EditorAppendResumeLabel: `ଆବେଦନ ଆରମ୍ଭ କର |`,
	EditorBgColorLabel: `ପୃଷ୍ଠଭୂମି ରଙ୍ଗ`,
	EditorClearAllLabel: `ସମସ୍ତ ସଫା କରନ୍ତୁ |`,
	EditorClipboardFormatsLabel: `କ୍ଲିପବୋର୍ଡ ଫର୍ମାଟ୍ |`,
	EditorConfirmNtfTitle: `ନିଶ୍ଚିତ କର |`,
	EditorDeleteAllButtonText: `ସମସ୍ତ ବିଲୋପ କରନ୍ତୁ |`,
	EditorDeleteAllTemplatesNtfText: `ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ '{0}' ର ସମସ୍ତ ବ୍ୟବହାର ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?

ଏହାକୁ ପୂର୍ବବତ୍ କରାଯାଇପାରିବ ନାହିଁ!`,
	EditorEditTemplateDetailsLabel: `ବିବରଣୀଗୁଡିକ ସଂପାଦନ କରନ୍ତୁ |`,
	EditorEditTemplateNameLabel: `ନାମ`,
	EditorFindLabel: `ଖୋଜ |`,
	EditorFontColorLabel: `ଫଣ୍ଟ୍ ରଙ୍ଗ |`,
	EditorFormatPaintLabel: `ଫର୍ମାଟ୍ ରଙ୍ଗ`,
	EditorInSelectionLabel: ` ଚୟନ ରେ`,
	EditorInsertImageLabel: `ପ୍ରତିଛବି ସନ୍ନିବେଶ କରନ୍ତୁ |`,
	EditorInsertLinkLabel: `ଲିଙ୍କ୍ ସନ୍ନିବେଶ କରନ୍ତୁ |`,
	EditorInsertVideoLabel: `ଭିଡିଓ ସନ୍ନିବେଶ କରନ୍ତୁ |`,
	EditorMatchCaseLabel: ` ମ୍ୟାଚ୍ ମାମଲା |`,
	EditorNewTemplateLabel: `ନୂତନ ଟେମ୍ପଲେଟ୍`,
	EditorNextTemplateLabel: `ପରବର୍ତ୍ତୀ ଟେମ୍ପଲେଟ୍ |`,
	EditorPasteButtonAppendBeginLabel: `ଯୋଡ ...`,
	EditorPasteButtonLabel: `ପେଷ୍ଟ କରନ୍ତୁ |`,
	EditorPasteTemplateWatermark: `ପେଷ୍ଟ ଟେକ୍ସଟ୍ ପ୍ରବେଶ କରନ୍ତୁ ...`,
	EditorPrevTemplateLabel: `ପୂର୍ବ ଟେମ୍ପଲେଟ୍ |`,
	EditorRegExLabel: ` ନିୟମିତ ଅଭିବ୍ୟକ୍ତି |`,
	EditorReplaceAllLabel: `ସମସ୍ତଙ୍କୁ ବଦଳାନ୍ତୁ |`,
	EditorReplaceLabel: `ବଦଳାନ୍ତୁ`,
	EditorTemplateContactHint: `<P> ଉପଲବ୍ଧ ସମ୍ପର୍କଗୁଡିକ ବ୍ୟବହାର କରି (ଏକ ଫେର୍ବେର୍ ପ୍ଲଗଇନ୍ ଆବଶ୍ୟକ କରେ) ଏହି କ୍ଷେତ୍ରଟି ପରବର୍ତ୍ତୀ ସମୟରେ ଏହି ଡକ୍ୟୁମେଣ୍ଟ୍ ପାଇଁ ରେ ରେଫରେନ୍ସ କରିବ | </ p> <p> ତେଣୁ ଉଦାହରଣ ସ୍ୱରୂପ ଯଦି ଇମେଲ ଠିକଣା ଚୟନ କରିବେ | ତା'ପରେ ଏଠାରେ ଆପଣ ଚୟନ କରୁଥିବା ଯୋଗାଯୋଗ କ୍ଷେତ୍ରକୁ ଏହି ଡକ୍ୟୁମେଣ୍ଟରେ ସମସ୍ତ ଉଦାହରଣ ପାଇଁ ବ୍ୟବହାର କରାଯିବ ଯାହାକୁ ଏହି ଡକ୍ୟୁମେଣ୍ଟରେ ସମସ୍ତ ଉଦାହରଣ ପାଇଁ ବ୍ୟବହାର କରାଯିବ | </ p>`,
	EditorTemplateContactName: `ଯୋଗାଯୋଗ କରନ୍ତୁ |`,
	EditorTemplateDateTimeCustomHint: `yy = ସ୍ୱଳ୍ପ ବର୍ଷ <br/> yyyy = ମାସରେ </> m = ମାସ (1-12) <br/> mm = ମାସ ସଂକ୍ଷିପ୍ତ (ଜାନ, ଫେବୃଆରୀ .. । ଡିସେମ୍ବର) <br/> mmmm = ଲମ୍ବା ମାସ (ଜାନୁଆରୀ, ଫେବୃଆରୀ ... ଡିସେମ୍ବର - << <> dd = ଦିନ) <br/> DDD = | ଶବ୍ଦର ଦିନ (ସୋମବାର, ମଙ୍ଗଳବାର ... ରବିବାର) <br/> e = ର ଛୋଟ ଦିନ (ସୋମ, ମଙ୍ଗଳ ... 3, 21, 23, 23, 31, 31, 4S, 4TH ...) <br /: AM / PM (00-12) <Cl = > H = ଦିନରେ ଘଣ୍ଟାରେ (0-23) <br:/> hh = ଘଣ୍ଟାରେ (00-23) <br /> MM = ମିନିଟ୍ <br/> MM = ଦ୍ୱିତୀୟ <br/> SSS = MLYSECHES <br/> | a = am / pm ମାର୍କର <br/> p = a.m./p.m | ମାର୍କର`,
	EditorTemplateDateTimeCustomLabel: `କଷ୍ଟମ୍`,
	EditorTemplateDateTimeHint: `ସାମ୍ପ୍ରତିକ ତାରିଖ ଏବଂ / କିମ୍ବା ସମୟ ପେଷ୍ଟ ହୋଇଥିବାବେଳେ ତାରିଖ ଟେମ୍ପଲେଟ୍ ପାଇଁ ବଦଳାଯିବ |`,
	EditorTemplateDateTimeName: `ତାରିଖ ସମୟ`,
	EditorTemplateDynamicHint: `ଏହି ଟେମ୍ପଲେଟର ସମସ୍ତ ଘଟଣା ଦ୍ the ାରା ପ୍ରଦାନ କରାଯାଇଥିବା ପାଠ୍ୟକୁ ବ୍ୟବହାର କରିବ | </ p>`,
	EditorTemplateDynamicName: `ଗତିଶୀଳତା |`,
	EditorTemplateEmptyPlaceholder: `{0} ଖାଲି ...`,
	EditorTemplateStaticHint: `ଏହି ଟେମ୍ପଲେଟର ସମସ୍ତ ଘଟଣା ଦ୍ the ାରା ପ୍ରଦାନ କରାଯାଇଥିବା ପାଠ୍ୟକୁ ବ୍ୟବହାର କରିବ | </ p>`,
	EditorTemplateStaticName: `ପରିସଂଖ୍ୟାନ`,
	EditorTemplateTeaserText: `ଶୀଘ୍ର ଅଧିକ ଦେଖାଯିବ!`,
	EditorWatermark: `ଦୟାକରି ଅପେକ୍ଷା କର...`,
	EditorWholeWordLabel: ` ପୁରା ଟର୍ମସୀ`,
	EditorWrapLabel: ` ଚାରିଆଡ଼େ ଗୁଡ଼ାଇ ରଖ |`,

};