var UiStrings = {
	EditorAppendCloseLabel: `Befejezi a mellékletet`,
	EditorAppendInlineModeLabel: `Engedélyezze a blokkot`,
	EditorAppendLineModeLabel: `Engedélyezze az inline -t`,
	EditorAppendManualModeLabel: `Váltókézés`,
	EditorAppendNonManualModeLabel: `Váltókézés`,
	EditorAppendPauseLabel: `Szüneteltesse a mellékletet`,
	EditorAppendPostLabel: `Váltás előtt`,
	EditorAppendPreLabel: `Váltás előtt`,
	EditorAppendResumeLabel: `Folytassa a függeléket`,
	EditorBgColorLabel: `Háttérszín`,
	EditorClearAllLabel: `Mindent kitöröl`,
	EditorClipboardFormatsLabel: `Vágólap formátumai`,
	EditorConfirmNtfTitle: `megerősít`,
	EditorDeleteAllButtonText: `Mindet törölni`,
	EditorDeleteAllTemplatesNtfText: `Biztos benne, hogy törölni akarja a '{0}' összes felhasználását?

Ezt nem lehet visszacsinálni!`,
	EditorEditTemplateDetailsLabel: `Részletek szerkesztése`,
	EditorEditTemplateNameLabel: `Név`,
	EditorFindLabel: `megtalálja`,
	EditorFontColorLabel: `Betű szín`,
	EditorFormatPaintLabel: `Formátumfesték`,
	EditorInSelectionLabel: ` Válogatáskor`,
	EditorInsertImageLabel: `Beilleszteni a képet`,
	EditorInsertLinkLabel: `Helyezze be a linket`,
	EditorInsertVideoLabel: `Beilleszteni a videót`,
	EditorMatchCaseLabel: ` Mérkőzés esetén`,
	EditorNewTemplateLabel: `Új sablon`,
	EditorNextTemplateLabel: `Következő sablon`,
	EditorPasteButtonAppendBeginLabel: `Mellékel...`,
	EditorPasteButtonLabel: `Paszta`,
	EditorPasteTemplateWatermark: `Írja be a paszta szöveget ...`,
	EditorPrevTemplateLabel: `Előző sablon`,
	EditorRegExLabel: ` Reguláris kifejezés`,
	EditorReplaceAllLabel: `Cserélje ki az összeset`,
	EditorReplaceLabel: `Cserél`,
	EditorTemplateContactHint: `<p>A rendelkezésre álló névjegyek használatával (amelyhez fetcher bővítmény szükséges) ez a mező lesz használva a sablon összes példányához ebben a dokumentumban, vagy bármely olyan példányban, amelyre később hivatkozni fogunk.</p><p> Tehát például, ha itt válassza ki az e-mail címet, akkor a kiválasztott kapcsolattartó e-mail mezőjét fogja használni a dokumentum összes példányához.</p>`,
	EditorTemplateContactName: `Kapcsolatba lépni`,
	EditorTemplateDateTimeCustomHint: `yy = rövid év<br/>yyyy = hosszú év<br/>M = hónap (1-12)<br/>MM = hónap (01-12)<br/>MMM = hónap rövidítése (január, február ... Dec)<br/>MMMM = hosszú hónap (január, február ... December)<br/>d = nap (1 - 31)<br/>dd = nap (01 - 31)<br/>ddd = a hét napja szavakkal (hétfő, kedd ... Vasárnap)<br/>E = a hét rövid napja szavakkal (hétfő, kedd ... Nap)<br/>D - Sorszám napja (1., 2., 3., 21., 22., 23., 31., 4. ...)<br/>h = óra dél/percben (0-12)<br/>HH = óra dél/percben (00-12)<br/>H = a nap órája (0-23)<br/>HH = óra a napban (00-23)<br/>mm = perc<br/>ss = másodperc<br/>SSS = ezredmásodperc<br/>a = AM/PM jelölő<br/>p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Egyedi`,
	EditorTemplateDateTimeHint: `Az aktuális dátumot és/vagy az időt helyettesítik a DateTime sablonok beillesztésekor.`,
	EditorTemplateDateTimeName: `Dátum idő`,
	EditorTemplateDynamicHint: `<p>A sablon minden előfordulása a megadott szöveget fogja használni.</p>`,
	EditorTemplateDynamicName: `Dinamikus`,
	EditorTemplateEmptyPlaceholder: `{0} üres ...`,
	EditorTemplateStaticHint: `<p>A sablon minden előfordulása a megadott szöveget fogja használni.</p>`,
	EditorTemplateStaticName: `Statikus`,
	EditorTemplateTeaserText: `Hamarosan még több jön!`,
	EditorWatermark: `Kérlek várj...`,
	EditorWholeWordLabel: ` Egész világ`,
	EditorWrapLabel: ` Körbeteker`,

};