var UiStrings = {
	EditorAppendCloseLabel: `الانتهاء من الإلحاق`,
	EditorAppendInlineModeLabel: `تمكين كتلة`,
	EditorAppendLineModeLabel: `تمكين مضمونة`,
	EditorAppendManualModeLabel: `دليل تبديل`,
	EditorAppendNonManualModeLabel: `دليل تبديل`,
	EditorAppendPauseLabel: `الإيقاف التوقف`,
	EditorAppendPostLabel: `تبديل من قبل`,
	EditorAppendPreLabel: `تبديل من قبل`,
	EditorAppendResumeLabel: `استئناف إلحاق`,
	EditorBgColorLabel: `لون الخلفية`,
	EditorClearAllLabel: `امسح الكل`,
	EditorClipboardFormatsLabel: `تنسيقات الحافظة`,
	EditorConfirmNtfTitle: `يتأكد`,
	EditorDeleteAllButtonText: `حذف الكل`,
	EditorDeleteAllTemplatesNtfText: `هل أنت متأكد من أنك تريد حذف جميع استخدامات "{0}؟

هذا لا يمكن التراجع عنها!`,
	EditorEditTemplateDetailsLabel: `عدل التفاصيل`,
	EditorEditTemplateNameLabel: `اسم`,
	EditorFindLabel: `يجد`,
	EditorFontColorLabel: `لون الخط`,
	EditorFormatPaintLabel: `تنسيق الطلاء`,
	EditorInSelectionLabel: ` في الاختيار`,
	EditorInsertImageLabel: `إدراج صورة`,
	EditorInsertLinkLabel: `أدخل الرابط`,
	EditorInsertVideoLabel: `أدخل الفيديو`,
	EditorMatchCaseLabel: ` حالة مباراة`,
	EditorNewTemplateLabel: `قالب جديد`,
	EditorNextTemplateLabel: `القالب التالي`,
	EditorPasteButtonAppendBeginLabel: `ألحق...`,
	EditorPasteButtonLabel: `معجون`,
	EditorPasteTemplateWatermark: `أدخل نص لصق ...`,
	EditorPrevTemplateLabel: `القالب السابق`,
	EditorRegExLabel: ` تعبير عادي`,
	EditorReplaceAllLabel: `استبدل كل شيء`,
	EditorReplaceLabel: `يستبدل`,
	EditorTemplateContactHint: `<p>باستخدام جهات الاتصال المتاحة (يتطلب مكونا إضافيا للجلب) ، سيتم استخدام هذا الحقل لجميع مثيلات هذا القالب عبر هذا المستند أو في أي منها سيتم الرجوع إليه لاحقا.</p><p> على سبيل المثال ، إذا حدد عنوان البريد الإلكتروني هنا ، استخدام حقل البريد الإلكتروني لجهة الاتصال التي تحددها لجميع الحالات في هذا المستند.</p>`,
	EditorTemplateContactName: `اتصال`,
	EditorTemplateDateTimeCustomHint: `yy = سنة قصيرة<br/>yyyy = سنة طويلة<br/>م = الشهر (1-12)<br/>MM = الشهر (01-12)<br/>MMM = اختصار الشهر (يناير ، فبراير ... ديسمبر)<br/>MMMM = شهر طويل (يناير ، فبراير ... ديسمبر)<br/>د = اليوم (1 - 31)<br/>اليوم = اليوم (01 - 31)<br/>ddd = يوم من أيام الأسبوع بالكلمات (الاثنين والثلاثاء ... الأحد)<br/>E = يوم قصير من الأسبوع بالكلمات (الاثنين ، الثلاثاء ... شمس)<br/>د - اليوم الترتيبي (1 ، 2 ، 3 ، 21 ، 22 ، 23 ، 31 ، 4 ...)<br/>h = الساعة في صباحا / مساء (0-12)<br/>HH = ساعة في صباحا / مساء (00-12)<br/>H = ساعة في اليوم (0-23)<br/>HH = ساعة في اليوم (00-23)<br/>مم = دقيقة<br/>ss = الثانية<br/>SSS = ميلي ثانية<br/>أ = علامة صباحا / مساء<br/>p = صباحا / مساء علامة`,
	EditorTemplateDateTimeCustomLabel: `مخصص`,
	EditorTemplateDateTimeHint: `سيتم استبدال التاريخ و/أو الوقت الحالي لقوالب DateTime عند لصقها.`,
	EditorTemplateDateTimeName: `وقت التاريخ`,
	EditorTemplateDynamicHint: `<p>ستستخدم جميع أحداث هذا القالب النص المقدم.</p>`,
	EditorTemplateDynamicName: `متحرك`,
	EditorTemplateEmptyPlaceholder: `{0} فارغ ...`,
	EditorTemplateStaticHint: `<p>ستستخدم جميع أحداث هذا القالب النص المقدم.</p>`,
	EditorTemplateStaticName: `ثابتة`,
	EditorTemplateTeaserText: `المزيد قادم قريبا!`,
	EditorWatermark: `انتظر من فضلك...`,
	EditorWholeWordLabel: ` الكلمة بالكامل`,
	EditorWrapLabel: ` التفاف حول`,

};