var UiStrings = {
	EditorAppendCloseLabel: `Ολοκληρώστε την κατάρτιση`,
	EditorAppendInlineModeLabel: `Ενεργοποίηση μπλοκ`,
	EditorAppendLineModeLabel: `Ενεργοποίηση inline`,
	EditorAppendManualModeLabel: `Εγχειρίδιο εναλλαγής`,
	EditorAppendNonManualModeLabel: `Εγχειρίδιο εναλλαγής`,
	EditorAppendPauseLabel: `Παύση προσθέτει`,
	EditorAppendPostLabel: `Εναλλαγή πριν`,
	EditorAppendPreLabel: `Εναλλαγή πριν`,
	EditorAppendResumeLabel: `Επαναλαμβάνω προσθέστε`,
	EditorBgColorLabel: `Χρώμα του φόντου`,
	EditorClearAllLabel: `Τα καθαρίζω όλα`,
	EditorClipboardFormatsLabel: `Μορφές προφίλ`,
	EditorColorChooserTitle: `Επεξεργαστής`,
	EditorConfirmNtfTitle: `Επιβεβαιώνω`,
	EditorDeleteAllButtonText: `Διαγραφή όλων`,
	EditorDeleteAllTemplatesNtfText: `Είστε βέβαιοι ότι θέλετε να διαγράψετε όλες τις συνήθειες του '{0}';

Αυτό δεν μπορεί να αναιρεθεί!`,
	EditorEditTemplateDetailsLabel: `Επεξεργασία λεπτομερειών`,
	EditorEditTemplateNameLabel: `Ονομα`,
	EditorFindLabel: `Εύρημα`,
	EditorFontColorLabel: `Γραμματοσειρά`,
	EditorFormatPaintLabel: `Βαφή μορφής`,
	EditorInSelectionLabel: ` Σε επιλογή`,
	EditorInsertImageLabel: `Εισαγάγετε εικόνα`,
	EditorInsertLinkLabel: `Εισαγάγετε σύνδεσμο`,
	EditorInsertVideoLabel: `Εισαγάγετε βίντεο`,
	EditorLinkButtonText: `Αποθηκεύσετε`,
	EditorLinkLabel: `Εισαγάγετε Σύνδεσμο`,
	EditorLinkPlaceholder: `Εισαγάγετε το Url`,
	EditorMatchCaseLabel: ` Υπόθεση αγώνα`,
	EditorNewTemplateLabel: `Νέο πρότυπο`,
	EditorNextTemplateLabel: `Επόμενο πρότυπο`,
	EditorPasteButtonAppendBeginLabel: `Προσαρτώ...`,
	EditorPasteButtonLabel: `Επικόλληση`,
	EditorPasteTemplateWatermark: `Εισαγάγετε κείμενο επικόλλησης ...`,
	EditorPrevTemplateLabel: `Προηγούμενο πρότυπο`,
	EditorRegExLabel: ` Κοινή έκφραση`,
	EditorReplaceAllLabel: `Αντικαταστήστε όλα`,
	EditorReplaceLabel: `Αντικαθιστώ`,
	EditorTemplateContactHint: `<p>Χρησιμοποιώντας τις διαθέσιμες επαφές (απαιτεί ένα πρόσθετο fetcher), αυτό το πεδίο θα χρησιμοποιηθεί για όλες τις εμφανίσεις αυτού του προτύπου σε αυτό το έγγραφο ή σε οποιοδήποτε θα αναφερθεί αργότερα.</p><p> Έτσι, για παράδειγμα, εάν επιλέξετε διεύθυνση ηλεκτρονικού ταχυδρομείου εδώ, τότε το πεδίο ηλεκτρονικού ταχυδρομείου της επαφής που επιλέγετε θα χρησιμοποιηθεί για όλες τις παρουσίες σε αυτό το έγγραφο.</p>`,
	EditorTemplateContactName: `Επικοινωνία`,
	EditorTemplateDateTimeCustomHint: `yy = σύντομο έτος<br/>εεεε = μακρύ έτος<br/>M = μήνας (1-12)<br/>MM = μήνας (01-12)<br/>MMM = συντομογραφία μήνα (Ιαν, Φεβ ... Δεκ)<br/>MMMM = μακρύς μήνας (Ιανουάριος, Φεβρουάριος ... Δεκέμβριος)<br/>d = ημέρα (1 - 31)<br/>dd = ημέρα (01 - 31)<br/>ddd = ημέρα της εβδομάδας με λέξεις (Δευτέρα, Τρίτη ... Κυριακή)<br/>E = σύντομη ημέρα της εβδομάδας με λέξεις (Δευ, Τρ ... Κυρ)<br/>D - Κανονική ημέρα (1η, 2η, 3η, 21η, 22η, 23η, 31η, 4η...)<br/>h = ώρα π.μ./μ.μ. (0-12)<br/>hh = ώρα π.μ./μ.μ. (00-12)<br/>H = ώρα την ημέρα (0-23)<br/>HH = ώρα την ημέρα (00-23)<br/>mm = λεπτό<br/>ss = δευτερόλεπτο<br/>SSS = χιλιοστά του δευτερολέπτου<br/>a = δείκτης π.μ./μ.μ.<br/>p = δείκτης π.μ./μ.μ.`,
	EditorTemplateDateTimeCustomLabel: `Εθιμο`,
	EditorTemplateDateTimeHint: `Η τρέχουσα ημερομηνία ή/και ο χρόνος θα αντικατασταθούν για πρότυπα ημερομηνίας όταν είναι επικολλημένες.`,
	EditorTemplateDateTimeName: `Ημερομηνία ώρα`,
	EditorTemplateDynamicHint: `<p>Όλες οι εμφανίσεις αυτού του προτύπου θα χρησιμοποιούν το παρεχόμενο κείμενο.</p>`,
	EditorTemplateDynamicName: `Δυναμικός`,
	EditorTemplateEmptyPlaceholder: `{0} είναι άδειο ...`,
	EditorTemplateStaticHint: `<p>Όλες οι εμφανίσεις αυτού του προτύπου θα χρησιμοποιούν το παρεχόμενο κείμενο.</p>`,
	EditorTemplateStaticName: `Στατικός`,
	EditorTemplateTeaserText: `Περισσότερα σε λίγο!`,
	EditorTt1: `Κάντε κλικ`,
	EditorTt2: `επεξεργασία "<em>{0}</em>" ...`,
	EditorTt3: `επεξεργασία χρώματος...`,
	EditorTt4: `αφαιρέστε το "<em>{0}</em>" ...`,
	EditorTt5: `αφαιρέστε το στοιχείο`,
	EditorTt6: `ακολουθώ ...`,
	EditorTt7: `πάω "<em>{0}</em>" ...`,
	EditorWatermark: `Παρακαλώ περιμένετε...`,
	EditorWholeWordLabel: ` Ολος ο κοσμος`,
	EditorWrapLabel: ` Τυλίγομαι γύρω`,

};