var UiStrings = {
	EditorAppendCloseLabel: `Hoàn thành việc nối thêm`,
	EditorAppendInlineModeLabel: `Bật khối`,
	EditorAppendLineModeLabel: `Bật nội tuyến`,
	EditorAppendManualModeLabel: `Chuyển đổi hướng dẫn sử dụng`,
	EditorAppendNonManualModeLabel: `Chuyển đổi hướng dẫn sử dụng`,
	EditorAppendPauseLabel: `Tạm dừng nối thêm`,
	EditorAppendPostLabel: `Chuyển đổi trước`,
	EditorAppendPreLabel: `Chuyển đổi trước`,
	EditorAppendResumeLabel: `Tiếp tục nối tiếp`,
	EditorBgColorLabel: `Màu nền`,
	EditorClearAllLabel: `Làm sạch tất cả`,
	EditorClipboardFormatsLabel: `Định dạng bảng tạm`,
	EditorConfirmNtfTitle: `Xác nhận`,
	EditorDeleteAllButtonText: `Xóa hết`,
	EditorDeleteAllTemplatesNtfText: `Bạn có chắc là bạn muốn xóa tất cả các cách sử dụng của '{0}' không?

Điều này không thể được hoàn tác!`,
	EditorEditTemplateDetailsLabel: `Chỉnh sửa chi tiết`,
	EditorEditTemplateNameLabel: `Tên`,
	EditorFindLabel: `Tìm thấy`,
	EditorFontColorLabel: `Màu chữ`,
	EditorFormatPaintLabel: `Định dạng sơn`,
	EditorInSelectionLabel: ` Trong lựa chọn`,
	EditorInsertImageLabel: `Chèn hình ảnh`,
	EditorInsertLinkLabel: `Chèn đường dẫn`,
	EditorInsertVideoLabel: `Chèn video`,
	EditorMatchCaseLabel: ` Trường hợp khớp`,
	EditorNewTemplateLabel: `Bản mẫu mới`,
	EditorNextTemplateLabel: `Mẫu tiếp theo`,
	EditorPasteButtonAppendBeginLabel: `Nối thêm ...`,
	EditorPasteButtonLabel: `Dán`,
	EditorPasteTemplateWatermark: `Nhập văn bản Paste ...`,
	EditorPrevTemplateLabel: `Mẫu trước`,
	EditorRegExLabel: ` Biểu hiện thông thường`,
	EditorReplaceAllLabel: `Thay thế tất cả`,
	EditorReplaceLabel: `Thay thế`,
	EditorTemplateContactHint: `<p> Sử dụng các liên hệ có sẵn (yêu cầu plugin Fetcher) Trường này sẽ được sử dụng cho tất cả các trường hợp của mẫu này trên tài liệu này hoặc trong bất kỳ nó sẽ được tham chiếu sau. </P> <p> Vì vậy, ví dụ nếu chọn địa chỉ email Tại đây, trường email của liên hệ bạn chọn sẽ được sử dụng cho tất cả các trường hợp trong tài liệu này. </P>`,
	EditorTemplateContactName: `Liên hệ`,
	EditorTemplateDateTimeCustomHint: `yy = năm ngắn <br/> yyyy = năm dài <br/> m = tháng (1-12) <br/> mm = tháng (01-12) <br/> MMM = Tháng viết tắt (Jan, Feb .. . Dec) <br/> mmmm = tháng dài (tháng 1, tháng 2 ... tháng 12) <br/> d = ngày (1 - 31) <br/> dd = ngày (01 - 31) <br/> ddd = Ngày trong tuần bằng lời nói (Thứ Hai, Thứ Ba ... Chủ nhật) <br/> E = Ngày ngắn trong tuần bằng lời nói (Thứ Hai, Tue ... Mặt trời) <br/> D - Ngày thứ tự (1, thứ 2, thứ 2, 3, 21, 22, 23, 31, 4th ...) <br/> h = giờ vào sáng/chiều (0-12) > H = giờ trong ngày (0-23) <br/> hh = giờ trong ngày (00-23) <br/> mm = phút <br/> ss = thứ hai <br/> sss = miliseconds <br/> A = AM/pm điểm đánh dấu <br/> p = a.m./p.m. đánh dấu`,
	EditorTemplateDateTimeCustomLabel: `Phong tục`,
	EditorTemplateDateTimeHint: `Ngày và/hoặc thời gian hiện tại sẽ được thay thế cho các mẫu DateTime khi chúng được dán.`,
	EditorTemplateDateTimeName: `Ngày giờ`,
	EditorTemplateDynamicHint: `<p> Tất cả các sự cố của mẫu này sẽ sử dụng văn bản được cung cấp. </P>`,
	EditorTemplateDynamicName: `Năng động`,
	EditorTemplateEmptyPlaceholder: `{0} trống ...`,
	EditorTemplateStaticHint: `<p> Tất cả các sự cố của mẫu này sẽ sử dụng văn bản được cung cấp. </P>`,
	EditorTemplateStaticName: `Tĩnh`,
	EditorTemplateTeaserText: `Sắp có thêm!`,
	EditorWatermark: `Vui lòng chờ...`,
	EditorWholeWordLabel: ` Cả từ`,
	EditorWrapLabel: ` Quấn quanh`,

};