var UiStrings = {
	EditorAppendCloseLabel: `Çykyşy tamamlaň`,
	EditorAppendInlineModeLabel: `Blok açyň`,
	EditorAppendLineModeLabel: `Inline-a mümkinçilik beriň`,
	EditorAppendManualModeLabel: `Gollanma`,
	EditorAppendNonManualModeLabel: `Gollanma`,
	EditorAppendPauseLabel: `Truzany arakesme`,
	EditorAppendPostLabel: `Öňem üýtgetmek`,
	EditorAppendPreLabel: `Öňem üýtgetmek`,
	EditorAppendResumeLabel: `Hasaplamak`,
	EditorBgColorLabel: `Arka reňki`,
	EditorClearAllLabel: `Hemmesini arassala`,
	EditorClipboardFormatsLabel: `Paneli formatlar`,
	EditorConfirmNtfTitle: `Tassykla`,
	EditorDeleteAllButtonText: `Hemmesini poz`,
	EditorDeleteAllTemplatesNtfText: `'{0}' ulanylmagynyň ähli ulanylyşyny pozmak isleýärsiňizmi?

Bu yzyna gaýtaryp bolmaz!`,
	EditorEditTemplateDetailsLabel: `Maglumatlary redaktirläň`,
	EditorEditTemplateNameLabel: `Ady`,
	EditorFindLabel: `Tap`,
	EditorFontColorLabel: `Şrift reňk`,
	EditorFormatPaintLabel: `Formatlamak boýagy`,
	EditorInSelectionLabel: ` Saýlamak`,
	EditorInsertImageLabel: `Suraty goýmak`,
	EditorInsertLinkLabel: `Baglanyşyk goýuň`,
	EditorInsertVideoLabel: `Wideo salyň`,
	EditorMatchCaseLabel: ` Gabat geliş meselesi`,
	EditorNewTemplateLabel: `Täze şablon`,
	EditorNextTemplateLabel: `Indiki şablon`,
	EditorPasteButtonAppendBeginLabel: `Goşuldy ...`,
	EditorPasteButtonLabel: `Çökdürmek`,
	EditorPasteTemplateWatermark: `Pasta tekstini giriziň ...`,
	EditorPrevTemplateLabel: `Öňki şablon`,
	EditorRegExLabel: ` Yzygiderli aňlatma`,
	EditorReplaceAllLabel: `Hemmesini çalyş`,
	EditorReplaceLabel: `Çalyş`,
	EditorTemplateContactHint: `<p>Elýeterli kontaktlary ulanmak (fetcher plýonkasyny talap edýär) bu ugur bu resminamanyň ähli ýagdaýlary üçin ýa-da onuň soňsalgylanjak islendik ýerinde ulanylar.</p><p> Mysal üçin, eger bu ýerde e-poçta adresini saýlasaňyz, onda saýlan kontaktyňyzyň e-mail meýdançasy şu dokumentdäki ähli ýagdaýlar üçin ulanylar.</p>`,
	EditorTemplateContactName: `Aragatnaşyk`,
	EditorTemplateDateTimeCustomHint: `yý = gysga ýyl<br/>yyyy = uzyn ýyl<br/>M = aý (1-12)<br/>MM = aý (01-12)<br/>MMM = aý gysgaldylyşy (Jan, Fewral ... Dek.<br/>MMMM = uzyn aý (ýanwar, fewral ... Bitaraplyk)<br/>d = gün (1 - 31)<br/>dd = gün (01 - 31)<br/>ddd = hepdäniň güni sözler bilen (Duşenbe, Sişenbe ... Ýekşenbe)<br/>E = söz bilen hepdäniň gysga güni (Mon, Tue ... Gün)<br/>D - Ordinal gün (1-nji, 2-nji, 3-nji, 21-nji, 22-nji, 23-nji, 31-nji, 4-nji...)<br/>h = hour in am/pm (0-12)<br/>hh = hour in am/pm (00-12)<br/>H = gündizine sagat (0-23)<br/>HH = günde sagat (00-23)<br/>mm = minut<br/>ss = ikinji<br/>SSS = milisekund<br/>a = AM/PM markeri<br/>p = a.a./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Ýörite`,
	EditorTemplateDateTimeHint: `Häzirki senä we / ýa-da wagt düwmeleriň ýelmese seadadylaşdyrylan sauşnik şablonlar üçin çalşylar.`,
	EditorTemplateDateTimeName: `Sene wagt`,
	EditorTemplateDynamicHint: `<p>Bu şablonyň ähli ýüze çykmagy üpjün edilen teksti ulanar.</p>`,
	EditorTemplateDynamicName: `Dinamiki`,
	EditorTemplateEmptyPlaceholder: `{0} boş ...`,
	EditorTemplateStaticHint: `<p>Bu şablonyň ähli ýüze çykmagy üpjün edilen teksti ulanar.</p>`,
	EditorTemplateStaticName: `Statiki`,
	EditorTemplateTeaserText: `Soonakynda has ýakyn!`,
	EditorWatermark: `Haýyş et!`,
	EditorWholeWordLabel: ` Tutuş söz`,
	EditorWrapLabel: ` Aýlanýar`,

};