var UiStrings = {
	EditorAppendCloseLabel: `थपिरहेको छ`,
	EditorAppendInlineModeLabel: `ब्लक सक्षम गर्नुहोस्`,
	EditorAppendLineModeLabel: `इनलाइन सक्षम गर्नुहोस्`,
	EditorAppendManualModeLabel: `टगल म्यानुअल`,
	EditorAppendNonManualModeLabel: `टगल म्यानुअल`,
	EditorAppendPauseLabel: `रोक्नुहोस्`,
	EditorAppendPostLabel: `अगाडि टगल गर्नुहोस्`,
	EditorAppendPreLabel: `अगाडि टगल गर्नुहोस्`,
	EditorAppendResumeLabel: `पुन: संयोजन गर्नुहोस्`,
	EditorBgColorLabel: `पृष्ठभूमि र color`,
	EditorClearAllLabel: `सबै खाली गर्नुहोस्`,
	EditorClipboardFormatsLabel: `क्लिपबोर्ड ढाँचाहरू`,
	EditorConfirmNtfTitle: `पक्का गर्नु`,
	EditorDeleteAllButtonText: `सबैलाई मेट्नुहोस्`,
	EditorDeleteAllTemplatesNtfText: `के तपाईं '{0}' को सबै सामानहरू मेटाउन निश्चित हुनुहुन्छ?

यो उल्ट्याउन सकिदैन!`,
	EditorEditTemplateDetailsLabel: `विवरण सम्पादन गर्नुहोस्`,
	EditorEditTemplateNameLabel: `नाम`,
	EditorFindLabel: `पाउनु`,
	EditorFontColorLabel: `फन्ट रंग`,
	EditorFormatPaintLabel: `ढाँचा पेन्ट`,
	EditorInSelectionLabel: ` छनौटमा`,
	EditorInsertImageLabel: `छवि घुसाउनुहोस्`,
	EditorInsertLinkLabel: `लिंक घुसाउनुहोस्`,
	EditorInsertVideoLabel: `भिडियो घुसाउनु`,
	EditorMatchCaseLabel: ` म्याच केस`,
	EditorNewTemplateLabel: `नयाँ टेम्प्लेट`,
	EditorNextTemplateLabel: `अर्को टेम्पलेट`,
	EditorPasteButtonAppendBeginLabel: `जोडिएको ...`,
	EditorPasteButtonLabel: `टाँसिनु`,
	EditorPasteTemplateWatermark: `टाँस्नुहोस् पाठ प्रविष्ट गर्नुहोस् ...`,
	EditorPrevTemplateLabel: `अघिल्लो टेम्पलेट`,
	EditorRegExLabel: ` नियमित अभिव्यक्ति`,
	EditorReplaceAllLabel: `सबैलाई बदल्नुहोस्`,
	EditorReplaceLabel: `ठाउमा राख्नु`,
	EditorTemplateContactHint: `<p> उपलब्ध सम्पर्कहरूको प्रयोग गरेर (एक फ्रिआर प्लगइन आवश्यक पर्दछ) यो फिल्ड यस फिल्ड यस फाँट यस कागजात भर वा कुनै पनि उदाहरणका लागि निर्दिष्ट गरिएको छ यदि ईमेल ठेगाना चयन गरियो भने। यहाँ तपाईले चयन गर्नुभएको सम्पर्कको ईमेल क्षेत्र यस कागजातमा सबै उदाहरणका लागि प्रयोग हुनेछ। </ p>`,
	EditorTemplateContactName: `सम्पर्क`,
	EditorTemplateDateTimeCustomHint: `yy = छोटो वर्ष <br/> yyyy = लामो वर्ष <br/> M = MM = MM = MM = MM = MMM = MMM = MMMESE (जनवरी, फेब। । डिसेम्बर) <br/> MMMM = लामो महिना (जनवरी, फेब्रुअरी ... डिसेम्बर) <br/> dd (01 - dd) <b1 - dd.1) हप्ताको दिन शब्दहरूमा दिन (सोमबार, मंगलबार ... आइतवार) <br/> X = SUMESTION B = TATHESTEST B = SUME BUTER BUTER BUTER) <br/> TU - पहिलो, दोस्रो, तेस्रो, 21, 22 औं, -1 औं, <br/12 घण्टा (0-12 घण्टा (0-12) बिहान / बत्ती (000-12) <br-12 > H = घण्टा (0-23) दिनमा (00/23 = घण्टा (00/2) मा (00/2) <br/> ss = MS = MSE = MSIECWODS <br/> ss = ms = ms = mm = mm = ms = mm = mm = mm = ms = me = /> A = AM / PM मार्कर <br/> p = a.m. / pm.m। मारफरीको पाल`,
	EditorTemplateDateTimeCustomLabel: `चलन`,
	EditorTemplateDateTimeHint: `हालको मिति र / वा समय मिति टेक्नेटि with को लागि प्रतिस्थापित गरिनेछ जब तिनीहरू टाँसिन्छन्।`,
	EditorTemplateDateTimeName: `मिति समय`,
	EditorTemplateDynamicHint: `<p> यस टेम्पलेटको सबै घटनाहरूले प्रदान गरिएको पाठ प्रयोग गर्दछ। </ p>`,
	EditorTemplateDynamicName: `गतिशील`,
	EditorTemplateEmptyPlaceholder: `{0} खाली छ ...`,
	EditorTemplateStaticHint: `<p> यस टेम्पलेटको सबै घटनाहरूले प्रदान गरिएको पाठ प्रयोग गर्दछ। </ p>`,
	EditorTemplateStaticName: `निर्मूल`,
	EditorTemplateTeaserText: `अधिक आउँदै!`,
	EditorWatermark: `कृपया पर्खनुहोस्...`,
	EditorWholeWordLabel: ` पुरै शब्द`,
	EditorWrapLabel: ` वरिपरि लपेट`,

};