var UiStrings = {
	EditorAppendCloseLabel: `Zaključek doda`,
	EditorAppendInlineModeLabel: `Omogoči blok`,
	EditorAppendLineModeLabel: `Omogoči inline`,
	EditorAppendManualModeLabel: `Preklopni priročnik`,
	EditorAppendNonManualModeLabel: `Preklopni priročnik`,
	EditorAppendPauseLabel: `Premor dodatka`,
	EditorAppendPostLabel: `Preklopite prej`,
	EditorAppendPreLabel: `Preklopite prej`,
	EditorAppendResumeLabel: `Življenjepis`,
	EditorBgColorLabel: `Barva ozadja`,
	EditorClearAllLabel: `Počisti vse`,
	EditorClipboardFormatsLabel: `Obloge`,
	EditorConfirmNtfTitle: `Potrdite`,
	EditorDeleteAllButtonText: `Izbriši vse`,
	EditorDeleteAllTemplatesNtfText: `Ali ste prepričani, da želite izbrisati vse navade '{0}'?

Tega ni mogoče razveljaviti!`,
	EditorEditTemplateDetailsLabel: `Uredi podrobnosti`,
	EditorEditTemplateNameLabel: `Ime`,
	EditorFindLabel: `Najti`,
	EditorFontColorLabel: `Barva pisave`,
	EditorFormatPaintLabel: `Oblika barve`,
	EditorInSelectionLabel: ` V izbiri`,
	EditorInsertImageLabel: `Vstavite sliko`,
	EditorInsertLinkLabel: `Vstavi povezavo`,
	EditorInsertVideoLabel: `Vstavite video`,
	EditorMatchCaseLabel: ` Primer`,
	EditorNewTemplateLabel: `Nova predloga`,
	EditorNextTemplateLabel: `Naslednja predloga`,
	EditorPasteButtonAppendBeginLabel: `Dodatek ...`,
	EditorPasteButtonLabel: `Prilepi`,
	EditorPasteTemplateWatermark: `Vnesite besedilo paste ...`,
	EditorPrevTemplateLabel: `Prejšnja predloga`,
	EditorRegExLabel: ` Vsakdanje izražanje`,
	EditorReplaceAllLabel: `Zamenjajte vse`,
	EditorReplaceLabel: `Zamenjati`,
	EditorTemplateContactHint: `<p> Uporaba razpoložljivih stikov (zahteva vtičnik Fetcher) To polje bo uporabljeno za vse primere te predloge v tem dokumentu ali v katerem koli njem Tukaj bo e -poštno polje iz izbranega stika uporabljeno za vse primere v tem dokumentu. </p>`,
	EditorTemplateContactName: `Stik`,
	EditorTemplateDateTimeCustomHint: `yy = kratko leto <br/> yyyy = dolgo leto <br/> m = mesec (1-12) <br/> mm = mesec (01-12) <br/> mmm = mesečna okrajšava (januar, feb .. . Dec) <br/> mmmm = dolg mesec (januar, februar ... december) <br/> d = dan (1 - 31) <br/> dd = dan (01 - 31) <br/> ddd = Dan v tednu z besedami (ponedeljek, torek ... nedelja) <br/> e = kratek dan v tednu z besedami (pon, tue ... sonce) <br/> d - redni dan (1., 2., 3., 21., 22., 23., 31., 4. ...) <br/> h = ura v am/pm (0-12) <br/> hh = ura v AM/PM (00-12) <Br/ > H = ura v dnevu (0-23) <br/> hh = ura v dan (00-23) <br/> mm = minuta <br/> ss = drugi <br/> sss = milisekund <br/> A = AM/PM Marker <br/> P = A.M./P.M. marker`,
	EditorTemplateDateTimeCustomLabel: `Navada`,
	EditorTemplateDateTimeHint: `Trenutni datum in/ali čas bosta nadomeščena za predloge DateTime, ko jih prilepijo.`,
	EditorTemplateDateTimeName: `Datum čas`,
	EditorTemplateDynamicHint: `<p> Vse pojave te predloge bodo uporabile priloženo besedilo. </p>`,
	EditorTemplateDynamicName: `Dinamično`,
	EditorTemplateEmptyPlaceholder: `{0} je prazen ...`,
	EditorTemplateStaticHint: `<p> Vse pojave te predloge bodo uporabile priloženo besedilo. </p>`,
	EditorTemplateStaticName: `Statična`,
	EditorTemplateTeaserText: `Kmalu pride še več!`,
	EditorWatermark: `Prosim počakaj...`,
	EditorWholeWordLabel: ` Celotna beseda`,
	EditorWrapLabel: ` Ovijte okoli`,

};