var UiStrings = {
	EditorTemplateContactHint: `<p>Using available contacts (requires a fetcher plugin) this field will be used for all instances of this template across this document or in any it will be referenced in later.</p><p> So for example if select email address here then the email field of the contact you select will be used for all instances in this document.</p>`,
	EditorTemplateDateTimeCustomHint: `<p>yy = short year</p><p>yyyy = long year</p><p>M = month (1-12)</p><p>MM = month (01-12)</p><p>MMM = month abbreviation (Jan, Feb ... Dec)</p><p>MMMM = long month (January, February ... December)</p><p>d = day (1 - 31)</p><p>dd = day (01 - 31)</p><p>ddd = day of the week in words (Monday, Tuesday ... Sunday)</p><p>E = short day of the week in words (Mon, Tue ... Sun)</p><p>D - Ordinal day (1st, 2nd, 3rd, 21st, 22nd, 23rd, 31st, 4th...)</p><p>h = hour in am/pm (0-12)</p><p>hh = hour in am/pm (00-12)</p><p>H = hour in day (0-23)</p><p>HH = hour in day (00-23)</p><p>mm = minute</p><p>ss = second</p><p>SSS = milliseconds</p><p>a = AM/PM marker</p><p>p = a.m./p.m. marker</p>`,
	EditorTemplateDateTimeHint: `<p>The current date and/or time will be substituted for DateTime templates from moment they evaluated ie. pasted.</p><p>The specified format is shared so changes here will update system - wide.</p>`,
	EditorTemplateDynamicHint: `<p>All occurances of this template will be set to the value you provide here</p>`,
	EditorTemplateStaticHint: `<p>The current date and/or time will be substituted for DateTime templates from moment they evaluated ie. pasted.</p><p>The specified format is shared so changes here will update system-wide.</p>`,
	EditorAppendCloseLabel: `Finish appending`,
	EditorAppendInlineModelLabel: `Enable Paragraph`,
	EditorAppendLineModeLabel: `Enable Inline`,
	EditorAppendManualModeLabel: `Toggle manual`,
	EditorAppendNonManualModeLabel: `Toggle manual`,
	EditorAppendPauseLabel: `Pause appending to clipboard`,
	EditorAppendPostLabel: `Toggle Before`,
	EditorAppendPreLabel: `Toggle Before`,
	EditorAppendResumeLabel: `Resume appending to clipboard`,
	EditorPasteButtonAppendBeginLabel: `Append...`,
	EditorPasteButtonLabel: `Paste`,
	EditorBgColorLabel: `Background Color`,
	EditorClearAllLabel: `Clear All`,
	EditorClipboardFormatsLabel: `Clipboard Formats`,
	EditorDeleteAllButtonText: `Delete All`,
	EditorEditTemplateDetailsLabel: `Edit Details`,
	EditorEditTemplateNameLabel: `Name`,
	EditorFindLabel: `Find`,
	EditorFontColorLabel: `Font Color`,
	EditorFormatPaintLabel: `Format Paint`,
	EditorInSelectionLabel: ` In Selection`,
	EditorInsertImageLabel: `Insert Image`,
	EditorInsertLinkLabel: `Insert Link`,
	EditorInsertVideoLabel: `Insert Video`,
	EditorMatchCaseLabel: ` Match Case`,
	EditorNewTemplateLabel: `New Template`,
	EditorNextTemplateLabel: `Next Template`,
	EditorPasteTemplateWatermark: `Enter paste text...`,
	EditorPrevTemplateLabel: `Previous Template`,
	EditorRegExLabel: ` Regular Expression`,
	EditorReplaceAllLabel: `Replace All`,
	EditorReplaceLabel: `Replace`,
	EditorWholeWordLabel: ` Whole Word`,
	EditorWrapLabel: ` Wrap Around`,
	EditorConfirmNtfTitle: `Confirm`,
	EditorTemplateContactName: `Contact`,
	EditorTemplateDateTimeName: `Date Time`,
	EditorDeleteAllTemplatesNtfText: `Are you sure you want to delete ALL usages of '{0}'? This cannot be undone.`,
	EditorTemplateDynamicName: `Dynamic`,
	EditorTemplateStaticName: `Static`,
	EditorTemplateEmptyPlaceholder: `{0} is empty...`,
	EditorTemplateTeaserText: `More coming soon!`,

};