var UiStrings = {
	EditorAppendCloseLabel: `ማቃጠል ጨርስ`,
	EditorAppendInlineModeLabel: `ብሎክ አንቃ`,
	EditorAppendLineModeLabel: `ውስጤን አንቃ`,
	EditorAppendManualModeLabel: `መመሪያን ይቀያይሩ`,
	EditorAppendNonManualModeLabel: `መመሪያን ይቀያይሩ`,
	EditorAppendPauseLabel: `ለአፍታ አቁም`,
	EditorAppendPostLabel: `ከዚህ በፊት ይቀያይሩ`,
	EditorAppendPreLabel: `ከዚህ በፊት ይቀያይሩ`,
	EditorAppendResumeLabel: `ከቆመበት ቀጥል`,
	EditorBgColorLabel: `የጀርባ ቀለም`,
	EditorClearAllLabel: `ሁሉንም ያፅዱ`,
	EditorClipboardFormatsLabel: `የቅንጥብ ሰሌዳ ቅርፀቶች`,
	EditorConfirmNtfTitle: `አረጋግጥ`,
	EditorDeleteAllButtonText: `ሁሉንም ሰርዝ`,
	EditorDeleteAllTemplatesNtfText: `እርግጠኛ ነዎት የ "{0} 'ን መድረስ እንደሚፈልጉ እርግጠኛ ነዎት?

ይህ ሊቀለበስ አይችልም!`,
	EditorEditTemplateDetailsLabel: `ዝርዝሮችን ያርትዑ`,
	EditorEditTemplateNameLabel: `ስም`,
	EditorFindLabel: `ይፈልጉ`,
	EditorFontColorLabel: `የቅርጸ-ቁምፊ ቀለም`,
	EditorFormatPaintLabel: `ቅርጸት ቀለም`,
	EditorInSelectionLabel: ` በምርጫ ውስጥ`,
	EditorInsertImageLabel: `ምስልን ያስገቡ`,
	EditorInsertLinkLabel: `አገናኝ ያስገቡ`,
	EditorInsertVideoLabel: `ቪዲዮ ያስገቡ`,
	EditorMatchCaseLabel: ` የግጥሚያ ጉዳይ`,
	EditorNewTemplateLabel: `አዲስ አብነት`,
	EditorNextTemplateLabel: `የሚቀጥለው ንድፍ`,
	EditorPasteButtonAppendBeginLabel: `ተማርኩ ...`,
	EditorPasteButtonLabel: `ፓስተር`,
	EditorPasteTemplateWatermark: `የመለጠጥ ጽሑፍ ያስገቡ ...`,
	EditorPrevTemplateLabel: `ያለፈው አብነት`,
	EditorRegExLabel: ` መደበኛ አገላለጽ`,
	EditorReplaceAllLabel: `ሁሉንም ይተኩ`,
	EditorReplaceLabel: `ይተኩ`,
	EditorTemplateContactHint: `<p>የሚገኙ አገናኞችን በመጠቀም (fetcher plugin) ይህ መስክ በዚህ ሰነድ ላይ ለሁሉም አጋጣሚዎች ጥቅም ላይ ይውላል ወይም በማንኛውም ጊዜ በኋላ ላይ ይጠቀሳሉ.</p><p> ስለዚህ ለምሳሌ እዚህ የኢሜይል አድራሻን ከመረጡ የመረጣችሁት የኢሜይል አድራሻ በዚህ ሰነድ ውስጥ ለሁሉም አጋጣሚዎች ጥቅም ላይ ይውላል።</p>`,
	EditorTemplateContactName: `እውቂያ`,
	EditorTemplateDateTimeCustomHint: `yy = አጭር ዓመት<br/>yyyy = ረጅም አመት<br/>መ = ወርሒ (1-12)<br/>ሚሜ = ወር (01-12)<br/>MM = የወር አህጽሮ (Jan, Feb ... Dec)<br/>MMMM = ረጅም ወር (ጥር, የካቲት ... ታህሳስ)<br/>d = ቀን (1 - 31)<br/>dd = ቀን (01 - 31)<br/>ddd = የሳምንቱ ቀን በቃላት (ሰኞ፣ ማክሰኞ ... እሁድ)<br/>E = የሳምንቱ አጭር ቀን በቃላት (Mon, Tue ... ፀሐይ)<br/>D - Ordinal ቀን (1ኛ, 2ኛ, 3ኛ, 21ኛ, 22ኛ, 23ኛ, 31ኛ, 4ኛ...)<br/>h = ሰዓት in am/pm (0-12)<br/>hh = ሰዓት in am/pm (00-12)<br/>H = ሰዓት ኣብ መዓልቲ (0-23)<br/>HH = ሰዓት በቀን (00-23)<br/>mm = ደቂቃ<br/>ss = ሁለተኛ<br/>SSS = ሚሊሰከንዶች<br/>a = AM/PM ምልክት<br/>p = a.m./p.m. ምልክት`,
	EditorTemplateDateTimeCustomLabel: `ብጁ`,
	EditorTemplateDateTimeHint: `የወቅቱ ቀን እና / ወይም ጊዜ ሲለቁ ለቀጣዩ ጊዜው አብነት ይተካሉ.`,
	EditorTemplateDateTimeName: `የቀን ሰዓት`,
	EditorTemplateDynamicHint: `<p>ይህ ንጥሎች በሙሉ በጽሑፉ ይጠቀማሉ።</p>`,
	EditorTemplateDynamicName: `ተለዋዋጭ`,
	EditorTemplateEmptyPlaceholder: `{0} ባዶ ነው ...`,
	EditorTemplateStaticHint: `<p>ይህ ንጥሎች በሙሉ በጽሑፉ ይጠቀማሉ።</p>`,
	EditorTemplateStaticName: `የማይንቀሳቀስ`,
	EditorTemplateTeaserText: `በቅርቡ ይመጣል!`,
	EditorWatermark: `ቆይ በናተህ...`,
	EditorWholeWordLabel: ` ሙሉ ቃል`,
	EditorWrapLabel: ` መጠቅለል`,

};