var UiStrings = {
	EditorAppendCloseLabel: `Finition d'appel`,
	EditorAppendInlineModeLabel: `Activer le bloc`,
	EditorAppendLineModeLabel: `Activer en ligne`,
	EditorAppendManualModeLabel: `Manuel de basculement`,
	EditorAppendNonManualModeLabel: `Manuel de basculement`,
	EditorAppendPauseLabel: `Pause Ajouter`,
	EditorAppendPostLabel: `Basculer avant`,
	EditorAppendPreLabel: `Basculer avant`,
	EditorAppendResumeLabel: `Reprendre`,
	EditorBgColorLabel: `Couleur de l'arrière plan`,
	EditorClearAllLabel: `Tout effacer`,
	EditorClipboardFormatsLabel: `Formats de presse-papiers`,
	EditorColorChooserTitle: `Couleur de l'éditeur`,
	EditorConfirmNtfTitle: `Confirmer`,
	EditorDeleteAllButtonText: `Supprimer tout`,
	EditorDeleteAllTemplatesNtfText: `Êtes-vous sûr de vouloir supprimer tous les usages de '{0}'?

Ça ne peut pas être annulé!`,
	EditorEditTemplateDetailsLabel: `Modifier les détails`,
	EditorEditTemplateNameLabel: `Nom`,
	EditorFindLabel: `Trouver`,
	EditorFontColorLabel: `Couleur de la police`,
	EditorFormatPaintLabel: `Peinture au format`,
	EditorInSelectionLabel: ` En sélection`,
	EditorInsertImageLabel: `Insérer une image`,
	EditorInsertLinkLabel: `Insérer un lien`,
	EditorInsertVideoLabel: `Insérer une vidéo`,
	EditorLinkButtonText: `Sauvegarder`,
	EditorLinkLabel: `Entrez le lien`,
	EditorLinkPlaceholder: `Entrer l'URL`,
	EditorMatchCaseLabel: ` Cas de correspondance`,
	EditorNewTemplateLabel: `Nouveau modèle`,
	EditorNextTemplateLabel: `Modèle suivant`,
	EditorPasteButtonAppendBeginLabel: `Ajouter...`,
	EditorPasteButtonLabel: `Pâte`,
	EditorPasteTemplateWatermark: `Entrez le texte de la pâte ...`,
	EditorPrevTemplateLabel: `Modèle précédent`,
	EditorRegExLabel: ` Expression régulière`,
	EditorReplaceAllLabel: `Remplace tout`,
	EditorReplaceLabel: `Remplacer`,
	EditorTemplateContactHint: `<p>En utilisant les contacts disponibles (nécessite un plugin fetcher), ce champ sera utilisé pour toutes les instances de ce modèle dans ce document ou dans tout autre document dans lequel il sera référencé ultérieurement.</p><p> Ainsi, par exemple, si vous sélectionnez l’adresse e-mail ici, le champ e-mail du contact que vous sélectionnez sera utilisé pour toutes les instances de ce document.</p>`,
	EditorTemplateContactName: `Contact`,
	EditorTemplateDateTimeCustomHint: `yy = année courte<br/>yyyy = année longue<br/>M = mois (1-12)<br/>MM = mois (01-12)<br/>MMM = abréviation du mois (janv., févr. ... Déc)<br/>MMMM = mois long (janvier, février ... Décembre)<br/>d = jour (1 - 31)<br/>jj = jour (01 - 31)<br/>ddd = jour de la semaine en mots (lundi, mardi ... Dimanche)<br/>E = jour court de la semaine en mots (Lun, Mar ... Soleil)<br/>D - Jour ordinal (1er, 2ème, 3ème, 21ème, 22ème, 23ème, 31ème, 4ème...)<br/>h = heure en am/pm (0-12)<br/>hh = heure en am/pm (00-12)<br/>H = heure dans la journée (0-23)<br/>HH = heure dans la journée (00-23)<br/>mm = minute<br/>ss = seconde<br/>SSS = millisecondes<br/>a = marqueur AM/PM<br/>p = marqueur a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Coutume`,
	EditorTemplateDateTimeHint: `La date et / ou l'heure actuelles seront remplacées par des modèles DateTime lorsqu'ils sont collés.`,
	EditorTemplateDateTimeName: `Date`,
	EditorTemplateDynamicHint: `<p>Toutes les occurrences de ce modèle utiliseront le texte fourni.</p>`,
	EditorTemplateDynamicName: `Dynamique`,
	EditorTemplateEmptyPlaceholder: `{0} est vide ...`,
	EditorTemplateStaticHint: `<p>Toutes les occurrences de ce modèle utiliseront le texte fourni.</p>`,
	EditorTemplateStaticName: `Statique`,
	EditorTemplateTeaserText: `Plus à venir bientôt!`,
	EditorTt1: `Cliquez sur`,
	EditorTt2: `Edit '<em> {0} </em>' ...`,
	EditorTt3: `Modifier la couleur ...`,
	EditorTt4: `supprimer '<em> {0} </em>' ...`,
	EditorTt5: `retirer l'objet`,
	EditorTt6: `suivre ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `S'il vous plaît, attendez...`,
	EditorWholeWordLabel: ` Mot entier`,
	EditorWrapLabel: ` Enrouler autour`,

};