var UiStrings = {
	EditorAppendCloseLabel: `Lõpeta lisamine`,
	EditorAppendInlineModeLabel: `Luba blokeerimine`,
	EditorAppendLineModeLabel: `Lubage sisemine`,
	EditorAppendManualModeLabel: `Lülitusjuhend`,
	EditorAppendNonManualModeLabel: `Lülitusjuhend`,
	EditorAppendPauseLabel: `Pausi lisama`,
	EditorAppendPostLabel: `Enne`,
	EditorAppendPreLabel: `Enne`,
	EditorAppendResumeLabel: `Jätkata lisa`,
	EditorBgColorLabel: `Taustavärv`,
	EditorClearAllLabel: `Kustuta kõik`,
	EditorClipboardFormatsLabel: `Lõikelauavormingud`,
	EditorColorChooserTitle: `Redigeerija värv`,
	EditorConfirmNtfTitle: `Kinnitama`,
	EditorDeleteAllButtonText: `Kustutada kõik`,
	EditorDeleteAllTemplatesNtfText: `Kas olete kindel, et soovite kustutada kõik '{0}' kasutusalad?

Seda ei saa olematuks teha!`,
	EditorEditTemplateDetailsLabel: `Redigeerimise üksikasjad`,
	EditorEditTemplateNameLabel: `Nimetus`,
	EditorFindLabel: `Leidma`,
	EditorFontColorLabel: `Fondi värv`,
	EditorFormatPaintLabel: `Vormingus värv`,
	EditorInSelectionLabel: ` Valimisel`,
	EditorInsertImageLabel: `Sisestage pilt`,
	EditorInsertLinkLabel: `Sisestage link`,
	EditorInsertVideoLabel: `Sisestage video`,
	EditorLinkButtonText: `Kokkuhoid`,
	EditorLinkLabel: `Sisestage link`,
	EditorLinkPlaceholder: `Sisestage URL`,
	EditorMatchCaseLabel: ` Tikutoos`,
	EditorNewTemplateLabel: `Uus mall`,
	EditorNextTemplateLabel: `Järgmine mall`,
	EditorPasteButtonAppendBeginLabel: `Lisa ...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteTemplateWatermark: `Sisestage pasta tekst ...`,
	EditorPrevTemplateLabel: `Eelmine mall`,
	EditorRegExLabel: ` Regulaarne väljendus`,
	EditorReplaceAllLabel: `Asendage kõik`,
	EditorReplaceLabel: `Asendama`,
	EditorTemplateContactHint: `<p>Kasutades saadaolevaid kontakte (nõuab fetcheri pistikprogrammi), kasutatakse seda välja selle malli kõigi eksemplaride jaoks selles dokumendis või mis tahes, millele hiljem viidatakse.</p><p> Näiteks kui valite siin e-posti aadressi, kasutatakse teie valitud kontakti e-posti välja kõigi selle dokumendi eksemplaride jaoks.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = lühike aasta<br/>yyyy = pikk aasta<br/>M = kuu (1–12)<br/>MM = kuu (01-12)<br/>MMM = kuu lühend (jaan, veebr ... detsember)<br/>MMMM = pikk kuu (jaanuar, veebruar ... detsember)<br/>d = päev (1 - 31)<br/>DD = päev (01 - 31)<br/>ddd = nädalapäev sõnadega (esmaspäev, teisipäev ... Pühapäev)<br/>E = lühike nädalapäev sõnadega (E, T ... Päike)<br/>D - ordinaalpäev (1., 2., 3., 21., 22., 23., 31., 4....)<br/>h = tund (am/pm) (0–12)<br/>hh = tund tunnis am/pm (00-12)<br/>H = tund päevas (0–23)<br/>HH = tund päevas (00–23)<br/>mm = minut<br/>ss = teine<br/>SSS = millisekundid<br/>a = AM/PM marker<br/>p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `Kohandatud`,
	EditorTemplateDateTimeHint: `Praegune kuupäev ja/või kellaaeg asendatakse nende kleepimisel DateTime'i mallidega.`,
	EditorTemplateDateTimeName: `Kuupäev Kellaaeg`,
	EditorTemplateDynamicHint: `<p>Kõik selle malli esinemised kasutavad esitatud teksti.</p>`,
	EditorTemplateDynamicName: `Dünaamiline`,
	EditorTemplateEmptyPlaceholder: `{0} on tühi ...`,
	EditorTemplateStaticHint: `<p>Kõik selle malli esinemised kasutavad esitatud teksti.</p>`,
	EditorTemplateStaticName: `Staatiline`,
	EditorTemplateTeaserText: `Veel varsti!`,
	EditorTt1: `Klõpsama`,
	EditorTt2: `redigeeri '<em> {0} </em>' ...`,
	EditorTt3: `Redigeeri värvi ...`,
	EditorTt4: `Eemalda '<em> {0} </em>' ...`,
	EditorTt5: `Eemaldage üksus`,
	EditorTt6: `järgima ...`,
	EditorTt7: `Goto '<em> {0} </em>' ...`,
	EditorWatermark: `Palun oota...`,
	EditorWholeWordLabel: ` Terve sõna`,
	EditorWrapLabel: ` Ümber mähkima`,

};