var UiStrings = {
	EditorAppendCloseLabel: `بڑھانا ختم کریں`,
	EditorAppendInlineModeLabel: `بلاک کو فعال کریں`,
	EditorAppendLineModeLabel: `ان لائن کو فعال کریں`,
	EditorAppendManualModeLabel: `ٹوگل دستی`,
	EditorAppendNonManualModeLabel: `ٹوگل دستی`,
	EditorAppendPauseLabel: `روکیں`,
	EditorAppendPostLabel: `اس سے پہلے ٹوگل`,
	EditorAppendPreLabel: `اس سے پہلے ٹوگل`,
	EditorAppendResumeLabel: `دوبارہ شروع کریں`,
	EditorBgColorLabel: `پس منظر کا رنگ`,
	EditorClearAllLabel: `تمام کو صاف کریں`,
	EditorClipboardFormatsLabel: `کلپ بورڈ فارمیٹس`,
	EditorConfirmNtfTitle: `تصدیق کریں`,
	EditorDeleteAllButtonText: `تمام حذف کریں`,
	EditorDeleteAllTemplatesNtfText: `کیا آپ واقعی '{0}' کے تمام استعمال کو حذف کرنا چاہتے ہیں؟

یہ کالعدم نہیں ہوسکتا!`,
	EditorEditTemplateDetailsLabel: `تفصیلات میں ترمیم کریں`,
	EditorEditTemplateNameLabel: `نام`,
	EditorFindLabel: `مل`,
	EditorFontColorLabel: `لکھائی کا رنگ`,
	EditorFormatPaintLabel: `فارمیٹ پینٹ`,
	EditorInSelectionLabel: ` انتخاب میں`,
	EditorInsertImageLabel: `تصویر داخل کریں`,
	EditorInsertLinkLabel: `لنک داخل کریں`,
	EditorInsertVideoLabel: `ویڈیو داخل کریں`,
	EditorMatchCaseLabel: ` میچ کیس`,
	EditorNewTemplateLabel: `نیا ٹیمپلیٹ`,
	EditorNextTemplateLabel: `اگلا ٹیمپلیٹ`,
	EditorPasteButtonAppendBeginLabel: `ضمیمہ ...`,
	EditorPasteButtonLabel: `چسپاں کریں`,
	EditorPasteTemplateWatermark: `پیسٹ متن درج کریں ...`,
	EditorPrevTemplateLabel: `پچھلا ٹیمپلیٹ`,
	EditorRegExLabel: ` باقاعدہ اظہار`,
	EditorReplaceAllLabel: `سب کو تبدیل کریں`,
	EditorReplaceLabel: `تبدیل کریں`,
	EditorTemplateContactHint: `<p>دستیاب رابطوں کا استعمال کرتے ہوئے (فیچر پلگ ان کی ضرورت ہوتی ہے) یہ فیلڈ اس دستاویز میں اس ٹیمپلیٹ کی تمام مثالوں کے لئے استعمال کی جائے گی یا کسی میں بھی بعد میں اس کا حوالہ دیا جائے گا۔</p><p> لہذا مثال کے طور پر اگر یہاں ای میل ایڈریس منتخب کریں تو آپ کے منتخب کردہ رابطے کا ای میل فیلڈ اس دستاویز میں تمام مثالوں کے لئے استعمال کیا جائے گا۔</p>`,
	EditorTemplateContactName: `رابطہ کریں`,
	EditorTemplateDateTimeCustomHint: `yy = مختصر سال<br/>yyyy = طویل سال<br/>ایم = مہینہ (1-12)<br/>ایم ایم = مہینہ (01-12)<br/>ایم ایم ایم = ماہ کا مخفف (جنوری، فروری ... دسمبر)<br/>ایم ایم ایم ایم = طویل مہینہ (جنوری، فروری ... دسمبر)<br/>دن = دن (1 - 31)<br/>ڈی ڈی = دن (01 - 31)<br/>ڈی ڈی ڈی = الفاظ میں ہفتے کا دن (پیر، منگل ... اتوار)<br/>ای = الفاظ میں ہفتے کا مختصر دن (مون، ٹو ... سورج)<br/>ڈی - آرڈینل دن (پہلا، دوسرا، تیسرا، 21 واں، 22 واں، 23 واں، 31 واں، چوتھا ...)<br/>ایچ = صبح / شام کا گھنٹہ (0-12)<br/>hh = صبح / شام کا گھنٹہ (00-12)<br/>H = دن میں گھنٹہ (0-23)<br/>ایچ ایچ = دن میں گھنٹہ (00-23)<br/>ملی میٹر = منٹ<br/>ایس ایس = دوسرا<br/>SSS = ملی سیکنڈ<br/>اے = اے ایم / پی ایم مارکر<br/>پی = اے ایم / پی ایم مارکر`,
	EditorTemplateDateTimeCustomLabel: `اپنی مرضی کے مطابق`,
	EditorTemplateDateTimeHint: `موجودہ تاریخ اور/یا وقت کو پیسٹ کیا جائے گا جب ڈیٹ ٹائم ٹیمپلیٹس کے لئے تبدیل کیا جائے گا۔`,
	EditorTemplateDateTimeName: `تاریخ وقت`,
	EditorTemplateDynamicHint: `<p>اس ٹیمپلیٹ کے تمام واقعات فراہم کردہ متن کا استعمال کریں گے۔</p>`,
	EditorTemplateDynamicName: `متحرک`,
	EditorTemplateEmptyPlaceholder: `{0} خالی ہے ...`,
	EditorTemplateStaticHint: `<p>اس ٹیمپلیٹ کے تمام واقعات فراہم کردہ متن کا استعمال کریں گے۔</p>`,
	EditorTemplateStaticName: `جامد`,
	EditorTemplateTeaserText: `مزید جلد آرہا ہے!`,
	EditorWatermark: `برائے مہربانی انتظار کریں...`,
	EditorWholeWordLabel: ` پورا لفظ`,
	EditorWrapLabel: ` ارد گرد لپیٹنا`,

};