var UiStrings = {
	EditorAppendCloseLabel: `Ολοκληρώστε την κατάρτιση`,
	EditorAppendInlineModeLabel: `Ενεργοποίηση μπλοκ`,
	EditorAppendLineModeLabel: `Ενεργοποίηση inline`,
	EditorAppendManualModeLabel: `Εγχειρίδιο εναλλαγής`,
	EditorAppendNonManualModeLabel: `Εγχειρίδιο εναλλαγής`,
	EditorAppendPauseLabel: `Παύση προσθέτει`,
	EditorAppendPostLabel: `Εναλλαγή πριν`,
	EditorAppendPreLabel: `Εναλλαγή πριν`,
	EditorAppendResumeLabel: `Επαναλαμβάνω προσθέστε`,
	EditorBgColorLabel: `Χρώμα του φόντου`,
	EditorClearAllLabel: `Τα καθαρίζω όλα`,
	EditorClipboardFormatsLabel: `Μορφές προφίλ`,
	EditorConfirmNtfTitle: `Επιβεβαιώνω`,
	EditorDeleteAllButtonText: `Διαγραφή όλων`,
	EditorDeleteAllTemplatesNtfText: `Είστε βέβαιοι ότι θέλετε να διαγράψετε όλες τις συνήθειες του '{0}';

Αυτό δεν μπορεί να αναιρεθεί!`,
	EditorEditTemplateDetailsLabel: `Επεξεργασία λεπτομερειών`,
	EditorEditTemplateNameLabel: `Ονομα`,
	EditorFindLabel: `Εύρημα`,
	EditorFontColorLabel: `Γραμματοσειρά`,
	EditorFormatPaintLabel: `Βαφή μορφής`,
	EditorInSelectionLabel: ` Σε επιλογή`,
	EditorInsertImageLabel: `Εισαγάγετε εικόνα`,
	EditorInsertLinkLabel: `Εισαγάγετε σύνδεσμο`,
	EditorInsertVideoLabel: `Εισαγάγετε βίντεο`,
	EditorMatchCaseLabel: ` Υπόθεση αγώνα`,
	EditorNewTemplateLabel: `Νέο πρότυπο`,
	EditorNextTemplateLabel: `Επόμενο πρότυπο`,
	EditorPasteButtonAppendBeginLabel: `Προσαρτώ...`,
	EditorPasteButtonLabel: `Επικόλληση`,
	EditorPasteTemplateWatermark: `Εισαγάγετε κείμενο επικόλλησης ...`,
	EditorPrevTemplateLabel: `Προηγούμενο πρότυπο`,
	EditorRegExLabel: ` Κοινή έκφραση`,
	EditorReplaceAllLabel: `Αντικαταστήστε όλα`,
	EditorReplaceLabel: `Αντικαθιστώ`,
	EditorTemplateContactHint: `<p> Χρησιμοποιώντας τις διαθέσιμες επαφές (απαιτεί ένα plugin fetcher) Αυτό το πεδίο θα χρησιμοποιηθεί για όλες τις περιπτώσεις αυτού του προτύπου σε αυτό το έγγραφο ή σε οποιοδήποτε που θα αναφερθεί αργότερα. Εδώ τότε το πεδίο ηλεκτρονικού ταχυδρομείου της επαφής που επιλέξετε θα χρησιμοποιηθεί για όλες τις περιπτώσεις σε αυτό το έγγραφο. </p>`,
	EditorTemplateContactName: `Επικοινωνία`,
	EditorTemplateDateTimeCustomHint: `yy = σύντομο έτος <br/> yyyy = long year <br/> m = μήνας (1-12) <br/> mm = μήνας (01-12) <br/> mmm = μήνας συντομογραφία (Jan, Feb .. . Δεκ) Ημέρα της εβδομάδας με λόγια (Δευτέρα, Τρίτη ... Κυριακή) <br/> E = σύντομη ημέρα της εβδομάδας με λέξεις (Mon, Tue ... Sun) <br/> D - Ορτική ημέρα (1η, 2η, 3η, 21η, 22η, 23η, 31η, 4η ...) <br/> h = ώρα σε am/pm (0-12) <br/> hh = ώρα σε am/pm (00-12) <Br/ > H = ώρα την ημέρα (0-23) <br/> hh = ώρα την ημέρα (00-23) <br/> mm = λεπτό <br/> ss = δεύτερο <br/> sss = milliseconds <br/> a = am/pm marker <br/> p = a.m./p.m. σημάδι`,
	EditorTemplateDateTimeCustomLabel: `Εθιμο`,
	EditorTemplateDateTimeHint: `Η τρέχουσα ημερομηνία ή/και ο χρόνος θα αντικατασταθούν για πρότυπα ημερομηνίας όταν είναι επικολλημένες.`,
	EditorTemplateDateTimeName: `Ημερομηνία ώρα`,
	EditorTemplateDynamicHint: `<p> Όλες οι εμφανίσεις αυτού του προτύπου θα χρησιμοποιήσουν το παρεχόμενο κείμενο. </p>`,
	EditorTemplateDynamicName: `Δυναμικός`,
	EditorTemplateEmptyPlaceholder: `{0} είναι άδειο ...`,
	EditorTemplateStaticHint: `<p> Όλες οι εμφανίσεις αυτού του προτύπου θα χρησιμοποιήσουν το παρεχόμενο κείμενο. </p>`,
	EditorTemplateStaticName: `Στατικός`,
	EditorTemplateTeaserText: `Περισσότερα σε λίγο!`,
	EditorWatermark: `Παρακαλώ περιμένετε...`,
	EditorWholeWordLabel: ` Ολος ο κοσμος`,
	EditorWrapLabel: ` Τυλίγομαι γύρω`,

};