var UiStrings = {
	EditorAppendCloseLabel: `Viimeistellä`,
	EditorAppendInlineModeLabel: `Ottaa käyttöön lohko`,
	EditorAppendLineModeLabel: `Ottaa käyttöön`,
	EditorAppendManualModeLabel: `Vaihtaa käsikirja`,
	EditorAppendNonManualModeLabel: `Vaihtaa käsikirja`,
	EditorAppendPauseLabel: `Tauko`,
	EditorAppendPostLabel: `Kypsyä ennen`,
	EditorAppendPreLabel: `Kypsyä ennen`,
	EditorAppendResumeLabel: `Jatkaa liitettä`,
	EditorBgColorLabel: `Taustaväri`,
	EditorClearAllLabel: `Tyhjennä`,
	EditorClipboardFormatsLabel: `Leikepöydän muodot`,
	EditorConfirmNtfTitle: `Vahvistaa`,
	EditorDeleteAllButtonText: `Poista kaikki`,
	EditorDeleteAllTemplatesNtfText: `Oletko varma, että haluat poistaa kaikki '{0}' käytöt?

Tätä ei voi peruuttaa!`,
	EditorEditTemplateDetailsLabel: `Muokkaa yksityiskohtia`,
	EditorEditTemplateNameLabel: `Nimi`,
	EditorFindLabel: `löytö`,
	EditorFontColorLabel: `Fontin väri`,
	EditorFormatPaintLabel: `Muotoilla maali`,
	EditorInSelectionLabel: ` Valinnassa`,
	EditorInsertImageLabel: `Lisätä kuva`,
	EditorInsertLinkLabel: `Aseta linkki`,
	EditorInsertVideoLabel: `Lisää video`,
	EditorMatchCaseLabel: ` Kotelo`,
	EditorNewTemplateLabel: `Uusi malli`,
	EditorNextTemplateLabel: `Seuraava malli`,
	EditorPasteButtonAppendBeginLabel: `Liitä ...`,
	EditorPasteButtonLabel: `Liittää`,
	EditorPasteTemplateWatermark: `Kirjoita liitä teksti ...`,
	EditorPrevTemplateLabel: `Aikaisempi malli`,
	EditorRegExLabel: ` Tavallinen ilme`,
	EditorReplaceAllLabel: `Korvaa kaikki`,
	EditorReplaceLabel: `Korvata`,
	EditorTemplateContactHint: `<p> Käytettävissä olevien yhteystietojen käyttäminen (vaatii Fetcher -laajennuksen) Tätä kenttää käytetään tämän mallin kaikkiin tapauksiin tämän asiakirjan välillä tai missä tahansa siihen viitataan myöhemmin. </p> <p> Joten esimerkiksi jos valitse sähköpostiosoite Tässä sitten valitsemasi yhteystietokenttä käytetään kaikkiin tämän asiakirjan tapauksiin. </p>`,
	EditorTemplateContactName: `Ottaa yhteyttä`,
	EditorTemplateDateTimeCustomHint: `yy = lyhyt vuosi <br/> yyyy = pitkä vuosi <br/> m = kuukausi (1-12) <br/> mm = kuukausi (01-12) <br/> mmm = kuukauden lyhenne (tammikuu, helmikuu .. .. . DEC) <br/> mmmm = pitkä kuukausi (tammikuu, helmikuu ... joulukuu) <br/> d = päivä (1 - 31) <br/> dd = päivä (01 - 31) <br/> ddd = Viikonpäivä sanoin (maanantai, tiistai ... sunnuntai) <br/> e = viikon lyhyt päivä sanoina (ma, tiistaina ... aurinko) <br/> d - ordinaalipäivä (1., 2., 2., 3., 21., 22., 23., 31., 4. ...) <br/> h = tunti AM/PM: ssä (0-12) <br/> HH = tunti AM/PM: ssä (00-12) <br/br/ > H = tunti päivässä (0-23) <br/> hh = tunti päivässä (00-23) <br/> mm = minuutti <br/> ss = toinen <br/> sss = millisekunnit <br/> A = AM/PM -merkki <br/> p = A.M./P.M. merkintä`,
	EditorTemplateDateTimeCustomLabel: `Mukautettu`,
	EditorTemplateDateTimeHint: `Nykyinen päivämäärä ja/tai aika korvataan DateTime -malleissa, kun ne on liitetty.`,
	EditorTemplateDateTimeName: `Treffiaika`,
	EditorTemplateDynamicHint: `<p> Tämän mallin kaikki tapahtumat käyttävät toimitettua tekstiä. </p>`,
	EditorTemplateDynamicName: `Dynaaminen`,
	EditorTemplateEmptyPlaceholder: `{0} on tyhjä ...`,
	EditorTemplateStaticHint: `<p> Tämän mallin kaikki tapahtumat käyttävät toimitettua tekstiä. </p>`,
	EditorTemplateStaticName: `Staattinen`,
	EditorTemplateTeaserText: `Lisää tulossa pian!`,
	EditorWatermark: `Odota...`,
	EditorWholeWordLabel: ` Koko maailma`,
	EditorWrapLabel: ` Kietoa`,

};