var UiStrings = {
	EditorAppendCloseLabel: `जोडणे समाप्त`,
	EditorAppendInlineModeLabel: `ब्लॉक सक्षम करा`,
	EditorAppendLineModeLabel: `इनलाइन सक्षम करा`,
	EditorAppendManualModeLabel: `मॅन्युअल टॉगल`,
	EditorAppendNonManualModeLabel: `मॅन्युअल टॉगल`,
	EditorAppendPauseLabel: `विराम द्या`,
	EditorAppendPostLabel: `आधी टॉगल`,
	EditorAppendPreLabel: `आधी टॉगल`,
	EditorAppendResumeLabel: `पुन्हा सुरू करा`,
	EditorBgColorLabel: `पार्श्वभूमी रंग`,
	EditorClearAllLabel: `सर्व साफ करा`,
	EditorClipboardFormatsLabel: `क्लिपबोर्ड स्वरूप`,
	EditorConfirmNtfTitle: `पुष्टी`,
	EditorDeleteAllButtonText: `सर्व हटवा`,
	EditorDeleteAllTemplatesNtfText: `आपणास खात्री आहे की आपण '{0}' चे सर्व उपयोग हटवू इच्छिता?

हे पूर्ववत केले जाऊ शकत नाही!`,
	EditorEditTemplateDetailsLabel: `तपशील संपादित करा`,
	EditorEditTemplateNameLabel: `नाव`,
	EditorFindLabel: `शोधणे`,
	EditorFontColorLabel: `फॉन्टचा रंग`,
	EditorFormatPaintLabel: `स्वरूप पेंट`,
	EditorInSelectionLabel: ` निवडीमध्ये`,
	EditorInsertImageLabel: `प्रतिमा घाला`,
	EditorInsertLinkLabel: `दुवा घाला`,
	EditorInsertVideoLabel: `व्हिडिओ घाला`,
	EditorMatchCaseLabel: ` सामना केस`,
	EditorNewTemplateLabel: `नवीन टेम्पलेट`,
	EditorNextTemplateLabel: `पुढील टेम्पलेट`,
	EditorPasteButtonAppendBeginLabel: `जोडा ...`,
	EditorPasteButtonLabel: `पेस्ट करा`,
	EditorPasteTemplateWatermark: `पेस्ट मजकूर प्रविष्ट करा ...`,
	EditorPrevTemplateLabel: `मागील टेम्पलेट`,
	EditorRegExLabel: ` नियमित अभिव्यक्ती`,
	EditorReplaceAllLabel: `सर्व बदला`,
	EditorReplaceLabel: `पुनर्स्थित करा`,
	EditorTemplateContactHint: `<p> उपलब्ध संपर्क वापरणे (फॅचर प्लगइन आवश्यक आहे) हे फील्ड या दस्तऐवजावरील या टेम्पलेटच्या सर्व घटनांसाठी किंवा नंतर संदर्भित केले जाईल. येथे आपण निवडलेल्या संपर्काचे ईमेल फील्ड या दस्तऐवजातील सर्व घटनांसाठी वापरले जाईल.`,
	EditorTemplateContactName: `संपर्क`,
	EditorTemplateDateTimeCustomHint: `yy = लहान वर्ष <br/> yyyy = दीर्घ वर्ष <br/> एम = महिना (1-12) <br/> मिमी = महिना (01-12) <br/> एमएमएम = महिना संक्षेप (जाने, फेब्रुवारी .. . डिसें) <br/> एमएमएमएम = लांब महिना (जानेवारी, फेब्रुवारी ... डिसेंबर) <br/> डी = दिवस (1 - 31) <br/> डीडी = दिवस (01 - 31) <br/> डीडीडी = शब्दात आठवड्याचा दिवस (सोमवार, मंगळवार ... रविवारी) <br/> ई = आठवड्याचा शब्द शब्दात (सोम, मंगळ ... सूर्य) <br/> डी - ऑर्डिनल डे (1 ला, 2 रा, तिसरा, 21, 22, 23, 31, 4 था ...) <br/> एच = एएम/पीएम इन एएम/पीएम (0-12) <br/> एएम/पीएम (00-12) <बीआर/मध्ये एचएच = तास <बीआर/ > एच = दिवसातील तास (0-23) <br/> दिवसातील एचएच = दिवस (00-23) ए = एएम/पंतप्रधान मार्कर <br/> पी = ए.एम./पी.एम. मार्कर`,
	EditorTemplateDateTimeCustomLabel: `सानुकूल`,
	EditorTemplateDateTimeHint: `सध्याची तारीख आणि/किंवा वेळ पेस्ट केल्यावर डेटटाइम टेम्पलेट्ससाठी बदलली जाईल.`,
	EditorTemplateDateTimeName: `तारीख वेळ`,
	EditorTemplateDynamicHint: `<p> या टेम्पलेटच्या सर्व घटना प्रदान केलेला मजकूर वापरतील.`,
	EditorTemplateDynamicName: `डायनॅमिक`,
	EditorTemplateEmptyPlaceholder: `{0 reach रिक्त आहे ...`,
	EditorTemplateStaticHint: `<p> या टेम्पलेटच्या सर्व घटना प्रदान केलेला मजकूर वापरतील.`,
	EditorTemplateStaticName: `स्थिर`,
	EditorTemplateTeaserText: `अधिक लवकरच येत आहे!`,
	EditorWatermark: `कृपया थांबा...`,
	EditorWholeWordLabel: ` संपूर्ण शब्द`,
	EditorWrapLabel: ` भोवती गुंडाळा`,

};