var UiStrings = {
	EditorAppendCloseLabel: `ઉમેરવાનું સમાપ્ત કરો`,
	EditorAppendInlineModeLabel: `સક્ષમ કરો અવરોધિત`,
	EditorAppendLineModeLabel: `ઇનલાઇનને સક્ષમ કરો`,
	EditorAppendManualModeLabel: `ટોકલ મેન મેન્યુઅલ`,
	EditorAppendNonManualModeLabel: `ટોકલ મેન મેન્યુઅલ`,
	EditorAppendPauseLabel: `સંલગ્ન કરવું`,
	EditorAppendPostLabel: `પહેલાં ટ gle ગલ કરવું`,
	EditorAppendPreLabel: `પહેલાં ટ gle ગલ કરવું`,
	EditorAppendResumeLabel: `ફરી શરૂ કરવું`,
	EditorBgColorLabel: `પૃષ્ઠભૂમિ રંગ`,
	EditorClearAllLabel: `બધું સાફ કરો`,
	EditorClipboardFormatsLabel: `ક્લિપબોર્ડ ફોર્મેટ્સ`,
	EditorColorChooserTitle: `સંપાદક રંગ`,
	EditorConfirmNtfTitle: `પુષ્ટિ આપવી`,
	EditorDeleteAllButtonText: `બધું કાઢી નાંખો`,
	EditorDeleteAllTemplatesNtfText: `શું તમે ખરેખર '{0}' ના બધા ઉપયોગોને કા delete ી નાખવા માંગો છો?

આ પૂર્વવત્ કરી શકાતું નથી!`,
	EditorEditTemplateDetailsLabel: `વિગતો સંપાદિત કરો`,
	EditorEditTemplateNameLabel: `નામ`,
	EditorFindLabel: `શોધો`,
	EditorFontColorLabel: `ફ ont ન્ટ રંગ`,
	EditorFormatPaintLabel: `ફોર્મેટ`,
	EditorInSelectionLabel: ` પસંદગીની`,
	EditorInsertImageLabel: `છબી દાખલ કરો`,
	EditorInsertLinkLabel: `લિંક દાખલ કરો`,
	EditorInsertVideoLabel: `વિડિઓ દાખલ કરો`,
	EditorLinkButtonText: `બચત કરવી`,
	EditorLinkLabel: `કડી દાખલ કરો`,
	EditorLinkPlaceholder: `URL દાખલ કરો`,
	EditorMatchCaseLabel: ` મેચ કેસ`,
	EditorNewTemplateLabel: `નવું નમૂના`,
	EditorNextTemplateLabel: `આગલું નમૂના`,
	EditorPasteButtonAppendBeginLabel: `જોડો ...`,
	EditorPasteButtonLabel: `આંચકો`,
	EditorPasteButtonLabelMobile: `નકલ`,
	EditorPasteTemplateWatermark: `પેસ્ટ ટેક્સ્ટ દાખલ કરો ...`,
	EditorPrevTemplateLabel: `પાછલું નમૂના`,
	EditorRegExLabel: ` નિયમિત સમીકરણ`,
	EditorReplaceAllLabel: `બધા બદલો`,
	EditorReplaceLabel: `બદલવું`,
	EditorTemplateContactHint: `<p>ઉપલબ્ધ સંપર્કોને વાપરી રહ્યા છે (લાવવાનું પ્લગઇન જરૂરી છે) આ ક્ષેત્ર આ દસ્તાવેજમાં આ ટેમ્પલેટના બધા દાખલાઓ માટે વપરાશે અથવા કોઇપણમાં તે પછીથી સંદર્ભિત થશે.</p><p> તેથી ઉદાહરણ તરીકે, જો અહીં ઇમેઇલ એડ્રેસ પસંદ કરો, તો તમે પસંદ કરો છો તે સંપર્કનું ઇમેઇલ ક્ષેત્ર આ દસ્તાવેજના તમામ દાખલાઓ માટે ઉપયોગમાં લેવામાં આવશે.</p>`,
	EditorTemplateContactName: `સંપર્ક`,
	EditorTemplateDateTimeCustomHint: `yy = ટૂંકુ વર્ષ<br/>yyyy = long year<br/>M = મહિનો (૧-૧૨)<br/>MM = મહિનો (01-12)<br/>MMM = મહિનાનું સંક્ષિપ્ત શબ્દ (જાન્યુઆરી, ફેબ્રુઆરી ... ડિસેમ્બર)<br/>MMMM = લાંબો મહિનો (જાન્યુઆરી, ફેબ્રુઆરી ... ડિસેમ્બર)<br/>d = દિવસ (1 - 31)<br/>dd = દિવસ (01 - 31)<br/>ddd = અઠવાડિયાનો દિવસ શબ્દોમાં (સોમવાર, મંગળવાર ... રવિવાર)<br/>E = અઠવાડિયાનો ટૂંકો દિવસ શબ્દોમાં (મોન, ટુ... સૂર્ય)<br/>ડી - ઓર્ડિનરી દિવસ (પ્રથમ, દ્વિતીય, ત્રીજો, 21મો, 22, 23, 31મો, ચોથો દિવસ...)<br/>h = કલાક in am/pm (0-12)<br/>hh = કલાક in am/pm (00-12)<br/>H = દિવસમાં કલાક (૦-૨૩)<br/>HH = દિવસમાં કલાક (૦૦-૨૩)<br/>mm = મિનિટ<br/>ss = second<br/>SSS = મિલિસેકન્ડો<br/>a = AM/PM માર્કર<br/>p = a.m./p.m. marker`,
	EditorTemplateDateTimeCustomLabel: `રિવાજ`,
	EditorTemplateDateTimeHint: `વર્તમાન તારીખ અને/અથવા સમય જ્યારે પેસ્ટ કરવામાં આવે ત્યારે ડેટટાઇમ નમૂનાઓ માટે બદલવામાં આવશે.`,
	EditorTemplateDateTimeName: `તારીખ સમય`,
	EditorTemplateDynamicHint: `<p>આ ટેમ્પલેટની તમામ ઘટનાઓ પ્રદાન કરેલા લખાણનો ઉપયોગ કરશે.</p>`,
	EditorTemplateDynamicName: `ગતિશીલ`,
	EditorTemplateEmptyPlaceholder: `{0} ખાલી છે...`,
	EditorTemplateStaticHint: `<p>આ ટેમ્પલેટની તમામ ઘટનાઓ પ્રદાન કરેલા લખાણનો ઉપયોગ કરશે.</p>`,
	EditorTemplateStaticName: `સ્થિર`,
	EditorTemplateTeaserText: `વધુ જલ્દી આવે છે!`,
	EditorTt1: `કળણ`,
	EditorTt2: `'<em> {0} </em>' સંપાદિત કરો ...`,
	EditorTt3: `રંગ સંપાદિત કરો ...`,
	EditorTt4: `'<em> {0} </em>' દૂર કરો ...`,
	EditorTt5: `વસ્તુ દૂર કરો`,
	EditorTt6: `અનુસરો ...`,
	EditorTt7: `ગોટો '<em> {0} </em>' ...`,
	EditorWatermark: `મહેરબાની કરી રાહ જુવો...`,
	EditorWholeWordLabel: ` સંપૂર્ણ શબ્દ`,
	EditorWrapLabel: ` આજુબાજુ વીંટાળો`,

};