var UiStrings = {
	EditorAppendCloseLabel: `Zakończyć dołączenie`,
	EditorAppendInlineModeLabel: `Włącz blok`,
	EditorAppendLineModeLabel: `Włącz inline`,
	EditorAppendManualModeLabel: `Podręcznik przełączania`,
	EditorAppendNonManualModeLabel: `Podręcznik przełączania`,
	EditorAppendPauseLabel: `Załącz pauzę`,
	EditorAppendPostLabel: `Przełącz wcześniej`,
	EditorAppendPreLabel: `Przełącz wcześniej`,
	EditorAppendResumeLabel: `Wznowić dodatek`,
	EditorBgColorLabel: `Kolor tła`,
	EditorClearAllLabel: `Wyczyść wszystko`,
	EditorClipboardFormatsLabel: `Formaty schowka`,
	EditorConfirmNtfTitle: `Potwierdzać`,
	EditorDeleteAllButtonText: `Usuń wszystko`,
	EditorDeleteAllTemplatesNtfText: `Czy na pewno chcesz usunąć wszystkie zastosowania „{0}”?

Tego nie da się cofnąć!`,
	EditorEditTemplateDetailsLabel: `Edytuj szczegóły`,
	EditorEditTemplateNameLabel: `Nazwa`,
	EditorFindLabel: `Znajdować`,
	EditorFontColorLabel: `Kolor czcionki`,
	EditorFormatPaintLabel: `Formatowanie farby`,
	EditorInSelectionLabel: ` W selekcji`,
	EditorInsertImageLabel: `Umieść obraz`,
	EditorInsertLinkLabel: `Wstaw link`,
	EditorInsertVideoLabel: `Wstaw wideo`,
	EditorMatchCaseLabel: ` Sprawa meczu`,
	EditorNewTemplateLabel: `Nowy szablon`,
	EditorNextTemplateLabel: `Następny szablon`,
	EditorPasteButtonAppendBeginLabel: `Dodać...`,
	EditorPasteButtonLabel: `Pasta`,
	EditorPasteTemplateWatermark: `Wprowadź tekst wklejania ...`,
	EditorPrevTemplateLabel: `Poprzedni szablon`,
	EditorRegExLabel: ` Wyrażenie regularne`,
	EditorReplaceAllLabel: `Zamień wszystko`,
	EditorReplaceLabel: `Zastępować`,
	EditorTemplateContactHint: `<p> Korzystanie z dostępnych kontaktów (wymaga wtyczki fetcher) To pole zostanie użyte dla wszystkich instancji tego szablonu w tym dokumencie lub w dowolnym odwołaniu do później. </p> <p> Więc na przykład, jeśli wybierz adres e -mail Tutaj, wówczas pole e -mail wybranego kontaktu zostanie użyte dla wszystkich instancji w tym dokumencie. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = krótki rok <br/> trys = długi rok <br/> m = miesiąc (1-12) <br/> mm = miesiąc (01-12) <br/> mmm = skrót miesiąca (Jan, luty .. . Grudzień) <br/> mmmm = długi miesiąc (styczeń, luty ... grudzień) <br/> d = dzień (1 - 31) <br/> dd = dzień (01 - 31) <br/> ddd = Dzień tygodnia słowami (poniedziałek, wtorek ... niedziela) <br/> e = krótki dzień tygodnia słowami (pon, wt ... Słońce) <br/> d - Dzień Ordinal (1, 2, 2, 3, 21, 22, 23, 31, 4 ...) <br/> h = godzina w AM/PM (0-12) <br/> hh = godzina w AM/PM (00-12) <Br// > H = godzina w dniu (0-23) <br/> hh = godzina w dniu (00-23) <br/> mm = minuta <br/> ss = drugi <br/> ss = milisekunds <br/> A = Marker AM/PM <br/> p = A.M./P.M. znacznik`,
	EditorTemplateDateTimeCustomLabel: `Zwyczaj`,
	EditorTemplateDateTimeHint: `Obecna data i/lub godzina zostaną zastąpione szablonami DATETIME po wklejeniu.`,
	EditorTemplateDateTimeName: `Data godzina`,
	EditorTemplateDynamicHint: `<p> Wszystkie zdarzenia tego szablonu będą używać dostarczonego tekstu. </p>`,
	EditorTemplateDynamicName: `Dynamiczny`,
	EditorTemplateEmptyPlaceholder: `{0} jest pusty ...`,
	EditorTemplateStaticHint: `<p> Wszystkie zdarzenia tego szablonu będą używać dostarczonego tekstu. </p>`,
	EditorTemplateStaticName: `Statyczny`,
	EditorTemplateTeaserText: `Więcej wkrótce!`,
	EditorWatermark: `Proszę czekać...`,
	EditorWholeWordLabel: ` Cały świat`,
	EditorWrapLabel: ` Owinąć`,

};