var UiStrings = {
	EditorAppendCloseLabel: `Críochnaigh ag clúdach`,
	EditorAppendInlineModeLabel: `Bloc Cumasaigh`,
	EditorAppendLineModeLabel: `Cumasaigh inlíne`,
	EditorAppendManualModeLabel: `Lámhleabhar Toggle`,
	EditorAppendNonManualModeLabel: `Lámhleabhar Toggle`,
	EditorAppendPauseLabel: `Sos aguisín`,
	EditorAppendPostLabel: `Toggle roimhe seo`,
	EditorAppendPreLabel: `Toggle roimhe seo`,
	EditorAppendResumeLabel: `Atosú aguisín`,
	EditorBgColorLabel: `Dath an chúlra`,
	EditorClearAllLabel: `Soiléir ar fad`,
	EditorClipboardFormatsLabel: `Formáidí gearrthaisce`,
	EditorConfirmNtfTitle: `Daingnigh`,
	EditorDeleteAllButtonText: `Scrios gach duine`,
	EditorDeleteAllTemplatesNtfText: `An bhfuil tú cinnte gur mian leat gach úsáid de '{0}' a scriosadh?

Ní féidir é seo a dhíothú!`,
	EditorEditTemplateDetailsLabel: `Sonraí a chur in eagar`,
	EditorEditTemplateNameLabel: `Ainmnigh`,
	EditorFindLabel: `Faigh amach`,
	EditorFontColorLabel: `Cló dath`,
	EditorFormatPaintLabel: `Péint fhormáid`,
	EditorInSelectionLabel: ` Agus é ag roghnú`,
	EditorInsertImageLabel: `Cuir isteach íomhá`,
	EditorInsertLinkLabel: `Cuir isteach nasc`,
	EditorInsertVideoLabel: `Cuir isteach físeán`,
	EditorMatchCaseLabel: ` Cás an chluiche`,
	EditorNewTemplateLabel: `Teimpléad nua`,
	EditorNextTemplateLabel: `An chéad teimpléad eile`,
	EditorPasteButtonAppendBeginLabel: `Aguisín ...`,
	EditorPasteButtonLabel: `Greab`,
	EditorPasteTemplateWatermark: `Iontráil téacs greamaigh ...`,
	EditorPrevTemplateLabel: `Teimpléad roimhe seo`,
	EditorRegExLabel: ` Léiriú rialta`,
	EditorReplaceAllLabel: `Ionadaigh go léir`,
	EditorReplaceLabel: `Cuir isteach`,
	EditorTemplateContactHint: `<p> Ag baint úsáide as na teagmhálacha atá ar fáil (teastaíonn breiseán fetcher) bainfear úsáid as an réimse seo do gach cás den teimpléad seo ar fud an doiciméid seo nó in aon cheann, déanfar tagairt dó níos déanaí. Anseo ansin bainfear úsáid as réimse ríomhphoist na teagmhála a roghnaíonn tú do gach cás sa doiciméad seo. </p>`,
	EditorTemplateContactName: `Lionsa`,
	EditorTemplateDateTimeCustomHint: `yy = bliain ghearr <br/> yyyy = bliain fhada <br/> m = month (1-12) <br/> mm = mí (01-12) <br/> Mmm = Mí Giorrúchán (Eanáir, Feabhra. Dec) <br/> mmmm = mí fhada (Eanáir, Feabhra ... Nollaig) <br/> d = lá (1 - 31) <br/> dd = lá (01 - 31) <br/> ddd = Lá na seachtaine i bhfocail (Dé Luain, Dé Máirt ... Dé Domhnaigh) <br/> e = lá gearr na seachtaine i bhfocail (Luan, tue ... Sun) <br/> D - Lá Ordaitheach (1ú, 2ú, 3ú, 21ú, 22ú, 23ú, 31ú, 4ú ...) <br/> H = uair an chloig in AM/PM (0-12) <br/> HH = uair an chloig in AM/PM (00-12) <br/ > H = uair an chloig sa lá (0-23) <br/> hh = uair an chloig sa lá (00-23) <br/> mm = nóiméad <br/> ss = an dara <br/> sss = milliseconds <br/> a = am/pm marcóir <br/> p = a.m./p.m. marcálaí`,
	EditorTemplateDateTimeCustomLabel: `Cur síos`,
	EditorTemplateDateTimeHint: `Cuirfear an dáta agus/nó an t -am reatha in ionad teimpléid dhátú nuair a ghreamaítear iad.`,
	EditorTemplateDateTimeName: `Dáta Am`,
	EditorTemplateDynamicHint: `<p> Bainfidh gach tarlú den teimpléad seo úsáid as an téacs atá curtha ar fáil. </p>`,
	EditorTemplateDynamicName: `Dinimiciúil`,
	EditorTemplateEmptyPlaceholder: `Tá {0} folamh ...`,
	EditorTemplateStaticHint: `<p> Bainfidh gach tarlú den teimpléad seo úsáid as an téacs atá curtha ar fáil. </p>`,
	EditorTemplateStaticName: `Statach`,
	EditorTemplateTeaserText: `Níos mó ag teacht go luath!`,
	EditorWatermark: `Fán le do thoil...`,
	EditorWholeWordLabel: ` Focal iomlán`,
	EditorWrapLabel: ` Timfhilleadh timpeall`,

};