var UiStrings = {
	EditorAppendCloseLabel: `Slutföra`,
	EditorAppendInlineModeLabel: `Aktivera block`,
	EditorAppendLineModeLabel: `Aktivera inline`,
	EditorAppendManualModeLabel: `Växla manual`,
	EditorAppendNonManualModeLabel: `Växla manual`,
	EditorAppendPauseLabel: `Pausa bifogas`,
	EditorAppendPostLabel: `Växla innan`,
	EditorAppendPreLabel: `Växla innan`,
	EditorAppendResumeLabel: `Återuppta`,
	EditorBgColorLabel: `Bakgrundsfärg`,
	EditorClearAllLabel: `Rensa alla`,
	EditorClipboardFormatsLabel: `Urklippsformat`,
	EditorConfirmNtfTitle: `Bekräfta`,
	EditorDeleteAllButtonText: `Radera allt`,
	EditorDeleteAllTemplatesNtfText: `Är du säker på att du vill ta bort alla användningar av '{0}'?

Detta kan inte göras ogjort!`,
	EditorEditTemplateDetailsLabel: `Redigera detaljer`,
	EditorEditTemplateNameLabel: `namn`,
	EditorFindLabel: `Hitta`,
	EditorFontColorLabel: `Fontfärg`,
	EditorFormatPaintLabel: `Formatfärg`,
	EditorInSelectionLabel: ` I urval`,
	EditorInsertImageLabel: `Infoga bild`,
	EditorInsertLinkLabel: `Infoga länk`,
	EditorInsertVideoLabel: `Infoga video`,
	EditorMatchCaseLabel: ` Liknande fall`,
	EditorNewTemplateLabel: `Ny mall`,
	EditorNextTemplateLabel: `Nästa mall`,
	EditorPasteButtonAppendBeginLabel: `Bifoga...`,
	EditorPasteButtonLabel: `Klistra`,
	EditorPasteTemplateWatermark: `Ange pasta text ...`,
	EditorPrevTemplateLabel: `Föregående mall`,
	EditorRegExLabel: ` Vanligt uttryck`,
	EditorReplaceAllLabel: `Ersätt alla`,
	EditorReplaceLabel: `Byta ut`,
	EditorTemplateContactHint: `<p> med tillgängliga kontakter (kräver en Fetcher -plugin) Detta fält kommer att användas för alla fall av denna mall över detta dokument eller i någon kommer det att hänvisas till senare. </p> <p> så till exempel om du väljer e -postadress Här kommer e -postfältet för kontakten du väljer att användas i alla fall i detta dokument. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kort år <br/> yyyy = långt år <br/> m = månad (1-12) <br/> mm = månad (01-12) <br/> mmm = månadsförkortning (Jan, februari .. . Dec) <br/> mmmm = lång månad (januari, februari ... december) <br/> d = dag (1 - 31) <br/> dd = dag (01 - 31) <br/> ddd = Veckodagen i ord (måndag, tisdag ... söndag) <br/> e = Kort veckodag i ord (mån, tis ... sol) <br/> d - ordinal dag (1: a, 2: a, 3: e, 21, 22: e, 23: e, 31, 4: e ...) <br/> h = timme i AM/PM (0-12) <br/> hh = timme i AM/PM (00-12) <br/ > H = timme i dag (0-23) <br/> hh = timme i dag (00-23) <br/> mm = minut <br/> ss = andra <br/> ss = millisekunder <br/> A = AM/PM -markör <br/> p = a.m./p.m. markör`,
	EditorTemplateDateTimeCustomLabel: `Beställnings`,
	EditorTemplateDateTimeHint: `Det aktuella datumet och/eller tiden kommer att ersättas med DateTime -mallar när de klistras in.`,
	EditorTemplateDateTimeName: `Datum Tid`,
	EditorTemplateDynamicHint: `<p> Alla förekomster i denna mall kommer att använda den medföljande texten. </p>`,
	EditorTemplateDynamicName: `Dynamisk`,
	EditorTemplateEmptyPlaceholder: `{0} är tomt ...`,
	EditorTemplateStaticHint: `<p> Alla förekomster i denna mall kommer att använda den medföljande texten. </p>`,
	EditorTemplateStaticName: `Statisk`,
	EditorTemplateTeaserText: `Mer kommer snart!`,
	EditorWatermark: `Vänta...`,
	EditorWholeWordLabel: ` Hela världen`,
	EditorWrapLabel: ` Vira runt`,

};