var UiStrings = {
	EditorAppendCloseLabel: `ਅਪੀਲ ਨੂੰ ਖਤਮ ਕਰੋ`,
	EditorAppendInlineModeLabel: `ਬਲਾਕ ਨੂੰ ਸਮਰੱਥ ਕਰੋ`,
	EditorAppendLineModeLabel: `ਇਨਲਾਈਨ ਨੂੰ ਸਮਰੱਥ ਕਰੋ`,
	EditorAppendManualModeLabel: `ਟੌਗਲ ਮੈਨੂਅਲ ਬਦਲੋ`,
	EditorAppendNonManualModeLabel: `ਟੌਗਲ ਮੈਨੂਅਲ ਬਦਲੋ`,
	EditorAppendPauseLabel: `ਵਿਰਾਮ ਸ਼ਾਮਲ ਕਰੋ`,
	EditorAppendPostLabel: `ਟੌਗਲ ਪਹਿਲਾਂ`,
	EditorAppendPreLabel: `ਟੌਗਲ ਪਹਿਲਾਂ`,
	EditorAppendResumeLabel: `ਦੁਬਾਰਾ ਪੇਸ਼ ਕਰੋ`,
	EditorBgColorLabel: `ਪਿਛੋਕੜ ਦਾ ਰੰਗ`,
	EditorClearAllLabel: `ਸਾਰਾ ਸਾਫ ਕਰੋ`,
	EditorClipboardFormatsLabel: `ਕਲਿੱਪਬੋਰਡ ਫਾਰਮੈਟ`,
	EditorConfirmNtfTitle: `ਪੁਸ਼ਟੀ ਕਰੋ`,
	EditorDeleteAllButtonText: `ਸਭ ਨੂੰ ਮਿਟਾਓ`,
	EditorDeleteAllTemplatesNtfText: `ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ '{0}' ਦੀਆਂ ਸਾਰੀਆਂ ਵਰਤੋਂਾਂ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?

ਇਸ ਨੂੰ ਵਾਪਸ ਨਹੀ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ!`,
	EditorEditTemplateDetailsLabel: `ਵੇਰਵੇ ਸੋਧੋ`,
	EditorEditTemplateNameLabel: `ਨਾਮ`,
	EditorFindLabel: `ਲੱਭੋ`,
	EditorFontColorLabel: `ਫੋਂਟ ਰੰਗ`,
	EditorFormatPaintLabel: `ਫਾਰਮੈਟ ਪੇਂਟ`,
	EditorInSelectionLabel: ` ਚੋਣ ਵਿੱਚ`,
	EditorInsertImageLabel: `ਚਿੱਤਰ ਸ਼ਾਮਲ ਕਰੋ`,
	EditorInsertLinkLabel: `ਲਿੰਕ ਪਾਓ`,
	EditorInsertVideoLabel: `ਵੀਡੀਓ ਪਾਓ`,
	EditorMatchCaseLabel: ` ਮੈਚ ਕੇਸ`,
	EditorNewTemplateLabel: `ਨਵਾਂ ਟੈਂਪਲੇਟ`,
	EditorNextTemplateLabel: `ਅਗਲਾ ਟੈਂਪਲੇਟ`,
	EditorPasteButtonAppendBeginLabel: `ਜੋੜ ...`,
	EditorPasteButtonLabel: `ਚਿਪਕਾਓ`,
	EditorPasteTemplateWatermark: `ਪੇਸਟ ਟੈਕਸਟ ਦਰਜ ਕਰੋ ...`,
	EditorPrevTemplateLabel: `ਪਿਛਲਾ ਟੈਂਪਲੇਟ`,
	EditorRegExLabel: ` ਨਿਯਮਤ ਸਮੀਕਰਨ`,
	EditorReplaceAllLabel: `ਸਭ ਨੂੰ ਤਬਦੀਲ ਕਰੋ`,
	EditorReplaceLabel: `ਬਦਲੋ`,
	EditorTemplateContactHint: `<p> ਉਪਲਬਧ ਸੰਪਰਕ ਦੀ ਵਰਤੋਂ (ਇੱਕ ਸ਼ਥੇਰ ਪਲੱਗਇਨ ਚਾਹੀਦਾ ਹੈ) ਇਹ ਖੇਤਰ ਇਸ ਟੈਂਪਲੇਟ ਦੇ ਸਾਰੇ ਉਦਾਹਰਣਾਂ ਲਈ ਵਰਤਿਆ ਜਾਏਗਾ ਜਾਂ ਕਿਸੇ ਵੀ ਉਦਾਹਰਣ ਲਈ ਇਸ ਦਾ ਹਵਾਲਾ ਦਿੱਤਾ ਜਾਂਦਾ ਹੈ ਜੇ ਈਮੇਲ ਪਤਾ ਚੁਣੋ ਇੱਥੇ ਇਸ ਦਸਤਾਵੇਜ਼ ਦੇ ਈਮੇਲ ਖੇਤਰ ਦੀ ਚੋਣ ਕਰੋ ਇਸ ਦਸਤਾਵੇਜ਼ ਵਿੱਚ ਸਾਰੇ ਉਦਾਹਰਣਾਂ ਲਈ ਵਰਤੇ ਜਾਣਗੇ. </ P>`,
	EditorTemplateContactName: `ਸੰਪਰਕ`,
	EditorTemplateDateTimeCustomHint: `yy = ਛੋਟਾ ਜਿਹਾ ਸਾਲ <br/> m = ਮਹੀਨਾ (1-12) ਵਾਲਾ (1-12) ਵਾਲਾ (01-12) (01-12) (ਜਨਵਰੀ, ਫਰਵਰੀ) . ਦਸੰਬਰ (> ਐਮਐਮਐਮਐਮ = ਲੰਬਾ ਮਹੀਨਾ (ਜਨਵਰੀ, ਫਰਵਰੀ ... ਦਸੰਬਰ) <br/> dd = 1 - 31) (01 - 31) (01 - 31) (01 - 31) ਹਫ਼ਤੇ ਦਾ ਦਿਨ (ਸੋਮਵਾਰ, ਮੰਗਲਵਾਰ ... ਹਫ਼ਤੇ ਦਾ ਦਿਨ ਦਾ ਦਿਨ ਦਾ ਛੋਟਾ ਦਿਨ) <br/> ਡੀ - ਆਰਗੇਨਲ ਡੇ (1, 2, 2, 3 ਵੇਂ, 21 ਵੇਂ, 22 ਵੇਂ, 31 ਵੇਂ ਨੰਬਰ 'ਤੇ / ਸ਼ਾਮ ਨੂੰ (0-12) / 0-122 ਵਿਚ ਘੰਟਾ = ਸਵੇਰੇ / ਸ਼ਾਮ ਨੂੰ (00-12) <BR / > H = 0-23) ਵਾਲਾ (0-23) ਵਾਲਾ (0-23) / 1 ਘੰਟਾ (00-23) ਏ = am / pm> a.m./p.m. ਮਾਰਕਰ`,
	EditorTemplateDateTimeCustomLabel: `ਪ੍ਰਥਾ`,
	EditorTemplateDateTimeHint: `ਮੌਜੂਦਾ ਤਾਰੀਖ ਅਤੇ / ਜਾਂ / ਜਾਂ ਸਮਾਂ ਤਾਰੀਖ ਦੇ ਟੈਂਪਲੇਟਸ ਲਈ ਬਦਲ ਦਿੱਤਾ ਜਾਵੇਗਾ ਜਦੋਂ ਉਹ ਚਿਪਕ ਜਾਂਦੇ ਹਨ.`,
	EditorTemplateDateTimeName: `ਤਾਰੀਖ ਦਾ ਸਮਾਂ`,
	EditorTemplateDynamicHint: `<p> ਇਸ ਟੈਂਪਲੇਟ ਦੇ ਸਾਰੇ ਅਵਸ਼ੇਸ਼ਾਨੀ ਪਾਠ ਦੀ ਵਰਤੋਂ ਕਰਨਗੇ. </ P>`,
	EditorTemplateDynamicName: `ਗਤੀਸ਼ੀਲ`,
	EditorTemplateEmptyPlaceholder: `{0} ਖਾਲੀ ਹੈ ...`,
	EditorTemplateStaticHint: `<p> ਇਸ ਟੈਂਪਲੇਟ ਦੇ ਸਾਰੇ ਅਵਸ਼ੇਸ਼ਾਨੀ ਪਾਠ ਦੀ ਵਰਤੋਂ ਕਰਨਗੇ. </ P>`,
	EditorTemplateStaticName: `ਸਥਿਰ`,
	EditorTemplateTeaserText: `ਜਲਦੀ ਆ ਰਹੇ ਹੋ!`,
	EditorWatermark: `ਕ੍ਰਿਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...`,
	EditorWholeWordLabel: ` ਪੂਰਾ ਸ਼ਬਦ`,
	EditorWrapLabel: ` ਆਲੇ - ਦੁਆਲੇ ਦੇ ਸਮੇਟਣਾ`,

};