var UiStrings = {
	EditorAppendCloseLabel: `Acaba de afegir`,
	EditorAppendInlineModeLabel: `Activar el bloc`,
	EditorAppendLineModeLabel: `Activa en línia`,
	EditorAppendManualModeLabel: `Manual de commutació`,
	EditorAppendNonManualModeLabel: `Manual de commutació`,
	EditorAppendPauseLabel: `Pausa Append`,
	EditorAppendPostLabel: `Commutació abans`,
	EditorAppendPreLabel: `Commutació abans`,
	EditorAppendResumeLabel: `Reprendre l’append`,
	EditorBgColorLabel: `Color de fons`,
	EditorClearAllLabel: `Esborrar tot`,
	EditorClipboardFormatsLabel: `Formats de porta -retalls`,
	EditorConfirmNtfTitle: `Confirmar`,
	EditorDeleteAllButtonText: `Eliminar tots`,
	EditorDeleteAllTemplatesNtfText: `Esteu segur que voleu eliminar tots els usos de '{0}'?

Això no es pot desfer!`,
	EditorEditTemplateDetailsLabel: `Editeu els detalls`,
	EditorEditTemplateNameLabel: `Nom`,
	EditorFindLabel: `Trobar`,
	EditorFontColorLabel: `Color de la lletra`,
	EditorFormatPaintLabel: `Format de pintura`,
	EditorInSelectionLabel: ` En selecció`,
	EditorInsertImageLabel: `Inseriu la imatge`,
	EditorInsertLinkLabel: `Enllaç d'inserció`,
	EditorInsertVideoLabel: `Inseriu el vídeo`,
	EditorMatchCaseLabel: ` Caixa de coincidència`,
	EditorNewTemplateLabel: `Plantilla nova`,
	EditorNextTemplateLabel: `Plantilla següent`,
	EditorPasteButtonAppendBeginLabel: `Append ...`,
	EditorPasteButtonLabel: `Pastar`,
	EditorPasteTemplateWatermark: `Introduïu el text de pasta ...`,
	EditorPrevTemplateLabel: `Plantilla anterior`,
	EditorRegExLabel: ` Expressió normal`,
	EditorReplaceAllLabel: `Substituïu -ho tot`,
	EditorReplaceLabel: `Tornar a col·locar`,
	EditorTemplateContactHint: `<P> Utilitzant els contactes disponibles (requereix un complement de cercador) Aquest camp s'utilitzarà per a totes les instàncies d'aquesta plantilla a través d'aquest document o en qualsevol que es faci referència a més endavant. </p> <p> Per exemple, per exemple, si seleccioneu l'adreça de correu electrònic A continuació, el camp de correu electrònic del contacte que seleccioneu s'utilitzarà per a totes les instàncies d'aquest document. </p>`,
	EditorTemplateContactName: `Contacte`,
	EditorTemplateDateTimeCustomHint: `yy = any curt <br/> Aaa = llarg any <br/> m = mes (1-12) <br/> mm = mes (01-12) <br/> mmm = abreviació del mes (Jan, febrer .. . Dec) <br/> mmmm = mes llarg (gener, febrer ... desembre) <br/> d = dia (1 - 31) <br/> dd = dia (01 - 31) <br/> ddd = dia de la setmana amb paraules (dilluns, dimarts ... diumenge) <br/> e = curt dia de la setmana en paraules (dilluns ... sol) <br/> d - dia ordinal (1r, 2n, 3r, 21, 22, 23, 31a, 4t ...) <br/> h = hora en am/pm (0-12) <br/> hh = hora en am/pm (00-12) <br/ > H = hora al dia (0-23) <br/> hh = hora al dia (00-23) <br/> mm = minut <br/> ss = segon <br/> sss = mil·lisegons <br/> A = AM/PM marcador <br/> P = A.M./P.M. marcador`,
	EditorTemplateDateTimeCustomLabel: `Costum`,
	EditorTemplateDateTimeHint: `La data i/o hora actuals es substituiran per les plantilles de DateTime quan siguin enganxades.`,
	EditorTemplateDateTimeName: `Data i hora`,
	EditorTemplateDynamicHint: `<p> Totes les ocasions d'aquesta plantilla utilitzaran el text proporcionat. </p>`,
	EditorTemplateDynamicName: `Dinàmic`,
	EditorTemplateEmptyPlaceholder: `{0} està buit ...`,
	EditorTemplateStaticHint: `<p> Totes les ocasions d'aquesta plantilla utilitzaran el text proporcionat. </p>`,
	EditorTemplateStaticName: `Estàtic`,
	EditorTemplateTeaserText: `Aviat, més!`,
	EditorWatermark: `Si us plau, espereu ...`,
	EditorWholeWordLabel: ` Paraula sencera`,
	EditorWrapLabel: ` Embolicar`,

};