var UiStrings = {
	EditorAppendCloseLabel: `Baigti pridėti`,
	EditorAppendInlineModeLabel: `Įgalinti bloką`,
	EditorAppendLineModeLabel: `Įgalinti įterpimą`,
	EditorAppendManualModeLabel: `Perjunkite vadovą`,
	EditorAppendNonManualModeLabel: `Perjunkite vadovą`,
	EditorAppendPauseLabel: `Pauzė priedas`,
	EditorAppendPostLabel: `Perjungti anksčiau`,
	EditorAppendPreLabel: `Perjungti anksčiau`,
	EditorAppendResumeLabel: `Atnaujinti priedą`,
	EditorBgColorLabel: `Fono spalva`,
	EditorClearAllLabel: `Išvalyti viską`,
	EditorClipboardFormatsLabel: `Iškarpų formatai`,
	EditorConfirmNtfTitle: `Patvirtinti`,
	EditorDeleteAllButtonText: `Ištrinti viską`,
	EditorDeleteAllTemplatesNtfText: `Ar tikrai norite ištrinti visus „{0}“ naudojimo būdus?

Tai negali būti panaikinta!`,
	EditorEditTemplateDetailsLabel: `Redaguoti išsamią informaciją`,
	EditorEditTemplateNameLabel: `vardas`,
	EditorFindLabel: `Rasti`,
	EditorFontColorLabel: `Šrifto spalva`,
	EditorFormatPaintLabel: `Formato dažai`,
	EditorInSelectionLabel: ` Atrankoje`,
	EditorInsertImageLabel: `Įterpkite vaizdą`,
	EditorInsertLinkLabel: `Įterpti nuorodą`,
	EditorInsertVideoLabel: `Įterpti vaizdo įrašą`,
	EditorMatchCaseLabel: ` Rungtynių atvejis`,
	EditorNewTemplateLabel: `Naujas šablonas`,
	EditorNextTemplateLabel: `Kitas šablonas`,
	EditorPasteButtonAppendBeginLabel: `Pridėkite ...`,
	EditorPasteButtonLabel: `Įklijuoti`,
	EditorPasteTemplateWatermark: `Įveskite įklijavimo tekstą ...`,
	EditorPrevTemplateLabel: `Ankstesnis šablonas`,
	EditorRegExLabel: ` Įprasta išraiška`,
	EditorReplaceAllLabel: `Pakeiskite visus`,
	EditorReplaceLabel: `Pakeiskite`,
	EditorTemplateContactHint: `<p> Naudojant turimus kontaktus (reikalingas „Fetcher“ papildinys) Šis laukas bus naudojamas visais šio šablono atvejų visame šiame dokumente arba bet kuriame jis bus nurodytas vėliau. </p> <p> Taigi, pavyzdžiui, jei pasirinkite el. Pašto adresą Tuomet jūsų pasirinktas kontakto el. Pašto laukas bus naudojamas visiems šio dokumento egzemplioriams. </p>`,
	EditorTemplateContactName: `kontaktas`,
	EditorTemplateDateTimeCustomHint: `yy = trumpi metai <br/> yyyy = ilgi metai <br/> m = mėnuo (1-12) <br/> mm = mėnuo (01-12) <br/> mmm = mėnesio santrumpos (sausio mėn., Vasario mėn. . Gruodis) <br/> mmmm = ilgas mėnuo (sausis, vasaris ... gruodis) <br/> d = diena (1 - 31) <br/> dd = diena (01 - 31) <br/> ddd = Savaitės diena žodžiais (pirmadienis, antradienis ... sekmadienis) <br/> e = trumpa savaitės diena žodžiais (pirmadienis, antradienis ... saulė) <br/> d - ordino diena (1, 2 -oji, 3, 21, 22, 23, 31, 4 ...) <br/> h = valanda am/pm (0-12) <br/> hh = valanda am/pm (00-12) <br/ > H = valanda dieną (0–23) <br/> hh = valanda dieną (00–23) <br/> mm = minutė <br/> ss = antra <br/> sss = milisekundės <br/> a = am/pm žymeklis <br/> p = a.m./p.m. žymeklis`,
	EditorTemplateDateTimeCustomLabel: `Paprotys`,
	EditorTemplateDateTimeHint: `Dabartinė data ir (arba) laikas bus pakeistas į „Datetime“ šablonus, kai jie bus įklijuojami.`,
	EditorTemplateDateTimeName: `Datos laikas`,
	EditorTemplateDynamicHint: `<p> Visi šio šablono atsiradimai bus naudojami pateiktame tekste. </p>`,
	EditorTemplateDynamicName: `Dinamiškas`,
	EditorTemplateEmptyPlaceholder: `{0} tuščias ...`,
	EditorTemplateStaticHint: `<p> Visi šio šablono atsiradimai bus naudojami pateiktame tekste. </p>`,
	EditorTemplateStaticName: `Statinis`,
	EditorTemplateTeaserText: `Greitai bus daugiau!`,
	EditorWatermark: `Prašau palauk...`,
	EditorWholeWordLabel: ` Visas žodis`,
	EditorWrapLabel: ` Apvynioti`,

};