var UiStrings = {
	EditorAppendCloseLabel: `Anhang beenden`,
	EditorAppendInlineModeLabel: `Block aktivieren`,
	EditorAppendLineModeLabel: `Inline aktivieren`,
	EditorAppendManualModeLabel: `Handbuch umschalten`,
	EditorAppendNonManualModeLabel: `Handbuch umschalten`,
	EditorAppendPauseLabel: `Pause anhängen`,
	EditorAppendPostLabel: `Vorher umschalten`,
	EditorAppendPreLabel: `Vorher umschalten`,
	EditorAppendResumeLabel: `Resume Append`,
	EditorBgColorLabel: `Hintergrundfarbe`,
	EditorClearAllLabel: `Alles löschen`,
	EditorClipboardFormatsLabel: `Zwischenablageformate`,
	EditorConfirmNtfTitle: `Bestätigen`,
	EditorDeleteAllButtonText: `Alles löschen`,
	EditorDeleteAllTemplatesNtfText: `Sind Sie sicher, dass Sie alle Verwendungen von '{0}' löschen möchten?

Das kann nicht rückgängig gemacht werden!`,
	EditorEditTemplateDetailsLabel: `Details bearbeiten`,
	EditorEditTemplateNameLabel: `Name`,
	EditorFindLabel: `Finden`,
	EditorFontColorLabel: `Schriftfarbe`,
	EditorFormatPaintLabel: `Formatfarbe`,
	EditorInSelectionLabel: ` In der Auswahl`,
	EditorInsertImageLabel: `Bild einfügen`,
	EditorInsertLinkLabel: `Link einfügen`,
	EditorInsertVideoLabel: `Video einfügen`,
	EditorMatchCaseLabel: ` Match -Fall`,
	EditorNewTemplateLabel: `Neue Vorlage`,
	EditorNextTemplateLabel: `Nächste Vorlage`,
	EditorPasteButtonAppendBeginLabel: `Anhängen ...`,
	EditorPasteButtonLabel: `Paste`,
	EditorPasteTemplateWatermark: `Eingeben Sie einen Einfügen von Text ...`,
	EditorPrevTemplateLabel: `Vorherige Vorlage`,
	EditorRegExLabel: ` Regulären Ausdruck`,
	EditorReplaceAllLabel: `Alles ersetzen`,
	EditorReplaceLabel: `Ersetzen`,
	EditorTemplateContactHint: `<p> Verwenden der verfügbaren Kontakte (erfordert ein Fetcher -Plugin). Dieses Feld wird für alle Instanzen dieser Vorlage in diesem Dokument oder in einem beliebigen Hinweis auf später verwiesen. Hier wird das E -Mail -Feld des Kontakts, den Sie auswählen, für alle Instanzen in diesem Dokument verwendet. </p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kurzes Jahr <br/> yyyy = langes Jahr <br/> m = Monat (1-12) <br/> mm = Monat (01-12) <br/> mmm = Monat Abkürzung (Jan, Februar. . Dec) <br/> Mmmm = langer Monat (Januar, Februar ... Dezember) <br/> d = Tag (1 - 31) <br/> DD = DAY (01 - 31) <br/> ddd = Tag der Woche in Worten (Montag, Dienstag ... Sonntag) <br/> E = Kurzer Wochentag in Worten (Mon, Di ... Sonne) <br/> d - Ordinaler Tag (1., 2. 3., 21., 22., 23., 31., 4. ...) <br/> H = Stunde in AM/PM (0-12) <br/> HH = Stunde in AM/PM (00-12) <Br/ > H = Stunde im Tag (0-23) <br/> HH = Stunde im Tag (00-23) <br/> mm = Minute <br/> SS = Second <br/> SSS = Milliseconds <br/> a = am/pm Marker <br/> p = a.m./p.m. Marker`,
	EditorTemplateDateTimeCustomLabel: `Brauch`,
	EditorTemplateDateTimeHint: `Das aktuelle Datum und/oder die Uhrzeit werden bei der Einfügung durch Vorlagen für DateTime ersetzt.`,
	EditorTemplateDateTimeName: `Terminzeit`,
	EditorTemplateDynamicHint: `<p> Alle Voraussetzungen dieser Vorlage verwenden den angegebenen Text. </p>`,
	EditorTemplateDynamicName: `Dynamisch`,
	EditorTemplateEmptyPlaceholder: `{0} ist leer ...`,
	EditorTemplateStaticHint: `<p> Alle Voraussetzungen dieser Vorlage verwenden den angegebenen Text. </p>`,
	EditorTemplateStaticName: `Statisch`,
	EditorTemplateTeaserText: `Mehr folgt bald!`,
	EditorWatermark: `Bitte warten...`,
	EditorWholeWordLabel: ` Ganze Welt`,
	EditorWrapLabel: ` Wickeln Sie herum`,

};