var UiStrings = {
	EditorAppendCloseLabel: `Maliza kukabiliana`,
	EditorAppendInlineModeLabel: `Wezesha block`,
	EditorAppendLineModeLabel: `Wezesha inline`,
	EditorAppendManualModeLabel: `Kubadilisha mwongozo`,
	EditorAppendNonManualModeLabel: `Kubadilisha mwongozo`,
	EditorAppendPauseLabel: `Pause append`,
	EditorAppendPostLabel: `Kugeuza kabla`,
	EditorAppendPreLabel: `Kugeuza kabla`,
	EditorAppendResumeLabel: `Anza tena`,
	EditorBgColorLabel: `Rangi ya asili`,
	EditorClearAllLabel: `Futa zote`,
	EditorClipboardFormatsLabel: `Fomati za clipboard`,
	EditorConfirmNtfTitle: `Thibitisha`,
	EditorDeleteAllButtonText: `Futa yote`,
	EditorDeleteAllTemplatesNtfText: `Je! Una uhakika unataka kufuta matumizi yote ya '{0}'?

Hii haiwezi kutekelezwa!`,
	EditorEditTemplateDetailsLabel: `Hariri maelezo`,
	EditorEditTemplateNameLabel: `Jina`,
	EditorFindLabel: `Pata`,
	EditorFontColorLabel: `Rangi ya fonti`,
	EditorFormatPaintLabel: `Rangi ya muundo`,
	EditorInSelectionLabel: ` Katika uteuzi`,
	EditorInsertImageLabel: `Ingiza picha`,
	EditorInsertLinkLabel: `Ingiza kiunga`,
	EditorInsertVideoLabel: `Ingiza video`,
	EditorMatchCaseLabel: ` Kesi ya mechi`,
	EditorNewTemplateLabel: `Template mpya`,
	EditorNextTemplateLabel: `Kiolezo kinachofuata`,
	EditorPasteButtonAppendBeginLabel: `Ongeza ...`,
	EditorPasteButtonLabel: `Bandika`,
	EditorPasteTemplateWatermark: `Ingiza maandishi ...`,
	EditorPrevTemplateLabel: `Kiolezo cha zamani`,
	EditorRegExLabel: ` Kujieleza mara kwa mara`,
	EditorReplaceAllLabel: `Badilisha yote`,
	EditorReplaceLabel: `Badilisha`,
	EditorTemplateContactHint: `<p> Kutumia anwani zinazopatikana (inahitaji programu -jalizi ya Fetcher) uwanja huu utatumika kwa visa vyote vya template hii kwenye hati hii au kwa yoyote itarejelewa baadaye. </p> <p> Kwa mfano ikiwa chagua anwani ya barua pepe Hapa basi uwanja wa barua pepe wa anwani unayochagua utatumika kwa visa vyote kwenye hati hii. </p>`,
	EditorTemplateContactName: `Wasiliana`,
	EditorTemplateDateTimeCustomHint: `YY = mwaka mfupi <br/> yyyy = mwaka mrefu <br/> m = mwezi (1-12) <br/> mm = mwezi (01-12) . DEC) <br/> mmmm = mwezi mrefu (Januari, Februari ... Desemba) <br/> d = siku (1 - 31) Siku ya Wiki kwa maneno (Jumatatu, Jumanne ... Jumapili) <br/> e = siku fupi ya wiki kwa maneno (mon, tue ... jua) <br/> d - siku ya kawaida (1, 2, 3, 21, 22, 23, 31, 4 ...) <br/> h = saa katika am/pm (0-12) > H = saa katika siku (0-23) A = AM/PM alama ya <br/> p = a.m./p.m. alama`,
	EditorTemplateDateTimeCustomLabel: `Desturi`,
	EditorTemplateDateTimeHint: `Tarehe ya sasa na/au wakati itabadilishwa kwa templeti za wakati wa wakati zinapowekwa.`,
	EditorTemplateDateTimeName: `Wakati wa tarehe`,
	EditorTemplateDynamicHint: `<p> Matukio yote ya template hii yatatumia maandishi yaliyotolewa. </p>`,
	EditorTemplateDynamicName: `Nguvu`,
	EditorTemplateEmptyPlaceholder: `{0} haina kitu ...`,
	EditorTemplateStaticHint: `<p> Matukio yote ya template hii yatatumia maandishi yaliyotolewa. </p>`,
	EditorTemplateStaticName: `Tuli`,
	EditorTemplateTeaserText: `Zaidi inakuja hivi karibuni!`,
	EditorWatermark: `Tafadhali subiri...`,
	EditorWholeWordLabel: ` Neno lote`,
	EditorWrapLabel: ` Funga pande zote`,

};