var UiStrings = {
	EditorAppendCloseLabel: `بڑھانا ختم کریں`,
	EditorAppendInlineModeLabel: `بلاک کو فعال کریں`,
	EditorAppendLineModeLabel: `ان لائن کو فعال کریں`,
	EditorAppendManualModeLabel: `ٹوگل دستی`,
	EditorAppendNonManualModeLabel: `ٹوگل دستی`,
	EditorAppendPauseLabel: `روکیں`,
	EditorAppendPostLabel: `اس سے پہلے ٹوگل`,
	EditorAppendPreLabel: `اس سے پہلے ٹوگل`,
	EditorAppendResumeLabel: `دوبارہ شروع کریں`,
	EditorBgColorLabel: `پس منظر کا رنگ`,
	EditorClearAllLabel: `تمام کو صاف کریں`,
	EditorClipboardFormatsLabel: `کلپ بورڈ فارمیٹس`,
	EditorConfirmNtfTitle: `تصدیق کریں`,
	EditorDeleteAllButtonText: `تمام حذف کریں`,
	EditorDeleteAllTemplatesNtfText: `کیا آپ واقعی '{0}' کے تمام استعمال کو حذف کرنا چاہتے ہیں؟

یہ کالعدم نہیں ہوسکتا!`,
	EditorEditTemplateDetailsLabel: `تفصیلات میں ترمیم کریں`,
	EditorEditTemplateNameLabel: `نام`,
	EditorFindLabel: `مل`,
	EditorFontColorLabel: `لکھائی کا رنگ`,
	EditorFormatPaintLabel: `فارمیٹ پینٹ`,
	EditorInSelectionLabel: ` انتخاب میں`,
	EditorInsertImageLabel: `تصویر داخل کریں`,
	EditorInsertLinkLabel: `لنک داخل کریں`,
	EditorInsertVideoLabel: `ویڈیو داخل کریں`,
	EditorMatchCaseLabel: ` میچ کیس`,
	EditorNewTemplateLabel: `نیا ٹیمپلیٹ`,
	EditorNextTemplateLabel: `اگلا ٹیمپلیٹ`,
	EditorPasteButtonAppendBeginLabel: `ضمیمہ ...`,
	EditorPasteButtonLabel: `چسپاں کریں`,
	EditorPasteTemplateWatermark: `پیسٹ متن درج کریں ...`,
	EditorPrevTemplateLabel: `پچھلا ٹیمپلیٹ`,
	EditorRegExLabel: ` باقاعدہ اظہار`,
	EditorReplaceAllLabel: `سب کو تبدیل کریں`,
	EditorReplaceLabel: `تبدیل کریں`,
	EditorTemplateContactHint: `<p> دستیاب رابطوں کا استعمال کرتے ہوئے (فیچر پلگ ان کی ضرورت ہوتی ہے) اس فیلڈ کو اس دستاویز کے اس ٹیمپلیٹ کی تمام مثالوں کے لئے استعمال کیا جائے گا یا کسی بھی میں اس کا بعد میں حوالہ دیا جائے گا۔ </p> <p> لہذا مثال کے طور پر اگر ای میل ایڈریس منتخب کریں تو یہاں پھر آپ کے منتخب کردہ رابطے کا ای میل فیلڈ اس دستاویز میں موجود تمام مثالوں کے لئے استعمال ہوگا۔ </p>`,
	EditorTemplateContactName: `رابطہ کریں`,
	EditorTemplateDateTimeCustomHint: `yy = مختصر سال <br/> yyyy = لمبا سال <br/> m = مہینہ (1-12) <br/> ملی میٹر = مہینہ (01-12) <br/> ایم ایم ایم = ماہ کا خلاصہ (جنوری ، فروری .. . دسمبر) <br/> ایم ایم ایم = طویل مہینہ (جنوری ، فروری ... دسمبر) <br/> ڈی = دن (1 - 31) <br/> ڈی ڈی = دن (01 - 31) الفاظ میں ہفتے کا دن (پیر ، منگل ... اتوار) <br/> ای = ہفتہ کا مختصر دن الفاظ میں (پیر ، منگل ... سن) <br/> ڈی - عام دن (پہلا ، دوسرا ، تیسرا ، 21 ویں ، 22 ویں ، 23 ویں ، 31 ویں ، چوتھا ...) <br/> h = AM/PM میں گھنٹہ (0-12) > H = دن میں گھنٹہ (0-23) <br/> HH = دن میں گھنٹہ (00-23) A = am/pm مارکر <br/> p = a.m./p.m. مارکر`,
	EditorTemplateDateTimeCustomLabel: `اپنی مرضی کے مطابق`,
	EditorTemplateDateTimeHint: `موجودہ تاریخ اور/یا وقت کو پیسٹ کیا جائے گا جب ڈیٹ ٹائم ٹیمپلیٹس کے لئے تبدیل کیا جائے گا۔`,
	EditorTemplateDateTimeName: `تاریخ وقت`,
	EditorTemplateDynamicHint: `<p> اس ٹیمپلیٹ کے تمام واقعات فراہم کردہ متن کو استعمال کریں گے۔ </p>`,
	EditorTemplateDynamicName: `متحرک`,
	EditorTemplateEmptyPlaceholder: `{0} خالی ہے ...`,
	EditorTemplateStaticHint: `<p> اس ٹیمپلیٹ کے تمام واقعات فراہم کردہ متن کو استعمال کریں گے۔ </p>`,
	EditorTemplateStaticName: `جامد`,
	EditorTemplateTeaserText: `مزید جلد آرہا ہے!`,
	EditorWatermark: `برائے مہربانی انتظار کریں...`,
	EditorWholeWordLabel: ` پورا لفظ`,
	EditorWrapLabel: ` ارد گرد لپیٹنا`,

};