var UiStrings = {
	EditorAppendCloseLabel: `Zaključek doda`,
	EditorAppendInlineModeLabel: `Omogoči blok`,
	EditorAppendLineModeLabel: `Omogoči inline`,
	EditorAppendManualModeLabel: `Preklopni priročnik`,
	EditorAppendNonManualModeLabel: `Preklopni priročnik`,
	EditorAppendPauseLabel: `Premor dodatka`,
	EditorAppendPostLabel: `Preklopite prej`,
	EditorAppendPreLabel: `Preklopite prej`,
	EditorAppendResumeLabel: `Življenjepis`,
	EditorBgColorLabel: `Barva ozadja`,
	EditorClearAllLabel: `Počisti vse`,
	EditorClipboardFormatsLabel: `Obloge`,
	EditorColorChooserTitle: `Barva urejevalnika`,
	EditorConfirmNtfTitle: `Potrdite`,
	EditorDeleteAllButtonText: `Izbriši vse`,
	EditorDeleteAllTemplatesNtfText: `Ali ste prepričani, da želite izbrisati vse navade '{0}'?

Tega ni mogoče razveljaviti!`,
	EditorEditTemplateDetailsLabel: `Uredi podrobnosti`,
	EditorEditTemplateNameLabel: `Ime`,
	EditorFindLabel: `Najti`,
	EditorFontColorLabel: `Barva pisave`,
	EditorFormatPaintLabel: `Oblika barve`,
	EditorInSelectionLabel: ` V izbiri`,
	EditorInsertImageLabel: `Vstavite sliko`,
	EditorInsertLinkLabel: `Vstavi povezavo`,
	EditorInsertVideoLabel: `Vstavite video`,
	EditorLinkButtonText: `Shrani`,
	EditorLinkLabel: `Vnesite povezavo`,
	EditorLinkPlaceholder: `Vnesite URL`,
	EditorMatchCaseLabel: ` Primer`,
	EditorNewTemplateLabel: `Nova predloga`,
	EditorNextTemplateLabel: `Naslednja predloga`,
	EditorPasteButtonAppendBeginLabel: `Dodatek ...`,
	EditorPasteButtonLabel: `Prilepi`,
	EditorPasteButtonLabelMobile: `Kopirati`,
	EditorPasteTemplateWatermark: `Vnesite besedilo paste ...`,
	EditorPrevTemplateLabel: `Prejšnja predloga`,
	EditorRegExLabel: ` Vsakdanje izražanje`,
	EditorReplaceAllLabel: `Zamenjajte vse`,
	EditorReplaceLabel: `Zamenjati`,
	EditorTemplateContactHint: `<p>Z uporabo stikov, ki so na voljo (zahteva vtičnik za fetcher), bo to polje uporabljeno za vse primerke te predloge v tem dokumentu ali v katerem koli drugem dokumentu, na katerega se boste sklicevali pozneje.</p><p> Torej, na primer, če tukaj izberete e-poštni naslov, bo e-poštno polje stika, ki ga izberete, uporabljeno za vse primerke v tem dokumentu.</p>`,
	EditorTemplateContactName: `Stik`,
	EditorTemplateDateTimeCustomHint: `yy = kratko leto<br/>llll = dolgo leto<br/>M = mesec (1-12)<br/>MM = mesec (01-12)<br/>MMM = mesečna okrajšava (januar, februar ... December)<br/>MMMM = dolg mesec (januar, februar ... decembra)<br/>d = dan (1 - 31)<br/>dd = dan (01 - 31)<br/>ddd = dan v tednu z besedami (ponedeljek, torek ... nedelja)<br/>E = kratek dan v tednu z besedami (pon, tor ... Sonce)<br/>D - Ordinalni dan (1., 2., 3., 21., 22., 23., 31., 4....)<br/>h = ura v am/pm (0-12)<br/>hh = ura v am/pm (00-12)<br/>H = ura na dan (0-23)<br/>HH = ura na dan (00-23)<br/>mm = minuta<br/>ss = sekunda<br/>SSS = milisekunde<br/>a = oznaka AM/PM<br/>p = oznaka a.m./p.m.`,
	EditorTemplateDateTimeCustomLabel: `Navada`,
	EditorTemplateDateTimeHint: `Trenutni datum in/ali čas bosta nadomeščena za predloge DateTime, ko jih prilepijo.`,
	EditorTemplateDateTimeName: `Datum čas`,
	EditorTemplateDynamicHint: `<p>Pri vseh dogodkih te predloge bo uporabljeno navedeno besedilo.</p>`,
	EditorTemplateDynamicName: `Dinamično`,
	EditorTemplateEmptyPlaceholder: `{0} je prazen ...`,
	EditorTemplateStaticHint: `<p>Pri vseh dogodkih te predloge bo uporabljeno navedeno besedilo.</p>`,
	EditorTemplateStaticName: `Statična`,
	EditorTemplateTeaserText: `Kmalu pride še več!`,
	EditorTt1: `Klik`,
	EditorTt2: `Uredi '<em> {0} </em>' ...`,
	EditorTt3: `Uredi barvo ...`,
	EditorTt4: `odstrani '<em> {0} </em>' ...`,
	EditorTt5: `odstranite element`,
	EditorTt6: `slediti ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Prosim počakaj...`,
	EditorWholeWordLabel: ` Celotna beseda`,
	EditorWrapLabel: ` Ovijte okoli`,

};