var UiStrings = {
	EditorAppendCloseLabel: `മികച്ചത് പൂർത്തിയാക്കുക`,
	EditorAppendInlineModeLabel: `തടക്കുക പ്രാപ്തമാക്കുക`,
	EditorAppendLineModeLabel: `ഇൻലൈൻ പ്രാപ്തമാക്കുക`,
	EditorAppendManualModeLabel: `മാവൽ ടോഗിൾ ചെയ്യുക`,
	EditorAppendNonManualModeLabel: `മാവൽ ടോഗിൾ ചെയ്യുക`,
	EditorAppendPauseLabel: `താൽക്കാലികമായ കൂട്ടിച്ചേർക്കൽ`,
	EditorAppendPostLabel: `മുമ്പ് ടോഗിൾ ചെയ്യുക`,
	EditorAppendPreLabel: `മുമ്പ് ടോഗിൾ ചെയ്യുക`,
	EditorAppendResumeLabel: `പുനരാരംഭിക്കുക കൂട്ടിച്ചേർക്കുക`,
	EditorBgColorLabel: `പശ്ചാത്തല നിറം`,
	EditorClearAllLabel: `എല്ലാം മായ്ക്കുക`,
	EditorClipboardFormatsLabel: `ക്ലിപ്പ്ബോർഡ് ഫോർമാറ്റുകൾ`,
	EditorColorChooserTitle: `എഡിറ്റർ നിറം`,
	EditorConfirmNtfTitle: `ഉറപ്പിക്കുക`,
	EditorDeleteAllButtonText: `എല്ലാം ഇല്ലാതാക്കുക`,
	EditorDeleteAllTemplatesNtfText: `'{0}' ന്റെ എല്ലാ ഉപയോഗങ്ങളും ഇല്ലാതാക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?

ഇത് പഴയപടിയാക്കാൻ കഴിയില്ല!`,
	EditorEditTemplateDetailsLabel: `വിശദാംശങ്ങൾ എഡിറ്റുചെയ്യുക`,
	EditorEditTemplateNameLabel: `പേര്`,
	EditorFindLabel: `കണ്ടെത്തുക`,
	EditorFontColorLabel: `അക്ഷരത്തിന്റെ നിറം`,
	EditorFormatPaintLabel: `ഫോർമാറ്റ് പെയിന്റ്`,
	EditorInSelectionLabel: ` തിരഞ്ഞെടുക്കലിൽ`,
	EditorInsertImageLabel: `ചിത്രം ചേർക്കുക`,
	EditorInsertLinkLabel: `ലിങ്ക് ചേർക്കുക`,
	EditorInsertVideoLabel: `വീഡിയോ ചേർക്കുക`,
	EditorLinkButtonText: `രക്ഷിക്കും`,
	EditorLinkLabel: `ലിങ്ക് നൽകുക`,
	EditorLinkPlaceholder: `URL നൽകുക`,
	EditorMatchCaseLabel: ` പൊരുത്തക്കേടുകൾ`,
	EditorNewTemplateLabel: `പുതിയ ടെംപ്ലേറ്റ്`,
	EditorNextTemplateLabel: `അടുത്ത ടെംപ്ലേറ്റ്`,
	EditorPasteButtonAppendBeginLabel: `കൂട്ടിച്ചേർക്കുക ...`,
	EditorPasteButtonLabel: `പേസ്റ്റ്`,
	EditorPasteButtonLabelMobile: `പകര്ത്തുക`,
	EditorPasteTemplateWatermark: `ഒട്ടിക്കുക വാചകം നൽകുക ...`,
	EditorPrevTemplateLabel: `മുമ്പത്തെ ടെംപ്ലേറ്റ്`,
	EditorRegExLabel: ` പതിവ് എക്സ്പ്രഷൻ`,
	EditorReplaceAllLabel: `എല്ലാം മാറ്റിസ്ഥാപിക്കുക`,
	EditorReplaceLabel: `തിരികെവയ്ക്കുക`,
	EditorTemplateContactHint: `<p>ലഭ്യമായ കോൺടാക്റ്റുകൾ ഉപയോഗിച്ച് (ഒരു ഫെറ്റർ പ്ലഗിൻ ആവശ്യമാണ്) ഈ ഡോക്യുമെന്റിലുടനീളം ഈ ടെംപ്ലേറ്റിന്റെ എല്ലാ സന്ദർഭങ്ങൾക്കും ഈ ഫീൽഡ് ഉപയോഗിക്കും അല്ലെങ്കിൽ ഏതെങ്കിലും ഒന്നിൽ ഇത് പിന്നീട് പരാമർശിക്കപ്പെടും.</p><p> ഉദാഹരണത്തിന് ഇവിടെ ഇമെയിൽ വിലാസം തിരഞ്ഞെടുക്കുകയാണെങ്കിൽ, നിങ്ങൾ തിരഞ്ഞെടുക്കുന്ന കോൺടാക്റ്റിന്റെ ഇമെയിൽ ഫീൽഡ് ഈ ഡോക്യുമെന്റിലെ എല്ലാ സന്ദർഭങ്ങൾക്കും ഉപയോഗിക്കും.</p>`,
	EditorTemplateContactName: `സന്വര്ക്കം`,
	EditorTemplateDateTimeCustomHint: `yy = ഹ്രസ്വ വർഷം<br/>yyyy = നീണ്ട വർഷം<br/>M = മാസം (1-12)<br/>MM = മാസം (01-12)<br/>MMM = മാസത്തിന്റെ ചുരുക്കെഴുത്ത് (ജനുവരി, ഫെബ്രുവരി ... ഡിസംബര് )<br/>MMMM = നീണ്ട മാസം (ജനുവരി, ഫെബ്രുവരി ... ഡിസംബര് )<br/>d = ദിവസം (1 - 31)<br/>dd = ദിവസം (01 - 31)<br/>ddd = വാക്കുകളിൽ ആഴ്ചയിലെ ദിവസം (തിങ്കൾ, ചൊവ്വാഴ്ച ... ഞായറാഴ്ച)<br/>E = വാക്കുകളിൽ ആഴ്ചയിലെ ഹ്രസ്വ ദിവസം (മോൺ, ചൊവ്വ ... സൂര്യൻ)<br/>D - ഓർഡിനൽ ദിവസം (1st, 2, 3rd, 21st, 22, 23, 31st, 4th...)<br/>h = am/pm (0-12)<br/>hh = am/pm -ൽ മണിക്കൂർ (00-12)<br/>H = ദിവസത്തിൽ മണിക്കൂർ (0-23)<br/>HH = ദിവസത്തിൽ മണിക്കൂർ (00-23)<br/>mm = മിനിറ്റ്<br/>ss = second<br/>SSS = milliseconds<br/>a = AM/PM മാർക്കർ<br/>p = a.m./p.m. മാർക്കർ`,
	EditorTemplateDateTimeCustomLabel: `സന്വദായം`,
	EditorTemplateDateTimeHint: `നിലവിലെ തീയതിയും കൂടാതെ / അല്ലെങ്കിൽ സമയവും ഡേറ്റ്ടൈം ടെംപ്ലേറ്റുകൾക്ക് പകരമായി സജ്ജമാക്കും.`,
	EditorTemplateDateTimeName: `തീയതി സമയം`,
	EditorTemplateDynamicHint: `<p>ഈ ടെംപ്ലേറ്റിന്റെ എല്ലാ സംഭവങ്ങളും നൽകിയ വാചകം ഉപയോഗിക്കും.</p>`,
	EditorTemplateDynamicName: `ചലനാത്മക`,
	EditorTemplateEmptyPlaceholder: `{0} ശൂന്യമാണ് ...`,
	EditorTemplateStaticHint: `<p>ഈ ടെംപ്ലേറ്റിന്റെ എല്ലാ സംഭവങ്ങളും നൽകിയ വാചകം ഉപയോഗിക്കും.</p>`,
	EditorTemplateStaticName: `സ്ഥിതിവിവരകം`,
	EditorTemplateTeaserText: `കൂടുതൽ ഉടനെ വരും!`,
	EditorTt1: `ക്ലിക്കുചെയ്യുക`,
	EditorTt2: `എഡിറ്റുചെയ്യുക '<em> {0 {0} </ em>' ...`,
	EditorTt3: `നിറം എഡിറ്റുചെയ്യുക ...`,
	EditorTt4: `'<em> {0 {0 {0 {0 {0} </ em>' നീക്കംചെയ്യുക.`,
	EditorTt5: `ഇനം നീക്കംചെയ്യുക`,
	EditorTt6: `പിന്തുടരാൻ ...`,
	EditorTt7: `goto '<em> {0 {0 {0} </ em>' ...`,
	EditorWatermark: `കാത്തിരിക്കൂ...`,
	EditorWholeWordLabel: ` മുഴുവൻ വാക്ക്`,
	EditorWrapLabel: ` ചുറ്റും പൊതിയുക`,

};