var UiStrings = {
	EditorAppendCloseLabel: `Дуусгах ажлыг дуусгах`,
	EditorAppendInlineModeLabel: `Блок идэвхжүүлэх`,
	EditorAppendLineModeLabel: `Доторыг идэвхжүүлэх`,
	EditorAppendManualModeLabel: `Гарын авлага`,
	EditorAppendNonManualModeLabel: `Гарын авлага`,
	EditorAppendPauseLabel: `Түр зогсоох`,
	EditorAppendPostLabel: `Өмнө нь сэлгэх`,
	EditorAppendPreLabel: `Өмнө нь сэлгэх`,
	EditorAppendResumeLabel: `ҮЙЛЧИЛГЭЭНИЙ ТӨЛӨВЛӨГӨӨ`,
	EditorBgColorLabel: `Дэвсгэр өнгө`,
	EditorClearAllLabel: `Бүгдийг цэвэрлэ`,
	EditorClipboardFormatsLabel: `Хяналтын самбарын форматууд`,
	EditorConfirmNtfTitle: `Батлах`,
	EditorDeleteAllButtonText: `Бүгдийг устгах`,
	EditorDeleteAllTemplatesNtfText: `Та '{0}' хэрэглээг устгахыг хүсч байна уу?

Энэ буцаах боломжгүй!`,
	EditorEditTemplateDetailsLabel: `Дэлгэрэнгүй чиглүүлэх`,
	EditorEditTemplateNameLabel: `Нэр`,
	EditorFindLabel: `Илрүүлэх`,
	EditorFontColorLabel: `Үсгийн өнгө`,
	EditorFormatPaintLabel: `Автомат чанар`,
	EditorInSelectionLabel: ` Сонгон шалгаруулах`,
	EditorInsertImageLabel: `Зураг оруулах`,
	EditorInsertLinkLabel: `Холбоос суулгах`,
	EditorInsertVideoLabel: `Судлах`,
	EditorMatchCaseLabel: ` Тохируулгын хэрэг`,
	EditorNewTemplateLabel: `Шинэ загвар`,
	EditorNextTemplateLabel: `Дараагийн загвар`,
	EditorPasteButtonAppendBeginLabel: `Нэмэх ...`,
	EditorPasteButtonLabel: `Товч`,
	EditorPasteTemplateWatermark: `Буулгах текстийг оруулна уу ...`,
	EditorPrevTemplateLabel: `Өмнөх загвар`,
	EditorRegExLabel: ` Тогтмол илэрхийлэл`,
	EditorReplaceAllLabel: `Бүгдийг орлуулаарай`,
	EditorReplaceLabel: `Буцааж тавих`,
	EditorTemplateContactHint: `<p> Боломжтой холбоо барих хаягийг ашиглах (Fetcher Plugnate-ийг энэ баримтад эсвэл энэ загварыг ашиглахад шаардлагатай бүх загварыг ашиглана. Энд, дараа нь таны сонгосон харилцагчийн талбарыг энд оруулсан холбоо барих талбарт энэ баримт бичигт бүх тохиолдлуудад ашиглагдах болно. </ p>`,
	EditorTemplateContactName: `Харилцах`,
	EditorTemplateDateTimeCustomHint: `YY = Богино жил <br/> yyyy yyyy = londy = 'MM = СУРГУУЛЬ <ТОГЛОЛТ (1-р сар) <br/> MM = СУРГУУЛЬ (012) <bm/> MM = СУРГУУЛЬ (1-р сар) <br/> mm = сар (1-р сар) <br/> MM = СУРГУУЛЬ (01-2) <br/> MM (1-р сар) <br/> mm = сар (1-р сар) <br/> MM = СУРГУУЛЬ (012) Байна. 12-р сар) <br/> mmmm = урт сар (1-р сар) <br/> D = 12-р сар (1-р сар) <br/1-21-р сар (0 - 31) <br/ 31) <br/ 31) <br/1 - 01 - 01) <br/ 31-р сарууд Долоо хоногийн өдөр (Даваа, Мягмар, Мягмар, Мягмар гараг) <bre, Tue ... SUN, TUE DOUNTER DOUNTON-д ҮНЭГҮЙ (Ням гараг) 3, 21-р, 22-р, 22-р 2, 23-р сар, 4-р сарын 4-ний өдөр. > H = Өдөрт (0-23) <br/> hh => mm => <br/> ss = ss => ss = sss = sss = sss = mildiseconds = Millisecods = Milliseconds = Milliseconds = Millisecons <brisecons <briancons <brisecons <brisecons <brisecons <brisecons <brisects <briancons <briancons <briancoads <brisecons <brisecons <briancons = ' A = = AM / PM MAPER <br/> P = A.M./P.A. Зиль`,
	EditorTemplateDateTimeCustomLabel: `Ес заншил`,
	EditorTemplateDateTimeHint: `Одоогийн огноо ба / эсвэл цаг хугацааг буулгах үед DateTime загварыг орлуулах болно.`,
	EditorTemplateDateTimeName: `Он сар өдөр цаг`,
	EditorTemplateDynamicHint: `<p> Энэ загваруудын бүх тохиолдол нь өгсөн текстийг ашиглах болно. </ p>`,
	EditorTemplateDynamicName: `Динамик`,
	EditorTemplateEmptyPlaceholder: `{0} хоосон байна ...`,
	EditorTemplateStaticHint: `<p> Энэ загваруудын бүх тохиолдол нь өгсөн текстийг ашиглах болно. </ p>`,
	EditorTemplateStaticName: `Стобик`,
	EditorTemplateTeaserText: `Илүү удахгүй ирэх болно!`,
	EditorWatermark: `Түр хүлээнэ үү ...`,
	EditorWholeWordLabel: ` Бүхэл үг`,
	EditorWrapLabel: ` Эргэн тойронд ороосон`,

};