var UiStrings = {
	EditorAppendCloseLabel: `Fullfør å legge til`,
	EditorAppendInlineModeLabel: `Aktiver blokkering`,
	EditorAppendLineModeLabel: `Aktiver inline`,
	EditorAppendManualModeLabel: `Vekslehåndbok`,
	EditorAppendNonManualModeLabel: `Vekslehåndbok`,
	EditorAppendPauseLabel: `Pause vedlegg`,
	EditorAppendPostLabel: `Veksle før`,
	EditorAppendPreLabel: `Veksle før`,
	EditorAppendResumeLabel: `Fortsett vedlegg`,
	EditorBgColorLabel: `Bakgrunnsfarge`,
	EditorClearAllLabel: `Rydd alt`,
	EditorClipboardFormatsLabel: `Utklippstavleformater`,
	EditorColorChooserTitle: `Redaktørfarge`,
	EditorConfirmNtfTitle: `Bekrefte`,
	EditorDeleteAllButtonText: `Slette alle`,
	EditorDeleteAllTemplatesNtfText: `Er du sikker på at du vil slette alle bruksområder av '{0}'?

Dette kan ikke angres!`,
	EditorEditTemplateDetailsLabel: `Rediger detaljer`,
	EditorEditTemplateNameLabel: `Navn`,
	EditorFindLabel: `Finne`,
	EditorFontColorLabel: `Skriftfarge`,
	EditorFormatPaintLabel: `Formatmaling`,
	EditorInSelectionLabel: ` I utvalg`,
	EditorInsertImageLabel: `Sett inn bilde`,
	EditorInsertLinkLabel: `Sett inn lenken`,
	EditorInsertVideoLabel: `Sett inn video`,
	EditorLinkButtonText: `Lagre`,
	EditorLinkLabel: `Skriv inn lenken`,
	EditorLinkPlaceholder: `Skriv inn URL`,
	EditorMatchCaseLabel: ` Match -sak`,
	EditorNewTemplateLabel: `Ny mal`,
	EditorNextTemplateLabel: `Neste mal`,
	EditorPasteButtonAppendBeginLabel: `Legg til ...`,
	EditorPasteButtonLabel: `Lim inn`,
	EditorPasteTemplateWatermark: `Skriv inn limtekst ...`,
	EditorPrevTemplateLabel: `Forrige mal`,
	EditorRegExLabel: ` Vanlig uttrykk`,
	EditorReplaceAllLabel: `Erstatt alle`,
	EditorReplaceLabel: `Erstatte`,
	EditorTemplateContactHint: `<p>Ved hjelp av tilgjengelige kontakter (krever en plugin-modul for henteren) vil dette feltet bli brukt for alle forekomster av denne malen på tvers av dette dokumentet, eller i alle tilfeller det vil bli referert til senere.</p><p> Så hvis du for eksempel velger e-postadresse her, vil e-postfeltet til kontakten du velger, bli brukt for alle forekomster i dette dokumentet.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kort år<br/>åååå = langt år<br/>M = måned (1-12)<br/>MM = måned (01-12)<br/>MMM = måned forkortelse (jan, feb ... desember)<br/>MMMM = lang måned (januar, februar ... desember)<br/>d = dag (1 - 31)<br/>dd = dag (01 - 31)<br/>ddd = ukedag i ord (mandag, tirsdag ... Søndag)<br/>E = kort dag i uken i ord (man, ti ... Sol)<br/>D - Ordinær dag (1., 2., 3., 21., 22., 23., 31., 4. ...)<br/>h = time i am/pm (0-12)<br/>hh = time i am/pm (00-12)<br/>H = time i døgn (0-23)<br/>HH = time i døgnet (00-23)<br/>mm = minutt<br/>ss = andre<br/>SSS = millisekunder<br/>a = AM/PM-markør<br/>p = a.m./p.m. markør`,
	EditorTemplateDateTimeCustomLabel: `Tilpasset`,
	EditorTemplateDateTimeHint: `Gjeldende dato og/eller tid vil bli erstattet av datetime -maler når de limes inn.`,
	EditorTemplateDateTimeName: `Dato tid`,
	EditorTemplateDynamicHint: `<p>Alle forekomster av denne malen vil bruke den angitte teksten.</p>`,
	EditorTemplateDynamicName: `Dynamisk`,
	EditorTemplateEmptyPlaceholder: `{0} er tom ...`,
	EditorTemplateStaticHint: `<p>Alle forekomster av denne malen vil bruke den angitte teksten.</p>`,
	EditorTemplateStaticName: `Statisk`,
	EditorTemplateTeaserText: `Mer kommer snart!`,
	EditorTt1: `Klikk`,
	EditorTt2: `Rediger '<em> {0} </em>' ...`,
	EditorTt3: `Rediger farge ...`,
	EditorTt4: `Fjern '<em> {0} </em>' ...`,
	EditorTt5: `fjerne gjenstand`,
	EditorTt6: `å følge ...`,
	EditorTt7: `goto '<em> {0} </em>' ...`,
	EditorWatermark: `Vennligst vent...`,
	EditorWholeWordLabel: ` Hele verden`,
	EditorWrapLabel: ` Pakk rundt`,

};