var UiStrings = {
	EditorAppendCloseLabel: `Afslut at tilføje`,
	EditorAppendInlineModeLabel: `Aktivér blok`,
	EditorAppendLineModeLabel: `Aktivér inline`,
	EditorAppendManualModeLabel: `Skift manual`,
	EditorAppendNonManualModeLabel: `Skift manual`,
	EditorAppendPauseLabel: `Pause Tilføj`,
	EditorAppendPostLabel: `Skift før`,
	EditorAppendPreLabel: `Skift før`,
	EditorAppendResumeLabel: `Genoptag tilføj`,
	EditorBgColorLabel: `Baggrundsfarve`,
	EditorClearAllLabel: `Slet alt`,
	EditorClipboardFormatsLabel: `Clipboard -formater`,
	EditorColorChooserTitle: `Redaktørens farve`,
	EditorConfirmNtfTitle: `Bekræfte`,
	EditorDeleteAllButtonText: `Slet alt`,
	EditorDeleteAllTemplatesNtfText: `Er du sikker på, at du vil slette alle anvendelser af '{0}'?

Dette kan ikke fortrydes!`,
	EditorEditTemplateDetailsLabel: `Rediger detaljer`,
	EditorEditTemplateNameLabel: `Navn`,
	EditorFindLabel: `Find`,
	EditorFontColorLabel: `Skrift farve`,
	EditorFormatPaintLabel: `Formatmaling`,
	EditorInSelectionLabel: ` I udvælgelse`,
	EditorInsertImageLabel: `Indsæt billede`,
	EditorInsertLinkLabel: `Indsæt link`,
	EditorInsertVideoLabel: `Indsæt video`,
	EditorLinkButtonText: `Gemme`,
	EditorLinkLabel: `Indtast link`,
	EditorLinkPlaceholder: `Indtast URL`,
	EditorMatchCaseLabel: ` Match -sag`,
	EditorNewTemplateLabel: `Ny skabelon`,
	EditorNextTemplateLabel: `Næste skabelon`,
	EditorPasteButtonAppendBeginLabel: `Tilføj...`,
	EditorPasteButtonLabel: `sæt ind`,
	EditorPasteTemplateWatermark: `Indtast pastatekst ...`,
	EditorPrevTemplateLabel: `Tidligere skabelon`,
	EditorRegExLabel: ` Almindelig udtryk`,
	EditorReplaceAllLabel: `Udskift alle`,
	EditorReplaceLabel: `Erstatte`,
	EditorTemplateContactHint: `<p>Ved hjælp af tilgængelige kontakter (kræver et hentningsplugin) vil dette felt blive brugt til alle forekomster af denne skabelon på tværs af dette dokument eller i nogen, der vil blive refereret til senere.</p><p> Så hvis du f.eks. vælger e-mail-adresse her, vil e-mail-feltet for den kontakt, du vælger, blive brugt til alle forekomster i dette dokument.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kort år<br/>åååå = langt år<br/>M = måned (1-12)<br/>MM = måned (01-12)<br/>MMM = måned forkortelse (Jan, Feb ... dec)<br/>MMMM = lang måned (januar, februar ... December)<br/>d = dag (1 - 31)<br/>dd = dag (01 - 31)<br/>ddd = ugedag i ord (mandag, tirsdag ... Søndag)<br/>E = kort ugedag i ord (man, tirs ... søn)<br/>D - Ordinær dag (1., 2., 3., 21., 22., 23., 31., 4....)<br/>h = time i am/pm (0-12)<br/>hh = time i am/pm (00-12)<br/>H = time i dag (0-23)<br/>HH = time i døgnet (00-23)<br/>mm = minut<br/>ss = sekund<br/>SSS = millisekunder<br/>a = AM/PM markør<br/>p = a.m./p.m. markør`,
	EditorTemplateDateTimeCustomLabel: `Brugerdefinerede`,
	EditorTemplateDateTimeHint: `Den aktuelle dato og/eller tiden erstattes af DateTime -skabeloner, når de indsættes.`,
	EditorTemplateDateTimeName: `Dato tid`,
	EditorTemplateDynamicHint: `<p>Alle forekomster af denne skabelon bruger den medfølgende tekst.</p>`,
	EditorTemplateDynamicName: `Dynamisk`,
	EditorTemplateEmptyPlaceholder: `{0} er tom ...`,
	EditorTemplateStaticHint: `<p>Alle forekomster af denne skabelon bruger den medfølgende tekst.</p>`,
	EditorTemplateStaticName: `Statisk`,
	EditorTemplateTeaserText: `Flere kommer snart!`,
	EditorTt1: `Klik`,
	EditorTt2: `rediger "<em>{0}</em>" ...`,
	EditorTt3: `rediger farve...`,
	EditorTt4: `fjern '<em>{0}</em>'...`,
	EditorTt5: `fjerne varen`,
	EditorTt6: `at følge ...`,
	EditorTt7: `gå til '<em>{0}</em>' ...`,
	EditorWatermark: `Vent venligst...`,
	EditorWholeWordLabel: ` Hele ord`,
	EditorWrapLabel: ` Vikle om`,

};