var UiStrings = {
	EditorAppendCloseLabel: `Anhang beenden`,
	EditorAppendInlineModeLabel: `Block aktivieren`,
	EditorAppendLineModeLabel: `Inline aktivieren`,
	EditorAppendManualModeLabel: `Handbuch umschalten`,
	EditorAppendNonManualModeLabel: `Handbuch umschalten`,
	EditorAppendPauseLabel: `Pause anhängen`,
	EditorAppendPostLabel: `Vorher umschalten`,
	EditorAppendPreLabel: `Vorher umschalten`,
	EditorAppendResumeLabel: `Resume Append`,
	EditorBgColorLabel: `Hintergrundfarbe`,
	EditorClearAllLabel: `Alles löschen`,
	EditorClipboardFormatsLabel: `Zwischenablageformate`,
	EditorColorChooserTitle: `Editorfarbe`,
	EditorConfirmNtfTitle: `Bestätigen`,
	EditorDeleteAllButtonText: `Alles löschen`,
	EditorDeleteAllTemplatesNtfText: `Sind Sie sicher, dass Sie alle Verwendungen von '{0}' löschen möchten?

Das kann nicht rückgängig gemacht werden!`,
	EditorEditTemplateDetailsLabel: `Details bearbeiten`,
	EditorEditTemplateNameLabel: `Name`,
	EditorFindLabel: `Finden`,
	EditorFontColorLabel: `Schriftfarbe`,
	EditorFormatPaintLabel: `Formatfarbe`,
	EditorInSelectionLabel: ` In der Auswahl`,
	EditorInsertImageLabel: `Bild einfügen`,
	EditorInsertLinkLabel: `Link einfügen`,
	EditorInsertVideoLabel: `Video einfügen`,
	EditorLinkButtonText: `Speichern`,
	EditorLinkLabel: `Link eingeben`,
	EditorLinkPlaceholder: `URL eingeben`,
	EditorMatchCaseLabel: ` Match -Fall`,
	EditorNewTemplateLabel: `Neue Vorlage`,
	EditorNextTemplateLabel: `Nächste Vorlage`,
	EditorPasteButtonAppendBeginLabel: `Anhängen ...`,
	EditorPasteButtonLabel: `Paste`,
	EditorPasteTemplateWatermark: `Eingeben Sie einen Einfügen von Text ...`,
	EditorPrevTemplateLabel: `Vorherige Vorlage`,
	EditorRegExLabel: ` Regulären Ausdruck`,
	EditorReplaceAllLabel: `Alles ersetzen`,
	EditorReplaceLabel: `Ersetzen`,
	EditorTemplateContactHint: `<p>Bei Verwendung verfügbarer Kontakte (erfordert ein Fetcher-Plugin) wird dieses Feld für alle Instanzen dieser Vorlage in diesem Dokument oder in jedem Dokument verwendet, auf das später verwiesen wird.</p><p> Wenn Sie hier beispielsweise eine E-Mail-Adresse auswählen, wird das E-Mail-Feld des von Ihnen ausgewählten Kontakts für alle Instanzen in diesem Dokument verwendet.</p>`,
	EditorTemplateContactName: `Kontakt`,
	EditorTemplateDateTimeCustomHint: `yy = kurzes Jahr<br/>yyyy = langes Jahr<br/>M = Monat (1-12)<br/>MM = Monat (01-12)<br/>MMM = Monatskürzel (Jan, Feb ... Dez)<br/>MMMM = langer Monat (Januar, Februar ... Dezember)<br/>d = Tag (1 - 31)<br/>dd = Tag (01 - 31)<br/>ddd = Wochentag in Worten (Montag, Dienstag ... Sonntag)<br/>E = kurzer Wochentag in Worten (Mo, Di ... So)<br/>D - Ordinaltag (1., 2., 3., 21., 22., 23., 31., 4....)<br/>h = Stunde in am/pm (0-12)<br/>hh = Stunde in vormittags/nachmittags (00-12)<br/>H = Stunde am Tag (0-23)<br/>HH = Stunde am Tag (00-23)<br/>mm = Minute<br/>ss = Sekunde<br/>SSS = Millisekunden<br/>a = AM/PM-Markierung<br/>p = a.m./p.m. Markierung`,
	EditorTemplateDateTimeCustomLabel: `Brauch`,
	EditorTemplateDateTimeHint: `Das aktuelle Datum und/oder die Uhrzeit werden bei der Einfügung durch Vorlagen für DateTime ersetzt.`,
	EditorTemplateDateTimeName: `Terminzeit`,
	EditorTemplateDynamicHint: `<p>Für alle Vorkommen dieser Vorlage wird der bereitgestellte Text verwendet.</p>`,
	EditorTemplateDynamicName: `Dynamisch`,
	EditorTemplateEmptyPlaceholder: `{0} ist leer ...`,
	EditorTemplateStaticHint: `<p>Für alle Vorkommen dieser Vorlage wird der bereitgestellte Text verwendet.</p>`,
	EditorTemplateStaticName: `Statisch`,
	EditorTemplateTeaserText: `Mehr folgt bald!`,
	EditorTt1: `Klicken`,
	EditorTt2: `'<em>{0}</em>' bearbeiten ...`,
	EditorTt3: `Farbe bearbeiten ...`,
	EditorTt4: `Entfernen Sie „<em>{0}</em>“ …`,
	EditorTt5: `Gegenstand entfernen`,
	EditorTt6: `Folgen ...`,
	EditorTt7: `gehe zu '<em>{0}</em>' ...`,
	EditorWatermark: `Bitte warten...`,
	EditorWholeWordLabel: ` Ganze Welt`,
	EditorWrapLabel: ` Wickeln Sie herum`,

};