namespace MonkeyPaste {
    public enum MpShortcutType {
        None = 0,
        // GLOBALS
        ToggleMainWindow,
        ToggleAutoCopyMode,
        ToggleRightClickPasteMode,
        ToggleListenToClipboard,
        ToggleAppendInsertMode,
        ToggleAppendLineMode,
        ToggleAppendPreMode,
        ToggleAppendPaused,
        ManuallyAddFromClipboard,

        // APPLICATION
        HideMainWindow,
        ExitApplication,
        PasteToExternal,
        PasteSelection,
        CopySelection,
        CutSelection,
        DeleteSelectedItems,
        SelectNextColumnItem,
        SelectPreviousColumnItem,
        SelectNextRowItem,
        SelectPreviousRowItem,
        AssignShortcut,
        Undo,
        Redo,
        ToggleContentReadOnly,
        Rename,
        Duplicate,
        ScrollToHome,
        ScrollToEnd,
        WindowSizeUp,
        WindowSizeDown,
        WindowSizeLeft,
        WindowSizeRight,
        PreviousPage,
        NextPage,
        FindAndReplaceSelectedItem,
        ToggleMainWindowLocked,
        ToggleFilterMenuVisible,
        ShowSettings,
        TogglePinned,
        OpenInWindow,
        PermanentlyDelete,
        ForceMinimizeMainWindow,
        ToggleAppendManualMode,
        OpenHelp,
        // CUT-OFF 
        MAX_APP_SHORTCUT,
        //remaining are data (not context) driven using commandId
        PasteCopyItem = 101,
        SelectTag = 102,
        AnalyzeCopyItemWithPreset = 103,
        InvokeTrigger = 104
    }

}
